<?php
declare(strict_types=1);

function mg_investment_pipeline_save_interest_audited_v2(PDO $pdo,array $actor,array $input): array
{
    $record=mg_investment_pipeline_record($pdo,mg_investment_text($input['investor_id']??'',36,36,'Investor identifier'));$round=mg_investment_pipeline_round($pdo,mg_investment_text($input['round_id']??'',36,36,'Round identifier'));$roundId=(int)$round['id'];$investorId=(int)$record['investor_user_id'];
    $signedQ=$pdo->prepare('SELECT COALESCE(SUM(signed_amount_cents),0) FROM investor_closing_records WHERE round_id=? AND investor_user_id=? AND signed_verification_source="maker_checker" AND status NOT IN ("withdrawn","declined")');$signedQ->execute([$roundId,$investorId]);$signed=(int)$signedQ->fetchColumn();$fundedQ=$pdo->prepare('SELECT COALESCE(SUM(verified_funded_cents),0) FROM investor_closing_records WHERE round_id=? AND investor_user_id=? AND funding_verification_source="maker_checker" AND status NOT IN ("withdrawn","declined")');$fundedQ->execute([$roundId,$investorId]);$funded=(int)$fundedQ->fetchColumn();
    if(mg_investment_money($input['signed']??0)!==$signed||mg_investment_money($input['funded']??0)!==$funded)throw new MgInvestmentException('Signed and funded values are read-only here and must match maker/checker closing records.',409);$status=(string)($input['status']??'invited');if($status==='signed'&&$signed<1)throw new MgInvestmentException('The signed relationship status requires maker/checker verified signed money.',409);if($status==='funded'&&$funded<1)throw new MgInvestmentException('The funded relationship status requires maker/checker verified funded money.',409);
    $safe=$input;$safe['signed']=number_format($signed/100,2,'.','');$safe['funded']=number_format($funded/100,2,'.','');return mg_investment_pipeline_save_interest($pdo,$actor,$safe);
}

function mg_investment_financial_decide_audited_v2(PDO $pdo,array $actor,array $input): array
{
    $requestId=mg_investment_text($input['request_id']??'',36,36,'Verification request identifier');$q=$pdo->prepare('SELECT vr.closing_record_id,vr.round_id,r.public_id AS round_public_id FROM investment_financial_verification_requests vr INNER JOIN investment_rounds r ON r.id=vr.round_id WHERE vr.public_id=? LIMIT 1');$q->execute([$requestId]);$request=$q->fetch(PDO::FETCH_ASSOC);if(!$request)throw new MgInvestmentException('Financial verification request not found.',404);mg_investment_financial_decide_audited($pdo,$actor,$input);
    $recordQ=$pdo->prepare('SELECT signed_amount_cents,signed_verification_source,verified_funded_cents,funding_verification_source FROM investor_closing_records WHERE id=? LIMIT 1');$recordQ->execute([(int)$request['closing_record_id']]);$record=$recordQ->fetch(PDO::FETCH_ASSOC)?:[];$status=($record['funding_verification_source']??'')==='maker_checker'&&(int)($record['verified_funded_cents']??0)>0?'funds_verified':((($record['signed_verification_source']??'')==='maker_checker'&&(int)($record['signed_amount_cents']??0)>0)?'signed':'soft_committed');$pdo->prepare('UPDATE investor_closing_records SET status=?,updated_by_user_id=?,updated_at=NOW() WHERE id=?')->execute([$status,(int)$actor['id'],(int)$request['closing_record_id']]);mg_investment_recalculate_round_totals_audited($pdo,(int)$request['round_id'],(int)$actor['id']);return mg_investment_closing_dashboard_audited($pdo,['round_id'=>$request['round_public_id']]);
}

function mg_investment_governance_save_notice_audited_v3(PDO $pdo,array $actor,array $input): array
{
    if((string)($input['status']??'draft')==='published'){$round=mg_investment_governance_round($pdo,$input['round_id']??'',false);$audience=(string)($input['audience']??'funded_investors');if($round&&$audience!=='board'){$roundId=(int)$round['id'];
        if($audience==='funded_investors'){$all=$pdo->prepare('SELECT COUNT(DISTINCT investor_user_id) FROM investor_closing_records WHERE round_id=? AND verified_funded_cents>0 AND status NOT IN ("withdrawn","declined")');$all->execute([$roundId]);$proven=$pdo->prepare('SELECT COUNT(DISTINCT investor_user_id) FROM investor_closing_records WHERE round_id=? AND verified_funded_cents>0 AND funding_verification_source="maker_checker" AND status NOT IN ("withdrawn","declined")');$proven->execute([$roundId]);$allCount=(int)$all->fetchColumn();$provenCount=(int)$proven->fetchColumn();if($provenCount<1||$allCount!==$provenCount)throw new MgInvestmentException('Resolve all legacy unproven funded records before publishing to the funded-investor audience.',409);}
        if(in_array($audience,['specific_investors','custom'],true)){$raw=$input['investor_user_ids']??[];if(is_string($raw))$raw=preg_split('/[\s,]+/',$raw,-1,PREG_SPLIT_NO_EMPTY)?:[];foreach(array_unique(array_map('intval',(array)$raw)) as $id)if($id>0&&!mg_investment_has_proven_funding_audited($pdo,$roundId,$id))throw new MgInvestmentException('Every specific notice recipient requires maker/checker verified funding.',409);}
        if($audience==='selected_investors'){$all=$pdo->prepare('SELECT COUNT(DISTINCT investor_user_id) FROM investment_round_access WHERE round_id=? AND status="granted" AND (expires_at IS NULL OR expires_at>NOW())');$all->execute([$roundId]);$proven=$pdo->prepare('SELECT COUNT(DISTINCT a.investor_user_id) FROM investment_round_access a INNER JOIN investor_closing_records c ON c.round_id=a.round_id AND c.investor_user_id=a.investor_user_id AND c.verified_funded_cents>0 AND c.funding_verification_source="maker_checker" AND c.status NOT IN ("withdrawn","declined") WHERE a.round_id=? AND a.status="granted" AND (a.expires_at IS NULL OR a.expires_at>NOW())');$proven->execute([$roundId]);$allCount=(int)$all->fetchColumn();$provenCount=(int)$proven->fetchColumn();if($allCount<1||$allCount!==$provenCount)throw new MgInvestmentException('Every selected notice recipient must have maker/checker verified funding.',409);}
    }}
    return mg_investment_governance_save_notice_audited_v2($pdo,$actor,$input);
}

function mg_investment_communication_save_audited_v2(PDO $pdo,array $actor,array $input): array
{
    if((string)($input['status']??'draft')==='published'&&(string)($input['audience_type']??'approved_investors')==='funded_investors'){$round=mg_investment_diligence_round($pdo,mg_investment_text($input['round_id']??'',36,36,'Round identifier'));$all=$pdo->prepare('SELECT COUNT(DISTINCT investor_user_id) FROM investor_closing_records WHERE round_id=? AND verified_funded_cents>0 AND status NOT IN ("withdrawn","declined")');$all->execute([(int)$round['id']]);$proven=$pdo->prepare('SELECT COUNT(DISTINCT investor_user_id) FROM investor_closing_records WHERE round_id=? AND verified_funded_cents>0 AND funding_verification_source="maker_checker" AND status NOT IN ("withdrawn","declined")');$proven->execute([(int)$round['id']]);$allCount=(int)$all->fetchColumn();$provenCount=(int)$proven->fetchColumn();if($provenCount<1||$allCount!==$provenCount)throw new MgInvestmentException('Resolve legacy unproven funded records before publishing a funded-investor communication.',409);}
    return mg_investment_communication_save_audited($pdo,$actor,$input);
}

function mg_investment_compliance_save_audited(PDO $pdo,array $actor,array $input): array
{
    mg_investment_pipeline_admin_user_audited($pdo,$input['assigned_user_id']??0);$status=(string)($input['status']??'not_started');$counselRequired=mg_investment_bool($input['counsel_required']??false);if(in_array($status,['filed','confirmed','approved'],true)){mg_investment_text($input['external_reference']??'',220,2,'External compliance reference');if($counselRequired&&empty($input['external_url']))throw new MgInvestmentException('Counsel-required completed compliance records need an external receipt or document URL.',409);}
    return mg_investment_compliance_save($pdo,$actor,$input);
}
