<?php
declare(strict_types=1);

function mg_investment_diligence_round(PDO $pdo,string $publicId): array
{
    $stmt=$pdo->prepare('SELECT r.*,w.public_id AS workspace_public_id FROM investment_rounds r INNER JOIN investment_workspaces w ON w.id=r.workspace_id WHERE r.public_id=? LIMIT 1');
    $stmt->execute([$publicId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);
    if(!$row)throw new MgInvestmentException('Investment round not found.',404);
    return $row;
}

function mg_investment_diligence_dashboard(PDO $pdo,array $filters=[]): array
{
    $roundPublicId=trim((string)($filters['round_id']??''));$roundId=null;
    if($roundPublicId!=='')$roundId=(int)mg_investment_diligence_round($pdo,$roundPublicId)['id'];
    $rounds=$pdo->query('SELECT r.public_id,r.public_name,r.status,r.visibility,r.target_raise_cents,r.funded_cents,p.publication_status FROM investment_rounds r LEFT JOIN investment_round_publication p ON p.round_id=r.id ORDER BY r.updated_at DESC')->fetchAll(PDO::FETCH_ASSOC);
    $admins=$pdo->query('SELECT DISTINCT u.id,u.full_name,u.email FROM users u INNER JOIN user_roles ur ON ur.user_id=u.id INNER JOIN roles r ON r.id=ur.role_id WHERE r.slug IN ("admin","super_admin") ORDER BY u.full_name')->fetchAll(PDO::FETCH_ASSOC);
    $investors=$pdo->query('SELECT ip.user_id,u.full_name,u.display_name,u.email,ip.firm_name FROM investor_profiles ip INNER JOIN users u ON u.id=ip.user_id WHERE ip.status="active" ORDER BY COALESCE(u.display_name,u.full_name),u.email')->fetchAll(PDO::FETCH_ASSOC);
    $where=$roundId? ' WHERE f.round_id='.(int)$roundId : '';
    $folders=$pdo->query('SELECT f.*,r.public_id AS round_public_id,r.public_name FROM investment_dataroom_folders f INNER JOIN investment_rounds r ON r.id=f.round_id'.$where.' ORDER BY r.updated_at DESC,f.sort_order,f.id')->fetchAll(PDO::FETCH_ASSOC);
    $where=$roundId? ' WHERE d.round_id='.(int)$roundId : '';
    $documents=$pdo->query('SELECT d.*,f.public_id AS folder_public_id,f.name AS folder_name,r.public_id AS round_public_id,r.public_name FROM investment_dataroom_documents d INNER JOIN investment_rounds r ON r.id=d.round_id LEFT JOIN investment_dataroom_folders f ON f.id=d.folder_id'.$where.' ORDER BY r.updated_at DESC,COALESCE(f.sort_order,999),d.title')->fetchAll(PDO::FETCH_ASSOC);
    $where=$roundId? ' WHERE q.round_id='.(int)$roundId : '';
    $requests=$pdo->query('SELECT q.*,r.public_id AS round_public_id,r.public_name,u.full_name,u.display_name,u.email,au.full_name AS assigned_name FROM investor_diligence_requests q INNER JOIN investment_rounds r ON r.id=q.round_id INNER JOIN users u ON u.id=q.investor_user_id LEFT JOIN users au ON au.id=q.assigned_user_id'.$where.' ORDER BY FIELD(q.status,"submitted","acknowledged","assigned","researching","draft_response","internal_review","legal_review","answered","closed","declined"),FIELD(q.priority,"urgent","high","normal","low"),q.created_at DESC LIMIT 500')->fetchAll(PDO::FETCH_ASSOC);
    $where=$roundId? ' WHERE (qa.round_id='.(int)$roundId.' OR qa.round_id IS NULL)' : '';
    $qa=$pdo->query('SELECT qa.*,r.public_id AS round_public_id,r.public_name FROM investment_qa_entries qa LEFT JOIN investment_rounds r ON r.id=qa.round_id'.$where.' ORDER BY qa.updated_at DESC LIMIT 500')->fetchAll(PDO::FETCH_ASSOC);
    $where=$roundId? ' WHERE m.round_id='.(int)$roundId : '';
    $meetings=$pdo->query('SELECT m.*,r.public_id AS round_public_id,r.public_name,u.full_name,u.display_name,u.email FROM investor_meetings m INNER JOIN users u ON u.id=m.investor_user_id LEFT JOIN investment_rounds r ON r.id=m.round_id'.$where.' ORDER BY m.starts_at DESC LIMIT 500')->fetchAll(PDO::FETCH_ASSOC);
    $where=$roundId? ' WHERE c.round_id='.(int)$roundId : '';
    $communications=$pdo->query('SELECT c.*,r.public_id AS round_public_id,r.public_name,(SELECT COUNT(*) FROM investor_communication_recipients cr WHERE cr.communication_id=c.id) AS recipient_count,(SELECT COUNT(*) FROM investor_communication_recipients cr WHERE cr.communication_id=c.id AND cr.first_viewed_at IS NOT NULL) AS viewed_count FROM investor_communications c LEFT JOIN investment_rounds r ON r.id=c.round_id'.$where.' ORDER BY c.updated_at DESC LIMIT 500')->fetchAll(PDO::FETCH_ASSOC);
    $where=$roundId? ' WHERE s.round_id='.(int)$roundId : '';
    $interest=$pdo->query('SELECT s.*,r.public_id AS round_public_id,r.public_name,u.full_name,u.display_name,u.email FROM investor_interest_submissions s INNER JOIN investment_rounds r ON r.id=s.round_id INNER JOIN users u ON u.id=s.investor_user_id'.$where.' ORDER BY FIELD(s.status,"submitted","reviewing","accepted_for_discussion","converted","declined","withdrawn"),s.created_at DESC LIMIT 500')->fetchAll(PDO::FETCH_ASSOC);
    $engagement=$pdo->query('SELECT e.*,r.public_id AS round_public_id,r.public_name,u.full_name,u.display_name,u.email,ip.firm_name FROM investor_engagement_snapshots e INNER JOIN users u ON u.id=e.investor_user_id LEFT JOIN investor_profiles ip ON ip.user_id=e.investor_user_id LEFT JOIN investment_rounds r ON r.id=e.round_id INNER JOIN (SELECT investor_user_id,COALESCE(round_id,0) AS rid,MAX(snapshot_at) AS latest FROM investor_engagement_snapshots GROUP BY investor_user_id,COALESCE(round_id,0)) latest ON latest.investor_user_id=e.investor_user_id AND latest.rid=COALESCE(e.round_id,0) AND latest.latest=e.snapshot_at ORDER BY e.engagement_score DESC,e.snapshot_at DESC LIMIT 500')->fetchAll(PDO::FETCH_ASSOC);
    $summary=['open_requests'=>0,'overdue_requests'=>0,'published_documents'=>0,'published_qa'=>0,'upcoming_meetings'=>0,'published_communications'=>0,'new_interest'=>0,'stalled_investors'=>0];
    foreach($requests as $item){if(!in_array($item['status'],['answered','closed','declined'],true))$summary['open_requests']++;if(!empty($item['due_at'])&&strtotime((string)$item['due_at'])<time()&&!in_array($item['status'],['answered','closed','declined'],true))$summary['overdue_requests']++;}
    foreach($documents as $item)if($item['status']==='published')$summary['published_documents']++;
    foreach($qa as $item)if($item['status']==='published')$summary['published_qa']++;
    foreach($meetings as $item)if(in_array($item['status'],['planned','confirmed'],true)&&strtotime((string)$item['starts_at'])>=time())$summary['upcoming_meetings']++;
    foreach($communications as $item)if($item['status']==='published')$summary['published_communications']++;
    foreach($interest as $item)if($item['status']==='submitted')$summary['new_interest']++;
    foreach($engagement as $item)if((int)$item['stalled']===1)$summary['stalled_investors']++;
    return compact('rounds','admins','investors','folders','documents','requests','qa','meetings','communications','interest','engagement','summary');
}

function mg_investment_dataroom_save_folder(PDO $pdo,array $actor,array $input): array
{
    mg_investment_require_permission($actor,'admin.investment.diligence.manage');$round=mg_investment_diligence_round($pdo,mg_investment_text($input['round_id']??'',36,36,'Round identifier'));
    $publicId=trim((string)($input['folder_id']??''));$name=mg_investment_text($input['name']??'',180,2,'Folder name');$category=mg_investment_text($input['category']??'other',80,2,'Folder category');
    $visibility=(string)($input['visibility']??'approved_investors');$status=(string)($input['status']??'active');if(!in_array($visibility,['approved_investors','selected_investors','funded_investors'],true)||!in_array($status,['active','hidden','archived'],true))throw new MgInvestmentException('Invalid folder visibility or status.');
    if($publicId===''){$publicId=mg_investment_uuid();$stmt=$pdo->prepare('INSERT INTO investment_dataroom_folders (public_id,round_id,name,category,description,visibility,status,sort_order,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,NOW(),NOW())');$stmt->execute([$publicId,(int)$round['id'],$name,$category,mg_investment_long_text($input['description']??'',4000)?:null,$visibility,$status,(int)($input['sort_order']??0),(int)$actor['id']]);}else{$stmt=$pdo->prepare('UPDATE investment_dataroom_folders SET name=?,category=?,description=?,visibility=?,status=?,sort_order=?,updated_at=NOW() WHERE public_id=? AND round_id=?');$stmt->execute([$name,$category,mg_investment_long_text($input['description']??'',4000)?:null,$visibility,$status,(int)($input['sort_order']??0),mg_investment_text($publicId,36,36,'Folder identifier'),(int)$round['id']]);}
    mg_audit('investment_dataroom_folder_saved','investment_dataroom',['folder_id'=>$publicId,'round_id'=>$round['public_id']],(int)$actor['id']);return mg_investment_diligence_dashboard($pdo,['round_id'=>$round['public_id']]);
}

function mg_investment_dataroom_save_document(PDO $pdo,array $actor,array $input): array
{
    mg_investment_require_permission($actor,'admin.investment.diligence.manage');$round=mg_investment_diligence_round($pdo,mg_investment_text($input['round_id']??'',36,36,'Round identifier'));$publicId=trim((string)($input['document_id']??''));
    $title=mg_investment_text($input['title']??'',220,2,'Document title');$status=(string)($input['status']??'draft');$visibility=(string)($input['visibility']??'approved_investors');$classification=(string)($input['classification']??'standard');
    if(!in_array($status,['draft','internal_review','legal_review','approved','published','superseded','archived'],true)||!in_array($visibility,['approved_investors','selected_investors','funded_investors'],true)||!in_array($classification,['standard','confidential','highly_sensitive'],true))throw new MgInvestmentException('Invalid document status, visibility, or classification.');
    $url=mg_investment_url($input['external_url']??'');$requiresLegal=mg_investment_bool($input['requires_legal_review']??false);if($classification==='highly_sensitive')$requiresLegal=true;if($status==='published'&&$url===null)throw new MgInvestmentException('Published data-room documents require an approved external URL.');if($status==='published'&&$requiresLegal&&!mg_investment_has_permission($actor,'admin.investment.diligence.publish'))throw new MgInvestmentException('Publishing legal-review documents requires publishing permission.',403);
    $folderId=null;if(!empty($input['folder_id'])){$q=$pdo->prepare('SELECT id FROM investment_dataroom_folders WHERE public_id=? AND round_id=? LIMIT 1');$q->execute([mg_investment_text($input['folder_id'],36,36,'Folder identifier'),(int)$round['id']]);$folderId=(int)$q->fetchColumn()?:null;}
    $pdo->beginTransaction();try{
        if($publicId===''){$publicId=mg_investment_uuid();$stmt=$pdo->prepare('INSERT INTO investment_dataroom_documents (public_id,round_id,folder_id,title,internal_description,investor_description,classification,status,visibility,external_url,download_allowed,requires_legal_review,expires_at,current_version_number,approved_by_user_id,approved_at,published_at,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,IF(? IN ("approved","published"),NOW(),NULL),IF(?="published",NOW(),NULL),?,?,NOW(),NOW())');$stmt->execute([$publicId,(int)$round['id'],$folderId,$title,mg_investment_long_text($input['internal_description']??'',6000)?:null,mg_investment_long_text($input['investor_description']??'',6000)?:null,$classification,$status,$visibility,$url,mg_investment_bool($input['download_allowed']??true)?1:0,$requiresLegal?1:0,mg_investment_date($input['expires_at']??null),in_array($status,['approved','published'],true)?(int)$actor['id']:null,$status,$status,(int)$actor['id'],(int)$actor['id']]);$documentId=(int)$pdo->lastInsertId();$version=1;}else{$q=$pdo->prepare('SELECT * FROM investment_dataroom_documents WHERE public_id=? AND round_id=? LIMIT 1 FOR UPDATE');$q->execute([mg_investment_text($publicId,36,36,'Document identifier'),(int)$round['id']]);$existing=$q->fetch(PDO::FETCH_ASSOC);if(!$existing)throw new MgInvestmentException('Data-room document not found.',404);$documentId=(int)$existing['id'];$version=(int)$existing['current_version_number']+1;$stmt=$pdo->prepare('UPDATE investment_dataroom_documents SET folder_id=?,title=?,internal_description=?,investor_description=?,classification=?,status=?,visibility=?,external_url=?,download_allowed=?,requires_legal_review=?,expires_at=?,current_version_number=?,approved_by_user_id=IF(? IN ("approved","published"),?,approved_by_user_id),approved_at=IF(? IN ("approved","published"),COALESCE(approved_at,NOW()),approved_at),published_at=IF(?="published",COALESCE(published_at,NOW()),published_at),updated_by_user_id=?,updated_at=NOW() WHERE id=?');$stmt->execute([$folderId,$title,mg_investment_long_text($input['internal_description']??'',6000)?:null,mg_investment_long_text($input['investor_description']??'',6000)?:null,$classification,$status,$visibility,$url,mg_investment_bool($input['download_allowed']??true)?1:0,$requiresLegal?1:0,mg_investment_date($input['expires_at']??null),$version,$status,(int)$actor['id'],$status,$status,(int)$actor['id'],$documentId]);}
        $v=$pdo->prepare('INSERT INTO investment_dataroom_document_versions (document_id,version_number,external_url,version_label,notes,status,created_by_user_id,created_at) VALUES (?,?,?,?,?,?,?,NOW())');$v->execute([$documentId,$version,$url,mg_investment_text($input['version_label']??('Version '.$version),120)?:null,mg_investment_long_text($input['version_notes']??'',4000)?:null,$status==='archived'?'superseded':$status,(int)$actor['id']]);$pdo->commit();
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    mg_audit('investment_dataroom_document_saved','investment_dataroom',['document_id'=>$publicId,'round_id'=>$round['public_id'],'version'=>$version,'status'=>$status],(int)$actor['id']);return mg_investment_diligence_dashboard($pdo,['round_id'=>$round['public_id']]);
}

function mg_investment_diligence_admin_save_request(PDO $pdo,array $actor,array $input): array
{
    mg_investment_require_permission($actor,'admin.investment.diligence.manage');$publicId=mg_investment_text($input['request_id']??'',36,36,'Request identifier');$status=(string)($input['status']??'acknowledged');$allowed=['submitted','acknowledged','assigned','researching','draft_response','internal_review','legal_review','answered','closed','declined'];if(!in_array($status,$allowed,true))throw new MgInvestmentException('Invalid diligence status.');
    $pdo->beginTransaction();try{$q=$pdo->prepare('SELECT q.*,r.public_id AS round_public_id FROM investor_diligence_requests q INNER JOIN investment_rounds r ON r.id=q.round_id WHERE q.public_id=? LIMIT 1 FOR UPDATE');$q->execute([$publicId]);$row=$q->fetch(PDO::FETCH_ASSOC);if(!$row)throw new MgInvestmentException('Diligence request not found.',404);$assigned=(int)($input['assigned_user_id']??0);$response=mg_investment_long_text($input['response_text']??'',30000);$responseStatus=(string)($input['response_status']??'draft');if(!in_array($responseStatus,['draft','internal_review','legal_review','approved','published','rejected'],true))throw new MgInvestmentException('Invalid response status.');if($responseStatus==='published'&&!mg_investment_has_permission($actor,'admin.investment.diligence.publish'))throw new MgInvestmentException('Publishing diligence responses requires publishing permission.',403);$approved=$responseStatus==='published'?$response:null;$stmt=$pdo->prepare('UPDATE investor_diligence_requests SET status=?,assigned_user_id=?,due_at=?,internal_notes=?,approved_response=COALESCE(?,approved_response),answered_by_user_id=IF(?="published",?,answered_by_user_id),answered_at=IF(?="published",NOW(),answered_at),closed_at=IF(?="closed",NOW(),closed_at),updated_at=NOW() WHERE id=?');$stmt->execute([$status,$assigned>0?$assigned:null,mg_investment_date($input['due_at']??null),mg_investment_long_text($input['internal_notes']??'',12000)?:null,$approved,$responseStatus,(int)$actor['id'],$responseStatus,$status,(int)$row['id']]);if($response!==''){$n=$pdo->prepare('SELECT COALESCE(MAX(version_number),0)+1 FROM investor_diligence_response_versions WHERE request_id=?');$n->execute([(int)$row['id']]);$version=(int)$n->fetchColumn();$pdo->prepare('INSERT INTO investor_diligence_response_versions (request_id,version_number,response_text,status,change_reason,created_by_user_id,created_at) VALUES (?,?,?,?,?,?,NOW())')->execute([(int)$row['id'],$version,$response,$responseStatus,mg_investment_text($input['change_reason']??'',500)?:null,(int)$actor['id']]);}mg_investment_pipeline_activity($pdo,(int)$row['investor_user_id'],(int)$row['round_id'],'note','Diligence request updated','Status: '.ucwords(str_replace('_',' ',$status)),(int)$actor['id'],['request_id'=>$publicId,'response_status'=>$responseStatus]);$pdo->commit();mg_audit('investor_diligence_request_updated','investor_diligence',['request_id'=>$publicId,'status'=>$status,'response_status'=>$responseStatus],(int)$actor['id']);return mg_investment_diligence_dashboard($pdo,['round_id'=>$row['round_public_id']]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
