<?php
declare(strict_types=1);

function mg_investment_portal_round_relation(PDO $pdo,int $roundId,int $userId): array
{
    $q=$pdo->prepare('SELECT EXISTS(SELECT 1 FROM investment_round_access WHERE round_id=? AND investor_user_id=? AND status="granted" AND (expires_at IS NULL OR expires_at>NOW())) AS selected_access,EXISTS(SELECT 1 FROM investor_round_interests WHERE round_id=? AND investor_user_id=? AND funded_cents>0 AND status NOT IN ("declined","passed","archived")) AS funded_access');
    $q->execute([$roundId,$userId,$roundId,$userId]);$row=$q->fetch(PDO::FETCH_ASSOC)?:[];return ['selected'=>(bool)($row['selected_access']??false),'funded'=>(bool)($row['funded_access']??false)];
}

function mg_investment_portal_log_v3(PDO $pdo,int $userId,int $roundId,string $eventType,string $subjectPublicId,array $metadata=[]): void
{
    if(!in_array($eventType,['communication_view','qa_view'],true))return;
    $stmt=$pdo->prepare('INSERT INTO investment_portal_events (public_id,investor_user_id,round_id,event_type,subject_public_id,metadata_json,created_at) VALUES (?,?,?,?,?,?,NOW())');
    $stmt->execute([mg_investment_uuid(),$userId,$roundId,$eventType,$subjectPublicId,$metadata?mg_investment_json_encode($metadata):null]);
    mg_investment_pipeline_activity($pdo,$userId,$roundId,'portal_view',$eventType==='communication_view'?'Investor viewed a communication':'Investor reviewed a Q&A entry','',null,$metadata);
}

function mg_investment_portal_data_v3(PDO $pdo,array $user): array
{
    $base=mg_investment_portal_data_v2($pdo,$user);$userId=(int)$user['id'];
    foreach($base['rounds'] as &$portalRound){$q=$pdo->prepare('SELECT id FROM investment_rounds WHERE public_id=? LIMIT 1');$q->execute([(string)$portalRound['id']]);$roundId=(int)$q->fetchColumn();if($roundId<1)continue;$relation=mg_investment_portal_round_relation($pdo,$roundId,$userId);
        $folderQ=$pdo->prepare('SELECT public_id,name,category,description,visibility,sort_order FROM investment_dataroom_folders WHERE round_id=? AND status="active" ORDER BY sort_order,id');$folderQ->execute([$roundId]);$folders=$folderQ->fetchAll(PDO::FETCH_ASSOC);
        $docQ=$pdo->prepare('SELECT d.public_id,d.title,d.investor_description,d.classification,d.visibility,d.external_url,d.download_allowed,d.expires_at,d.current_version_number,f.public_id AS folder_public_id,f.name AS folder_name FROM investment_dataroom_documents d LEFT JOIN investment_dataroom_folders f ON f.id=d.folder_id WHERE d.round_id=? AND d.status="published" AND (d.expires_at IS NULL OR d.expires_at>NOW()) ORDER BY COALESCE(f.sort_order,999),d.title');$docQ->execute([$roundId]);$documents=[];foreach($docQ->fetchAll(PDO::FETCH_ASSOC) as $doc){$allowed=$doc['visibility']==='approved_investors'||($doc['visibility']==='selected_investors'&&$relation['selected'])||($doc['visibility']==='funded_investors'&&$relation['funded']);if($allowed)$documents[]=$doc;}
        $qaQ=$pdo->prepare('SELECT public_id,category,question,answer,version_number,published_at FROM investment_qa_entries WHERE status="published" AND (round_id=? OR round_id IS NULL) ORDER BY category,question');$qaQ->execute([$roundId]);
        $requestQ=$pdo->prepare('SELECT public_id,category,request_type,priority,status,subject,request_text,approved_response,answered_at,created_at,updated_at FROM investor_diligence_requests WHERE round_id=? AND investor_user_id=? ORDER BY created_at DESC');$requestQ->execute([$roundId,$userId]);
        $communicationQ=$pdo->prepare('SELECT c.public_id,c.communication_type,c.subject,c.body,c.published_at,cr.first_viewed_at,cr.last_viewed_at,cr.view_count FROM investor_communications c INNER JOIN investor_communication_recipients cr ON cr.communication_id=c.id AND cr.investor_user_id=? WHERE c.round_id=? AND c.status="published" AND cr.status IN ("published","viewed") ORDER BY c.published_at DESC');$communicationQ->execute([$userId,$roundId]);
        $interestQ=$pdo->prepare('SELECT public_id,proposed_range,expected_timing,questions_conditions,preferred_next_step,meeting_requested,status,created_at,updated_at FROM investor_interest_submissions WHERE round_id=? AND investor_user_id=? ORDER BY created_at DESC');$interestQ->execute([$roundId,$userId]);
        $engagementQ=$pdo->prepare('SELECT portal_sessions,round_views,document_views,unique_documents_viewed,metric_views,questions_submitted,communications_viewed,meetings_completed,days_since_last_engagement,engagement_score,stalled,snapshot_at FROM investor_engagement_snapshots WHERE investor_user_id=? AND round_id=? ORDER BY snapshot_at DESC LIMIT 1');$engagementQ->execute([$userId,$roundId]);
        $portalRound['diligence']=['folders'=>$folders,'documents'=>$documents,'qa'=>$qaQ->fetchAll(PDO::FETCH_ASSOC),'requests'=>$requestQ->fetchAll(PDO::FETCH_ASSOC),'communications'=>$communicationQ->fetchAll(PDO::FETCH_ASSOC),'interest_submissions'=>$interestQ->fetchAll(PDO::FETCH_ASSOC),'engagement'=>$engagementQ->fetch(PDO::FETCH_ASSOC)?:null,'relationship'=>$relation];
    }
    unset($portalRound);return $base;
}

function mg_investment_portal_submit_diligence(PDO $pdo,array $user,array $input): array
{
    if(!mg_investment_has_permission($user,'investment.diligence.submit'))throw new MgInvestmentException('Diligence submission permission is required.',403);$round=mg_investment_diligence_round($pdo,mg_investment_text($input['round_id']??'',36,36,'Round identifier'));$userId=(int)$user['id'];
    $visible=mg_investment_portal_data_v2($pdo,$user);$allowed=false;foreach($visible['rounds'] as $item)if((string)$item['id']===(string)$round['public_id']){$allowed=true;break;}if(!$allowed)throw new MgInvestmentException('This round is not available to your Investor account.',403);
    $category=(string)($input['category']??'other');$type=(string)($input['request_type']??'question');$priority=(string)($input['priority']??'normal');$categories=['company','corporate','capitalization','financial','product','technology','market','operations','contracts','intellectual_property','risk','round_terms','documents','other'];if(!in_array($category,$categories,true)||!in_array($type,['question','document_request','clarification'],true)||!in_array($priority,['low','normal','high','urgent'],true))throw new MgInvestmentException('Invalid diligence category, type, or priority.');
    $publicId=mg_investment_uuid();$stmt=$pdo->prepare('INSERT INTO investor_diligence_requests (public_id,round_id,investor_user_id,category,request_type,priority,status,subject,request_text,created_at,updated_at) VALUES (?,?,?,?,?,? ,"submitted",?,?,NOW(),NOW())');$stmt->execute([$publicId,(int)$round['id'],$userId,$category,$type,$priority,mg_investment_text($input['subject']??'',220,4,'Subject'),mg_investment_long_text($input['request_text']??'',12000,10,'Question or request')]);mg_investment_pipeline_activity($pdo,$userId,(int)$round['id'],'note','Investor diligence request submitted',mg_investment_text($input['subject']??'',220),(int)$user['id'],['request_id'=>$publicId,'category'=>$category]);mg_audit('investor_diligence_submitted','investor_diligence',['request_id'=>$publicId,'round_id'=>$round['public_id']],$userId);return mg_investment_portal_data_v3($pdo,$user);
}

function mg_investment_portal_submit_interest(PDO $pdo,array $user,array $input): array
{
    if(!mg_investment_has_permission($user,'investment.interest.submit'))throw new MgInvestmentException('Interest submission permission is required.',403);if(!mg_investment_bool($input['acknowledgement']??false))throw new MgInvestmentException('Accept the non-binding acknowledgement before submitting.');$round=mg_investment_diligence_round($pdo,mg_investment_text($input['round_id']??'',36,36,'Round identifier'));$userId=(int)$user['id'];$visible=mg_investment_portal_data_v2($pdo,$user);$allowed=false;foreach($visible['rounds'] as $item)if((string)$item['id']===(string)$round['public_id']){$allowed=true;break;}if(!$allowed)throw new MgInvestmentException('This round is not available to your Investor account.',403);
    $publicId=mg_investment_uuid();$stmt=$pdo->prepare('INSERT INTO investor_interest_submissions (public_id,round_id,investor_user_id,proposed_range,expected_timing,questions_conditions,preferred_next_step,meeting_requested,acknowledgement_at,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,NOW(),"submitted",NOW(),NOW())');$stmt->execute([$publicId,(int)$round['id'],$userId,mg_investment_text($input['proposed_range']??'',80,2,'Proposed range'),mg_investment_text($input['expected_timing']??'',120)?:null,mg_investment_long_text($input['questions_conditions']??'',8000)?:null,mg_investment_text($input['preferred_next_step']??'',220)?:null,mg_investment_bool($input['meeting_requested']??false)?1:0]);mg_investment_pipeline_activity($pdo,$userId,(int)$round['id'],'commitment_update','Non-binding interest submitted',mg_investment_text($input['proposed_range']??'',80),(int)$user['id'],['submission_id'=>$publicId,'non_binding'=>true]);mg_audit('investor_interest_submitted','investor_interest',['submission_id'=>$publicId,'round_id'=>$round['public_id']],$userId);return mg_investment_portal_data_v3($pdo,$user);
}

function mg_investment_portal_event_v3(PDO $pdo,array $user,array $input): array
{
    $event=(string)($input['event_type']??'');if(in_array($event,['document_open','metric_view','round_view'],true))return mg_investment_portal_event_v2($pdo,$user,$input);if(!in_array($event,['communication_view','qa_view'],true))throw new MgInvestmentException('Invalid portal event.');$round=mg_investment_diligence_round($pdo,mg_investment_text($input['round_id']??'',36,36,'Round identifier'));$subjectId=mg_investment_text($input['subject_id']??'',36,36,'Subject identifier');
    if($event==='communication_view'){$q=$pdo->prepare('SELECT c.id FROM investor_communications c INNER JOIN investor_communication_recipients cr ON cr.communication_id=c.id WHERE c.public_id=? AND c.round_id=? AND cr.investor_user_id=? AND c.status="published" LIMIT 1');$q->execute([$subjectId,(int)$round['id'],(int)$user['id']]);$communicationId=(int)$q->fetchColumn();if($communicationId<1)throw new MgInvestmentException('Communication is not available.',404);$pdo->prepare('UPDATE investor_communication_recipients SET status="viewed",first_viewed_at=COALESCE(first_viewed_at,NOW()),last_viewed_at=NOW(),view_count=view_count+1 WHERE communication_id=? AND investor_user_id=?')->execute([$communicationId,(int)$user['id']]);}
    mg_investment_portal_log_v3($pdo,(int)$user['id'],(int)$round['id'],$event,$subjectId,['title'=>mg_investment_text($input['title']??'',220)]);return ['recorded'=>true];
}
