<?php
declare(strict_types=1);

function mg_investment_portal_log_v4(PDO $pdo,int $userId,int $roundId,string $eventType,string $subjectPublicId,array $metadata=[]): void
{
    if(!in_array($eventType,['report_view','closing_document_open'],true))return;$subject=$eventType==='report_view'?'Investor viewed a post-investment report':'Investor opened a closing document';mg_investment_pipeline_activity($pdo,$userId,$roundId,$eventType==='closing_document_open'?'document_view':'portal_view',$subject,'',null,$metadata+['subject_public_id'=>$subjectPublicId,'event_type'=>$eventType]);
}

function mg_investment_portal_data_v4(PDO $pdo,array $user): array
{
    $base=mg_investment_portal_data_v3($pdo,$user);$userId=(int)$user['id'];$canClosing=mg_investment_has_permission($user,'investment.closing.view');$canRelations=mg_investment_has_permission($user,'investment.relations.view');
    foreach($base['rounds'] as &$portalRound){$q=$pdo->prepare('SELECT id FROM investment_rounds WHERE public_id=? LIMIT 1');$q->execute([(string)$portalRound['id']]);$roundId=(int)$q->fetchColumn();if($roundId<1){$portalRound['relations']=null;continue;}$recordQ=$pdo->prepare('SELECT cr.public_id,cr.status,cr.instrument_type,cr.final_amount_cents,cr.signed_amount_cents,cr.verified_funded_cents,cr.agreement_reference,cr.funding_reference,cr.investor_signed_at,cr.company_countersigned_at,cr.funds_verified_at,cr.closing_completed_at,b.public_id AS batch_public_id,b.batch_name,b.actual_close_at,cp.stage AS closing_stage,cp.readiness_score,cp.actual_final_close_at FROM investor_closing_records cr LEFT JOIN investment_closing_batches b ON b.id=cr.batch_id LEFT JOIN investment_closing_profiles cp ON cp.round_id=cr.round_id WHERE cr.round_id=? AND cr.investor_user_id=? AND cr.verified_funded_cents>0 LIMIT 1');$recordQ->execute([$roundId,$userId]);$record=$recordQ->fetch(PDO::FETCH_ASSOC);if(!$record||!$canClosing){$portalRound['relations']=null;continue;}
        $packetsQ=$pdo->prepare('SELECT public_id,packet_name,status,required_document_count,completed_document_count,external_packet_reference,completed_at FROM investment_closing_packets WHERE round_id=? AND investor_user_id=? AND status<>"archived" ORDER BY updated_at DESC');$packetsQ->execute([$roundId,$userId]);$packets=$packetsQ->fetchAll(PDO::FETCH_ASSOC);
        $documentsQ=$pdo->prepare('SELECT d.public_id,d.document_type,d.title,d.status,d.external_url,d.version_number,d.investor_signature_status,d.company_signature_status,d.counsel_status,d.completed_at,p.public_id AS packet_public_id,p.packet_name FROM investment_closing_documents d INNER JOIN investment_closing_packets p ON p.id=d.packet_id WHERE p.round_id=? AND p.investor_user_id=? AND d.status IN ("approved","executed","complete","not_applicable") ORDER BY p.updated_at DESC,d.title');$documentsQ->execute([$roundId,$userId]);$documents=$documentsQ->fetchAll(PDO::FETCH_ASSOC);
        $reports=[];if($canRelations){$reportQ=$pdo->prepare('SELECT p.public_id AS period_public_id,p.period_name,p.period_type,p.starts_at,p.ends_at,p.published_at,s.public_id AS snapshot_public_id,s.version_number,s.headline,s.narrative,s.metrics_json,s.use_of_funds_json,s.milestones_json,s.risks_json,s.published_at AS snapshot_published_at FROM investment_reporting_periods p INNER JOIN investment_reporting_snapshots s ON s.reporting_period_id=p.id INNER JOIN (SELECT reporting_period_id,MAX(version_number) AS version_number FROM investment_reporting_snapshots WHERE status="published" GROUP BY reporting_period_id) latest ON latest.reporting_period_id=s.reporting_period_id AND latest.version_number=s.version_number WHERE p.round_id=? AND p.status="published" AND s.status="published" ORDER BY p.starts_at DESC');$reportQ->execute([$roundId]);foreach($reportQ->fetchAll(PDO::FETCH_ASSOC) as $report){$report['metrics']=mg_investment_json($report['metrics_json']);$report['use_of_funds']=mg_investment_json($report['use_of_funds_json']);$report['milestones']=mg_investment_json($report['milestones_json']);$report['risks']=mg_investment_json($report['risks_json']);unset($report['metrics_json'],$report['use_of_funds_json'],$report['milestones_json'],$report['risks_json']);$reports[]=$report;}}
        $actualQ=$pdo->prepare('SELECT public_id,budget_category,amount_cents,spent_at,description,evidence_reference FROM investment_use_of_funds_actuals WHERE round_id=? AND investor_visible=1 ORDER BY spent_at DESC,id DESC');$actualQ->execute([$roundId]);$reconQ=$pdo->prepare('SELECT snapshot_type,signed_cents,verified_funded_cents,target_raise_cents,available_capacity_cents,modeled_dilution_bps,actual_estimated_dilution_bps,output_json,created_at FROM investment_cap_reconciliation_snapshots WHERE round_id=? ORDER BY created_at DESC LIMIT 1');$reconQ->execute([$roundId]);$recon=$reconQ->fetch(PDO::FETCH_ASSOC);if($recon){$recon['output']=mg_investment_json($recon['output_json']);unset($recon['output_json']);}
        $portalRound['relations']=['closing'=>$record,'packets'=>$packets,'documents'=>$documents,'reports'=>$reports,'use_of_funds_actuals'=>$actualQ->fetchAll(PDO::FETCH_ASSOC),'reconciliation'=>$recon];
    }
    unset($portalRound);return $base;
}

function mg_investment_portal_submit_diligence_v4(PDO $pdo,array $user,array $input): array
{
    mg_investment_portal_submit_diligence($pdo,$user,$input);return mg_investment_portal_data_v4($pdo,$user);
}

function mg_investment_portal_submit_interest_v4(PDO $pdo,array $user,array $input): array
{
    mg_investment_portal_submit_interest($pdo,$user,$input);return mg_investment_portal_data_v4($pdo,$user);
}

function mg_investment_portal_event_v4(PDO $pdo,array $user,array $input): array
{
    $event=(string)($input['event_type']??'');if(!in_array($event,['report_view','closing_document_open'],true))return mg_investment_portal_event_v3($pdo,$user,$input);$round=mg_investment_closing_round($pdo,mg_investment_text($input['round_id']??'',36,36,'Round identifier'));$subjectId=mg_investment_text($input['subject_id']??'',36,36,'Subject identifier');$userId=(int)$user['id'];$funded=$pdo->prepare('SELECT COUNT(*) FROM investor_closing_records WHERE round_id=? AND investor_user_id=? AND verified_funded_cents>0');$funded->execute([(int)$round['id'],$userId]);if((int)$funded->fetchColumn()<1)throw new MgInvestmentException('Funded-investor access is required.',403);
    if($event==='closing_document_open'){$q=$pdo->prepare('SELECT COUNT(*) FROM investment_closing_documents d INNER JOIN investment_closing_packets p ON p.id=d.packet_id WHERE d.public_id=? AND p.round_id=? AND p.investor_user_id=? AND d.status IN ("approved","executed","complete","not_applicable")');$q->execute([$subjectId,(int)$round['id'],$userId]);if((int)$q->fetchColumn()<1)throw new MgInvestmentException('Closing document is not available.',404);}else{$q=$pdo->prepare('SELECT COUNT(*) FROM investment_reporting_snapshots s INNER JOIN investment_reporting_periods p ON p.id=s.reporting_period_id WHERE s.public_id=? AND p.round_id=? AND s.status="published" AND p.status="published"');$q->execute([$subjectId,(int)$round['id']]);if((int)$q->fetchColumn()<1)throw new MgInvestmentException('Investor report is not available.',404);}mg_investment_portal_log_v4($pdo,$userId,(int)$round['id'],$event,$subjectId,['title'=>mg_investment_text($input['title']??'',220)]);return ['recorded'=>true];
}
