<?php
declare(strict_types=1);

function mg_investment_qa_save(PDO $pdo,array $actor,array $input): array
{
    mg_investment_require_permission($actor,'admin.investment.diligence.manage');$publicId=trim((string)($input['qa_id']??''));$roundId=null;$roundPublicId='';if(!empty($input['round_id'])){$round=mg_investment_diligence_round($pdo,mg_investment_text($input['round_id'],36,36,'Round identifier'));$roundId=(int)$round['id'];$roundPublicId=(string)$round['public_id'];}
    $status=(string)($input['status']??'draft');if(!in_array($status,['draft','internal_review','legal_review','approved','published','archived'],true))throw new MgInvestmentException('Invalid Q&A status.');$requiresLegal=mg_investment_bool($input['requires_legal_review']??false);if($status==='published'&&!mg_investment_has_permission($actor,'admin.investment.diligence.publish'))throw new MgInvestmentException('Publishing Q&A requires publishing permission.',403);
    $question=mg_investment_text($input['question']??'',500,4,'Question');$answer=mg_investment_long_text($input['answer']??'',30000,2,'Answer');
    if($publicId===''){$publicId=mg_investment_uuid();$stmt=$pdo->prepare('INSERT INTO investment_qa_entries (public_id,round_id,category,question,answer,status,requires_legal_review,source_request_id,version_number,published_at,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,1,IF(?="published",NOW(),NULL),?,?,NOW(),NOW())');$stmt->execute([$publicId,$roundId,mg_investment_text($input['category']??'general',80,2,'Category'),$question,$answer,$status,$requiresLegal?1:0,null,$status,(int)$actor['id'],(int)$actor['id']]);}else{$q=$pdo->prepare('SELECT * FROM investment_qa_entries WHERE public_id=? LIMIT 1');$q->execute([mg_investment_text($publicId,36,36,'Q&A identifier')]);$existing=$q->fetch(PDO::FETCH_ASSOC);if(!$existing)throw new MgInvestmentException('Q&A entry not found.',404);$version=(int)$existing['version_number']+1;$stmt=$pdo->prepare('UPDATE investment_qa_entries SET round_id=?,category=?,question=?,answer=?,status=?,requires_legal_review=?,version_number=?,published_at=IF(?="published",COALESCE(published_at,NOW()),published_at),updated_by_user_id=?,updated_at=NOW() WHERE id=?');$stmt->execute([$roundId,mg_investment_text($input['category']??'general',80,2,'Category'),$question,$answer,$status,$requiresLegal?1:0,$version,$status,(int)$actor['id'],(int)$existing['id']]);}
    mg_audit('investment_qa_saved','investment_qa',['qa_id'=>$publicId,'status'=>$status],(int)$actor['id']);return mg_investment_diligence_dashboard($pdo,$roundPublicId!==''?['round_id'=>$roundPublicId]:[]);
}

function mg_investment_meeting_save(PDO $pdo,array $actor,array $input): array
{
    mg_investment_require_permission($actor,'admin.investment.diligence.manage');$publicId=trim((string)($input['meeting_id']??''));$investorUserId=(int)($input['investor_user_id']??0);if($investorUserId<1)throw new MgInvestmentException('Select an investor.');$roundId=null;$roundPublicId='';if(!empty($input['round_id'])){$round=mg_investment_diligence_round($pdo,mg_investment_text($input['round_id'],36,36,'Round identifier'));$roundId=(int)$round['id'];$roundPublicId=(string)$round['public_id'];}
    $type=(string)($input['meeting_type']??'intro');$status=(string)($input['status']??'planned');$sentiment=(string)($input['sentiment']??'unknown');if(!in_array($type,['intro','follow_up','demo','diligence','terms','closing','other'],true)||!in_array($status,['planned','confirmed','completed','cancelled','no_show'],true)||!in_array($sentiment,['unknown','negative','neutral','positive','strong'],true))throw new MgInvestmentException('Invalid meeting type, status, or sentiment.');$starts=mg_investment_date($input['starts_at']??null);if($starts===null)throw new MgInvestmentException('Meeting start time is required.');$ends=mg_investment_date($input['ends_at']??null);$attendees=array_values(array_filter(array_map(static fn($v)=>mg_investment_text($v,180),is_array($input['attendees']??null)?$input['attendees']:preg_split('/[,\n]+/',(string)($input['attendees']??'')))));
    $values=[$roundId,$investorUserId,$type,$status,$starts,$ends,mg_investment_text($input['location']??'',300)?:null,mg_investment_url($input['meeting_url']??''),mg_investment_json_encode($attendees),mg_investment_long_text($input['agenda']??'',8000)?:null,mg_investment_long_text($input['preparation_notes']??'',12000)?:null,mg_investment_long_text($input['outcome']??'',12000)?:null,$sentiment,mg_investment_text($input['next_step']??'',500)?:null,(int)$actor['id']];
    if($publicId===''){$publicId=mg_investment_uuid();$stmt=$pdo->prepare('INSERT INTO investor_meetings (public_id,round_id,investor_user_id,meeting_type,status,starts_at,ends_at,location,meeting_url,attendees_json,agenda,preparation_notes,outcome,sentiment,next_step,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())');$stmt->execute(array_merge([$publicId],$values,[(int)$actor['id']]));}else{$stmt=$pdo->prepare('UPDATE investor_meetings SET round_id=?,investor_user_id=?,meeting_type=?,status=?,starts_at=?,ends_at=?,location=?,meeting_url=?,attendees_json=?,agenda=?,preparation_notes=?,outcome=?,sentiment=?,next_step=?,updated_by_user_id=?,updated_at=NOW() WHERE public_id=?');$stmt->execute(array_merge($values,[mg_investment_text($publicId,36,36,'Meeting identifier')]));}
    mg_investment_pipeline_activity($pdo,$investorUserId,$roundId,'meeting',$status==='completed'?'Investor meeting completed':'Investor meeting saved',mg_investment_text($input['next_step']??'',500),(int)$actor['id'],['meeting_id'=>$publicId,'meeting_type'=>$type,'status'=>$status]);mg_audit('investor_meeting_saved','investor_meeting',['meeting_id'=>$publicId,'status'=>$status],(int)$actor['id']);return mg_investment_diligence_dashboard($pdo,$roundPublicId!==''?['round_id'=>$roundPublicId]:[]);
}

function mg_investment_communication_recipients(PDO $pdo,array $communication): array
{
    $audience=(string)$communication['audience_type'];$roundId=$communication['round_id']!==null?(int)$communication['round_id']:null;
    if($audience==='approved_investors')return $pdo->query('SELECT user_id FROM investor_profiles WHERE status="active"')->fetchAll(PDO::FETCH_COLUMN);
    if($roundId===null)return [];
    if($audience==='selected_investors'){$q=$pdo->prepare('SELECT investor_user_id FROM investment_round_access WHERE round_id=? AND status="granted" AND (expires_at IS NULL OR expires_at>NOW())');$q->execute([$roundId]);return $q->fetchAll(PDO::FETCH_COLUMN);}
    if($audience==='funded_investors'){$q=$pdo->prepare('SELECT investor_user_id FROM investor_round_interests WHERE round_id=? AND funded_cents>0 AND status NOT IN ("declined","passed","archived")');$q->execute([$roundId]);return $q->fetchAll(PDO::FETCH_COLUMN);}
    return [];
}

function mg_investment_communication_save(PDO $pdo,array $actor,array $input): array
{
    mg_investment_require_permission($actor,'admin.investment.diligence.manage');$publicId=trim((string)($input['communication_id']??''));$roundId=null;$roundPublicId='';if(!empty($input['round_id'])){$round=mg_investment_diligence_round($pdo,mg_investment_text($input['round_id'],36,36,'Round identifier'));$roundId=(int)$round['id'];$roundPublicId=(string)$round['public_id'];}
    $type=(string)($input['communication_type']??'round_update');$audience=(string)($input['audience_type']??'approved_investors');$status=(string)($input['status']??'draft');if(!in_array($type,['individual_follow_up','selected_investor_update','round_update','monthly_report','milestone_update','document_announcement','important_notice','meeting_recap'],true)||!in_array($audience,['individual','selected_investors','approved_investors','funded_investors'],true)||!in_array($status,['draft','internal_review','legal_review','approved','published','archived'],true))throw new MgInvestmentException('Invalid communication type, audience, or status.');if($status==='published'&&!mg_investment_has_permission($actor,'admin.investment.diligence.publish'))throw new MgInvestmentException('Publishing communications requires publishing permission.',403);if($audience==='individual')throw new MgInvestmentException('Individual communications are drafted in the pipeline and are not portal-published in this phase.');
    $pdo->beginTransaction();try{
        if($publicId===''){$publicId=mg_investment_uuid();$stmt=$pdo->prepare('INSERT INTO investor_communications (public_id,round_id,communication_type,audience_type,subject,body,status,requires_legal_review,published_at,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,IF(?="published",NOW(),NULL),?,?,NOW(),NOW())');$stmt->execute([$publicId,$roundId,$type,$audience,mg_investment_text($input['subject']??'',220,2,'Subject'),mg_investment_long_text($input['body']??'',30000,2,'Communication body'),$status,mg_investment_bool($input['requires_legal_review']??false)?1:0,$status,(int)$actor['id'],(int)$actor['id']]);$communicationId=(int)$pdo->lastInsertId();}else{$q=$pdo->prepare('SELECT * FROM investor_communications WHERE public_id=? LIMIT 1 FOR UPDATE');$q->execute([mg_investment_text($publicId,36,36,'Communication identifier')]);$existing=$q->fetch(PDO::FETCH_ASSOC);if(!$existing)throw new MgInvestmentException('Communication not found.',404);$communicationId=(int)$existing['id'];$stmt=$pdo->prepare('UPDATE investor_communications SET round_id=?,communication_type=?,audience_type=?,subject=?,body=?,status=?,requires_legal_review=?,published_at=IF(?="published",COALESCE(published_at,NOW()),published_at),updated_by_user_id=?,updated_at=NOW() WHERE id=?');$stmt->execute([$roundId,$type,$audience,mg_investment_text($input['subject']??'',220,2,'Subject'),mg_investment_long_text($input['body']??'',30000,2,'Communication body'),$status,mg_investment_bool($input['requires_legal_review']??false)?1:0,$status,(int)$actor['id'],$communicationId]);}
        if($status==='published'){$q=$pdo->prepare('SELECT * FROM investor_communications WHERE id=?');$q->execute([$communicationId]);$communication=$q->fetch(PDO::FETCH_ASSOC);$recipients=mg_investment_communication_recipients($pdo,$communication?:[]);$insert=$pdo->prepare('INSERT INTO investor_communication_recipients (communication_id,investor_user_id,status,published_at) VALUES (?,? ,"published",NOW()) ON DUPLICATE KEY UPDATE status="published",published_at=COALESCE(published_at,NOW())');foreach($recipients as $userId)$insert->execute([$communicationId,(int)$userId]);}
        $pdo->commit();
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    mg_audit('investor_communication_saved','investor_communication',['communication_id'=>$publicId,'status'=>$status,'audience'=>$audience],(int)$actor['id']);return mg_investment_diligence_dashboard($pdo,$roundPublicId!==''?['round_id'=>$roundPublicId]:[]);
}

function mg_investment_interest_review(PDO $pdo,array $actor,array $input): array
{
    mg_investment_require_permission($actor,'admin.investment.diligence.manage');$publicId=mg_investment_text($input['submission_id']??'',36,36,'Submission identifier');$status=(string)($input['status']??'reviewing');if(!in_array($status,['submitted','reviewing','accepted_for_discussion','declined','converted','withdrawn'],true))throw new MgInvestmentException('Invalid interest status.');$q=$pdo->prepare('SELECT s.*,r.public_id AS round_public_id FROM investor_interest_submissions s INNER JOIN investment_rounds r ON r.id=s.round_id WHERE s.public_id=? LIMIT 1');$q->execute([$publicId]);$row=$q->fetch(PDO::FETCH_ASSOC);if(!$row)throw new MgInvestmentException('Interest submission not found.',404);$pdo->prepare('UPDATE investor_interest_submissions SET status=?,reviewed_by_user_id=?,reviewed_at=NOW(),internal_notes=?,updated_at=NOW() WHERE id=?')->execute([$status,(int)$actor['id'],mg_investment_long_text($input['internal_notes']??'',12000)?:null,(int)$row['id']]);mg_investment_pipeline_activity($pdo,(int)$row['investor_user_id'],(int)$row['round_id'],'commitment_update','Non-binding interest reviewed','Status: '.ucwords(str_replace('_',' ',$status)),(int)$actor['id'],['submission_id'=>$publicId]);mg_audit('investor_interest_reviewed','investor_interest',['submission_id'=>$publicId,'status'=>$status],(int)$actor['id']);return mg_investment_diligence_dashboard($pdo,['round_id'=>$row['round_public_id']]);
}
