<?php
declare(strict_types=1);

require_once __DIR__ . '/includes/admin-auth.php';
require_once __DIR__ . '/includes/share-market/admin-actions.php';

$user = mg_require_admin_page_any(['share_market.admin']);
$page_title = 'Share Market Program Review | Microgifter';
$page_section = 'account';
$header_mode = 'account';
$page_styles = ['/assets/css/admin-dashboard.css'];
$page_scripts = ['/assets/js/account.js', '/assets/js/share-market-program-review.js'];
require __DIR__ . '/includes/header.php';
?>
<style>
.sm-review{display:grid;gap:18px;color:#0f172a}.sm-review *{box-sizing:border-box}.sm-review-hero{padding:28px;border:1px solid #dbe5f1;border-radius:26px;background:linear-gradient(135deg,#fff,#f8fafc);box-shadow:0 20px 60px rgba(15,23,42,.07)}.sm-review-kicker{display:inline-flex;width:max-content;min-height:26px;align-items:center;padding:0 10px;border-radius:999px;background:#050505;color:#fff;font-size:10px;font-weight:950;letter-spacing:.12em;text-transform:uppercase}.sm-review h1{margin:16px 0 0;color:#050505;font-size:clamp(34px,4vw,58px);line-height:.94;letter-spacing:-.07em;font-weight:950}.sm-review p{margin:12px 0 0;color:#475569;font-size:13px;line-height:1.5;font-weight:650}.sm-review-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.sm-review-panel{padding:22px;border:1px solid #dbe5f1;border-radius:22px;background:#fff;box-shadow:0 14px 42px rgba(15,23,42,.04)}.sm-review-panel h2{margin:0;color:#050505;font-size:26px;line-height:1;letter-spacing:-.055em;font-weight:950}.sm-review-list{display:grid;gap:10px;margin-top:16px}.sm-review-card{display:grid;gap:9px;padding:15px;border:1px solid #e2e8f0;border-radius:16px;background:#f8fafc}.sm-review-card small{color:#64748b;font-size:9px;font-weight:950;letter-spacing:.08em;text-transform:uppercase}.sm-review-card strong{color:#0f172a;font-size:15px;font-weight:950}.sm-review-card span{color:#64748b;font-size:11px;line-height:1.4;font-weight:700}.sm-review-actions{display:flex;flex-wrap:wrap;gap:8px}.sm-review-btn{display:inline-flex;align-items:center;justify-content:center;min-height:36px;padding:0 11px;border:1px solid #dbe5f1;border-radius:10px;background:#fff;color:#111827;cursor:pointer;font-size:10px;font-weight:950}.sm-review-btn.primary{background:#050505;color:#fff;border-color:#050505}.sm-review-btn.danger{background:#fff1f2;color:#9f1239;border-color:#fecdd3}.sm-review-status{min-height:20px;color:#475569;font-size:12px;font-weight:750}.sm-review-status.error{color:#b91c1c}.sm-review-status.success{color:#166534}.sm-modal[hidden]{display:none}.sm-modal{position:fixed;inset:0;z-index:10040;display:grid;place-items:center;padding:20px}.sm-modal-backdrop{position:absolute;inset:0;border:0;background:rgba(2,6,23,.72);backdrop-filter:blur(8px)}.sm-modal-card{position:relative;z-index:1;width:min(680px,100%);padding:22px;border-radius:22px;background:#fff;box-shadow:0 30px 100px rgba(2,6,23,.45)}.sm-modal-card h3{margin:0;color:#050505;font-size:24px;font-weight:950;letter-spacing:-.05em}.sm-field{display:grid;gap:7px;margin-top:14px}.sm-field label{font-size:10px;font-weight:950;letter-spacing:.08em;text-transform:uppercase;color:#334155}.sm-field textarea{width:100%;min-height:120px;padding:10px 12px;border:1px solid #cbd5e1;border-radius:11px;font:inherit;font-size:13px;font-weight:650;resize:vertical}@media(max-width:880px){.sm-review-grid{grid-template-columns:1fr}}
</style>
<section class="mg-app-shell mg-account-app">
  <aside class="mg-app-sidebar mg-account-left"><div class="mg-app-sidebar-brand"><a class="mg-brand mg-sidebar-logo" href="/index.php" aria-label="Microgifter home"><img src="/images/logo_main_drk.png" alt="Microgifter"><span class="mg-sidebar-logo-text">Microgifter</span></a></div><nav class="mg-app-side-nav mg-account-nav" aria-label="Share Market administration"><a href="/account-share-market-admin.php"><strong>Share Market Admin</strong><span>Pool controls</span></a><a class="is-active" href="/account-share-market-review.php"><strong>Program Review</strong><span>Enrollment and series review</span></a><a href="/account-share-market-approvals.php"><strong>Approval Queue</strong><span>Maker-checker controls</span></a></nav></aside>
  <main class="mg-app-workspace mg-account-main sm-review" data-sm-review>
    <section class="sm-review-hero"><span class="sm-review-kicker">Admin Review</span><h1>Review participant requests and submitted series.</h1><p>Approving a request moves it to an approved state only. It does not mint, sell, list, redeem, or launch shares. Live execution remains locked until the final SQL and transaction layer exist.</p></section>
    <section class="sm-review-grid"><article class="sm-review-panel"><h2>Enrollment queue</h2><div class="sm-review-list" data-sm-enrollment-review><div class="sm-review-card"><strong>Loading…</strong></div></div></article><article class="sm-review-panel"><h2>Series queue</h2><div class="sm-review-list" data-sm-series-review><div class="sm-review-card"><strong>Loading…</strong></div></div></article></section>
    <div class="sm-review-status" data-sm-review-status></div>
  </main>
</section>
<div class="sm-modal" data-sm-review-modal hidden><button class="sm-modal-backdrop" type="button" data-sm-review-close></button><form class="sm-modal-card" data-sm-decision-form><h3 data-sm-modal-title>Review decision</h3><input type="hidden" name="target_type"><input type="hidden" name="participant_id"><input type="hidden" name="participant_user_id"><input type="hidden" name="series_id"><input type="hidden" name="decision"><div class="sm-field"><label>Admin note</label><textarea name="note" required maxlength="1000"></textarea></div><div class="sm-review-status" data-sm-modal-status></div><div class="sm-review-actions"><button class="sm-review-btn primary" type="submit">Record decision</button><button class="sm-review-btn" type="button" data-sm-review-close>Cancel</button></div></form></div>
<?php require __DIR__ . '/includes/footer.php'; ?>
