<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/feed/_feed.php';
mg_require_method('GET');
$slug=trim((string)($_GET['slug']??''));if($slug==='')mg_fail('Storefront not found.',404);$pdo=mg_db();
$storeStmt=$pdo->prepare("SELECT ms.* FROM merchant_storefronts ms WHERE ms.slug=? AND ms.status = 'published' LIMIT 1");$storeStmt->execute([$slug]);$store=$storeStmt->fetch();if(!$store)mg_fail('Storefront not found.',404);
$revisionStmt=$pdo->prepare("SELECT r.* FROM merchant_storefront_states s INNER JOIN merchant_storefront_revisions r ON r.id=s.published_revision_id WHERE s.storefront_id=? AND r.revision_status='published' LIMIT 1");$revisionStmt->execute([(int)$store['id']]);$revision=$revisionStmt->fetch();
if($revision){
 $productsStmt=$pdo->prepare("SELECT cp.public_id,cp.slug,cp.product_type,cpv.public_id version_id,cpv.title,cpv.description,cpv.unit_value_cents,cpv.currency,rp.is_featured,rp.sort_order,cover.public_id cover_asset_id
 FROM merchant_storefront_revision_products rp INNER JOIN catalog_products cp ON cp.id=rp.catalog_product_id AND cp.status='published' INNER JOIN catalog_product_versions cpv ON cpv.id=cp.current_version_id AND cpv.version_status='published' LEFT JOIN catalog_product_version_assets pva ON pva.product_version_id=cpv.id AND pva.role='cover' LEFT JOIN catalog_assets cover ON cover.id=pva.asset_id WHERE rp.storefront_revision_id=? AND rp.visibility='visible' ORDER BY rp.is_featured DESC,rp.sort_order ASC,rp.id ASC");$productsStmt->execute([(int)$revision['id']]);
 $assetPublic=static function(PDO $pdo,mixed $id):?string{if(!$id)return null;$q=$pdo->prepare('SELECT public_id FROM catalog_assets WHERE id=?');$q->execute([(int)$id]);$v=$q->fetchColumn();return $v?(string)$v:null;};$logo=$assetPublic($pdo,$revision['logo_asset_id']);$cover=$assetPublic($pdo,$revision['cover_asset_id']);
 $profile=['public_id'=>$store['public_id'],'slug'=>$store['slug'],'display_name'=>$revision['display_name'],'headline'=>$revision['headline'],'description'=>$revision['description'],'logo_url'=>$logo?'/api/public/media.php?asset='.rawurlencode($logo):null,'cover_url'=>$cover?'/api/public/media.php?asset='.rawurlencode($cover):null,'contact'=>$revision['contact_json']?json_decode((string)$revision['contact_json'],true):[],'theme'=>$revision['theme_json']?json_decode((string)$revision['theme_json'],true):[]];
}else{
 $productsStmt=$pdo->prepare("SELECT cp.public_id,cp.slug,cp.product_type,cpv.public_id version_id,cpv.title,cpv.description,cpv.unit_value_cents,cpv.currency,0 is_featured,0 sort_order,cover.public_id cover_asset_id FROM catalog_products cp INNER JOIN catalog_product_versions cpv ON cpv.id=cp.current_version_id AND cpv.version_status='published' LEFT JOIN catalog_product_version_assets pva ON pva.product_version_id=cpv.id AND pva.role='cover' LEFT JOIN catalog_assets cover ON cover.id=pva.asset_id WHERE cp.merchant_user_id=? AND cp.status='published' ORDER BY cp.published_at DESC,cp.id DESC");$productsStmt->execute([(int)$store['merchant_user_id']]);
 $profile=['public_id'=>$store['public_id'],'slug'=>$store['slug'],'display_name'=>$store['display_name'],'headline'=>$store['headline'],'description'=>$store['description'],'logo_url'=>$store['logo_asset_id']?'/api/public/media.php?asset='.rawurlencode((string)$store['logo_asset_id']):null,'cover_url'=>$store['cover_asset_id']?'/api/public/media.php?asset='.rawurlencode((string)$store['cover_asset_id']):null,'contact'=>[],'theme'=>[]];
}
$products=array_map(static function(array $p):array{$p['cover_url']=$p['cover_asset_id']?'/api/public/media.php?asset='.rawurlencode((string)$p['cover_asset_id']):null;$p['product_url']='/product.php?p='.rawurlencode((string)$p['slug']);return $p;},$productsStmt->fetchAll());mg_ok(['storefront'=>$profile,'products'=>$products]);
