<?php
declare(strict_types=1);

function mg_creator_campaign_application_save_creator(PDO $pdo,array $user,string $campaignPublicId,array $input,bool $submit):array
{
    $context=mg_creator_campaign_creator_context($pdo,$user,'creator.campaign_applications.manage_own');$creatorUserId=(int)$context['creator_user_id'];$creatorProfileId=(int)$context['creator_profile_id'];$actorId=(int)$context['actor_user_id'];
    $coverNote=mg_creator_campaign_string($input['cover_note']??null,'cover_note',8000);$portfolioUrl=mg_creator_campaign_string($input['portfolio_url']??null,'portfolio_url',600);if($portfolioUrl!==null&&filter_var($portfolioUrl,FILTER_VALIDATE_URL)===false)throw new InvalidArgumentException('Portfolio URL must be valid.');$answers=is_array($input['answers']??null)?$input['answers']:[];
    mg_creator_campaign_assert_transaction_boundary($pdo);$pdo->beginTransaction();
    try{
        $campaign=mg_creator_campaign_participation_campaign_by_public_id($pdo,$campaignPublicId,null,true);if(!mg_creator_campaign_participation_campaign_accepts_applications($campaign))throw new DomainException('This campaign is not accepting applications.');mg_creator_campaign_participation_require_application_capacity($pdo,$campaign,$creatorUserId);
        $stmt=$pdo->prepare('SELECT * FROM creator_campaign_applications WHERE campaign_id=? AND creator_user_id=? LIMIT 1 FOR UPDATE');$stmt->execute([(int)$campaign['id'],$creatorUserId]);$application=$stmt->fetch(PDO::FETCH_ASSOC);$fromStatus=$application['status']??null;
        if($application){
            if(!in_array((string)$application['status'],['draft','information_requested','withdrawn'],true))throw new DomainException('This application can no longer be edited.');$expectedLock=(int)($input['expected_lock_version']??0);mg_creator_campaign_participation_require_expected_lock($application,$expectedLock);if($submit)mg_creator_campaign_assert_transition('application',(string)$application['status'],'submitted');$applicationId=(int)$application['id'];$publicId=(string)$application['public_id'];$toStatus=$submit?'submitted':(string)$application['status'];$update=$pdo->prepare("UPDATE creator_campaign_applications SET status=?,cover_note=?,portfolio_url=?,submitted_at=IF(?=1,NOW(),submitted_at),creator_snapshot_json=?,updated_by_user_id=?,lock_version=lock_version+1,updated_at=NOW() WHERE id=? AND lock_version=?");$update->execute([$toStatus,$coverNote,$portfolioUrl,$submit?1:0,mg_creator_campaign_json_encode(mg_creator_campaign_participation_creator_snapshot($pdo,$creatorUserId)),$actorId,$applicationId,$expectedLock]);if($update->rowCount()!==1)throw new DomainException('Application save lost its optimistic lock.');
        }else{
            $insert=$pdo->prepare("INSERT INTO creator_campaign_applications(public_id,campaign_id,creator_user_id,creator_profile_id,status,cover_note,portfolio_url,creator_snapshot_json,submitted_at,lock_version,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,IF(?=1,NOW(),NULL),1,?,?,NOW(),NOW())");$publicId=mg_creator_campaign_public_id('cca');$insert->execute([$publicId,(int)$campaign['id'],$creatorUserId,$creatorProfileId,$submit?'submitted':'draft',$coverNote,$portfolioUrl,mg_creator_campaign_json_encode(mg_creator_campaign_participation_creator_snapshot($pdo,$creatorUserId)),$submit?1:0,$actorId,$actorId]);$applicationId=(int)$pdo->lastInsertId();
        }
        mg_creator_campaign_application_write_answers($pdo,$applicationId,(int)$campaign['id'],$answers,$submit);
        $finalStatus=$submit?'submitted':($fromStatus??'draft');$participant=null;$agreement=null;$automaticEvaluation=null;
        if($submit&&!empty($campaign['automatic_acceptance'])){
            $automaticEvaluation=mg_creator_campaign_evaluate_automatic_acceptance($pdo,$campaign,$creatorUserId);
            if(!empty($automaticEvaluation['eligible'])){
                $eligibility=mg_creator_campaign_require_creator_eligibility($pdo,$creatorUserId);$participant=mg_creator_campaign_participant_upsert_pending($pdo,$campaign,$eligibility,'application',$applicationId,null,$actorId,'Automatically accepted by campaign eligibility rules.');$agreement=mg_creator_campaign_agreement_ensure_offered($pdo,$campaign,$participant,(int)($campaign['campaign_manager_user_id']??$campaign['created_by_user_id']??$actorId));$pdo->prepare("UPDATE creator_campaign_applications SET status='approved',decision_note='Automatically accepted by campaign eligibility rules.',reviewed_at=NOW(),decided_at=NOW(),updated_by_user_id=?,lock_version=lock_version+1,updated_at=NOW() WHERE id=?")->execute([$actorId,$applicationId]);$finalStatus='approved';
            }
        }
        mg_creator_campaign_participation_event($pdo,['campaign_id'=>(int)$campaign['id'],'application_id'=>$applicationId,'participant_id'=>$participant?(int)$participant['id']:null,'actor_user_id'=>$actorId,'event_type'=>$finalStatus==='approved'?'application.auto_approved':($submit?'application.submitted':'application.saved'),'from_status'=>$fromStatus,'to_status'=>$finalStatus,'reason'=>$finalStatus==='approved'?'Campaign automatic acceptance rules passed.':null,'context'=>['automatic_acceptance_enabled'=>!empty($campaign['automatic_acceptance']),'automatic_evaluation'=>$automaticEvaluation===null?null:['eligible'=>(bool)$automaticEvaluation['eligible'],'checks'=>$automaticEvaluation['checks'],'capacity'=>$automaticEvaluation['capacity']]]]);
        $pdo->commit();$result=mg_creator_campaign_participation_application_by_public_id($pdo,$publicId,(int)$campaign['id'],$creatorUserId);$result['answers']=mg_creator_campaign_participation_answer_rows($pdo,(int)$result['id']);$result['participant']=$participant;$result['agreement']=$agreement;return $result;
    }catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
}

function mg_creator_campaign_application_withdraw_creator(PDO $pdo,array $user,string $applicationPublicId,array $input):array
{
    $context=mg_creator_campaign_creator_context($pdo,$user,'creator.campaign_applications.manage_own');$creatorUserId=(int)$context['creator_user_id'];$reason=mg_creator_campaign_string($input['reason']??null,'reason',1000);$expectedLock=(int)($input['expected_lock_version']??0);mg_creator_campaign_assert_transaction_boundary($pdo);$pdo->beginTransaction();
    try{$application=mg_creator_campaign_participation_application_by_public_id($pdo,$applicationPublicId,null,$creatorUserId,true);mg_creator_campaign_participation_require_expected_lock($application,$expectedLock);$from=(string)$application['status'];mg_creator_campaign_assert_transition('application',$from,'withdrawn');$update=$pdo->prepare("UPDATE creator_campaign_applications SET status='withdrawn',withdrawn_at=NOW(),updated_by_user_id=?,lock_version=lock_version+1,updated_at=NOW() WHERE id=? AND lock_version=?");$update->execute([(int)$context['actor_user_id'],(int)$application['id'],$expectedLock]);if($update->rowCount()!==1)throw new DomainException('Application withdrawal lost its optimistic lock.');mg_creator_campaign_participation_event($pdo,['campaign_id'=>(int)$application['campaign_id'],'application_id'=>(int)$application['id'],'actor_user_id'=>(int)$context['actor_user_id'],'event_type'=>'application.withdrawn','from_status'=>$from,'to_status'=>'withdrawn','reason'=>$reason,'idempotency_key'=>$input['idempotency_key']??null]);$pdo->commit();return mg_creator_campaign_participation_application_by_public_id($pdo,$applicationPublicId,null,$creatorUserId);}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
}

function mg_creator_campaign_application_list_creator(PDO $pdo,array $user):array
{
    $context=mg_creator_campaign_creator_context($pdo,$user,'creator.campaign_applications.manage_own');$stmt=$pdo->prepare("SELECT a.public_id,a.status,a.cover_note,a.portfolio_url,a.decision_note,a.submitted_at,a.reviewed_at,a.decided_at,a.withdrawn_at,a.lock_version,a.updated_at,cc.public_id campaign_public_id,cc.title campaign_title,cc.objective,cc.category,cc.starts_at,cc.ends_at,mw.display_name merchant_name FROM creator_campaign_applications a INNER JOIN creator_campaigns cc ON cc.id=a.campaign_id INNER JOIN merchant_workspaces mw ON mw.id=cc.workspace_id WHERE a.creator_user_id=? ORDER BY a.updated_at DESC,a.id DESC");$stmt->execute([(int)$context['creator_user_id']]);return ['items'=>$stmt->fetchAll(PDO::FETCH_ASSOC)?:[]];
}
