<?php
declare(strict_types=1);

function mg_creator_campaign_deliverable_dashboard_merchant(PDO $pdo,array $user):array
{
    $context=mg_creator_campaign_deliverable_merchant_context($pdo,$user,'merchant.creator_deliverables.view');$workspaceId=(int)$context['workspace_id'];
    $metrics=[];$queries=['deliverables'=>"SELECT COUNT(*) FROM creator_campaign_deliverables d INNER JOIN creator_campaigns cc ON cc.id=d.campaign_id WHERE cc.workspace_id=? AND d.status<>'retired'",'assignments'=>"SELECT COUNT(*) FROM creator_campaign_participant_deliverables pd INNER JOIN creator_campaigns cc ON cc.id=pd.campaign_id WHERE cc.workspace_id=? AND pd.status NOT IN ('waived','cancelled')",'awaiting_review'=>"SELECT COUNT(*) FROM creator_campaign_submissions s INNER JOIN creator_campaigns cc ON cc.id=s.campaign_id WHERE cc.workspace_id=? AND s.status IN ('submitted','under_review','proof_submitted')",'revision_requested'=>"SELECT COUNT(*) FROM creator_campaign_submissions s INNER JOIN creator_campaigns cc ON cc.id=s.campaign_id WHERE cc.workspace_id=? AND s.status='revision_requested'",'overdue'=>"SELECT COUNT(*) FROM creator_campaign_participant_deliverables pd INNER JOIN creator_campaigns cc ON cc.id=pd.campaign_id WHERE cc.workspace_id=? AND pd.due_at<NOW() AND pd.status NOT IN ('approved','verified','waived','cancelled')"];
    foreach($queries as $key=>$sql){$stmt=$pdo->prepare($sql);$stmt->execute([$workspaceId]);$metrics[$key]=(int)$stmt->fetchColumn();}
    $campaigns=$pdo->prepare("SELECT cc.public_id campaign_public_id,cc.title campaign_title,cc.status,COUNT(DISTINCT d.id) deliverable_count,COUNT(DISTINCT pd.id) assignment_count,SUM(CASE WHEN s.status IN ('submitted','under_review','proof_submitted') THEN 1 ELSE 0 END) awaiting_review FROM creator_campaigns cc LEFT JOIN creator_campaign_deliverables d ON d.campaign_id=cc.id AND d.status<>'retired' LEFT JOIN creator_campaign_participant_deliverables pd ON pd.campaign_id=cc.id LEFT JOIN creator_campaign_submissions s ON s.participant_deliverable_id=pd.id WHERE cc.workspace_id=? GROUP BY cc.id ORDER BY cc.updated_at DESC LIMIT 100");$campaigns->execute([$workspaceId]);return ['metrics'=>$metrics,'campaigns'=>$campaigns->fetchAll(PDO::FETCH_ASSOC)?:[]];
}

function mg_creator_campaign_deliverable_list_merchant(PDO $pdo,array $user,array $filters=[]):array
{
    $context=mg_creator_campaign_deliverable_merchant_context($pdo,$user,'merchant.creator_deliverables.view');$workspaceId=(int)$context['workspace_id'];$where=['cc.workspace_id=?'];$params=[$workspaceId];$campaignId=trim((string)($filters['campaign_id']??''));$status=trim((string)($filters['status']??''));if($campaignId!==''){$where[]='cc.public_id=?';$params[]=$campaignId;}if($status!==''){$where[]='d.status=?';$params[]=$status;}$stmt=$pdo->prepare('SELECT d.*,cc.public_id campaign_public_id,cc.title campaign_title,COUNT(pd.id) assignment_count FROM creator_campaign_deliverables d INNER JOIN creator_campaigns cc ON cc.id=d.campaign_id LEFT JOIN creator_campaign_participant_deliverables pd ON pd.campaign_deliverable_id=d.id WHERE '.implode(' AND ',$where).' GROUP BY d.id ORDER BY cc.updated_at DESC,d.sort_order,d.id');$stmt->execute($params);$items=$stmt->fetchAll(PDO::FETCH_ASSOC)?:[];foreach($items as &$item){$item['required_talking_points']=mg_creator_campaign_deliverable_decode_json($item['required_talking_points_json']??null);$item['required_disclosures']=mg_creator_campaign_deliverable_decode_json($item['required_disclosures_json']??null);unset($item['required_talking_points_json'],$item['required_disclosures_json']);}unset($item);return ['items'=>$items];
}

function mg_creator_campaign_assignment_list_merchant(PDO $pdo,array $user,array $filters=[]):array
{
    $context=mg_creator_campaign_deliverable_merchant_context($pdo,$user,'merchant.creator_deliverables.view');$workspaceId=(int)$context['workspace_id'];$where=['cc.workspace_id=?'];$params=[$workspaceId];foreach(['campaign_id'=>'cc.public_id','status'=>'pd.status','participant_id'=>'p.public_id'] as $key=>$column){$value=trim((string)($filters[$key]??''));if($value!==''){$where[]=$column.'=?';$params[]=$value;}}$stmt=$pdo->prepare('SELECT pd.*,d.public_id deliverable_public_id,d.title deliverable_title,d.deliverable_type,d.platform,d.publication_required,d.proof_required,cc.public_id campaign_public_id,cc.title campaign_title,p.public_id participant_public_id,cp.public_id creator_profile_public_id,COALESCE(cp.display_name,u.display_name,u.full_name,u.email) creator_name,s.public_id submission_public_id,s.status submission_status,s.current_revision_number,s.updated_at submission_updated_at FROM creator_campaign_participant_deliverables pd INNER JOIN creator_campaign_deliverables d ON d.id=pd.campaign_deliverable_id INNER JOIN creator_campaigns cc ON cc.id=pd.campaign_id INNER JOIN creator_campaign_participants p ON p.id=pd.participant_id INNER JOIN creator_profiles cp ON cp.id=p.creator_profile_id INNER JOIN users u ON u.id=p.creator_user_id LEFT JOIN creator_campaign_submissions s ON s.participant_deliverable_id=pd.id WHERE '.implode(' AND ',$where).' ORDER BY COALESCE(pd.due_at,\'9999-12-31\'),pd.id DESC LIMIT 500');$stmt->execute($params);return ['items'=>$stmt->fetchAll(PDO::FETCH_ASSOC)?:[]];
}

function mg_creator_campaign_submission_list_merchant(PDO $pdo,array $user,array $filters=[]):array
{
    $context=mg_creator_campaign_deliverable_merchant_context($pdo,$user,'merchant.creator_submissions.view');$workspaceId=(int)$context['workspace_id'];$where=['cc.workspace_id=?'];$params=[$workspaceId];foreach(['campaign_id'=>'cc.public_id','status'=>'s.status'] as $key=>$column){$value=trim((string)($filters[$key]??''));if($value!==''){$where[]=$column.'=?';$params[]=$value;}}$stmt=$pdo->prepare('SELECT s.*,pd.public_id assignment_public_id,d.public_id deliverable_public_id,d.title deliverable_title,d.deliverable_type,d.revision_limit,d.publication_required,d.proof_required,cc.public_id campaign_public_id,cc.title campaign_title,p.public_id participant_public_id,cp.public_id creator_profile_public_id,COALESCE(cp.display_name,u.display_name,u.full_name,u.email) creator_name FROM creator_campaign_submissions s INNER JOIN creator_campaign_participant_deliverables pd ON pd.id=s.participant_deliverable_id INNER JOIN creator_campaign_deliverables d ON d.id=pd.campaign_deliverable_id INNER JOIN creator_campaigns cc ON cc.id=s.campaign_id INNER JOIN creator_campaign_participants p ON p.id=s.participant_id INNER JOIN creator_profiles cp ON cp.id=p.creator_profile_id INNER JOIN users u ON u.id=s.creator_user_id WHERE '.implode(' AND ',$where).' ORDER BY FIELD(s.status,\'submitted\',\'under_review\',\'proof_submitted\',\'revision_requested\',\'approved\',\'verified\',\'rejected\',\'draft\',\'withdrawn\'),s.updated_at DESC,s.id DESC LIMIT 500');$stmt->execute($params);return ['items'=>$stmt->fetchAll(PDO::FETCH_ASSOC)?:[]];
}

function mg_creator_campaign_submission_hydrate(PDO $pdo,array $submission):array
{
    $revisions=$pdo->prepare('SELECT public_id,revision_number,actor_user_id,change_type,content_snapshot_json,feedback,created_at FROM creator_campaign_submission_revisions WHERE submission_id=? ORDER BY revision_number DESC');$revisions->execute([(int)$submission['id']]);$submission['revisions']=$revisions->fetchAll(PDO::FETCH_ASSOC)?:[];foreach($submission['revisions'] as &$revision){$revision['content_snapshot']=mg_creator_campaign_participation_decode_json($revision['content_snapshot_json']??null);unset($revision['content_snapshot_json']);}unset($revision);$assets=$pdo->prepare('SELECT public_id,asset_type,storage_key,original_name,mime_type,size_bytes,external_url,content_hash,metadata_json,created_at FROM creator_campaign_assets WHERE submission_id=? ORDER BY created_at,id');$assets->execute([(int)$submission['id']]);$submission['assets']=$assets->fetchAll(PDO::FETCH_ASSOC)?:[];foreach($submission['assets'] as &$asset){$asset['metadata']=mg_creator_campaign_participation_decode_json($asset['metadata_json']??null);unset($asset['metadata_json']);}unset($asset);return $submission;
}

function mg_creator_campaign_submission_detail_merchant(PDO $pdo,array $user,string $submissionPublicId):array
{
    $context=mg_creator_campaign_deliverable_merchant_context($pdo,$user,'merchant.creator_submissions.view');return mg_creator_campaign_submission_hydrate($pdo,mg_creator_campaign_submission_by_public_id($pdo,$submissionPublicId,(int)$context['workspace_id']));
}

function mg_creator_campaign_assignment_list_creator(PDO $pdo,array $user,array $filters=[]):array
{
    $context=mg_creator_campaign_deliverable_creator_context($pdo,$user,'creator.campaign_deliverables.view_own');$creatorUserId=(int)$context['creator_user_id'];$where=['pd.creator_user_id=?'];$params=[$creatorUserId];$status=trim((string)($filters['status']??''));if($status!==''){$where[]='pd.status=?';$params[]=$status;}$stmt=$pdo->prepare('SELECT pd.*,d.public_id deliverable_public_id,d.title deliverable_title,d.description deliverable_description,d.deliverable_type,d.platform deliverable_platform,d.content_format,d.instructions,d.required_talking_points_json,d.required_disclosures_json,d.publication_required,d.proof_required,d.merchant_review_required,d.revision_limit,cc.public_id campaign_public_id,cc.title campaign_title,cc.starts_at,cc.ends_at,mw.display_name merchant_name,s.public_id submission_public_id,s.status submission_status,s.caption_text,s.content_url,s.platform,s.disclosure_text,s.creator_note,s.merchant_feedback,s.publication_url,s.publication_platform,s.current_revision_number,s.lock_version submission_lock_version,s.updated_at submission_updated_at FROM creator_campaign_participant_deliverables pd INNER JOIN creator_campaign_deliverables d ON d.id=pd.campaign_deliverable_id INNER JOIN creator_campaigns cc ON cc.id=pd.campaign_id INNER JOIN merchant_workspaces mw ON mw.id=cc.workspace_id LEFT JOIN creator_campaign_submissions s ON s.participant_deliverable_id=pd.id WHERE '.implode(' AND ',$where).' ORDER BY FIELD(pd.status,\'revision_requested\',\'assigned\',\'in_progress\',\'submitted\',\'approved\',\'published\',\'verified\',\'rejected\',\'waived\',\'cancelled\'),COALESCE(pd.due_at,\'9999-12-31\'),pd.id');$stmt->execute($params);$items=$stmt->fetchAll(PDO::FETCH_ASSOC)?:[];foreach($items as &$item){$item['required_talking_points']=mg_creator_campaign_deliverable_decode_json($item['required_talking_points_json']??null);$item['required_disclosures']=mg_creator_campaign_deliverable_decode_json($item['required_disclosures_json']??null);unset($item['required_talking_points_json'],$item['required_disclosures_json']);}unset($item);return ['items'=>$items];
}

function mg_creator_campaign_submission_list_creator(PDO $pdo,array $user):array
{
    $context=mg_creator_campaign_deliverable_creator_context($pdo,$user,'creator.campaign_deliverables.view_own');$stmt=$pdo->prepare('SELECT s.public_id,s.status,s.caption_text,s.content_url,s.platform,s.disclosure_text,s.creator_note,s.merchant_feedback,s.publication_url,s.publication_platform,s.current_revision_number,s.lock_version,s.updated_at,pd.public_id assignment_public_id,d.public_id deliverable_public_id,d.title deliverable_title,cc.public_id campaign_public_id,cc.title campaign_title,mw.display_name merchant_name FROM creator_campaign_submissions s INNER JOIN creator_campaign_participant_deliverables pd ON pd.id=s.participant_deliverable_id INNER JOIN creator_campaign_deliverables d ON d.id=pd.campaign_deliverable_id INNER JOIN creator_campaigns cc ON cc.id=s.campaign_id INNER JOIN merchant_workspaces mw ON mw.id=cc.workspace_id WHERE s.creator_user_id=? ORDER BY s.updated_at DESC,s.id DESC');$stmt->execute([(int)$context['creator_user_id']]);return ['items'=>$stmt->fetchAll(PDO::FETCH_ASSOC)?:[]];
}

function mg_creator_campaign_submission_detail_creator(PDO $pdo,array $user,string $submissionPublicId):array
{
    $context=mg_creator_campaign_deliverable_creator_context($pdo,$user,'creator.campaign_deliverables.view_own');return mg_creator_campaign_submission_hydrate($pdo,mg_creator_campaign_submission_by_public_id($pdo,$submissionPublicId,null,(int)$context['creator_user_id']));
}
