<?php
declare(strict_types=1);

function mg_creator_campaign_submission_normalize(array $input, bool $submitting = false): array
{
    $contentUrl = mg_creator_campaign_deliverable_url($input['content_url'] ?? null, 'content_url', $submitting);
    return [
        'caption_text'=>mg_creator_campaign_string($input['caption_text'] ?? null,'caption_text',32000),
        'content_url'=>$contentUrl,
        'platform'=>mg_creator_campaign_string($input['platform'] ?? null,'platform',80),
        'disclosure_text'=>mg_creator_campaign_string($input['disclosure_text'] ?? null,'disclosure_text',1000),
        'creator_note'=>mg_creator_campaign_string($input['creator_note'] ?? null,'creator_note',2000),
    ];
}

function mg_creator_campaign_submission_attach_external_assets(PDO $pdo,array $submission,array $assets,int $actorUserId,string $assetType='external_url'):void
{
    if(count($assets)>10)throw new InvalidArgumentException('No more than 10 assets may be attached at once.');
    foreach($assets as $asset){$url=is_array($asset)?($asset['url']??''):$asset;$url=mg_creator_campaign_deliverable_url($url,'asset URL',true);$hash=hash('sha256',(string)$url);$exists=$pdo->prepare('SELECT 1 FROM creator_campaign_assets WHERE submission_id=? AND content_hash=? LIMIT 1');$exists->execute([(int)$submission['id'],$hash]);if($exists->fetchColumn())continue;$stmt=$pdo->prepare('INSERT INTO creator_campaign_assets(public_id,submission_id,revision_id,asset_type,storage_key,original_name,mime_type,size_bytes,external_url,content_hash,metadata_json,created_by_user_id,created_at) VALUES (?,?,NULL,?,NULL,NULL,NULL,NULL,?,?,NULL,?,NOW())');$stmt->execute([mg_creator_campaign_public_id('ccas'),(int)$submission['id'],$assetType,$url,$hash,$actorUserId]);}
}

function mg_creator_campaign_submission_for_assignment(PDO $pdo,int $assignmentId,bool $forUpdate=false):?array
{
    $stmt=$pdo->prepare('SELECT * FROM creator_campaign_submissions WHERE participant_deliverable_id=? LIMIT 1'.($forUpdate?' FOR UPDATE':''));$stmt->execute([$assignmentId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);return $row?:null;
}

function mg_creator_campaign_submission_save_creator(PDO $pdo,array $user,string $assignmentPublicId,array $input,bool $submit):array
{
    $context=mg_creator_campaign_deliverable_creator_context($pdo,$user,'creator.campaign_submissions.manage_own');$creatorUserId=(int)$context['creator_user_id'];$actorId=(int)$context['actor_user_id'];$data=mg_creator_campaign_submission_normalize($input,$submit);
    mg_creator_campaign_assert_transaction_boundary($pdo);$pdo->beginTransaction();
    try{$assignment=mg_creator_campaign_participant_deliverable_by_public_id($pdo,$assignmentPublicId,null,$creatorUserId,true);mg_creator_campaign_deliverable_require_active_participant($assignment);if(in_array((string)$assignment['status'],['verified','waived','cancelled'],true))throw new DomainException('This deliverable assignment is already final.');$submission=mg_creator_campaign_submission_for_assignment($pdo,(int)$assignment['id'],true);
        if(!$submission){$publicId=mg_creator_campaign_public_id('ccsb');$stmt=$pdo->prepare("INSERT INTO creator_campaign_submissions(public_id,campaign_id,participant_id,participant_deliverable_id,agreement_version_id,creator_user_id,status,caption_text,content_url,platform,disclosure_text,creator_note,current_revision_number,lock_version,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,'draft',?,?,?,?,?,0,1,?,?,NOW(),NOW())");$stmt->execute([$publicId,(int)$assignment['campaign_id'],(int)$assignment['participant_id'],(int)$assignment['id'],(int)$assignment['agreement_version_id'],$creatorUserId,$data['caption_text'],$data['content_url'],$data['platform'],$data['disclosure_text'],$data['creator_note'],$actorId,$actorId]);$submission=mg_creator_campaign_submission_for_assignment($pdo,(int)$assignment['id'],true);}else{mg_creator_campaign_participation_require_expected_lock($submission,(int)($input['expected_lock_version']??0));if(!in_array((string)$submission['status'],['draft','revision_requested','rejected','withdrawn'],true))throw new DomainException('This submission cannot be edited in its current status.');$pdo->prepare('UPDATE creator_campaign_submissions SET caption_text=?,content_url=?,platform=?,disclosure_text=?,creator_note=?,updated_by_user_id=?,lock_version=lock_version+1,updated_at=NOW() WHERE id=?')->execute([$data['caption_text'],$data['content_url'],$data['platform'],$data['disclosure_text'],$data['creator_note'],$actorId,(int)$submission['id']]);}
        $submission=mg_creator_campaign_submission_by_public_id($pdo,(string)$submission['public_id'],null,$creatorUserId,true);$from=(string)$submission['status'];$to=$submit?'submitted':($from==='draft'?'draft':$from);if($submit){mg_creator_campaign_assert_submission_transition($from,'submitted');$pdo->prepare("UPDATE creator_campaign_submissions SET status='submitted',submitted_at=NOW(),reviewed_at=NULL,merchant_feedback=NULL,withdrawn_at=NULL,updated_by_user_id=?,lock_version=lock_version+1,updated_at=NOW() WHERE id=?")->execute([$actorId,(int)$submission['id']]);$pdo->prepare("UPDATE creator_campaign_participant_deliverables SET status='submitted',submitted_at=NOW(),updated_by_user_id=?,lock_version=lock_version+1,updated_at=NOW() WHERE id=?")->execute([$actorId,(int)$assignment['id']]);}elseif((string)$assignment['status']==='assigned'){$pdo->prepare("UPDATE creator_campaign_participant_deliverables SET status='in_progress',started_at=NOW(),updated_by_user_id=?,lock_version=lock_version+1,updated_at=NOW() WHERE id=?")->execute([$actorId,(int)$assignment['id']]);}
        $submission=mg_creator_campaign_submission_by_public_id($pdo,(string)$submission['public_id'],null,$creatorUserId,true);mg_creator_campaign_submission_revision($pdo,$submission,$actorId,$submit?'creator_submit':'creator_save');$assets=is_array($input['assets']??null)?$input['assets']:[];mg_creator_campaign_submission_attach_external_assets($pdo,$submission,$assets,$actorId);mg_creator_campaign_deliverable_event($pdo,$assignment,$actorId,$submit?'submission.submitted':'submission.saved',(string)$assignment['status'],$submit?'submitted':'in_progress',null,['submission_id'=>$submission['public_id']]);if($submit)mg_creator_campaign_notify_merchant_submission($pdo,$submission,$actorId,'submitted');$pdo->commit();return mg_creator_campaign_submission_detail_creator($pdo,$user,(string)$submission['public_id']);
    }catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
}

function mg_creator_campaign_submission_withdraw_creator(PDO $pdo,array $user,string $submissionPublicId,array $input):array
{
    $context=mg_creator_campaign_deliverable_creator_context($pdo,$user,'creator.campaign_submissions.manage_own');$creatorUserId=(int)$context['creator_user_id'];$actorId=(int)$context['actor_user_id'];$reason=mg_creator_campaign_string($input['reason']??null,'reason',2000);
    mg_creator_campaign_assert_transaction_boundary($pdo);$pdo->beginTransaction();
    try{$submission=mg_creator_campaign_submission_by_public_id($pdo,$submissionPublicId,null,$creatorUserId,true);mg_creator_campaign_participation_require_expected_lock($submission,(int)($input['expected_lock_version']??0));$from=(string)$submission['status'];mg_creator_campaign_assert_submission_transition($from,'withdrawn');$pdo->prepare("UPDATE creator_campaign_submissions SET status='withdrawn',withdrawn_at=NOW(),creator_note=COALESCE(?,creator_note),updated_by_user_id=?,lock_version=lock_version+1,updated_at=NOW() WHERE id=?")->execute([$reason,$actorId,(int)$submission['id']]);$pdo->prepare("UPDATE creator_campaign_participant_deliverables SET status='in_progress',status_reason=?,updated_by_user_id=?,lock_version=lock_version+1,updated_at=NOW() WHERE id=?")->execute([$reason,$actorId,(int)$submission['participant_deliverable_id']]);$submission=mg_creator_campaign_submission_by_public_id($pdo,$submissionPublicId,null,$creatorUserId,true);mg_creator_campaign_submission_revision($pdo,$submission,$actorId,'creator_withdraw',$reason);$assignment=mg_creator_campaign_participant_deliverable_by_public_id($pdo,(string)$submission['assignment_public_id'],null,$creatorUserId);mg_creator_campaign_deliverable_event($pdo,$assignment,$actorId,'submission.withdrawn',$from,'withdrawn',$reason,['submission_id'=>$submissionPublicId]);$pdo->commit();return mg_creator_campaign_submission_detail_creator($pdo,$user,$submissionPublicId);}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
}

function mg_creator_campaign_submission_publication_proof_creator(PDO $pdo,array $user,string $submissionPublicId,array $input):array
{
    $context=mg_creator_campaign_deliverable_creator_context($pdo,$user,'creator.campaign_submissions.manage_own');$creatorUserId=(int)$context['creator_user_id'];$actorId=(int)$context['actor_user_id'];$publicationUrl=mg_creator_campaign_deliverable_url($input['publication_url']??null,'publication_url',true);$platform=mg_creator_campaign_string($input['publication_platform']??null,'publication_platform',80,true);$identifier=mg_creator_campaign_string($input['publication_identifier']??null,'publication_identifier',255);
    mg_creator_campaign_assert_transaction_boundary($pdo);$pdo->beginTransaction();
    try{$submission=mg_creator_campaign_submission_by_public_id($pdo,$submissionPublicId,null,$creatorUserId,true);mg_creator_campaign_participation_require_expected_lock($submission,(int)($input['expected_lock_version']??0));$from=(string)$submission['status'];if(!in_array($from,['approved','published','proof_submitted'],true))throw new DomainException('Publication proof may only be submitted after content approval.');$to=!empty($submission['proof_required'])?'proof_submitted':'published';if($from!==$to&&$from!=='proof_submitted')mg_creator_campaign_assert_submission_transition($from,$to);$pdo->prepare('UPDATE creator_campaign_submissions SET status=?,publication_url=?,publication_platform=?,publication_identifier=?,published_at=COALESCE(published_at,NOW()),proof_submitted_at=NOW(),updated_by_user_id=?,lock_version=lock_version+1,updated_at=NOW() WHERE id=?')->execute([$to,$publicationUrl,$platform,$identifier,$actorId,(int)$submission['id']]);$pdo->prepare("UPDATE creator_campaign_participant_deliverables SET status='published',published_at=NOW(),updated_by_user_id=?,lock_version=lock_version+1,updated_at=NOW() WHERE id=?")->execute([$actorId,(int)$submission['participant_deliverable_id']]);$submission=mg_creator_campaign_submission_by_public_id($pdo,$submissionPublicId,null,$creatorUserId,true);mg_creator_campaign_submission_revision($pdo,$submission,$actorId,'publication_proof');$assets=is_array($input['assets']??null)?$input['assets']:[];if($assets===[])$assets=[$publicationUrl];mg_creator_campaign_submission_attach_external_assets($pdo,$submission,$assets,$actorId,'publication_proof');$assignment=mg_creator_campaign_participant_deliverable_by_public_id($pdo,(string)$submission['assignment_public_id'],null,$creatorUserId);mg_creator_campaign_deliverable_event($pdo,$assignment,$actorId,'submission.publication_proof',$from,$to,null,['submission_id'=>$submissionPublicId,'publication_url'=>$publicationUrl]);mg_creator_campaign_notify_merchant_submission($pdo,$submission,$actorId,'publication_proof');$pdo->commit();return mg_creator_campaign_submission_detail_creator($pdo,$user,$submissionPublicId);}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
}

function mg_creator_campaign_submission_review_merchant(PDO $pdo,array $user,string $submissionPublicId,string $decision,array $input):array
{
    $context=mg_creator_campaign_deliverable_merchant_context($pdo,$user,'merchant.creator_submissions.review');$workspaceId=(int)$context['workspace_id'];$actorId=(int)$context['actor_user_id'];$decision=strtolower(trim($decision));$allowed=['under_review','revision_requested','approved','rejected','verified'];if(!in_array($decision,$allowed,true))throw new InvalidArgumentException('Submission review action is invalid.');$feedback=mg_creator_campaign_string($input['feedback']??null,'feedback',32000,in_array($decision,['revision_requested','rejected'],true));
    mg_creator_campaign_assert_transaction_boundary($pdo);$pdo->beginTransaction();
    try{$submission=mg_creator_campaign_submission_by_public_id($pdo,$submissionPublicId,$workspaceId,null,true);mg_creator_campaign_participation_require_expected_lock($submission,(int)($input['expected_lock_version']??0));$from=(string)$submission['status'];if($from!==$decision)mg_creator_campaign_assert_submission_transition($from,$decision);if($decision==='revision_requested'){$count=$pdo->prepare("SELECT COUNT(*) FROM creator_campaign_submission_revisions WHERE submission_id=? AND change_type='merchant_revision_request'");$count->execute([(int)$submission['id']]);if((int)$count->fetchColumn()>=(int)$submission['revision_limit'])throw new DomainException('The deliverable revision limit has been reached.');}
        $timeField=match($decision){'approved'=>'approved_at','rejected'=>'rejected_at','verified'=>'verified_at',default=>'reviewed_at'};$pdo->prepare("UPDATE creator_campaign_submissions SET status=?,merchant_feedback=?,reviewed_at=NOW(),{$timeField}=NOW(),updated_by_user_id=?,lock_version=lock_version+1,updated_at=NOW() WHERE id=?")->execute([$decision,$feedback,$actorId,(int)$submission['id']]);$assignmentStatus=match($decision){'under_review'=>'submitted','revision_requested'=>'revision_requested','approved'=>'approved','rejected'=>'rejected','verified'=>'verified'};$assignmentTime=match($decision){'approved'=>'approved_at','rejected'=>'rejected_at','verified'=>'verified_at',default=>null};$sql='UPDATE creator_campaign_participant_deliverables SET status=?,status_reason=?,updated_by_user_id=?,lock_version=lock_version+1,updated_at=NOW()';if($assignmentTime!==null)$sql.=', '.$assignmentTime.'=NOW()';$sql.=' WHERE id=?';$pdo->prepare($sql)->execute([$assignmentStatus,$feedback,$actorId,(int)$submission['participant_deliverable_id']]);$submission=mg_creator_campaign_submission_by_public_id($pdo,$submissionPublicId,$workspaceId,null,true);$changeType=match($decision){'under_review'=>'merchant_review','revision_requested'=>'merchant_revision_request','approved'=>'merchant_approve','rejected'=>'merchant_reject','verified'=>'merchant_verify'};mg_creator_campaign_submission_revision($pdo,$submission,$actorId,$changeType,$feedback);$assignment=mg_creator_campaign_participant_deliverable_by_public_id($pdo,(string)$submission['assignment_public_id'],$workspaceId);mg_creator_campaign_deliverable_event($pdo,$assignment,$actorId,'submission.'.$decision,$from,$decision,$feedback,['submission_id'=>$submissionPublicId]);if($decision!=='under_review')mg_creator_campaign_notify_creator_review($pdo,$submission,$actorId,$decision);$pdo->commit();return mg_creator_campaign_submission_detail_merchant($pdo,$user,$submissionPublicId);}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
}
