<?php
declare(strict_types=1);
require_once dirname(__DIR__,2) . '/bootstrap.php';
require_once dirname(__DIR__,3) . '/includes/reviews-case-studies.php';
mg_require_method('GET');$pdo=mg_db();$slug=strtolower(trim((string)($_GET['slug']??'')));if($slug===''||preg_match('/^[a-z0-9][a-z0-9-]{0,119}$/',$slug)!==1)mg_fail('Invalid case study.',422);
try{
 $stmt=$pdo->prepare("SELECT p.id profile_db_id,p.public_id profile_public_id,p.user_id merchant_user_id,p.slug,p.display_name,p.headline,p.bio,p.location_label,p.status profile_status,p.visibility,
 f.id case_db_id,f.public_id case_public_id,f.status case_status,f.display_order,f.hero_featured,f.title,f.subtitle,f.challenge_text,f.solution_text,f.outcomes_json,f.testimonial_text,f.testimonial_name,f.testimonial_role,f.published_at,f.selected_review_id
 FROM public_profiles p LEFT JOIN featured_case_studies f ON f.profile_id=p.id AND f.status='published'
 WHERE p.slug=? AND p.status='active' AND p.visibility='public' LIMIT 1");$stmt->execute([$slug]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row)mg_fail('Case study not found.',404);
 $isFeatured=!empty($row['case_public_id']);$reviews=[];
 if(mg_rcs_table_exists($pdo,'customer_reviews')){$reviewSql="SELECT r.public_id,r.reviewer_name,r.rating,r.review_title,r.review_body,r.submitted_at,rr.public_id reply_id,rr.reply_body,rr.created_at reply_created_at FROM customer_reviews r LEFT JOIN customer_review_replies rr ON rr.review_id=r.id AND rr.status='published' WHERE r.merchant_user_id=? AND r.status='published'";$args=[(int)$row['merchant_user_id']];if($isFeatured){$reviewSql.=' AND (r.featured_in_case_study=1 OR r.id=?)';$args[]=(int)($row['selected_review_id']??0);}$reviewSql.=' ORDER BY r.featured_in_case_study DESC,r.submitted_at DESC LIMIT 6';$rs=$pdo->prepare($reviewSql);$rs->execute($args);$reviews=array_map(static fn(array $r):array=>['id'=>(string)$r['public_id'],'reviewer_name'=>(string)$r['reviewer_name'],'rating'=>(int)$r['rating'],'title'=>$r['review_title'],'body'=>(string)$r['review_body'],'submitted_at'=>(string)$r['submitted_at'],'reply'=>!empty($r['reply_id'])?['id'=>(string)$r['reply_id'],'body'=>(string)$r['reply_body'],'created_at'=>(string)$r['reply_created_at']]:null],$rs->fetchAll(PDO::FETCH_ASSOC));}
 mg_ok(['case_study'=>['id'=>$isFeatured?(string)$row['case_public_id']:(string)$row['profile_public_id'],'profile_id'=>(string)$row['profile_public_id'],'slug'=>(string)$row['slug'],'merchant_user_id'=>(int)$row['merchant_user_id'],'merchant_name'=>(string)$row['display_name'],'profile_headline'=>(string)($row['headline']??''),'bio'=>(string)($row['bio']??''),'location'=>(string)($row['location_label']??''),'title'=>$isFeatured?($row['title']?:$row['display_name']):(string)$row['display_name'],'subtitle'=>$isFeatured?($row['subtitle']?:$row['headline']):$row['headline'],'challenge'=>$isFeatured?$row['challenge_text']:null,'solution'=>$isFeatured?$row['solution_text']:null,'outcomes'=>$isFeatured?mg_rcs_decode($row['outcomes_json'],[]):[],'testimonial'=>$isFeatured?['text'=>$row['testimonial_text'],'name'=>$row['testimonial_name'],'role'=>$row['testimonial_role']]:['text'=>null,'name'=>null,'role'=>null],'hero_featured'=>$isFeatured&&!empty($row['hero_featured']),'published_at'=>$isFeatured?$row['published_at']:null,'is_featured_case_study'=>$isFeatured,'page_mode'=>$isFeatured?'featured':'profile_case_study','reviews'=>$reviews]]);
}catch(Throwable $e){mg_security_log('error','public.case_studies.detail_failed','Unable to load case study.',['slug'=>$slug,'message'=>$e->getMessage()],null);mg_fail('Unable to load case study.',500);}