<?php
declare(strict_types=1);

function mg_mcp_creator_campaign_action_target(PDO $pdo,array $context,string $tool,array $input): array
{
    $workspaceId=(int)$context['workspace_id'];$campaignId=null;$targetType='creator_campaign';$targetId='';$lock=0;$status='';$amount=0;
    $campaignTools=['microgifter.creator_campaigns.publish','microgifter.creator_campaigns.schedule','microgifter.creator_campaigns.pause','microgifter.creator_campaigns.resume','microgifter.creator_campaigns.complete','microgifter.creator_campaigns.cancel'];
    if(in_array($tool,$campaignTools,true)){
        $targetId=mg_mcp_creator_campaign_action_public_id($input['campaign_id']??'','campaign_id');$row=mg_creator_campaign_repository_by_public_id($pdo,$targetId,$workspaceId);$campaignId=$targetId;$lock=(int)$row['lock_version'];$status=(string)$row['status'];
    }elseif(str_contains($tool,'.application.')){
        $targetType='creator_campaign_application';$targetId=mg_mcp_creator_campaign_action_public_id($input['application_id']??'','application_id');$stmt=$pdo->prepare('SELECT a.lock_version,a.status,cc.public_id campaign_public_id FROM creator_campaign_applications a INNER JOIN creator_campaigns cc ON cc.id=a.campaign_id WHERE a.public_id=? AND cc.workspace_id=? LIMIT 1');$stmt->execute([$targetId,$workspaceId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row)throw new MgMcpCreatorCampaignActionException('Application was not found in this workspace.',404);$campaignId=(string)$row['campaign_public_id'];$lock=(int)$row['lock_version'];$status=(string)$row['status'];
    }elseif($tool==='microgifter.creator_campaigns.invitation.send'){
        $targetType='creator_profile';$targetId=mg_mcp_creator_campaign_action_public_id($input['creator_profile_id']??'','creator_profile_id');$campaignId=mg_mcp_creator_campaign_action_public_id($input['campaign_id']??'','campaign_id');$campaign=mg_creator_campaign_repository_by_public_id($pdo,$campaignId,$workspaceId);$lock=(int)$campaign['lock_version'];$stmt=$pdo->prepare("SELECT cp.status FROM creator_profiles cp INNER JOIN users u ON u.id=cp.user_id AND u.status='active' INNER JOIN user_model_assignments uma ON uma.user_id=u.id AND uma.status='active' INNER JOIN user_models um ON um.id=uma.user_model_id AND um.code='creator' WHERE cp.public_id=? AND cp.status='active' LIMIT 1");$stmt->execute([$targetId]);$creatorStatus=(string)($stmt->fetchColumn()?:'');if($creatorStatus!=='active')throw new MgMcpCreatorCampaignActionException('Creator profile is unavailable.',404);$status=(string)$campaign['status'].'|creator:'.$creatorStatus;
    }elseif($tool==='microgifter.creator_campaigns.agreement.offer'||str_contains($tool,'.participant.')||$tool==='microgifter.creator_campaigns.payout.record'){
        $targetType='creator_campaign_participant';$targetId=mg_mcp_creator_campaign_action_public_id($input['participant_id']??'','participant_id');$stmt=$pdo->prepare('SELECT p.lock_version,p.status,cc.public_id campaign_public_id FROM creator_campaign_participants p INNER JOIN creator_campaigns cc ON cc.id=p.campaign_id WHERE p.public_id=? AND cc.workspace_id=? LIMIT 1');$stmt->execute([$targetId,$workspaceId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row)throw new MgMcpCreatorCampaignActionException('Participant was not found in this workspace.',404);$campaignId=(string)$row['campaign_public_id'];$lock=(int)$row['lock_version'];$status=(string)$row['status'];
        if($tool==='microgifter.creator_campaigns.payout.record'){$currency=strtoupper(trim((string)($input['currency']??'USD')));$sum=$pdo->prepare("SELECT COALESCE(SUM(r.amount_minor),0) FROM creator_campaign_budget_reservations r INNER JOIN creator_campaign_participants p ON p.id=r.participant_id LEFT JOIN creator_campaign_payout_items i ON i.reservation_id=r.id AND i.status IN ('scheduled','paid') WHERE p.public_id=? AND r.status='committed' AND r.currency=? AND i.id IS NULL");$sum->execute([$targetId,$currency]);$amount=(int)$sum->fetchColumn();}
    }elseif(str_contains($tool,'.submission.')){
        $targetType='creator_campaign_submission';$targetId=mg_mcp_creator_campaign_action_public_id($input['submission_id']??'','submission_id');$stmt=$pdo->prepare('SELECT s.lock_version,s.status,cc.public_id campaign_public_id FROM creator_campaign_submissions s INNER JOIN creator_campaigns cc ON cc.id=s.campaign_id WHERE s.public_id=? AND cc.workspace_id=? LIMIT 1');$stmt->execute([$targetId,$workspaceId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row)throw new MgMcpCreatorCampaignActionException('Submission was not found in this workspace.',404);$campaignId=(string)$row['campaign_public_id'];$lock=(int)$row['lock_version'];$status=(string)$row['status'];
    }elseif($tool==='microgifter.creator_campaigns.attribution.override'){
        $targetType='creator_campaign_attribution';$targetId=mg_mcp_creator_campaign_action_public_id($input['attribution_id']??'','attribution_id');$stmt=$pdo->prepare('SELECT a.lock_version,a.status,cc.public_id campaign_public_id FROM creator_campaign_attributions a INNER JOIN creator_campaigns cc ON cc.id=a.campaign_id WHERE a.public_id=? AND cc.workspace_id=? LIMIT 1');$stmt->execute([$targetId,$workspaceId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row)throw new MgMcpCreatorCampaignActionException('Attribution was not found in this workspace.',404);$campaignId=(string)$row['campaign_public_id'];$lock=(int)$row['lock_version'];$status=(string)$row['status'];
    }elseif(str_contains($tool,'.earning.')){
        $targetType='creator_campaign_earning';$targetId=mg_mcp_creator_campaign_action_public_id($input['earning_id']??'','earning_id');$stmt=$pdo->prepare("SELECT e.amount_minor,e.event_type,cc.public_id campaign_public_id,COALESCE(r.status,'unreviewed') review_status,COALESCE(r.lock_version,0) review_lock FROM creator_campaign_earning_events e INNER JOIN creator_campaigns cc ON cc.id=e.campaign_id LEFT JOIN creator_campaign_earning_reviews r ON r.earning_event_id=e.id WHERE e.public_id=? AND cc.workspace_id=? LIMIT 1");$stmt->execute([$targetId,$workspaceId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row)throw new MgMcpCreatorCampaignActionException('Earning was not found in this workspace.',404);$campaignId=(string)$row['campaign_public_id'];$lock=(int)$row['review_lock'];$status=(string)$row['review_status'].'|event:'.(string)$row['event_type'];$amount=abs((int)$row['amount_minor']);
    }elseif($tool==='microgifter.creator_campaigns.dispute.resolve'){
        $targetType='creator_campaign_dispute';$targetId=mg_mcp_creator_campaign_action_public_id($input['dispute_id']??'','dispute_id');$stmt=$pdo->prepare('SELECT d.lock_version,d.status,cc.public_id campaign_public_id FROM creator_campaign_disputes d INNER JOIN creator_campaigns cc ON cc.id=d.campaign_id WHERE d.public_id=? AND cc.workspace_id=? LIMIT 1');$stmt->execute([$targetId,$workspaceId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row)throw new MgMcpCreatorCampaignActionException('Dispute was not found in this workspace.',404);$campaignId=(string)$row['campaign_public_id'];$lock=(int)$row['lock_version'];$status=(string)$row['status'];
    }
    if($targetId==='')throw new MgMcpCreatorCampaignActionException('Action target is required.');
    return ['type'=>$targetType,'id'=>$targetId,'campaign_id'=>$campaignId,'lock_version'=>$lock,'status'=>$status,'state_token'=>mg_mcp_creator_campaign_action_state_token($targetType,$targetId,$lock,$status),'amount_cents'=>$amount,'quantity'=>1];
}

function mg_mcp_creator_campaign_action_normalize(string $tool,array $input): array
{
    $clean=[];
    foreach(['campaign_id','application_id','creator_profile_id','participant_id','submission_id','attribution_id','earning_id','dispute_id','source_id'] as $key){if(array_key_exists($key,$input)&&trim((string)$input[$key])!=='')$clean[$key]=mg_mcp_creator_campaign_action_public_id($input[$key],$key);}
    if(array_key_exists('expected_lock_version',$input)){$lock=(int)$input['expected_lock_version'];if($lock<1)throw new MgMcpCreatorCampaignActionException('expected_lock_version must be at least 1.');$clean['expected_lock_version']=$lock;}
    foreach(['reason'=>2000,'feedback'=>32000,'invitation_message'=>8000,'internal_note'=>16000,'response_deadline_at'=>80,'summary'=>1000,'terms_text'=>32000,'deliverables'=>16000,'compensation'=>16000,'content_rights'=>16000,'disclosures'=>16000,'cancellation'=>16000,'reversal'=>16000,'creator_specific'=>16000,'change_summary'=>2000,'currency'=>3,'resolution_note'=>4000] as $key=>$max){if(array_key_exists($key,$input)&&trim((string)$input[$key])!=='')$clean[$key]=mg_mcp_creator_campaign_action_text($input[$key],$max,$key,false);}
    if(array_key_exists('requires_reacceptance',$input))$clean['requires_reacceptance']=filter_var($input['requires_reacceptance'],FILTER_VALIDATE_BOOLEAN);
    if($tool==='microgifter.creator_campaigns.dispute.resolve'){$to=strtolower(trim((string)($input['resolution']??'')));if(!in_array($to,['resolved_upheld','resolved_adjusted','rejected'],true))throw new MgMcpCreatorCampaignActionException('Invalid dispute resolution.');$clean['resolution']=$to;}
    if($tool==='microgifter.creator_campaigns.attribution.override'&&!array_key_exists('source_id',$clean))$clean['source_id']='';
    if($tool==='microgifter.creator_campaigns.payout.record'){$currency=strtoupper((string)($clean['currency']??'USD'));if(preg_match('/^[A-Z]{3}$/',$currency)!==1)throw new MgMcpCreatorCampaignActionException('Invalid currency.');$clean['currency']=$currency;}
    return $clean;
}

function mg_mcp_creator_campaign_action_request(PDO $pdo,array $context,string $toolName,array $input): array
{
    if(!mg_mcp_creator_campaign_action_schema_ready($pdo))throw new MgMcpCreatorCampaignActionException('Phase 13C schema has not been imported.',503,'MCP_CREATOR_CAMPAIGN_ACTION_SCHEMA_MISSING');
    $contract=mg_mcp_creator_campaign_action_contract($toolName);$scope=(string)$contract['scope'];
    if((string)($context['maximum_operation_class']??'')!=='approval_gated'||(string)($context['client_maximum_operation_class']??'')!=='approval_gated')throw new MgMcpCreatorCampaignActionException('Connection is not approval-gated.',403,'MCP_CREATOR_CAMPAIGN_ACTION_OPERATION_DENIED');
    if(!in_array($scope,array_map('strval',(array)($context['scopes']??[])),true))throw new MgMcpCreatorCampaignActionException('Required action scope is not granted.',403,'MCP_CREATOR_CAMPAIGN_ACTION_SCOPE_DENIED');
    if(!in_array((string)($context['workspace_type']??''),['merchant','merchant_workspace'],true)||(int)($context['workspace_id']??0)<1)throw new MgMcpCreatorCampaignActionException('Merchant workspace authority is required.',403,'MCP_CREATOR_CAMPAIGN_ACTION_WORKSPACE_REQUIRED');
    $grantPublicId=mg_mcp_creator_campaign_action_uuid($input['grant_id']??'','grant_id');$ownerId=(int)$context['user_id'];
    $grantStmt=$pdo->prepare('SELECT g.* FROM mcp_automation_grants g WHERE g.public_id=? AND g.connection_id=? AND g.authorizing_user_id=? AND g.workspace_id=? LIMIT 1');$grantStmt->execute([$grantPublicId,(int)$context['connection_db_id'],$ownerId,(int)$context['workspace_id']]);$grant=$grantStmt->fetch(PDO::FETCH_ASSOC);if(!$grant)throw new MgMcpCreatorCampaignActionException('Action grant was not found.',403,'MCP_CREATOR_CAMPAIGN_ACTION_GRANT_DENIED');
    $clean=mg_mcp_creator_campaign_action_normalize($toolName,$input);$target=mg_mcp_creator_campaign_action_target($pdo,$context,$toolName,$clean);
    try{mg_mcp_automation_authorize_grant_action($pdo,(string)$context['connection_public_id'],$grantPublicId,$toolName,'approval_gated',(string)$contract['risk'],(int)$target['amount_cents'],1,['campaign_id'=>$target['campaign_id']]);}catch(MgMcpAutomationGrantException $e){throw new MgMcpCreatorCampaignActionException($e->getMessage(),$e->httpStatus(),$e->errorCode());}
    $requestedReason=mg_mcp_creator_campaign_action_text($input['requested_reason']??'',1000,'requested_reason');$externalKey=mg_mcp_creator_campaign_action_text($input['idempotency_key']??'',190,'idempotency_key');if(preg_match('/^[A-Za-z0-9._:-]{8,190}$/',$externalKey)!==1)throw new MgMcpCreatorCampaignActionException('Invalid idempotency_key.');
    $clean['_native_idempotency_key']=$externalKey;$clean['_target']=$target;$fingerprint=mg_mcp_creator_campaign_action_fingerprint(['tool'=>$toolName,'input'=>$clean]);$storedKey='cc13c:'.hash('sha256',(string)$context['connection_public_id'].'|'.$grantPublicId.'|'.$toolName.'|'.$externalKey);
    $pdo->beginTransaction();
    try{
        $existing=$pdo->prepare('SELECT aa.public_id,aa.input_fingerprint FROM mcp_automation_actions aa INNER JOIN mcp_automation_runs r ON r.id=aa.run_id WHERE r.grant_id=? AND aa.idempotency_key=? LIMIT 1 FOR UPDATE');$existing->execute([(int)$grant['id'],$storedKey]);$row=$existing->fetch(PDO::FETCH_ASSOC);
        if($row){if(!hash_equals((string)$row['input_fingerprint'],$fingerprint))throw new MgMcpCreatorCampaignActionException('Idempotency key conflicts with different action content.',409,'MCP_CREATOR_CAMPAIGN_ACTION_IDEMPOTENCY_CONFLICT');$pdo->commit();return mg_mcp_creator_campaign_action_projection(mg_mcp_creator_campaign_action_row($pdo,(string)$row['public_id'],$ownerId),true);}
        $automation=mg_mcp_creator_campaign_action_automation($pdo,$grant);$runPublic=mg_public_uuid();$runKey='cc13c-run:'.hash('sha256',$storedKey);
        $pdo->prepare("INSERT INTO mcp_automation_runs(public_id,automation_id,grant_id,trigger_id,status,idempotency_key,input_fingerprint,scheduled_at,queued_at,attempt,maximum_attempts,created_at,updated_at) VALUES (?,?,?,NULL,'waiting_for_approval',?,?,NULL,NOW(),1,1,NOW(),NOW())")->execute([$runPublic,(int)$automation['id'],(int)$grant['id'],$runKey,$fingerprint]);$runId=(int)$pdo->lastInsertId();
        $actionPublic=mg_public_uuid();$pdo->prepare("INSERT INTO mcp_automation_actions(public_id,run_id,sequence_number,tool_name,tool_version,operation_class,risk_level,status,approval_required,idempotency_key,input_fingerprint,sanitized_input_json,fresh_state_token,proposed_amount_cents,proposed_quantity,created_at,updated_at) VALUES (?,?,1,?,'1.0','approval_gated',?,'waiting_for_approval',1,?,?,?,?,?,1,NOW(),NOW())")->execute([$actionPublic,$runId,$toolName,(string)$contract['risk'],$storedKey,$fingerprint,json_encode($clean,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),(string)$target['state_token'],(int)$target['amount_cents']]);$actionId=(int)$pdo->lastInsertId();
        $approvalPublic=mg_public_uuid();$pdo->prepare("INSERT INTO mcp_creator_campaign_action_approvals(public_id,action_id,owner_user_id,status,requested_reason,requested_at,expires_at,created_at,updated_at) VALUES (?,?,?,'pending',?,NOW(),DATE_ADD(NOW(),INTERVAL 24 HOUR),NOW(),NOW())")->execute([$approvalPublic,$actionId,$ownerId,$requestedReason]);
        $pdo->commit();$metadata=['action_id'=>$actionPublic,'approval_id'=>$approvalPublic,'tool'=>$toolName,'grant_id'=>$grantPublicId,'campaign_id'=>$target['campaign_id'],'resource_type'=>$target['type'],'resource_id'=>$target['id'],'risk'=>$contract['risk'],'external_effect_executed'=>false];mg_mcp_creator_campaign_action_security($pdo,$context,'mcp.creator_campaign.action.requested','External client requested an owner-approved Creator Campaign action.',$metadata,'high');mg_audit('mcp_creator_campaign_action_requested','mcp_automation_action',$metadata,$ownerId);mg_event('mcp.creator_campaign.action.requested',$metadata,$ownerId);
        return mg_mcp_creator_campaign_action_projection(mg_mcp_creator_campaign_action_row($pdo,$actionPublic,$ownerId));
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
