<?php
declare(strict_types=1);

require_once __DIR__ . '/_merchant.php';
require_once dirname(__DIR__) . '/public/campaigns/_followups.php';

function mg_campaign_followup_row(array $r): array { return ['id'=>(string)$r['public_id'],'campaign_id'=>(string)$r['campaign_public_id'],'name'=>(string)$r['name'],'trigger_event'=>(string)$r['trigger_event'],'delay_preset'=>(string)$r['delay_preset'],'custom_delay_minutes'=>$r['custom_delay_minutes']===null?null:(int)$r['custom_delay_minutes'],'delay_seconds'=>(int)$r['delay_seconds'],'channel'=>(string)$r['channel'],'message_mode'=>(string)$r['message_mode'],'subject'=>(string)($r['subject']??''),'body'=>(string)($r['body']??''),'status'=>(string)$r['status'],'created_at'=>$r['created_at']??null,'updated_at'=>$r['updated_at']??null]; }
function mg_campaign_followup_trigger(string $v): string { $v=strtolower(trim($v)); if(!preg_match('/^[a-z0-9_.:-]{3,90}$/',$v))mg_fail('Invalid follow-up action.',422); return $v; }

$method=strtoupper($_SERVER['REQUEST_METHOD']??'GET');
$user=$method==='GET'?mg_require_permission('merchant.campaigns.view'):mg_require_permission('merchant.campaigns.manage');$merchantId=(int)$user['id'];$pdo=mg_db();mg_merchant_ensure_workspace($pdo,$user);mg_campaign_followup_install($pdo);
if($method==='GET'){
 $campaignRef=strtolower(trim((string)($_GET['campaign']??$_GET['campaign_id']??'')));$sql="SELECT r.*,c.public_id campaign_public_id FROM campaign_followup_rules r INNER JOIN campaigns c ON c.id=r.campaign_id WHERE r.merchant_user_id=?";$params=[$merchantId];if($campaignRef!==''){$sql.=' AND (c.public_id=? OR c.public_slug=?)';$params[]=$campaignRef;$params[]=$campaignRef;}$sql.=' ORDER BY c.updated_at DESC,r.id DESC LIMIT 200';$stmt=$pdo->prepare($sql);$stmt->execute($params);mg_ok(['rules'=>array_map('mg_campaign_followup_row',$stmt->fetchAll(PDO::FETCH_ASSOC)),'schema_ready'=>true]);
}
if($method!=='POST')mg_fail('Method not allowed.',405);
$input=mg_input();mg_require_csrf_for_write($input);
$campaignRef=strtolower(trim((string)($input['campaign_id']??$input['campaign']??'')));$ruleRef=strtolower(trim((string)($input['rule_id']??'')));$name=trim((string)($input['name']??''));$trigger=mg_campaign_followup_trigger((string)($input['trigger_event']??$input['action']??''));$preset=trim((string)($input['delay_preset']??$input['delay']??'1_hour'));$custom=max(0,(int)($input['custom_delay_minutes']??0));$channel=trim((string)($input['channel']??'email'));$mode=trim((string)($input['message_mode']??'automatic'));$subject=trim((string)($input['subject']??''));$body=trim((string)($input['body']??''));$status=trim((string)($input['status']??'active'));
if($campaignRef===''||$name===''||mb_strlen($name)>160||!in_array($preset,['1_hour','6_hours','1_day','15_days','custom'],true)||!in_array($channel,['email','microgifter_message','both'],true)||!in_array($mode,['automatic','custom'],true)||!in_array($status,['active','paused','archived'],true)||($preset==='custom'&&$custom<1)||mb_strlen($subject)>180||mb_strlen($body)>4000)mg_fail('Invalid follow-up rule.',422);
$c=$pdo->prepare('SELECT id,public_id,campaign_type,title FROM campaigns WHERE merchant_user_id=? AND (public_id=? OR public_slug=?) LIMIT 1');$c->execute([$merchantId,$campaignRef,$campaignRef]);$campaign=$c->fetch(PDO::FETCH_ASSOC);if(!$campaign)mg_fail('Campaign not found.',404);
$delay=mg_campaign_followup_delay($preset,$custom);$meta=['campaign_type'=>(string)$campaign['campaign_type'],'campaign_title'=>(string)$campaign['title']];
if($ruleRef!==''){$stmt=$pdo->prepare('UPDATE campaign_followup_rules SET name=?,trigger_event=?,delay_preset=?,custom_delay_minutes=?,delay_seconds=?,channel=?,message_mode=?,subject=?,body=?,status=?,metadata_json=?,updated_at=NOW() WHERE public_id=? AND merchant_user_id=? AND campaign_id=?');$stmt->execute([$name,$trigger,$preset,$preset==='custom'?$custom:null,$delay,$channel,$mode,$subject!==''?$subject:null,$body!==''?$body:null,$status,json_encode($meta,JSON_UNESCAPED_SLASHES),$ruleRef,$merchantId,(int)$campaign['id']]);$public=$ruleRef;$msg='Follow-up rule updated.';}else{$public=mg_campaign_followup_uuid();$stmt=$pdo->prepare('INSERT INTO campaign_followup_rules (public_id,merchant_user_id,campaign_id,name,trigger_event,delay_preset,custom_delay_minutes,delay_seconds,channel,message_mode,subject,body,status,metadata_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())');$stmt->execute([$public,$merchantId,(int)$campaign['id'],$name,$trigger,$preset,$preset==='custom'?$custom:null,$delay,$channel,$mode,$subject!==''?$subject:null,$body!==''?$body:null,$status,json_encode($meta,JSON_UNESCAPED_SLASHES)]);$msg='Follow-up rule created.';}
$s=$pdo->prepare('SELECT r.*,c.public_id campaign_public_id FROM campaign_followup_rules r INNER JOIN campaigns c ON c.id=r.campaign_id WHERE r.public_id=? AND r.merchant_user_id=? LIMIT 1');$s->execute([$public,$merchantId]);$row=$s->fetch(PDO::FETCH_ASSOC);mg_ok(['rule'=>$row?mg_campaign_followup_row($row):null,'schema_ready'=>true],$msg,201);
