<?php
declare(strict_types=1);
require_once __DIR__ . '/_claims.php';
mg_require_method('POST');$user=mg_require_permission('merchant.claim_codes.manage');$input=mg_input();mg_require_csrf_for_write($input);$action=trim((string)($input['action']??''));$id=trim((string)($input['claim_code_id']??''));$pdo=mg_db();$workspace=mg_claim_workspace($pdo,$user);
$stmt=$pdo->prepare('SELECT mcc.*,ml.public_id location_public_id FROM merchant_claim_codes mcc INNER JOIN merchant_locations ml ON ml.id=mcc.location_id WHERE mcc.public_id=? AND mcc.merchant_user_id=? AND ml.workspace_id=? LIMIT 1 FOR UPDATE');
$pdo->beginTransaction();
try{$stmt->execute([$id,(int)$user['id'],(int)$workspace['id']]);$current=$stmt->fetch();if(!$current)mg_fail('Claim code not found.',404);
 if($action==='status'){$status=trim((string)($input['status']??''));if(!in_array($status,['active','inactive','revoked'],true))mg_fail('Invalid claim-code status.',422);$pdo->prepare('UPDATE merchant_claim_codes SET status=?,updated_at=NOW() WHERE id=?')->execute([$status,(int)$current['id']]);$event=$status==='active'?'activated':($status==='inactive'?'deactivated':'revoked');$newId=(int)$current['id'];$public=(string)$current['public_id'];}
 elseif($action==='limit'){$limit=($input['usage_limit']??'')===''?null:max(1,(int)$input['usage_limit']);$pdo->prepare('UPDATE merchant_claim_codes SET usage_limit=?,updated_at=NOW() WHERE id=?')->execute([$limit,(int)$current['id']]);$event='limit_changed';$newId=(int)$current['id'];$public=(string)$current['public_id'];}
 elseif($action==='rotate'){$code=trim((string)($input['code']??''));$label=trim((string)($input['label']??$current['label']));if(mb_strlen($code)<4||mb_strlen($code)>64||$label===''||mb_strlen($label)>120)mg_fail('Invalid replacement claim code.',422);$pepper=mg_claim_code_pepper();$public=mg_merchant_uuid();$pdo->prepare("INSERT INTO merchant_claim_codes (public_id,merchant_user_id,location_id,label,code_hash,code_last4,status,valid_from,valid_until,usage_limit,usage_count,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,'active',NOW(),?,?,0,?,NOW(),NOW())")->execute([$public,(int)$user['id'],(int)$current['location_id'],$label,hash_hmac('sha256',$code,$pepper),substr($code,-4),$input['valid_until']??null,($input['usage_limit']??'')===''?null:max(1,(int)$input['usage_limit']),(int)$user['id']]);$newId=(int)$pdo->lastInsertId();$pdo->prepare("UPDATE merchant_claim_codes SET status='revoked',updated_at=NOW() WHERE id=?")->execute([(int)$current['id']]);$event='rotated';}
 else mg_fail('Invalid claim-code action.',422);
 $pdo->prepare('INSERT INTO merchant_claim_code_events (public_id,merchant_user_id,claim_code_id,location_id,event_type,previous_claim_code_id,metadata_json,actor_user_id,created_at) VALUES (?,?,?,?,?,?,?,?,NOW())')->execute([mg_merchant_uuid(),(int)$user['id'],$newId,(int)$current['location_id'],$event,$event==='rotated'?(int)$current['id']:null,json_encode(['code_last4'=>$event==='rotated'?substr((string)$input['code'],-4):$current['code_last4']],JSON_UNESCAPED_SLASHES),(int)$user['id']]);
 $pdo->commit();mg_audit('merchant.claim_code_'.$event,'merchant_claim_code',['claim_code_id'=>$public,'location_id'=>$current['location_public_id']],(int)$user['id']);mg_ok(['claim_code_id'=>$public,'event'=>$event,'code_last4'=>$event==='rotated'?substr((string)$input['code'],-4):$current['code_last4']],'Claim code updated.');
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();mg_security_log('error','merchant.claim_code_action_failed','Claim-code action failed.',['exception_type'=>get_class($e)],(int)$user['id']);mg_fail('Unable to update claim code.',500);}
