<?php
declare(strict_types=1);

require_once __DIR__ . '/_merchant.php';
require_once dirname(__DIR__) . '/rewards/_zero_value_bridge.php';
require_once dirname(__DIR__) . '/communications/_delivery.php';
require_once dirname(__DIR__) . '/stamps/_stamps.php';
require_once dirname(__DIR__, 2) . '/includes/merchant-crm.php';
require_once dirname(__DIR__, 2) . '/includes/mail.php';

function mg_crm_gift_uuid(): string { $b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4)); }
function mg_crm_gift_expiry(array $t): ?string { $r=(string)($t['expiration_rule']??'none'); if(($r==='fixed_date'||$r==='event_date')&&!empty($t['expires_at']))return (string)$t['expires_at']; if($r==='after_issue'&&!empty($t['expiration_days']))return date('Y-m-d H:i:s',time()+((int)$t['expiration_days']*86400)); return null; }
function mg_crm_gift_event(PDO $pdo,array $contact,?int $walletId,string $type,array $context=[]): void { $stmt=$pdo->prepare('INSERT INTO campaign_events (public_id,merchant_user_id,campaign_id,wallet_item_id,contact_id,event_type,event_context_json,created_at) VALUES (?,?,?,?,?,?,?,NOW())');$stmt->execute([mg_crm_gift_uuid(),(int)$contact['merchant_user_id'],(int)$contact['campaign_id'],$walletId,(int)$contact['id'],$type,json_encode($context,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]); }
function mg_crm_gift_bridge(PDO $pdo,array $contact,array $template,int $walletDbId,string $walletPublicId,?int $userId,?string $expiresAt,string $note): ?array { if(!$userId)return null; return mg_zero_reward_issue_from_wallet($pdo,['merchant_user_id'=>(int)$contact['merchant_user_id'],'recipient_user_id'=>$userId,'recipient_external_id'=>(string)$contact['public_id'],'wallet_item_db_id'=>$walletDbId,'wallet_item_public_id'=>$walletPublicId,'campaign_public_id'=>(string)$contact['campaign_public_id'],'reward_template_public_id'=>(string)$template['public_id'],'source_type'=>'merchant_crm_direct_gift','source_reference'=>$walletPublicId,'source_line_reference'=>(string)$contact['public_id'],'title'=>(string)$template['title'],'description'=>$template['description']??null,'currency'=>(string)$template['currency'],'display_value_cents'=>(int)$template['value_amount_cents'],'expires_at'=>$expiresAt,'redemption_instructions'=>$template['redemption_instructions']??null,'terms'=>['campaign_type'=>'merchant_crm_direct_gift','original_campaign_type'=>(string)$contact['campaign_type'],'note'=>$note]]); }
function mg_crm_gift_email_payload(array $contact,array $template,string $walletPublicId,string $note,?string $expiresAt): array { $name=trim((string)($contact['name']??''))?:'there';$url=mg_app_base_url().'/inbox.php';$title=(string)$template['title'];$body='<p style="margin:0 0 14px;color:#334155;font-size:16px;line-height:1.6;">Hi '.mg_mail_escape($name).', a merchant sent you a Microgifter reward.</p><p style="margin:0 0 14px;color:#334155;font-size:16px;line-height:1.6;"><strong>'.mg_mail_escape($title).'</strong></p>'.($note!==''?'<p style="margin:0 0 14px;color:#334155;font-size:15px;line-height:1.6;">'.nl2br(mg_mail_escape($note)).'</p>':'').mg_email_button($url,'Open Microgifter inbox').'<p style="margin:14px 0 0;color:#64748b;font-size:13px;line-height:1.6;">Sign into your Microgifter account with this email and the reward will link to your inbox.</p>';return ['subject'=>'You received a Microgifter reward','html'=>mg_email_layout('You received a reward',$body,'Open Microgifter to claim your reward.'),'text'=>"Hi {$name},\n\nA merchant sent you: {$title}\n\n{$note}\n\nOpen Microgifter: {$url}",'email'=>(string)$contact['email'],'campaign_public_id'=>(string)$contact['campaign_public_id'],'contact_public_id'=>(string)$contact['public_id'],'wallet_item_id'=>$walletPublicId,'campaign_type'=>'merchant_crm_gift','original_campaign_type'=>(string)$contact['campaign_type'],'message_type'=>'merchant_crm_gift','expires_at'=>$expiresAt]; }

mg_require_method('POST');
$user=mg_require_permission('merchant.campaigns.manage');$merchantId=(int)$user['id'];$pdo=mg_db();mg_merchant_ensure_workspace($pdo,$user);$input=mg_input();mg_require_csrf_for_write($input);
$contactRef=strtolower(trim((string)($input['contact_id']??$input['contact']??'')));$templateRef=strtolower(trim((string)($input['reward_template_id']??$input['template_id']??'')));$note=trim((string)($input['note']??''));$idem=trim((string)($input['idempotency_key']??''));
if($contactRef===''||strlen($contactRef)!==36||$templateRef===''||strlen($templateRef)!==36||mb_strlen($note)>1000)mg_fail('Invalid CRM gift request.',422);if($idem==='')$idem=substr('crm-gift:'.hash('sha256',$merchantId.'|'.$contactRef.'|'.$templateRef.'|'.$note.'|'.microtime(true)),0,190);
try{
 mg_delivery_install_schema($pdo);$pdo->beginTransaction();
 $stmt=$pdo->prepare('SELECT cc.*,c.public_id campaign_public_id,c.title campaign_title,c.campaign_type FROM campaign_contacts cc INNER JOIN campaigns c ON c.id=cc.campaign_id WHERE cc.public_id=? AND cc.merchant_user_id=? LIMIT 1 FOR UPDATE');$stmt->execute([$contactRef,$merchantId]);$contact=$stmt->fetch(PDO::FETCH_ASSOC);if(!$contact){$pdo->rollBack();mg_fail('CRM contact not found.',404);} if((int)($contact['user_id']??0)<=0){$pdo->rollBack();mg_fail('Customer account required before sending a direct CRM reward.',409);} $t=$pdo->prepare("SELECT * FROM reward_templates WHERE public_id=? AND merchant_user_id=? AND status='active' LIMIT 1 FOR UPDATE");$t->execute([$templateRef,$merchantId]);$template=$t->fetch(PDO::FETCH_ASSOC);if(!$template){$pdo->rollBack();mg_fail('Active reward template not found.',404);} if($template['quantity_limit']!==null&&(int)$template['issued_count']>=(int)$template['quantity_limit']){ $pdo->rollBack();mg_fail('Reward template limit has been reached.',409); }
 $packageContext=mg_user_package_context($pdo,$user);$stampLimit=mg_package_limit_value($packageContext,'monthly_stamps_included');if($stampLimit!==null&&$stampLimit!==''){$stampUsage=$pdo->prepare("SELECT COUNT(*) FROM wallet_items WHERE merchant_user_id=? AND status<>'cancelled' AND issued_at>=?");$stampUsage->execute([$merchantId,gmdate('Y-m-01 00:00:00')]);if((int)$stampUsage->fetchColumn()>=max(0,(int)$stampLimit)&&!mg_package_limit_value($packageContext,'stamp_overage_enabled')){$pdo->rollBack();mg_fail('Monthly stamp limit reached. Upgrade your package or enable stamp overage.',402);}}
 $existing=$pdo->prepare("SELECT public_id FROM wallet_items WHERE merchant_user_id=? AND source_type='manual_send' AND source_id=? AND JSON_UNQUOTE(JSON_EXTRACT(metadata_json,'$.crm_idempotency_key'))=? LIMIT 1");$existing->execute([$merchantId,(string)$contact['public_id'],$idem]);$old=(string)($existing->fetchColumn()?:''); if($old!==''){$pdo->commit();mg_ok(['wallet_item_id'=>$old,'duplicate'=>true],'CRM gift already issued.');}
 $activeDuplicate=$pdo->prepare("SELECT public_id FROM wallet_items WHERE merchant_user_id=? AND contact_id=? AND reward_template_id=? AND source_type='manual_send' AND status IN ('issued','viewed','claimed','redeemed') AND (expires_at IS NULL OR expires_at>NOW()) ORDER BY id DESC LIMIT 1");$activeDuplicate->execute([$merchantId,(int)$contact['id'],(int)$template['id']]);$activeDuplicateId=(string)($activeDuplicate->fetchColumn()?:'');if($activeDuplicateId!==''){$pdo->rollBack();mg_fail('This active reward has already been sent to this customer.',409,['wallet_item_id'=>$activeDuplicateId]);}
 $recent=$pdo->prepare("SELECT COUNT(*) FROM wallet_items WHERE merchant_user_id=? AND contact_id=? AND source_type='manual_send' AND created_at>(NOW() - INTERVAL 10 MINUTE)");$recent->execute([$merchantId,(int)$contact['id']]);if((int)$recent->fetchColumn()>0){$pdo->rollBack();mg_fail('Please wait before sending another reward to this customer.',429);}
 $expiresAt=mg_crm_gift_expiry($template);$walletPublicId=mg_crm_gift_uuid();$stampLedger=mg_stamp_debit_send($pdo,$merchantId,$merchantId,'direct_reward_send',$idem,['source_type'=>'merchant_crm_direct_gift','source_id'=>$walletPublicId,'reference'=>(string)$contact['public_id'],'reason_code'=>'crm_reward_issue','note'=>'CRM reward sent: '.(string)$template['title'],'metadata'=>['campaign_id'=>(string)$contact['campaign_public_id'],'crm_contact_id'=>(string)$contact['public_id'],'reward_template_id'=>(string)$template['public_id'],'recipient_user_id'=>(int)$contact['user_id']]]);$metadata=['campaign_type'=>'merchant_crm_direct_gift','original_campaign_type'=>(string)$contact['campaign_type'],'crm_contact_id'=>(string)$contact['public_id'],'campaign_public_id'=>(string)$contact['campaign_public_id'],'reward_template_id'=>(string)$template['public_id'],'note'=>$note,'crm_idempotency_key'=>$idem,'stamp_ledger_entry_id'=>$stampLedger['entry']['entry_id']??null];
 $ins=$pdo->prepare('INSERT INTO wallet_items (public_id,user_id,contact_id,merchant_user_id,reward_template_id,campaign_id,source_type,source_id,status,value_cents_snapshot,currency_snapshot,title_snapshot,metadata_json,issued_at,expires_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),?,NOW(),NOW())');$ins->execute([$walletPublicId,(int)$contact['user_id'],(int)$contact['id'],$merchantId,(int)$template['id'],(int)$contact['campaign_id'],'manual_send',(string)$contact['public_id'],'issued',(int)$template['value_amount_cents'],(string)$template['currency'],(string)$template['title'],json_encode($metadata,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),$expiresAt]);$walletDbId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE reward_templates SET issued_count=issued_count+1,updated_at=NOW() WHERE id=?')->execute([(int)$template['id']]);
 $bridge=mg_crm_gift_bridge($pdo,$contact,$template,$walletDbId,$walletPublicId,(int)$contact['user_id'],$expiresAt,$note);$emailDelivery=null;if(filter_var((string)$contact['email'],FILTER_VALIDATE_EMAIL)&&mg_package_limit_value($packageContext,'email_stamps_enabled')){try{$payload=mg_crm_gift_email_payload($contact,$template,$walletPublicId,$note,$expiresAt);$emailDelivery=mg_delivery_enqueue($pdo,['idempotency_key'=>'crm-gift-email:'.$idem,'event_type'=>'campaign.outbound_email','category'=>'campaign','channel'=>'email','template_key'=>'campaign.merchant_crm_gift','recipient_user_id'=>(int)$contact['user_id'],'recipient_snapshot'=>['email'=>(string)$contact['email'],'name'=>(string)($contact['name']??'')],'payload'=>$payload,'max_attempts'=>3]);}catch(Throwable $e){$emailDelivery=['queued'=>false,'reason'=>'delivery_enqueue_failed'];}}elseif(filter_var((string)$contact['email'],FILTER_VALIDATE_EMAIL)){$emailDelivery=['queued'=>false,'reason'=>'email_stamps_disabled'];}
 mg_crm_gift_event($pdo,$contact,$walletDbId,'crm.gift.issued',['wallet_item_id'=>$walletPublicId,'reward_template_id'=>(string)$template['public_id'],'campaign_type'=>'merchant_crm_direct_gift','original_campaign_type'=>(string)$contact['campaign_type'],'pppm_bridge'=>$bridge,'email_delivery'=>$emailDelivery,'stamp_ledger_entry_id'=>$stampLedger['entry']['entry_id']??null]); if($emailDelivery)mg_crm_gift_event($pdo,$contact,$walletDbId,'crm.gift.email_queued',['wallet_item_id'=>$walletPublicId,'delivery'=>$emailDelivery,'campaign_type'=>'merchant_crm_direct_gift']);
 mg_merchant_crm_record_event($pdo,['merchant_user_id'=>$merchantId,'campaign_id'=>(int)$contact['campaign_id'],'campaign_type'=>'merchant_crm_direct_gift','event_type'=>'crm.gift.issued','source_type'=>'merchant_crm_direct_gift','source_public_id'=>(string)$contact['public_id'],'user_id'=>(int)$contact['user_id'],'email'=>(string)$contact['email'],'name'=>(string)($contact['name']??''),'value_cents'=>(int)$template['value_amount_cents'],'metadata'=>['wallet_item_id'=>$walletPublicId,'reward_template_id'=>(string)$template['public_id'],'original_campaign_type'=>(string)$contact['campaign_type'],'stamp_ledger_entry_id'=>$stampLedger['entry']['entry_id']??null]]);
 $pdo->commit();mg_ok(['contact_id'=>(string)$contact['public_id'],'campaign_id'=>(string)$contact['campaign_public_id'],'campaign_type'=>'merchant_crm_direct_gift','wallet_item_id'=>$walletPublicId,'expires_at'=>$expiresAt,'pppm_bridge'=>$bridge,'email_delivery'=>$emailDelivery,'stamp_ledger'=>$stampLedger,'duplicate'=>false],'CRM gift issued.',201);
}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();mg_security_log('error','merchant.crm_gift.failed','Unable to send CRM gift.',['exception_class'=>$error::class,'message'=>$error->getMessage()],$merchantId);mg_fail('Unable to send CRM gift.',500);}
