<?php
declare(strict_types=1);

require_once __DIR__ . '/_merchant.php';
require_once dirname(__DIR__) . '/messages/_messaging.php';
require_once dirname(__DIR__) . '/communications/_communications.php';

function mg_crm_thread_contact_expr(): string { return "SUBSTRING_INDEX(SUBSTRING(mt.conversation_key,5),':',1)"; }
function mg_crm_message_row(array $r,int $merchantId): array { return ['id'=>(string)$r['public_id'],'body'=>(string)$r['body'],'sender_id'=>(int)$r['sender_user_id'],'sender_name'=>(string)($r['sender_name']?:'Microgifter user'),'created_at'=>$r['created_at']??null,'mine'=>(int)$r['sender_user_id']===$merchantId]; }
function mg_crm_thread_row(array $r): array { return ['id'=>(string)$r['public_id'],'subject'=>(string)($r['subject']??'CRM conversation'),'contact_id'=>(string)($r['contact_public_id']??''),'contact_name'=>(string)($r['contact_name']??''),'contact_email'=>(string)($r['contact_email']??''),'campaign_id'=>(string)($r['campaign_public_id']??''),'campaign_title'=>(string)($r['campaign_title']??''),'campaign_type'=>(string)($r['campaign_type']??''),'latest_message'=>(string)($r['latest_body']??''),'latest_sender'=>(string)($r['latest_sender_name']??''),'latest_at'=>$r['latest_created_at']??$r['updated_at']??null,'unread'=>(bool)($r['unread']??false),'updated_at'=>$r['updated_at']??null,'action_url'=>'/merchant-crm.php?thread='.(string)$r['public_id']]; }

$method=strtoupper($_SERVER['REQUEST_METHOD']??'GET');
$user=$method==='GET'?mg_require_permission('merchant.campaigns.view'):mg_require_permission('merchant.campaigns.manage');
$merchantId=(int)$user['id'];$pdo=mg_db();mg_merchant_ensure_workspace($pdo,$user);
$contactExpr=mg_crm_thread_contact_expr();

if($method==='GET'){
 $threadRef=strtolower(trim((string)($_GET['thread']??'')));
 if($threadRef!==''){
  if(strlen($threadRef)!==36)mg_fail('Invalid CRM thread.',422);
  $sql="SELECT mt.id,mt.public_id,mt.subject,mt.updated_at,cc.public_id contact_public_id,cc.name contact_name,cc.email contact_email,c.public_id campaign_public_id,c.title campaign_title,c.campaign_type FROM message_threads mt INNER JOIN campaign_contacts cc ON cc.public_id={$contactExpr} AND cc.merchant_user_id=? LEFT JOIN campaigns c ON c.id=cc.campaign_id WHERE mt.public_id=? AND mt.conversation_key LIKE 'crm:%' LIMIT 1";
  $stmt=$pdo->prepare($sql);$stmt->execute([$merchantId,$threadRef]);$thread=$stmt->fetch(PDO::FETCH_ASSOC);if(!$thread)mg_fail('CRM thread not found.',404);
  $messages=$pdo->prepare("SELECT m.public_id,m.body,m.sender_user_id,m.created_at,COALESCE(NULLIF(u.display_name,''),NULLIF(u.full_name,''),u.email) sender_name FROM messages m INNER JOIN users u ON u.id=m.sender_user_id WHERE m.thread_id=? AND m.moderation_status NOT IN ('hidden','removed') ORDER BY m.created_at ASC,m.id ASC");$messages->execute([(int)$thread['id']]);
  $pdo->prepare('UPDATE message_thread_participants SET last_read_at=NOW() WHERE thread_id=? AND user_id=?')->execute([(int)$thread['id'],$merchantId]);
  mg_ok(['thread'=>array_merge(mg_crm_thread_row($thread),['messages'=>array_map(fn($r)=>mg_crm_message_row($r,$merchantId),$messages->fetchAll(PDO::FETCH_ASSOC))])]);
 }
 $limit=max(1,min(100,(int)($_GET['limit']??50)));
 $sql="SELECT mt.id,mt.public_id,mt.subject,mt.updated_at,cc.public_id contact_public_id,cc.name contact_name,cc.email contact_email,c.public_id campaign_public_id,c.title campaign_title,c.campaign_type,latest.body latest_body,latest.created_at latest_created_at,COALESCE(NULLIF(sender.display_name,''),NULLIF(sender.full_name,''),sender.email) latest_sender_name,CASE WHEN latest.created_at IS NOT NULL AND (mtp.last_read_at IS NULL OR latest.created_at>mtp.last_read_at) AND latest.sender_user_id<>? THEN 1 ELSE 0 END unread FROM message_threads mt INNER JOIN message_thread_participants mtp ON mtp.thread_id=mt.id AND mtp.user_id=? INNER JOIN campaign_contacts cc ON cc.public_id={$contactExpr} AND cc.merchant_user_id=? LEFT JOIN campaigns c ON c.id=cc.campaign_id LEFT JOIN messages latest ON latest.id=(SELECT m2.id FROM messages m2 WHERE m2.thread_id=mt.id ORDER BY m2.created_at DESC,m2.id DESC LIMIT 1) LEFT JOIN users sender ON sender.id=latest.sender_user_id WHERE mt.conversation_key LIKE 'crm:%' ORDER BY unread DESC,COALESCE(latest.created_at,mt.updated_at) DESC LIMIT {$limit}";
 $stmt=$pdo->prepare($sql);$stmt->execute([$merchantId,$merchantId,$merchantId]);$threads=array_map('mg_crm_thread_row',$stmt->fetchAll(PDO::FETCH_ASSOC));
 $unread=count(array_filter($threads,fn($t)=>$t['unread']));mg_ok(['threads'=>$threads,'unread_count'=>$unread]);
}
if($method!=='POST')mg_fail('Method not allowed.',405);
$input=mg_input();mg_require_csrf_for_write($input);$threadRef=strtolower(trim((string)($input['thread_id']??$input['thread']??'')));$body=mg_message_validate_body($input['body']??'');if($threadRef===''||strlen($threadRef)!==36)mg_fail('Invalid CRM thread.',422);
try{$pdo->beginTransaction();$sql="SELECT mt.id,mt.public_id,mt.subject,cc.public_id contact_public_id,cc.id contact_db_id,cc.campaign_id,cc.user_id,c.campaign_type FROM message_threads mt INNER JOIN message_thread_participants mtp ON mtp.thread_id=mt.id AND mtp.user_id=? INNER JOIN campaign_contacts cc ON cc.public_id={$contactExpr} AND cc.merchant_user_id=? LEFT JOIN campaigns c ON c.id=cc.campaign_id WHERE mt.public_id=? AND mt.conversation_key LIKE 'crm:%' LIMIT 1 FOR UPDATE";$stmt=$pdo->prepare($sql);$stmt->execute([$merchantId,$merchantId,$threadRef]);$thread=$stmt->fetch(PDO::FETCH_ASSOC);if(!$thread)mg_fail('CRM thread not found.',404);$messageId=mg_public_uuid();$pdo->prepare("INSERT INTO messages (public_id,thread_id,sender_user_id,body,idempotency_key,source_type,source_reference,created_at) VALUES (?,?,?,?,?,?,?,NOW())")->execute([$messageId,(int)$thread['id'],$merchantId,$body,'merchant-crm-reply:'.hash('sha256',$merchantId.'|'.$threadRef.'|'.$body.'|'.microtime(true)),'merchant_crm',(string)$thread['contact_public_id']]);$pdo->prepare('UPDATE message_threads SET updated_at=NOW() WHERE id=?')->execute([(int)$thread['id']]);$pdo->prepare('UPDATE message_thread_participants SET last_read_at=NOW() WHERE thread_id=? AND user_id=?')->execute([(int)$thread['id'],$merchantId]);$parts=$pdo->prepare('SELECT user_id FROM message_thread_participants WHERE thread_id=? AND user_id<>?');$parts->execute([(int)$thread['id'],$merchantId]);foreach($parts->fetchAll(PDO::FETCH_ASSOC) as $p){mg_create_notification($pdo,(int)$p['user_id'],'message','New merchant message',mb_substr($body,0,500),'/messages.php?thread='.rawurlencode($threadRef),['actor_user_id'=>$merchantId,'event_key'=>'crm.reply.'.$messageId,'thread_id'=>(int)$thread['id'],'message_id'=>$messageId,'contact_id'=>(int)$thread['contact_db_id'],'campaign_id'=>(int)$thread['campaign_id'],'campaign_type'=>(string)($thread['campaign_type']??'')]);}$pdo->prepare('INSERT INTO campaign_events (public_id,merchant_user_id,campaign_id,wallet_item_id,contact_id,event_type,event_context_json,created_at) VALUES (?,?,?,?,?,?,?,NOW())')->execute([mg_public_uuid(),$merchantId,(int)$thread['campaign_id'],null,(int)$thread['contact_db_id'],'crm.message.sent',json_encode(['thread_id'=>$threadRef,'message_id'=>$messageId,'source'=>'merchant_crm_messages_panel'],JSON_UNESCAPED_SLASHES)]);$pdo->commit();mg_ok(['thread_id'=>$threadRef,'message_id'=>$messageId],'CRM message sent.',201);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();mg_security_log('error','merchant.crm_messages.send_failed','CRM message send failed.',['exception_class'=>$e::class,'message'=>$e->getMessage()],$merchantId);mg_fail('Unable to send CRM message.',500);} 
