<?php
declare(strict_types=1);
require_once __DIR__ . '/_merchant.php';

function mg_dcl_can(array $user,string $permission): bool{ $roles=is_array($user['roles']??null)?$user['roles']:[]; if(array_intersect($roles,['merchant','admin','super_admin']))return true; $permissions=is_array($user['permissions']??null)?$user['permissions']:[]; return in_array($permission,$permissions,true)||in_array('merchant.manage',$permissions,true); }
function mg_dcl_require(array $user,string $permission): void{ if(!mg_dcl_can($user,$permission))mg_fail('Permission denied.',403); }
function mg_dcl_text(mixed $value,string $fallback='',int $max=180): string{ $text=trim((string)$value); if($text==='')$text=$fallback; $text=preg_replace('/\s+/',' ',$text)?:$fallback; return mb_substr($text,0,$max); }
function mg_dcl_json(mixed $value): ?string{ if($value===null||$value===''||$value===[])return null; if(!is_array($value))mg_fail('Metadata must be an object.',422); return json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE); }
function mg_dcl_campaign(PDO $pdo,int $merchantId,string $ref): array{ $ref=strtolower(trim($ref)); if($ref==='')mg_fail('Campaign reference is required.',422); $stmt=$pdo->prepare('SELECT * FROM campaigns WHERE merchant_user_id=? AND (public_id=? OR public_slug=?) LIMIT 1');$stmt->execute([$merchantId,$ref,$ref]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row)mg_fail('Campaign reference not found for this merchant.',404);return $row; }
function mg_dcl_campaign_type(string $type): string{ return match($type){'newsletter_signup'=>'newsletter','contest_giveaway'=>'contest','qr_reward_drop'=>'landing_page','referral_reward'=>'promotional_crm','birthday_vip'=>'promotional_crm','agent_offer'=>'distribution',default=>'custom'}; }
function mg_dcl_landing(array $c): string{ $path=match((string)$c['campaign_type']){'newsletter_signup'=>'/newsletter-signup.php','contest_giveaway'=>'/contest-entry.php','qr_reward_drop'=>'/qr-drop.php','referral_reward'=>'/referral-reward.php','birthday_vip'=>'/birthday-vip.php','agent_offer'=>'/agent-offer.php',default=>'/campaign.php'}; return (string)$c['campaign_type']==='qr_reward_drop'&&!empty($c['qr_code_token'])?$path.'?token='.rawurlencode((string)$c['qr_code_token']):$path.'?campaign='.rawurlencode((string)($c['public_slug']?:$c['public_id'])); }
function mg_dcl_project(PDO $pdo,int $workspaceId,?string $id): ?array{ if(!$id)return null; $stmt=$pdo->prepare('SELECT * FROM merchant_design_projects WHERE public_id=? AND workspace_id=? LIMIT 1');$stmt->execute([$id,$workspaceId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);return $row?:null; }
function mg_dcl_qr(PDO $pdo,int $workspaceId,?string $id): ?array{ if(!$id)return null; $stmt=$pdo->prepare("SELECT * FROM merchant_qr_codes WHERE public_id=? AND workspace_id=? AND status <> 'archived' LIMIT 1");$stmt->execute([$id,$workspaceId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);return $row?:null; }
function mg_dcl_row(array $row): array{ return ['id'=>(string)$row['public_id'],'project_id'=>$row['project_public_id']??null,'project_name'=>$row['project_name']??null,'qr_code_id'=>$row['qr_public_id']??null,'qr_label'=>$row['qr_label']??null,'qr_payload_url'=>$row['qr_payload_url']??null,'qr_destination_url'=>$row['qr_destination_url']??null,'campaign_type'=>(string)$row['campaign_type'],'campaign_ref'=>(string)$row['campaign_ref'],'campaign_title'=>$row['campaign_title']??null,'landing_page_url'=>$row['landing_page_url']??null,'label'=>$row['label']??null,'metadata'=>json_decode((string)($row['metadata_json']??''),true)?:[],'created_at'=>$row['created_at']??null]; }

$user=mg_require_api_user();$method=strtoupper((string)($_SERVER['REQUEST_METHOD']??'GET'));$pdo=mg_db();$workspace=mg_merchant_ensure_workspace($pdo,$user);$workspaceId=(int)$workspace['id'];$merchantId=(int)$user['id'];
if($method==='GET'){mg_dcl_require($user,'merchant.design_assets.view');$stmt=$pdo->prepare('SELECT l.*,p.public_id project_public_id,p.name project_name,q.public_id qr_public_id,q.label qr_label,q.qr_payload_url,q.destination_url qr_destination_url,c.title campaign_title,CASE WHEN c.public_id IS NOT NULL THEN CASE c.campaign_type WHEN "newsletter_signup" THEN CONCAT("/newsletter-signup.php?campaign=",COALESCE(c.public_slug,c.public_id)) WHEN "contest_giveaway" THEN CONCAT("/contest-entry.php?campaign=",COALESCE(c.public_slug,c.public_id)) WHEN "qr_reward_drop" THEN CONCAT("/qr-drop.php?token=",c.qr_code_token) WHEN "referral_reward" THEN CONCAT("/referral-reward.php?campaign=",COALESCE(c.public_slug,c.public_id)) WHEN "birthday_vip" THEN CONCAT("/birthday-vip.php?campaign=",COALESCE(c.public_slug,c.public_id)) WHEN "agent_offer" THEN CONCAT("/agent-offer.php?campaign=",COALESCE(c.public_slug,c.public_id)) ELSE CONCAT("/campaign.php?campaign=",COALESCE(c.public_slug,c.public_id)) END ELSE NULL END landing_page_url FROM merchant_design_campaign_links l LEFT JOIN merchant_design_projects p ON p.id=l.project_id LEFT JOIN merchant_qr_codes q ON q.id=l.qr_code_id LEFT JOIN campaigns c ON c.merchant_user_id=l.merchant_user_id AND (c.public_id=l.campaign_ref OR c.public_slug=l.campaign_ref) WHERE l.workspace_id=? ORDER BY l.created_at DESC LIMIT 100');$stmt->execute([$workspaceId]);mg_ok(['campaign_links'=>array_map('mg_dcl_row',$stmt->fetchAll(PDO::FETCH_ASSOC))]);}
if($method!=='POST')mg_fail('Method not allowed.',405);$input=mg_input();mg_require_csrf_for_write($input);mg_dcl_require($user,'merchant.design_assets.manage');$campaign=mg_dcl_campaign($pdo,$merchantId,(string)($input['campaign_ref']??$input['campaign']??''));$project=mg_dcl_project($pdo,$workspaceId,trim((string)($input['project_id']??''))?:null);$qr=mg_dcl_qr($pdo,$workspaceId,trim((string)($input['qr_code_id']??''))?:null);$landing=mg_dcl_landing($campaign);$meta=is_array($input['metadata']??null)?$input['metadata']:[];$meta['campaign_public_id']=(string)$campaign['public_id'];$meta['campaign_type']=(string)$campaign['campaign_type'];$meta['landing_page_url']=$landing;if($qr){$meta['qr_payload_url']=(string)$qr['qr_payload_url'];$pdo->prepare('UPDATE merchant_qr_codes SET campaign_ref=COALESCE(campaign_ref,?),destination_url=IF(qr_type="campaign",?,destination_url),updated_at=NOW() WHERE id=?')->execute([(string)($campaign['public_slug']?:$campaign['public_id']),$landing,(int)$qr['id']]);}$linkId=mg_merchant_uuid();$pdo->prepare('INSERT INTO merchant_design_campaign_links (public_id,workspace_id,merchant_user_id,project_id,qr_code_id,campaign_type,campaign_ref,label,metadata_json,created_by_user_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,NOW())')->execute([$linkId,$workspaceId,$merchantId,$project?(int)$project['id']:null,$qr?(int)$qr['id']:null,mg_dcl_campaign_type((string)$campaign['campaign_type']),(string)($campaign['public_slug']?:$campaign['public_id']),mg_dcl_text($input['label']??'', '',180)?:null,mg_dcl_json($meta),$merchantId]);mg_audit('merchant.design_campaign_linked','merchant_design_campaign_link',['link_id'=>$linkId,'campaign_ref'=>(string)$campaign['public_id'],'landing_page_url'=>$landing,'qr_id'=>$qr?(string)$qr['public_id']:null],$merchantId);mg_ok(['link_id'=>$linkId,'campaign_ref'=>(string)$campaign['public_id'],'landing_page_url'=>$landing,'qr_code_id'=>$qr?(string)$qr['public_id']:null],'Campaign link saved.',201);
