<?php
declare(strict_types=1);
require_once __DIR__ . '/_merchant.php';
mg_require_method('GET');$user=mg_require_permission('merchant.payments.view');$pdo=mg_db();
$workspace=mg_merchant_ensure_workspace($pdo,$user);
$merchantId=(int)$user['id'];
$summary=$pdo->prepare("SELECT COUNT(*) orders,COALESCE(SUM(total_cents),0) gross_cents,COALESCE(SUM(payment_status='paid'),0) paid_orders,COALESCE(SUM(payment_status IN ('refunded','partially_refunded')),0) refunded_orders,COALESCE(SUM(payment_status='disputed'),0) disputed_orders FROM commerce_orders WHERE merchant_user_id=?");$summary->execute([$merchantId]);
$orders=$pdo->prepare("SELECT o.public_id,o.currency,o.total_cents,o.payment_status,o.fulfillment_status,o.paid_at,o.created_at,COUNT(DISTINCT coi.id) item_count,COALESCE(SUM(DISTINCT pr.amount_cents),0) refunded_cents,COUNT(DISTINCT ppi.id) pppm_item_count,COUNT(DISTINCT mi.id) microgift_count,COUNT(DISTINCT ac.public_id) inbox_item_count,COUNT(DISTINCT CASE WHEN ppi.status='redeemed' THEN ppi.id END) redeemed_pppm_count FROM commerce_orders o LEFT JOIN commerce_order_items coi ON coi.order_id=o.id LEFT JOIN payment_refunds pr ON pr.order_id=o.id AND pr.status='succeeded' LEFT JOIN pppm_items ppi ON ppi.merchant_user_id=o.merchant_user_id AND ppi.source_reference=o.public_id LEFT JOIN microgift_instances mi ON mi.pppm_item_id=ppi.id LEFT JOIN microgift_inbox_items ac ON ac.instance_id=mi.id AND ac.archived_at IS NULL WHERE o.merchant_user_id=? GROUP BY o.id ORDER BY o.created_at DESC LIMIT 200");$orders->execute([$merchantId]);
$refunds=$pdo->prepare('SELECT public_id,amount_cents,currency,reason,status,processed_at,created_at FROM payment_refunds WHERE merchant_user_id=? ORDER BY created_at DESC LIMIT 100');$refunds->execute([$merchantId]);
$payouts=$pdo->prepare('SELECT public_id,provider_key,currency,gross_cents,fee_cents,adjustment_cents,net_cents,status,arrival_date,paid_at,created_at FROM merchant_payouts WHERE merchant_user_id=? ORDER BY created_at DESC LIMIT 100');$payouts->execute([$merchantId]);
$disputes=$pdo->prepare('SELECT public_id,amount_cents,currency,reason,status,response_due_at,created_at FROM payment_disputes WHERE merchant_user_id=? ORDER BY created_at DESC LIMIT 100');$disputes->execute([$merchantId]);
$ledger=$pdo->prepare("SELECT account_code,entry_type,SUM(amount_cents) amount_cents,currency FROM financial_ledger_entries WHERE merchant_user_id=? GROUP BY account_code,entry_type,currency ORDER BY account_code");$ledger->execute([$merchantId]);
$reconciliation=$pdo->prepare('SELECT public_id,provider_key,period_start,period_end,status,expected_cents,provider_cents,difference_cents,exception_count,created_at FROM financial_reconciliation_runs WHERE merchant_user_id=? ORDER BY created_at DESC LIMIT 50');$reconciliation->execute([$merchantId]);
$methodStmt=$pdo->prepare('SELECT state_json FROM merchant_payment_readiness WHERE workspace_id=? LIMIT 1');$methodStmt->execute([(int)$workspace['id']]);
$methodRow=$methodStmt->fetch(PDO::FETCH_ASSOC)?:[];$methodState=json_decode((string)($methodRow['state_json']??''),true);if(!is_array($methodState))$methodState=[];
$paymentMethods=['cash'=>['enabled'=>!empty($methodState['payment_methods']['cash']['enabled']),'mode'=>'test','label'=>'Pay with cash']];
mg_ok(['summary'=>$summary->fetch()?:[],'orders'=>$orders->fetchAll(),'refunds'=>$refunds->fetchAll(),'payouts'=>$payouts->fetchAll(),'disputes'=>$disputes->fetchAll(),'ledger'=>$ledger->fetchAll(),'reconciliation'=>$reconciliation->fetchAll(),'payment_methods'=>$paymentMethods,'links'=>['pppm'=>'/merchant-pppm.php','payments'=>'/merchant-payments.php']]);