<?php
declare(strict_types=1);
require_once __DIR__ . '/_merchant.php';
require_once dirname(__DIR__) . '/communications/_communications.php';
require_once dirname(__DIR__) . '/messages/_delivery_validation.php';
require_once dirname(__DIR__,2) . '/includes/reviews-case-studies.php';

$user=mg_merchant_require_permission('merchant.campaigns.manage');
$merchantId=(int)$user['id'];$pdo=mg_db();mg_merchant_ensure_workspace($pdo,$user);

if($_SERVER['REQUEST_METHOD']==='GET'){
 $status=strtolower(trim((string)($_GET['status']??'all')));$rating=(int)($_GET['rating']??0);$q=trim((string)($_GET['q']??''));$where=['r.merchant_user_id=?'];$args=[$merchantId];
 if(in_array($status,['pending','published','hidden','removed'],true)){$where[]='r.status=?';$args[]=$status;}if($rating>=1&&$rating<=5){$where[]='r.rating=?';$args[]=$rating;}if($q!==''){$where[]='(r.reviewer_name LIKE ? OR r.review_title LIKE ? OR r.review_body LIKE ?)';$like='%'.$q.'%';array_push($args,$like,$like,$like);}
 $stmt=$pdo->prepare("SELECT r.*,p.display_name merchant_name,p.slug profile_slug,rr.public_id reply_public_id,rr.reply_body,rr.status reply_status,rr.created_at reply_created_at,rr.updated_at reply_updated_at FROM customer_reviews r INNER JOIN public_profiles p ON p.id=r.profile_id LEFT JOIN customer_review_replies rr ON rr.review_id=r.id AND rr.status<>'removed' WHERE ".implode(' AND ',$where)." ORDER BY r.submitted_at DESC,r.id DESC LIMIT 200");$stmt->execute($args);$reviews=array_map('mg_rcs_review_payload',$stmt->fetchAll(PDO::FETCH_ASSOC));
 $summaryStmt=$pdo->prepare("SELECT COUNT(*) total,COALESCE(AVG(IF(status='published',rating,NULL)),0) average_rating,SUM(status='pending') pending_count,SUM(status='published') published_count,SUM(featured_on_profile=1 AND status='published') featured_count,SUM(status='published' AND NOT EXISTS(SELECT 1 FROM customer_review_replies rr WHERE rr.review_id=customer_reviews.id AND rr.status='published')) unanswered_count FROM customer_reviews WHERE merchant_user_id=?");$summaryStmt->execute([$merchantId]);$summary=$summaryStmt->fetch(PDO::FETCH_ASSOC)?:[];
 mg_ok(['reviews'=>$reviews,'summary'=>['total'=>(int)($summary['total']??0),'average'=>round((float)($summary['average_rating']??0),1),'pending'=>(int)($summary['pending_count']??0),'published'=>(int)($summary['published_count']??0),'featured'=>(int)($summary['featured_count']??0),'unanswered'=>(int)($summary['unanswered_count']??0)]]);
}

mg_require_method('POST');$input=mg_input();mg_require_csrf_for_write($input);$action=strtolower(trim((string)($input['action']??'')));$reviewRef=strtolower(trim((string)($input['review_id']??'')));
try{$pdo->beginTransaction();$stmt=$pdo->prepare("SELECT r.*,cc.public_id contact_public_id,cc.email contact_email,cc.name contact_name,COALESCE(cc.user_id,r.reviewer_user_id) recipient_user_id FROM customer_reviews r LEFT JOIN campaign_contacts cc ON cc.id=r.contact_id WHERE r.public_id=? AND r.merchant_user_id=? LIMIT 1 FOR UPDATE");$stmt->execute([$reviewRef,$merchantId]);$review=$stmt->fetch(PDO::FETCH_ASSOC);if(!$review)mg_fail('Review not found.',404);
 if($action==='reply'){$body=trim((string)($input['reply_body']??''));if(mb_strlen($body)<2||mb_strlen($body)>3000)mg_fail('Reply must be between 2 and 3000 characters.',422);$existing=$pdo->prepare('SELECT * FROM customer_review_replies WHERE review_id=? LIMIT 1 FOR UPDATE');$existing->execute([(int)$review['id']]);$before=$existing->fetch(PDO::FETCH_ASSOC);if($before){$pdo->prepare("UPDATE customer_review_replies SET reply_body=?,status='published',author_user_id=?,updated_at=NOW() WHERE id=?")->execute([$body,$merchantId,(int)$before['id']]);$replyId=(int)$before['id'];$replyRef=(string)$before['public_id'];}else{$replyRef=mg_rcs_uuid();$pdo->prepare("INSERT INTO customer_review_replies(public_id,review_id,merchant_user_id,author_user_id,reply_body,status,created_at,updated_at) VALUES(?,?,?,?,?,'published',NOW(),NOW())")->execute([$replyRef,(int)$review['id'],$merchantId,$merchantId,$body]);$replyId=(int)$pdo->lastInsertId();}
   $recipientId=(int)($review['recipient_user_id']??0);if($recipientId>0){$conversationKey='review:'.$reviewRef;$thread=$pdo->prepare('SELECT id,public_id FROM message_threads WHERE conversation_key=? LIMIT 1 FOR UPDATE');$thread->execute([$conversationKey]);$threadRow=$thread->fetch(PDO::FETCH_ASSOC);if(!$threadRow){$threadRef=mg_rcs_uuid();$subject=mb_substr('Review follow-up: '.((string)($review['review_title']??'Customer review')),0,160);$pdo->prepare('INSERT INTO message_threads(public_id,conversation_key,created_by_user_id,subject,created_at,updated_at) VALUES(?,?,?,?,NOW(),NOW())')->execute([$threadRef,$conversationKey,$merchantId,$subject]);$threadRow=['id'=>(int)$pdo->lastInsertId(),'public_id'=>$threadRef];}$pdo->prepare('INSERT IGNORE INTO message_thread_participants(thread_id,user_id,joined_at,last_read_at) VALUES(?,?,NOW(),NOW())')->execute([(int)$threadRow['id'],$merchantId]);$pdo->prepare('INSERT IGNORE INTO message_thread_participants(thread_id,user_id,joined_at) VALUES(?,?,NOW())')->execute([(int)$threadRow['id'],$recipientId]);$messageRef=mg_rcs_uuid();$messageBody='Merchant replied to your review: '.$body;$pdo->prepare("INSERT INTO messages(public_id,thread_id,sender_user_id,recipient_user_id,body,idempotency_key,source_type,source_reference,created_at) VALUES(?,?,?,?,?,?,?,?,NOW())")->execute([$messageRef,(int)$threadRow['id'],$merchantId,$recipientId,$messageBody,'review-reply:'.$replyRef.':'.time(),'customer_review_reply',$reviewRef]);$pdo->prepare('UPDATE message_threads SET updated_at=NOW() WHERE id=?')->execute([(int)$threadRow['id']]);mg_create_notification($pdo,$recipientId,'message','Merchant replied to your review',$body,'/messages.php?thread='.rawurlencode((string)$threadRow['public_id']),['actor_user_id'=>$merchantId,'event_key'=>'review.reply.'.$replyRef,'review_id'=>(int)$review['id'],'thread_id'=>(int)$threadRow['id'],'thread_public_id'=>(string)$threadRow['public_id'],'source_system'=>'customer_reviews']);}
   mg_rcs_audit($pdo,['actor_user_id'=>$merchantId,'merchant_user_id'=>$merchantId,'review_id'=>(int)$review['id'],'action'=>'merchant.review.replied','before'=>$before,'after'=>['reply_body'=>$body,'status'=>'published']]);$pdo->commit();mg_ok(['reply_id'=>$replyRef],'Public reply saved and customer messaging updated.');}
 if($action==='feature'){$featured=!empty($input['featured'])?1:0;$before=['featured_on_profile'=>(int)$review['featured_on_profile']];$pdo->prepare('UPDATE customer_reviews SET featured_on_profile=?,updated_at=NOW() WHERE id=?')->execute([$featured,(int)$review['id']]);mg_rcs_audit($pdo,['actor_user_id'=>$merchantId,'merchant_user_id'=>$merchantId,'review_id'=>(int)$review['id'],'action'=>'merchant.review.featured','before'=>$before,'after'=>['featured_on_profile'=>$featured]]);$pdo->commit();mg_ok(['featured'=>(bool)$featured],'Review feature setting updated.');}
 if($action==='status'){$status=strtolower(trim((string)($input['status']??'')));if(!in_array($status,['published','hidden'],true))mg_fail('Merchants may publish or hide reviews.',422);$before=['status'=>$review['status']];$pdo->prepare('UPDATE customer_reviews SET status=?,updated_at=NOW() WHERE id=?')->execute([$status,(int)$review['id']]);mg_rcs_audit($pdo,['actor_user_id'=>$merchantId,'merchant_user_id'=>$merchantId,'review_id'=>(int)$review['id'],'action'=>'merchant.review.status_changed','before'=>$before,'after'=>['status'=>$status]]);$pdo->commit();mg_ok(['status'=>$status],'Review status updated.');}
 if($action==='message'){$body=trim((string)($input['message']??''));if(mb_strlen($body)<1||mb_strlen($body)>5000)mg_fail('Message is required and must be 5000 characters or fewer.',422);$recipientId=(int)($review['recipient_user_id']??0);if($recipientId<1)mg_fail('This reviewer is not linked to a Microgifter account.',409);$conversationKey='review:'.$reviewRef;$thread=$pdo->prepare('SELECT id,public_id FROM message_threads WHERE conversation_key=? LIMIT 1 FOR UPDATE');$thread->execute([$conversationKey]);$threadRow=$thread->fetch(PDO::FETCH_ASSOC);if(!$threadRow){$threadRef=mg_rcs_uuid();$pdo->prepare('INSERT INTO message_threads(public_id,conversation_key,created_by_user_id,subject,created_at,updated_at) VALUES(?,?,?,?,NOW(),NOW())')->execute([$threadRef,$conversationKey,$merchantId,'Review follow-up']);$threadRow=['id'=>(int)$pdo->lastInsertId(),'public_id'=>$threadRef];}$pdo->prepare('INSERT IGNORE INTO message_thread_participants(thread_id,user_id,joined_at,last_read_at) VALUES(?,?,NOW(),NOW())')->execute([(int)$threadRow['id'],$merchantId]);$pdo->prepare('INSERT IGNORE INTO message_thread_participants(thread_id,user_id,joined_at) VALUES(?,?,NOW())')->execute([(int)$threadRow['id'],$recipientId]);$messageRef=mg_rcs_uuid();$pdo->prepare('INSERT INTO messages(public_id,thread_id,sender_user_id,recipient_user_id,body,idempotency_key,source_type,source_reference,created_at) VALUES(?,?,?,?,?,?,?,?,NOW())')->execute([$messageRef,(int)$threadRow['id'],$merchantId,$recipientId,$body,'review-message:'.$merchantId.':'.$reviewRef.':'.hash('sha256',$body.microtime(true)),'customer_review_message',$reviewRef]);$pdo->prepare('UPDATE message_threads SET updated_at=NOW() WHERE id=?')->execute([(int)$threadRow['id']]);mg_create_notification($pdo,$recipientId,'message','New merchant message',$body,'/messages.php?thread='.rawurlencode((string)$threadRow['public_id']),['actor_user_id'=>$merchantId,'event_key'=>'review.message.'.$messageRef,'review_id'=>(int)$review['id'],'thread_id'=>(int)$threadRow['id'],'thread_public_id'=>(string)$threadRow['public_id'],'source_system'=>'customer_reviews']);mg_rcs_audit($pdo,['actor_user_id'=>$merchantId,'merchant_user_id'=>$merchantId,'review_id'=>(int)$review['id'],'action'=>'merchant.review.private_message_sent','metadata'=>['thread_id'=>$threadRow['public_id'],'message_id'=>$messageRef]]);$pdo->commit();mg_ok(['thread_id'=>$threadRow['public_id'],'message_id'=>$messageRef],'Message sent through Microgifter Messages.');}
 mg_fail('Unsupported action.',422);
}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();mg_security_log('error','merchant.reviews.failed','Review action failed.',['action'=>$action,'message'=>$error->getMessage()],$merchantId);mg_fail('Unable to complete review action.',500);}
