<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/api/db.php';
function mg_blog_statuses(): array { return ['draft','published','scheduled','archived']; }
function mg_blog_table_exists(PDO $pdo, string $table): bool { try { $s=$pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?'); $s->execute([$table]); return (int)$s->fetchColumn()>0; } catch (Throwable) { return false; } }
function mg_blog_schema_ready(PDO $pdo): array { $missing=[]; foreach(['blog_posts','blog_categories','blog_tags','blog_post_tags'] as $t){ if(!mg_blog_table_exists($pdo,$t)){$missing[]=$t;} } return ['ready'=>$missing===[],'missing'=>$missing]; }
function mg_blog_slugify(string $value, string $fallback='post'): string { $value=trim(strtolower($value)); if(function_exists('iconv')){ $c=@iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$value); if(is_string($c)&&$c!==''){$value=$c;} } $value=trim(preg_replace('/[^a-z0-9]+/','-',$value) ?? '', '-'); return $value!=='' ? substr($value,0,180) : $fallback; }
function mg_blog_unique_slug(PDO $pdo,string $slug,int $excludeId=0): string { $base=mg_blog_slugify($slug); $candidate=$base; $i=2; while(true){ $sql='SELECT id FROM blog_posts WHERE slug=? AND deleted_at IS NULL'; $p=[$candidate]; if($excludeId>0){$sql.=' AND id<>?';$p[]=$excludeId;} $s=$pdo->prepare($sql.' LIMIT 1'); $s->execute($p); if(!$s->fetch(PDO::FETCH_ASSOC)){return $candidate;} $candidate=substr($base,0,172).'-'.$i++; } }
function mg_blog_datetime_input_to_sql(?string $v): ?string { $v=trim((string)$v); if($v===''){return null;} try{return (new DateTimeImmutable(str_replace('T',' ',$v)))->format('Y-m-d H:i:s');}catch(Throwable){return null;} }
function mg_blog_sql_to_datetime_input(?string $v): string { $v=trim((string)$v); if($v===''){return '';} try{return (new DateTimeImmutable($v))->format('Y-m-d\TH:i');}catch(Throwable){return '';} }
function mg_blog_format_date(?string $v): string { $v=trim((string)$v); if($v===''){return 'Unpublished';} try{return (new DateTimeImmutable($v))->format('M j, Y');}catch(Throwable){return $v;} }
function mg_blog_excerpt(string $body,int $limit=170): string { $t=trim(preg_replace('/\s+/',' ',strip_tags($body)) ?? ''); if($t===''){return '';} return mb_strlen($t)<=$limit ? $t : rtrim(mb_substr($t,0,$limit-1)," \t\n\r\0\x0B.,;:").'…'; }
function mg_blog_reading_time(string $body): int { $w=preg_split('/\s+/',trim(strip_tags($body))) ?: []; return max(1,(int)ceil(count(array_filter($w))/220)); }
function mg_blog_allowed_html(string $html): string { $html=strip_tags($html,'<p><br><strong><b><em><i><u><h2><h3><h4><ul><ol><li><blockquote><a><img><figure><figcaption><code><pre><hr>'); $html=preg_replace('/\s+on[a-z]+\s*=\s*("[^"]*"|\'[^\']*\'|[^\s>]+)/i','',$html) ?? $html; $html=preg_replace('/\s+(href|src)\s*=\s*("|\')\s*javascript:[^"\']*("|\')/i','',$html) ?? $html; return trim($html); }
function mg_blog_categories(PDO $pdo,bool $activeOnly=false): array { $sql='SELECT id,name,slug,description,sort_order,is_active FROM blog_categories'.($activeOnly?' WHERE is_active=1':'').' ORDER BY sort_order ASC,name ASC'; return $pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC) ?: []; }
function mg_blog_category_by_slug(PDO $pdo,string $slug): ?array { $s=$pdo->prepare('SELECT id,name,slug,description,sort_order,is_active FROM blog_categories WHERE slug=? AND is_active=1 LIMIT 1'); $s->execute([$slug]); $r=$s->fetch(PDO::FETCH_ASSOC); return $r?:null; }
function mg_blog_public_post_url(array $post): string { return '/blog-post.php?slug='.rawurlencode((string)($post['slug']??'')); }
function mg_blog_public_category_url(array $cat): string { return '/blog-category.php?slug='.rawurlencode((string)($cat['slug']??'')); }
function mg_blog_public_where(array $filters,array &$params): array { $w=["p.status='published'",'p.deleted_at IS NULL','(p.published_at IS NULL OR p.published_at <= NOW())']; if(!empty($filters['category_slug'])){$w[]='c.slug=?';$params[]=(string)$filters['category_slug'];} if(!empty($filters['search'])){$w[]='(p.title LIKE ? OR p.excerpt LIKE ? OR p.body LIKE ?)';$n='%'.(string)$filters['search'].'%';array_push($params,$n,$n,$n);} if(!empty($filters['featured'])){$w[]='p.is_featured=1';} return $w; }
function mg_blog_list_public_posts(PDO $pdo,array $filters=[]): array { $p=[];$w=mg_blog_public_where($filters,$p);$limit=max(1,min(60,(int)($filters['limit']??12)));$offset=max(0,(int)($filters['offset']??0));$sql='SELECT p.*,c.name AS category_name,c.slug AS category_slug,u.display_name AS author_display_name,u.full_name AS author_full_name,u.email AS author_email FROM blog_posts p LEFT JOIN blog_categories c ON c.id=p.category_id LEFT JOIN users u ON u.id=p.author_id WHERE '.implode(' AND ',$w).' ORDER BY p.is_featured DESC, COALESCE(p.published_at,p.created_at) DESC, p.id DESC LIMIT '.$limit.' OFFSET '.$offset; $s=$pdo->prepare($sql);$s->execute($p);return $s->fetchAll(PDO::FETCH_ASSOC)?:[]; }
function mg_blog_count_public_posts(PDO $pdo,array $filters=[]): int { $p=[];$w=mg_blog_public_where($filters,$p);$s=$pdo->prepare('SELECT COUNT(*) FROM blog_posts p LEFT JOIN blog_categories c ON c.id=p.category_id WHERE '.implode(' AND ',$w));$s->execute($p);return (int)$s->fetchColumn(); }
function mg_blog_get_public_post(PDO $pdo,string $slug): ?array { $s=$pdo->prepare("SELECT p.*,c.name AS category_name,c.slug AS category_slug,u.display_name AS author_display_name,u.full_name AS author_full_name,u.email AS author_email FROM blog_posts p LEFT JOIN blog_categories c ON c.id=p.category_id LEFT JOIN users u ON u.id=p.author_id WHERE p.slug=? AND p.status='published' AND p.deleted_at IS NULL AND (p.published_at IS NULL OR p.published_at <= NOW()) LIMIT 1");$s->execute([$slug]);$r=$s->fetch(PDO::FETCH_ASSOC);return $r?:null; }
function mg_blog_get_admin_post(PDO $pdo,int $id): ?array { $s=$pdo->prepare('SELECT p.*,c.name AS category_name,c.slug AS category_slug,u.display_name AS author_display_name,u.full_name AS author_full_name,u.email AS author_email FROM blog_posts p LEFT JOIN blog_categories c ON c.id=p.category_id LEFT JOIN users u ON u.id=p.author_id WHERE p.id=? AND p.deleted_at IS NULL LIMIT 1');$s->execute([$id]);$r=$s->fetch(PDO::FETCH_ASSOC);return $r?:null; }
function mg_blog_admin_posts(PDO $pdo,array $filters=[]): array { $w=['p.deleted_at IS NULL'];$p=[]; if(!empty($filters['status'])&&in_array((string)$filters['status'],mg_blog_statuses(),true)){$w[]='p.status=?';$p[]=(string)$filters['status'];} if(!empty($filters['category_id'])){$w[]='p.category_id=?';$p[]=(int)$filters['category_id'];} if(!empty($filters['search'])){$w[]='(p.title LIKE ? OR p.slug LIKE ? OR p.excerpt LIKE ?)';$n='%'.(string)$filters['search'].'%';array_push($p,$n,$n,$n);} $limit=max(1,min(100,(int)($filters['limit']??50))); $sql='SELECT p.id,p.title,p.slug,p.excerpt,p.status,p.featured_image,p.is_featured,p.published_at,p.updated_at,c.name AS category_name,u.display_name AS author_display_name,u.full_name AS author_full_name,u.email AS author_email FROM blog_posts p LEFT JOIN blog_categories c ON c.id=p.category_id LEFT JOIN users u ON u.id=p.author_id WHERE '.implode(' AND ',$w).' ORDER BY p.updated_at DESC,p.id DESC LIMIT '.$limit; $s=$pdo->prepare($sql);$s->execute($p);return $s->fetchAll(PDO::FETCH_ASSOC)?:[]; }
function mg_blog_status_counts(PDO $pdo): array { $c=['all'=>0,'draft'=>0,'published'=>0,'scheduled'=>0,'archived'=>0]; foreach(($pdo->query('SELECT status,COUNT(*) total FROM blog_posts WHERE deleted_at IS NULL GROUP BY status')->fetchAll(PDO::FETCH_ASSOC)?:[]) as $r){$s=(string)$r['status'];$t=(int)$r['total'];if(isset($c[$s])){$c[$s]=$t;$c['all']+=$t;}} return $c; }
function mg_blog_tag_names(PDO $pdo,int $postId): array { if($postId<1){return [];} $s=$pdo->prepare('SELECT t.name FROM blog_tags t INNER JOIN blog_post_tags pt ON pt.tag_id=t.id WHERE pt.post_id=? ORDER BY t.name ASC');$s->execute([$postId]);return array_values(array_filter(array_column($s->fetchAll(PDO::FETCH_ASSOC)?:[],'name'))); }
function mg_blog_sync_tags(PDO $pdo,int $postId,string $csv): void { $tags=[]; foreach(explode(',',$csv) as $tag){$name=trim(preg_replace('/\s+/',' ',$tag)??''); if($name!==''){$tags[mg_blog_slugify($name,'tag')]=mb_substr($name,0,80);} } $pdo->prepare('DELETE FROM blog_post_tags WHERE post_id=?')->execute([$postId]); if(!$tags){return;} $sel=$pdo->prepare('SELECT id FROM blog_tags WHERE slug=? LIMIT 1');$ins=$pdo->prepare('INSERT INTO blog_tags (name,slug) VALUES (?,?)');$link=$pdo->prepare('INSERT IGNORE INTO blog_post_tags (post_id,tag_id) VALUES (?,?)'); foreach($tags as $slug=>$name){$sel->execute([$slug]);$id=(int)$sel->fetchColumn(); if($id<1){$ins->execute([$name,$slug]);$id=(int)$pdo->lastInsertId();} if($id>0){$link->execute([$postId,$id]);}} }
function mg_blog_handle_featured_image_upload(string $field,array &$errors): ?string { if(empty($_FILES[$field])||!is_array($_FILES[$field])||(int)($_FILES[$field]['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE){return null;} $f=$_FILES[$field]; if((int)($f['error']??UPLOAD_ERR_OK)!==UPLOAD_ERR_OK){$errors[]='Featured image upload failed.';return null;} $size=(int)($f['size']??0); if($size<1||$size>5*1024*1024){$errors[]='Featured image must be smaller than 5 MB.';return null;} $ext=strtolower(pathinfo((string)($f['name']??'image'),PATHINFO_EXTENSION));$allowed=['jpg'=>'image/jpeg','jpeg'=>'image/jpeg','png'=>'image/png','webp'=>'image/webp']; if(!isset($allowed[$ext])){$errors[]='Featured image must be JPG, PNG, or WebP.';return null;} $dir=dirname(__DIR__,2).'/uploads/blog/featured'; if(!is_dir($dir)&&!mkdir($dir,0775,true)&&!is_dir($dir)){$errors[]='Could not prepare blog upload directory.';return null;} $fn='blog-'.gmdate('Ymd-His').'-'.bin2hex(random_bytes(5)).'.'.($ext==='jpeg'?'jpg':$ext); if(!move_uploaded_file((string)$f['tmp_name'],$dir.'/'.$fn)){$errors[]='Could not save featured image.';return null;} return '/uploads/blog/featured/'.$fn; }
function mg_blog_save_post(PDO $pdo,array $input,array $user,array &$errors): ?int { $id=max(0,(int)($input['id']??0));$existing=$id>0?mg_blog_get_admin_post($pdo,$id):null;if($id>0&&!$existing){$errors[]='Blog post not found.';return null;} $title=trim((string)($input['title']??'')); if($title===''){$errors[]='Post title is required.';} $body=mg_blog_allowed_html((string)($input['body']??'')); if($body===''){$errors[]='Post body is required.';} $status=in_array((string)($input['status']??'draft'),mg_blog_statuses(),true)?(string)$input['status']:'draft'; $slug=mg_blog_unique_slug($pdo,trim((string)($input['slug']??'')) ?: $title,$id); $excerpt=mb_substr(trim((string)($input['excerpt']??'')) ?: mg_blog_excerpt($body,220),0,500); $categoryId=(int)($input['category_id']??0); $categoryId=$categoryId>0?$categoryId:null; $seoTitle=mb_substr(trim((string)($input['seo_title']??'')),0,180); $seoDesc=mb_substr(trim((string)($input['seo_description']??'')),0,255); $canonical=mb_substr(trim((string)($input['canonical_url']??'')),0,255); $cta=(string)($input['cta_type']??'none'); if(!in_array($cta,['none','merchant_signup','investor_page','demo_request','campaign_builder','contact'],true)){$cta='none';} $isFeatured=!empty($input['is_featured'])?1:0; $alt=mb_substr(trim((string)($input['featured_image_alt']??'')),0,255); $image=trim((string)($existing['featured_image']??'')); $upload=mg_blog_handle_featured_image_upload('featured_image_file',$errors); if(is_string($upload)&&$upload!==''){$image=$upload;} elseif(trim((string)($input['featured_image']??''))!==''){$image=mb_substr(trim((string)$input['featured_image']),0,700);} $published=mg_blog_datetime_input_to_sql($input['published_at']??null); $scheduled=null; if($status==='published'&&$published===null){$published=gmdate('Y-m-d H:i:s');} if($status==='scheduled'){$scheduled=$published;} if($errors){return null;} $author=max(1,(int)($user['id']??0)); if($id>0){$s=$pdo->prepare('UPDATE blog_posts SET title=?,slug=?,excerpt=?,body=?,featured_image=?,featured_image_alt=?,status=?,author_id=?,category_id=?,seo_title=?,seo_description=?,canonical_url=?,cta_type=?,is_featured=?,published_at=?,scheduled_at=?,updated_at=NOW() WHERE id=?');$s->execute([$title,$slug,$excerpt,$body,$image?:null,$alt?:null,$status,$author,$categoryId,$seoTitle?:null,$seoDesc?:null,$canonical?:null,$cta,$isFeatured,$published,$scheduled,$id]);} else {$s=$pdo->prepare('INSERT INTO blog_posts (title,slug,excerpt,body,featured_image,featured_image_alt,status,author_id,category_id,seo_title,seo_description,canonical_url,cta_type,is_featured,published_at,scheduled_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$title,$slug,$excerpt,$body,$image?:null,$alt?:null,$status,$author,$categoryId,$seoTitle?:null,$seoDesc?:null,$canonical?:null,$cta,$isFeatured,$published,$scheduled]);$id=(int)$pdo->lastInsertId();} mg_blog_sync_tags($pdo,$id,(string)($input['tags']??'')); return $id; }
function mg_blog_update_post_status(PDO $pdo,int $id,string $status): bool { if($id<1||!in_array($status,mg_blog_statuses(),true)){return false;} $pub=$status==='published'?', published_at=COALESCE(published_at,NOW())':''; $s=$pdo->prepare('UPDATE blog_posts SET status=?, updated_at=NOW()'.$pub.' WHERE id=? AND deleted_at IS NULL');$s->execute([$status,$id]);return $s->rowCount()>0; }
function mg_blog_soft_delete_post(PDO $pdo,int $id): bool { if($id<1){return false;} $s=$pdo->prepare("UPDATE blog_posts SET deleted_at=NOW(), status='archived', updated_at=NOW() WHERE id=? AND deleted_at IS NULL");$s->execute([$id]);return $s->rowCount()>0; }
function mg_blog_author_name(array $post): string { $n=trim((string)($post['author_display_name']??$post['author_full_name']??'')); if($n!==''){return $n;} $e=trim((string)($post['author_email']??'')); return $e!==''?$e:'Microgifter Team'; }
function mg_blog_render_cta(string $type): string { $m=['merchant_signup'=>['Turn future demand into present-day revenue.','Use Microgifter to pre-sell products, reward customers, and track claims in one connected platform.','/pricing.php','Explore merchant tools'],'investor_page'=>['Microgifter is building Pre Sale Revenue infrastructure.','Review the market opportunity and current category thesis for social gifting, local rewards, and demand intelligence.','/investors.php','Open investor page'],'demo_request'=>['See Microgifter in action.','Explore how hospitality merchants can launch rewards, offers, claims, and customer engagement programs from one system.','/learn-more.php','Book a demo'],'campaign_builder'=>['Build a campaign around your best offer.','Create products, rewards, and customer recovery campaigns with Microgifter campaign tools.','/build.php','Open builder'],'contact'=>['Have a Microgifter question?','Start a conversation about merchant growth, local rewards, or investor interest.','/learn-more.php','Contact Microgifter']]; if(!isset($m[$type])){return '';} [$t,$c,$h,$l]=$m[$type]; return '<aside class="mg-blog-cta"><div><span>Microgifter</span><h2>'.mg_e($t).'</h2><p>'.mg_e($c).'</p></div><a href="'.mg_e($h).'">'.mg_e($l).'</a></aside>'; }
