<?php
declare(strict_types=1);
require_once __DIR__ . '/blog-functions.php';
function mg_blog_settings_defaults(): array { return ['blog_title'=>'Microgifter Blog','blog_description'=>'Insights on hospitality marketing, loyalty CRM, social gifting, automated commerce, and Pre Sale Revenue.','default_social_image'=>'','posts_per_page'=>'9','default_cta'=>'demo_request','rss_enabled'=>'1','sitemap_enabled'=>'1','coming_soon_title'=>'Microgifter is preparing public articles.','coming_soon_message'=>'The Content Studio is ready for founder notes, merchant education, product updates, and Pre Sale Revenue category-building posts. Draft starter posts stay private until they are reviewed and published.']; }
function mg_blog_settings_ready(PDO $pdo): bool { return mg_blog_table_exists($pdo,'blog_settings'); }
function mg_blog_media_ready(PDO $pdo): bool { return mg_blog_table_exists($pdo,'blog_media'); }
function mg_blog_get_settings(PDO $pdo): array { $settings=mg_blog_settings_defaults(); if(!mg_blog_settings_ready($pdo)){return $settings;} $rows=$pdo->query('SELECT setting_key,setting_value FROM blog_settings')->fetchAll(PDO::FETCH_ASSOC) ?: []; foreach($rows as $r){$k=(string)$r['setting_key']; if(array_key_exists($k,$settings)){$settings[$k]=(string)($r['setting_value']??'');}} return $settings; }
function mg_blog_save_settings(PDO $pdo,array $input): void { $defaults=mg_blog_settings_defaults(); $s=$pdo->prepare('INSERT INTO blog_settings (setting_key,setting_value) VALUES (?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value), updated_at=NOW()'); foreach($defaults as $k=>$d){$v=trim((string)($input[$k]??$d)); if(in_array($k,['rss_enabled','sitemap_enabled'],true)){$v=!empty($input[$k])?'1':'0';} if($k==='posts_per_page'){$v=(string)max(3,min(24,(int)$v));} $s->execute([$k,$v]);} }
function mg_blog_media_items(PDO $pdo,int $limit=80): array { if(!mg_blog_media_ready($pdo)){return [];} $limit=max(1,min(120,$limit)); return $pdo->query('SELECT * FROM blog_media ORDER BY created_at DESC,id DESC LIMIT '.$limit)->fetchAll(PDO::FETCH_ASSOC) ?: []; }
function mg_blog_save_media(PDO $pdo,array $user,string $path,string $filename,string $mime,int $size,string $altText=''): int { $s=$pdo->prepare('INSERT INTO blog_media (file_path,file_name,mime_type,file_size,alt_text,uploaded_by) VALUES (?,?,?,?,?,?)'); $s->execute([$path,$filename,$mime,$size,$altText!==''?$altText:null,max(1,(int)($user['id']??0))]); return (int)$pdo->lastInsertId(); }
function mg_blog_handle_media_upload(PDO $pdo,array $user,array &$errors): ?int { if(empty($_FILES['media_file'])||!is_array($_FILES['media_file'])||(int)($_FILES['media_file']['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE){return null;} $f=$_FILES['media_file']; if((int)($f['error']??UPLOAD_ERR_OK)!==UPLOAD_ERR_OK){$errors[]='Media upload failed.';return null;} $size=(int)($f['size']??0); if($size<1||$size>8*1024*1024){$errors[]='Blog media must be smaller than 8 MB.';return null;} $ext=strtolower(pathinfo((string)($f['name']??'image'),PATHINFO_EXTENSION)); $allowed=['jpg'=>'image/jpeg','jpeg'=>'image/jpeg','png'=>'image/png','webp'=>'image/webp','gif'=>'image/gif']; if(!isset($allowed[$ext])){$errors[]='Blog media must be JPG, PNG, WebP, or GIF.';return null;} $dir=dirname(__DIR__,2).'/uploads/blog/media'; if(!is_dir($dir)&&!mkdir($dir,0775,true)&&!is_dir($dir)){$errors[]='Could not prepare blog media directory.';return null;} $fn='media-'.gmdate('Ymd-His').'-'.bin2hex(random_bytes(5)).'.'.($ext==='jpeg'?'jpg':$ext); if(!move_uploaded_file((string)$f['tmp_name'],$dir.'/'.$fn)){$errors[]='Could not save blog media.';return null;} return mg_blog_save_media($pdo,$user,'/uploads/blog/media/'.$fn,$fn,$allowed[$ext],$size,trim((string)($_POST['alt_text']??''))); }
function mg_blog_seo_issues(array $post): array { $i=[]; if(trim((string)($post['seo_title']??''))===''){$i[]='SEO title';} if(trim((string)($post['seo_description']??''))===''){$i[]='Meta description';} if(trim((string)($post['featured_image']??''))===''){$i[]='Featured image';} if(empty($post['category_name'])&&empty($post['category_id'])){$i[]='Category';} if(trim((string)($post['excerpt']??''))===''){$i[]='Excerpt';} if(strlen((string)($post['slug']??''))>75){$i[]='Long slug';} if(($post['cta_type']??'none')==='none'){$i[]='CTA';} return $i; }
