START TRANSACTION;

CREATE TABLE IF NOT EXISTS gift_bundle_orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  bundle_id BIGINT UNSIGNED NOT NULL,
  bundle_terms_version INT UNSIGNED NOT NULL,
  buyer_user_id BIGINT UNSIGNED NOT NULL,
  recipient_user_id BIGINT UNSIGNED NULL,
  recipient_name VARCHAR(190) NULL,
  recipient_email VARCHAR(255) NULL,
  commerce_order_id BIGINT UNSIGNED NULL,
  order_status ENUM('draft','reserved','awaiting_payment','paid','fulfillment_pending','partially_issued','issued','cancelled','refunded','partially_refunded') NOT NULL DEFAULT 'draft',
  payment_status ENUM('unpaid','pending','paid','failed','cancelled','partially_refunded','refunded') NOT NULL DEFAULT 'unpaid',
  fulfillment_status ENUM('pending','partial','issued','failed','cancelled') NOT NULL DEFAULT 'pending',
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  subtotal_cents BIGINT UNSIGNED NOT NULL,
  platform_fee_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  total_cents BIGINT UNSIGNED NOT NULL,
  fixed_platform_fee_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  component_count INT UNSIGNED NOT NULL,
  bundle_snapshot_json JSON NOT NULL,
  commission_snapshot_json JSON NOT NULL,
  campaign_attribution_json JSON NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  reserved_at DATETIME NULL,
  paid_at DATETIME NULL,
  issued_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_gift_bundle_orders_public_id (public_id),
  UNIQUE KEY uq_gift_bundle_orders_idempotency (idempotency_key),
  KEY idx_gift_bundle_orders_buyer_status (buyer_user_id,order_status,created_at),
  KEY idx_gift_bundle_orders_bundle_status (bundle_id,order_status,created_at),
  KEY idx_gift_bundle_orders_commerce_order (commerce_order_id),
  CONSTRAINT fk_gift_bundle_orders_bundle FOREIGN KEY (bundle_id) REFERENCES gift_bundles(id),
  CONSTRAINT fk_gift_bundle_orders_buyer FOREIGN KEY (buyer_user_id) REFERENCES users(id),
  CONSTRAINT fk_gift_bundle_orders_recipient FOREIGN KEY (recipient_user_id) REFERENCES users(id),
  CONSTRAINT fk_gift_bundle_orders_commerce FOREIGN KEY (commerce_order_id) REFERENCES commerce_orders(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gift_bundle_order_components (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  bundle_order_id BIGINT UNSIGNED NOT NULL,
  bundle_component_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  product_version_id BIGINT UNSIGNED NOT NULL,
  commerce_order_item_id BIGINT UNSIGNED NULL,
  pppm_issuance_request_id BIGINT UNSIGNED NULL,
  pppm_item_id BIGINT UNSIGNED NULL,
  microgift_instance_id BIGINT UNSIGNED NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  unit_amount_cents BIGINT UNSIGNED NOT NULL,
  gross_amount_cents BIGINT UNSIGNED NOT NULL,
  commissionable_amount_cents BIGINT UNSIGNED NOT NULL,
  commission_rate_bps INT UNSIGNED NOT NULL,
  commission_amount_cents BIGINT UNSIGNED NOT NULL,
  merchant_net_amount_cents BIGINT UNSIGNED NOT NULL,
  commission_source VARCHAR(100) NOT NULL,
  commission_rule_version VARCHAR(100) NOT NULL,
  settlement_policy VARCHAR(100) NOT NULL,
  claim_policy VARCHAR(100) NOT NULL,
  product_snapshot_json JSON NOT NULL,
  terms_snapshot_json JSON NOT NULL,
  inventory_snapshot_json JSON NULL,
  component_status ENUM('reserved','payment_pending','paid','issuance_pending','issued','claimed','redeemed','cancelled','refunded','reversed','failed') NOT NULL DEFAULT 'reserved',
  issued_at DATETIME NULL,
  claimed_at DATETIME NULL,
  redeemed_at DATETIME NULL,
  refunded_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_gift_bundle_order_components_public_id (public_id),
  UNIQUE KEY uq_gift_bundle_order_component (bundle_order_id,bundle_component_id),
  KEY idx_gift_bundle_order_components_merchant (merchant_user_id,component_status,created_at),
  KEY idx_gift_bundle_order_components_pppm (pppm_item_id),
  KEY idx_gift_bundle_order_components_microgift (microgift_instance_id),
  CONSTRAINT fk_gift_bundle_order_components_order FOREIGN KEY (bundle_order_id) REFERENCES gift_bundle_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_gift_bundle_order_components_component FOREIGN KEY (bundle_component_id) REFERENCES gift_bundle_components(id),
  CONSTRAINT fk_gift_bundle_order_components_merchant FOREIGN KEY (merchant_user_id) REFERENCES users(id),
  CONSTRAINT fk_gift_bundle_order_components_product FOREIGN KEY (product_id) REFERENCES catalog_products(id),
  CONSTRAINT fk_gift_bundle_order_components_version FOREIGN KEY (product_version_id) REFERENCES catalog_product_versions(id),
  CONSTRAINT fk_gift_bundle_order_components_commerce_item FOREIGN KEY (commerce_order_item_id) REFERENCES commerce_order_items(id),
  CONSTRAINT fk_gift_bundle_order_components_pppm_request FOREIGN KEY (pppm_issuance_request_id) REFERENCES pppm_issuance_requests(id),
  CONSTRAINT fk_gift_bundle_order_components_pppm_item FOREIGN KEY (pppm_item_id) REFERENCES pppm_items(id),
  CONSTRAINT fk_gift_bundle_order_components_microgift FOREIGN KEY (microgift_instance_id) REFERENCES microgift_instances(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gift_bundle_inventory_reservations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  bundle_order_id BIGINT UNSIGNED NOT NULL,
  bundle_component_id BIGINT UNSIGNED NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  reservation_status ENUM('active','committed','released','expired','cancelled') NOT NULL DEFAULT 'active',
  idempotency_key VARCHAR(190) NOT NULL,
  expires_at DATETIME NULL,
  committed_at DATETIME NULL,
  released_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_gift_bundle_inventory_public_id (public_id),
  UNIQUE KEY uq_gift_bundle_inventory_idempotency (idempotency_key),
  KEY idx_gift_bundle_inventory_component_status (bundle_component_id,reservation_status,expires_at),
  CONSTRAINT fk_gift_bundle_inventory_order FOREIGN KEY (bundle_order_id) REFERENCES gift_bundle_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_gift_bundle_inventory_component FOREIGN KEY (bundle_component_id) REFERENCES gift_bundle_components(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gift_bundle_order_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  bundle_order_id BIGINT UNSIGNED NOT NULL,
  component_id BIGINT UNSIGNED NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(100) NOT NULL,
  idempotency_key VARCHAR(190) NULL,
  event_data JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_gift_bundle_order_events_public_id (public_id),
  UNIQUE KEY uq_gift_bundle_order_events_idempotency (idempotency_key),
  KEY idx_gift_bundle_order_events_order_created (bundle_order_id,created_at),
  CONSTRAINT fk_gift_bundle_order_events_order FOREIGN KEY (bundle_order_id) REFERENCES gift_bundle_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_gift_bundle_order_events_component FOREIGN KEY (component_id) REFERENCES gift_bundle_order_components(id) ON DELETE CASCADE,
  CONSTRAINT fk_gift_bundle_order_events_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
