-- HomeServer operational intelligence, export grants, and campaign authority v1
-- Additive MySQL 8 / MariaDB 10.11 compatible migration.

CREATE TABLE IF NOT EXISTS homeserver_dataset_grants (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    device_id BIGINT UNSIGNED NOT NULL,
    merchant_user_id BIGINT UNSIGNED NOT NULL,
    tenant_id VARCHAR(120) NULL,
    site_id VARCHAR(120) NULL,
    dataset_key VARCHAR(160) NOT NULL,
    grant_state ENUM('enabled','paused','revoked') NOT NULL DEFAULT 'enabled',
    classification ENUM('business','restricted','sensitive') NOT NULL DEFAULT 'business',
    permitted_uses_json JSON NOT NULL,
    permitted_fields_json JSON NULL,
    retention_days SMALLINT UNSIGNED NOT NULL DEFAULT 365,
    include_message_bodies TINYINT(1) NOT NULL DEFAULT 0,
    include_contact_details TINYINT(1) NOT NULL DEFAULT 0,
    include_purchase_history TINYINT(1) NOT NULL DEFAULT 0,
    include_gift_ownership TINYINT(1) NOT NULL DEFAULT 0,
    approved_by_user_id BIGINT UNSIGNED NOT NULL,
    approved_at DATETIME NOT NULL,
    revoked_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_homeserver_dataset_grant_public_id (public_id),
    UNIQUE KEY uq_homeserver_dataset_grant_scope (device_id, merchant_user_id, dataset_key),
    KEY idx_homeserver_dataset_grant_merchant_state (merchant_user_id, grant_state),
    KEY idx_homeserver_dataset_grant_device_state (device_id, grant_state),
    CONSTRAINT fk_homeserver_dataset_grant_device FOREIGN KEY (device_id) REFERENCES homeserver_devices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS homeserver_operational_export_receipts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    device_id BIGINT UNSIGNED NOT NULL,
    merchant_user_id BIGINT UNSIGNED NOT NULL,
    dataset_key VARCHAR(160) NOT NULL,
    export_mode ENUM('manifest','snapshot','incremental','event') NOT NULL,
    cursor_before VARCHAR(500) NULL,
    cursor_after VARCHAR(500) NULL,
    source_revision VARCHAR(190) NOT NULL,
    record_count INT UNSIGNED NOT NULL DEFAULT 0,
    event_count INT UNSIGNED NOT NULL DEFAULT 0,
    payload_hash CHAR(64) NOT NULL,
    disposition ENUM('accepted','empty','rejected','failed') NOT NULL,
    reason_code VARCHAR(120) NULL,
    requested_at DATETIME NOT NULL,
    completed_at DATETIME NOT NULL,
    metadata_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_homeserver_export_receipt_public_id (public_id),
    KEY idx_homeserver_export_receipt_device_dataset (device_id, dataset_key, completed_at),
    KEY idx_homeserver_export_receipt_merchant (merchant_user_id, completed_at),
    CONSTRAINT fk_homeserver_export_receipt_device FOREIGN KEY (device_id) REFERENCES homeserver_devices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS homeserver_campaign_authorizations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    device_id BIGINT UNSIGNED NOT NULL,
    merchant_user_id BIGINT UNSIGNED NOT NULL,
    campaign_type VARCHAR(80) NOT NULL,
    authorization_state ENUM('enabled','paused','revoked') NOT NULL DEFAULT 'enabled',
    authority_level ENUM('analyze','draft','approval_required','authorized_execution') NOT NULL DEFAULT 'draft',
    allowed_campaign_ids_json JSON NULL,
    allowed_product_ids_json JSON NULL,
    allowed_channels_json JSON NOT NULL,
    allowed_audience_rules_json JSON NOT NULL,
    maximum_value_cents INT UNSIGNED NULL,
    maximum_daily_value_cents INT UNSIGNED NULL,
    maximum_total_value_cents INT UNSIGNED NULL,
    maximum_recipients INT UNSIGNED NULL,
    approval_threshold_cents INT UNSIGNED NULL,
    duplicate_window_days SMALLINT UNSIGNED NOT NULL DEFAULT 90,
    require_consent TINYINT(1) NOT NULL DEFAULT 1,
    require_evidence TINYINT(1) NOT NULL DEFAULT 1,
    allowed_send_start TIME NULL,
    allowed_send_end TIME NULL,
    timezone_name VARCHAR(80) NOT NULL DEFAULT 'America/Phoenix',
    approved_by_user_id BIGINT UNSIGNED NOT NULL,
    approved_at DATETIME NOT NULL,
    expires_at DATETIME NULL,
    revoked_at DATETIME NULL,
    policy_hash CHAR(64) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_homeserver_campaign_authorization_public_id (public_id),
    UNIQUE KEY uq_homeserver_campaign_authorization_scope (device_id, merchant_user_id, campaign_type),
    KEY idx_homeserver_campaign_authorization_state (merchant_user_id, authorization_state),
    CONSTRAINT fk_homeserver_campaign_authorization_device FOREIGN KEY (device_id) REFERENCES homeserver_devices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS homeserver_campaign_action_receipts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    device_id BIGINT UNSIGNED NOT NULL,
    merchant_user_id BIGINT UNSIGNED NOT NULL,
    authorization_id BIGINT UNSIGNED NOT NULL,
    idempotency_key VARCHAR(190) NOT NULL,
    action_type ENUM('campaign.draft','campaign.publish','campaign.pause','campaign.resume','campaign.send_make_good','campaign.send_authorized') NOT NULL,
    campaign_type VARCHAR(80) NOT NULL,
    campaign_public_id CHAR(36) NULL,
    contact_public_id CHAR(36) NULL,
    evidence_json JSON NOT NULL,
    request_json JSON NOT NULL,
    request_hash CHAR(64) NOT NULL,
    policy_hash CHAR(64) NOT NULL,
    disposition ENUM('drafted','awaiting_approval','executed','rejected','failed','duplicate') NOT NULL,
    reason_code VARCHAR(120) NULL,
    provider_response_json JSON NULL,
    value_cents INT UNSIGNED NOT NULL DEFAULT 0,
    recipient_count INT UNSIGNED NOT NULL DEFAULT 0,
    executed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_homeserver_campaign_action_public_id (public_id),
    UNIQUE KEY uq_homeserver_campaign_action_idempotency (device_id, idempotency_key),
    KEY idx_homeserver_campaign_action_merchant_created (merchant_user_id, created_at),
    KEY idx_homeserver_campaign_action_campaign (campaign_public_id, created_at),
    CONSTRAINT fk_homeserver_campaign_action_device FOREIGN KEY (device_id) REFERENCES homeserver_devices(id) ON DELETE CASCADE,
    CONSTRAINT fk_homeserver_campaign_action_authorization FOREIGN KEY (authorization_id) REFERENCES homeserver_campaign_authorizations(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Existing paired devices receive endpoint scopes only. No operational dataset or
-- campaign becomes usable until the account owner creates the separate grants
-- and campaign authorization records above.
UPDATE homeserver_devices
SET scopes_json=JSON_ARRAY(
    'homeserver.status',
    'homeserver.sync.write',
    'homeserver.operational.read',
    'homeserver.reviews.read',
    'homeserver.messages.read',
    'homeserver.crm.read',
    'homeserver.commerce_history.read',
    'homeserver.gifts.read',
    'homeserver.campaigns.read',
    'homeserver.campaigns.execute'
), updated_at=CURRENT_TIMESTAMP
WHERE status='active';
