-- Creator Campaign Payouts and Disputes v8
-- Scope: payout eligibility profiles, payout records/items/events, reversals, disputes, and audit history.
-- Automatic provider transfers, tax filing, banking secrets, and MCP execution remain outside this phase.
START TRANSACTION;
CREATE TABLE IF NOT EXISTS creator_campaign_payout_profiles (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id VARCHAR(40) NOT NULL,creator_user_id BIGINT UNSIGNED NOT NULL,currency CHAR(3) NOT NULL DEFAULT 'USD',status ENUM('incomplete','pending_review','eligible','blocked') NOT NULL DEFAULT 'incomplete',method_label VARCHAR(120) NULL,minimum_payout_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,eligibility_note VARCHAR(2000) NULL,lock_version INT UNSIGNED NOT NULL DEFAULT 1,created_by_user_id BIGINT UNSIGNED NOT NULL,updated_by_user_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id),UNIQUE KEY uq_cc_payout_profile_public(public_id),UNIQUE KEY uq_cc_payout_profile_creator_currency(creator_user_id,currency),KEY idx_cc_payout_profile_status(status,updated_at,id),
 CONSTRAINT fk_cc_payout_profile_creator FOREIGN KEY(creator_user_id) REFERENCES users(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_payout_profile_created_by FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_payout_profile_updated_by FOREIGN KEY(updated_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS creator_campaign_payouts (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id VARCHAR(40) NOT NULL,campaign_id BIGINT UNSIGNED NOT NULL,participant_id BIGINT UNSIGNED NOT NULL,creator_user_id BIGINT UNSIGNED NOT NULL,payout_profile_id BIGINT UNSIGNED NOT NULL,currency CHAR(3) NOT NULL,amount_minor BIGINT UNSIGNED NOT NULL,status ENUM('draft','approved','processing','paid','failed','cancelled','reversed') NOT NULL DEFAULT 'draft',provider_reference VARCHAR(255) NULL,failure_reason VARCHAR(2000) NULL,idempotency_hash CHAR(64) NOT NULL,lock_version INT UNSIGNED NOT NULL DEFAULT 1,approved_at DATETIME NULL,processing_at DATETIME NULL,paid_at DATETIME NULL,failed_at DATETIME NULL,cancelled_at DATETIME NULL,reversed_at DATETIME NULL,created_by_user_id BIGINT UNSIGNED NOT NULL,updated_by_user_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id),UNIQUE KEY uq_cc_payout_public(public_id),UNIQUE KEY uq_cc_payout_idempotency(campaign_id,idempotency_hash),KEY idx_cc_payout_creator(creator_user_id,status,updated_at,id),KEY idx_cc_payout_campaign(campaign_id,status,updated_at,id),
 CONSTRAINT fk_cc_payout_campaign FOREIGN KEY(campaign_id) REFERENCES creator_campaigns(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_payout_participant FOREIGN KEY(participant_id) REFERENCES creator_campaign_participants(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_payout_creator FOREIGN KEY(creator_user_id) REFERENCES users(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_payout_profile FOREIGN KEY(payout_profile_id) REFERENCES creator_campaign_payout_profiles(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_payout_created_by FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_payout_updated_by FOREIGN KEY(updated_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,CONSTRAINT chk_cc_payout_amount CHECK(amount_minor>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS creator_campaign_payout_items (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id VARCHAR(40) NOT NULL,payout_id BIGINT UNSIGNED NOT NULL,reservation_id BIGINT UNSIGNED NOT NULL,earning_event_id BIGINT UNSIGNED NOT NULL,amount_minor BIGINT UNSIGNED NOT NULL,currency CHAR(3) NOT NULL,status ENUM('scheduled','paid','released','reversed') NOT NULL DEFAULT 'scheduled',active_reservation_key BIGINT UNSIGNED GENERATED ALWAYS AS(CASE WHEN status IN('scheduled','paid') THEN reservation_id ELSE NULL END) STORED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id),UNIQUE KEY uq_cc_payout_item_public(public_id),UNIQUE KEY uq_cc_payout_item_active_reservation(active_reservation_key),KEY idx_cc_payout_item_payout(payout_id,status,id),KEY idx_cc_payout_item_reservation(reservation_id,status,id),
 CONSTRAINT fk_cc_payout_item_payout FOREIGN KEY(payout_id) REFERENCES creator_campaign_payouts(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_payout_item_reservation FOREIGN KEY(reservation_id) REFERENCES creator_campaign_budget_reservations(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_payout_item_earning FOREIGN KEY(earning_event_id) REFERENCES creator_campaign_earning_events(id) ON DELETE RESTRICT,CONSTRAINT chk_cc_payout_item_amount CHECK(amount_minor>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS creator_campaign_payout_events (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id VARCHAR(40) NOT NULL,payout_id BIGINT UNSIGNED NOT NULL,event_type ENUM('created','approved','processing','paid','failed','cancelled','reversed','note') NOT NULL,from_status VARCHAR(40) NULL,to_status VARCHAR(40) NULL,provider_reference VARCHAR(255) NULL,reason VARCHAR(2000) NULL,idempotency_hash CHAR(64) NOT NULL,snapshot_json JSON NOT NULL,actor_user_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(id),UNIQUE KEY uq_cc_payout_event_public(public_id),UNIQUE KEY uq_cc_payout_event_idempotency(payout_id,idempotency_hash),KEY idx_cc_payout_event_timeline(payout_id,created_at,id),CONSTRAINT fk_cc_payout_event_payout FOREIGN KEY(payout_id) REFERENCES creator_campaign_payouts(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_payout_event_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS creator_campaign_disputes (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id VARCHAR(40) NOT NULL,campaign_id BIGINT UNSIGNED NOT NULL,participant_id BIGINT UNSIGNED NOT NULL,creator_user_id BIGINT UNSIGNED NOT NULL,source_type ENUM('payout','reservation','earning') NOT NULL,source_public_id VARCHAR(80) NOT NULL,status ENUM('open','under_review','resolved_upheld','resolved_adjusted','rejected','closed') NOT NULL DEFAULT 'open',active_source_key VARCHAR(180) GENERATED ALWAYS AS(CASE WHEN status IN('open','under_review') THEN CONCAT(source_type,':',source_public_id) ELSE NULL END) STORED,reason VARCHAR(2000) NOT NULL,resolution_note VARCHAR(4000) NULL,lock_version INT UNSIGNED NOT NULL DEFAULT 1,opened_by_user_id BIGINT UNSIGNED NOT NULL,resolved_by_user_id BIGINT UNSIGNED NULL,opened_at DATETIME NOT NULL,resolved_at DATETIME NULL,closed_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id),UNIQUE KEY uq_cc_dispute_public(public_id),UNIQUE KEY uq_cc_dispute_active_source(active_source_key),KEY idx_cc_dispute_campaign(campaign_id,status,updated_at,id),KEY idx_cc_dispute_creator(creator_user_id,status,updated_at,id),CONSTRAINT fk_cc_dispute_campaign FOREIGN KEY(campaign_id) REFERENCES creator_campaigns(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_dispute_participant FOREIGN KEY(participant_id) REFERENCES creator_campaign_participants(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_dispute_creator FOREIGN KEY(creator_user_id) REFERENCES users(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_dispute_opened_by FOREIGN KEY(opened_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_dispute_resolved_by FOREIGN KEY(resolved_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS creator_campaign_dispute_events (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id VARCHAR(40) NOT NULL,dispute_id BIGINT UNSIGNED NOT NULL,event_type ENUM('opened','review_started','resolved','rejected','closed','note') NOT NULL,from_status VARCHAR(40) NULL,to_status VARCHAR(40) NULL,note VARCHAR(4000) NULL,idempotency_hash CHAR(64) NOT NULL,snapshot_json JSON NOT NULL,actor_user_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(id),UNIQUE KEY uq_cc_dispute_event_public(public_id),UNIQUE KEY uq_cc_dispute_event_idempotency(dispute_id,idempotency_hash),KEY idx_cc_dispute_event_timeline(dispute_id,created_at,id),CONSTRAINT fk_cc_dispute_event_dispute FOREIGN KEY(dispute_id) REFERENCES creator_campaign_disputes(id) ON DELETE RESTRICT,CONSTRAINT fk_cc_dispute_event_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT IGNORE INTO permissions(slug,name,description,created_at) VALUES
('merchant.creator_payouts.view','View Creator payouts','View payout eligibility, payout records, items, events, and disputes.',NOW()),('merchant.creator_payouts.manage','Manage Creator payouts','Manage eligibility profiles and payout status records.',NOW()),('merchant.creator_disputes.manage','Manage Creator payout disputes','Review and resolve Creator Campaign payout, reservation, and earning disputes.',NOW()),('creator.campaign_payouts.view_own','View own Creator payouts','View authenticated Creator payout eligibility, records, and items.',NOW()),('creator.campaign_disputes.manage_own','Manage own Creator disputes','Open and view disputes for authenticated Creator Campaign records.',NOW());
INSERT IGNORE INTO role_permissions(role_id,permission_id,created_at) SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p ON p.slug IN('merchant.creator_payouts.view','merchant.creator_payouts.manage','merchant.creator_disputes.manage') WHERE r.slug IN('merchant','admin','super_admin');
INSERT IGNORE INTO role_permissions(role_id,permission_id,created_at) SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p ON p.slug IN('creator.campaign_payouts.view_own','creator.campaign_disputes.manage_own') WHERE r.slug IN('creator','admin','super_admin');
COMMIT;
