START TRANSACTION;

CREATE TABLE IF NOT EXISTS gift_bundles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  owner_merchant_user_id BIGINT UNSIGNED NOT NULL,
  commission_profile_id BIGINT UNSIGNED NULL,
  title VARCHAR(190) NOT NULL,
  slug VARCHAR(190) NOT NULL,
  short_statement VARCHAR(255) NULL,
  description TEXT NULL,
  cover_asset_url VARCHAR(500) NULL,
  category VARCHAR(100) NULL,
  occasion VARCHAR(100) NULL,
  primary_location VARCHAR(255) NULL,
  service_area VARCHAR(255) NULL,
  estimated_duration VARCHAR(100) NULL,
  customer_highlights JSON NULL,
  recipient_instructions TEXT NULL,
  bundle_type ENUM('fixed_single_merchant','fixed_multi_merchant') NOT NULL DEFAULT 'fixed_single_merchant',
  commission_mode ENUM('merchant_default','bundle_starting_rate','custom_participant_rates') NOT NULL DEFAULT 'merchant_default',
  starting_commission_bps INT UNSIGNED NULL,
  status ENUM('draft','review','published','paused','ended','archived') NOT NULL DEFAULT 'draft',
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  sales_start_at DATETIME NULL,
  sales_end_at DATETIME NULL,
  redemption_expires_at DATETIME NULL,
  inventory_limit INT UNSIGNED NULL,
  visibility ENUM('private','unlisted','public') NOT NULL DEFAULT 'private',
  terms_version INT UNSIGNED NOT NULL DEFAULT 1,
  published_terms_snapshot JSON NULL,
  published_at DATETIME NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  updated_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_gift_bundles_public_id (public_id),
  UNIQUE KEY uq_gift_bundles_owner_slug (owner_merchant_user_id,slug),
  KEY idx_gift_bundles_owner_status (owner_merchant_user_id,status),
  KEY idx_gift_bundles_dates (sales_start_at,sales_end_at),
  CONSTRAINT fk_gift_bundles_owner FOREIGN KEY (owner_merchant_user_id) REFERENCES users(id),
  CONSTRAINT fk_gift_bundles_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id),
  CONSTRAINT fk_gift_bundles_updater FOREIGN KEY (updated_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gift_bundle_components (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  bundle_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  product_version_id BIGINT UNSIGNED NOT NULL,
  product_title_snapshot VARCHAR(255) NOT NULL,
  product_description_snapshot TEXT NULL,
  image_snapshot VARCHAR(500) NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  display_order INT UNSIGNED NOT NULL DEFAULT 0,
  is_required TINYINT(1) NOT NULL DEFAULT 1,
  customer_amount_cents BIGINT UNSIGNED NOT NULL,
  commissionable_amount_cents BIGINT UNSIGNED NOT NULL,
  commission_rate_bps INT UNSIGNED NOT NULL,
  commission_amount_cents BIGINT UNSIGNED NOT NULL,
  merchant_net_amount_cents BIGINT UNSIGNED NOT NULL,
  commission_source VARCHAR(100) NOT NULL,
  commission_rule_version VARCHAR(100) NOT NULL,
  inventory_commitment INT UNSIGNED NULL,
  settlement_policy ENUM('after_payment','after_merchant_confirmation','after_claim','after_redemption') NOT NULL DEFAULT 'after_payment',
  claim_policy VARCHAR(100) NOT NULL DEFAULT 'standard',
  expiration_rule VARCHAR(255) NULL,
  reservation_requirement VARCHAR(255) NULL,
  customer_instructions TEXT NULL,
  merchant_instructions TEXT NULL,
  terms_version INT UNSIGNED NOT NULL DEFAULT 1,
  status ENUM('draft','pending_acceptance','accepted','declined','inactive') NOT NULL DEFAULT 'draft',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_gift_bundle_components_public_id (public_id),
  KEY idx_gift_bundle_components_bundle (bundle_id,display_order),
  KEY idx_gift_bundle_components_merchant (merchant_user_id,status),
  KEY idx_gift_bundle_components_product (product_id,product_version_id),
  CONSTRAINT fk_gift_bundle_components_bundle FOREIGN KEY (bundle_id) REFERENCES gift_bundles(id) ON DELETE CASCADE,
  CONSTRAINT fk_gift_bundle_components_merchant FOREIGN KEY (merchant_user_id) REFERENCES users(id),
  CONSTRAINT fk_gift_bundle_components_product FOREIGN KEY (product_id) REFERENCES catalog_products(id),
  CONSTRAINT fk_gift_bundle_components_version FOREIGN KEY (product_version_id) REFERENCES catalog_product_versions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gift_bundle_participants (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  bundle_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  requested_product_id BIGINT UNSIGNED NULL,
  requested_product_version_id BIGINT UNSIGNED NULL,
  invitation_status ENUM('draft','pending','accepted','countered','declined','question') NOT NULL DEFAULT 'draft',
  proposed_terms JSON NOT NULL,
  accepted_terms JSON NULL,
  terms_version INT UNSIGNED NOT NULL DEFAULT 1,
  message TEXT NULL,
  invited_by_user_id BIGINT UNSIGNED NOT NULL,
  accepted_by_user_id BIGINT UNSIGNED NULL,
  invited_at DATETIME NULL,
  responded_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_gift_bundle_participants_public_id (public_id),
  UNIQUE KEY uq_gift_bundle_participant_version (bundle_id,merchant_user_id,terms_version),
  KEY idx_gift_bundle_participants_merchant_status (merchant_user_id,invitation_status),
  CONSTRAINT fk_gift_bundle_participants_bundle FOREIGN KEY (bundle_id) REFERENCES gift_bundles(id) ON DELETE CASCADE,
  CONSTRAINT fk_gift_bundle_participants_merchant FOREIGN KEY (merchant_user_id) REFERENCES users(id),
  CONSTRAINT fk_gift_bundle_participants_product FOREIGN KEY (requested_product_id) REFERENCES catalog_products(id),
  CONSTRAINT fk_gift_bundle_participants_version FOREIGN KEY (requested_product_version_id) REFERENCES catalog_product_versions(id),
  CONSTRAINT fk_gift_bundle_participants_inviter FOREIGN KEY (invited_by_user_id) REFERENCES users(id),
  CONSTRAINT fk_gift_bundle_participants_acceptor FOREIGN KEY (accepted_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gift_bundle_audit_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  bundle_id BIGINT UNSIGNED NOT NULL,
  actor_user_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(100) NOT NULL,
  entity_type VARCHAR(100) NOT NULL,
  entity_public_id VARCHAR(100) NULL,
  event_data JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_gift_bundle_audit_public_id (public_id),
  KEY idx_gift_bundle_audit_bundle_created (bundle_id,created_at),
  CONSTRAINT fk_gift_bundle_audit_bundle FOREIGN KEY (bundle_id) REFERENCES gift_bundles(id) ON DELETE CASCADE,
  CONSTRAINT fk_gift_bundle_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
