-- Microgifter Investor Governance, Information Rights & Board Operations v5
-- Additive single-install migration. Requires Investor Wizard v1 through Closing v4.
-- This module records externally approved governance, rights, tax and notice information.
-- It does not appoint directors, determine legal rights, sign documents, cast votes,
-- prepare tax forms, issue securities, replace the official stock ledger, or provide legal/tax advice.

INSERT INTO permissions (slug,name,created_at) VALUES
('investment.governance.view','View published funded-investor governance materials',NOW()),
('investment.tax_documents.view','View published investor tax and annual documents',NOW()),
('admin.investment.governance.view','View investor governance administration',NOW()),
('admin.investment.governance.manage','Manage governance participants, meetings and actions',NOW()),
('admin.investment.governance.publish','Publish approved governance materials and notices',NOW()),
('admin.investment.governance.vote','Record externally executed consent responses',NOW()),
('admin.investment.rights.manage','Manage counsel-confirmed investor rights',NOW()),
('admin.investment.obligations.manage','Manage recurring investor reporting obligations',NOW()),
('admin.investment.tax_documents.manage','Manage externally prepared tax and annual documents',NOW())
ON DUPLICATE KEY UPDATE name=VALUES(name);

INSERT IGNORE INTO role_permissions (role_id,permission_id,created_at)
SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p ON p.slug IN
('investment.governance.view','investment.tax_documents.view')
WHERE r.slug='investor';

INSERT IGNORE INTO role_permissions (role_id,permission_id,created_at)
SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p ON p.slug IN
('admin.investment.governance.view','admin.investment.governance.manage','admin.investment.governance.publish','admin.investment.governance.vote','admin.investment.rights.manage','admin.investment.obligations.manage','admin.investment.tax_documents.manage')
WHERE r.slug IN ('admin','super_admin');

CREATE TABLE IF NOT EXISTS investment_governance_participants (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  participant_type ENUM('director','board_observer','officer','committee_member','investor_representative','counsel','administrator','guest','other') NOT NULL DEFAULT 'other',
  display_name VARCHAR(180) NOT NULL,
  organization VARCHAR(180) NULL,
  email VARCHAR(254) NULL,
  phone VARCHAR(60) NULL,
  title VARCHAR(180) NULL,
  biography TEXT NULL,
  conflict_disclosure TEXT NULL,
  confidentiality_status ENUM('not_recorded','requested','confirmed','expired','not_applicable') NOT NULL DEFAULT 'not_recorded',
  status ENUM('active','inactive','removed','archived') NOT NULL DEFAULT 'active',
  created_by_user_id BIGINT UNSIGNED NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_governance_participant_public (public_id),
  KEY idx_investment_governance_participant_status (participant_type,status,display_name),
  CONSTRAINT fk_investment_governance_participant_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_governance_participant_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_governance_participant_updater FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_governance_appointments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  participant_id BIGINT UNSIGNED NOT NULL,
  round_id BIGINT UNSIGNED NULL,
  appointment_type ENUM('director','board_observer','officer','committee_member','investor_representative','counsel','administrator','other') NOT NULL,
  appointment_source ENUM('board_resolution','stockholder_consent','financing_agreement','side_letter','employment','engagement_letter','other') NOT NULL DEFAULT 'other',
  committee_name VARCHAR(180) NULL,
  voting_status ENUM('voting','non_voting','advisory','not_applicable') NOT NULL DEFAULT 'not_applicable',
  starts_at DATE NULL,
  ends_at DATE NULL,
  appointment_document_reference VARCHAR(220) NULL,
  appointment_document_url VARCHAR(1000) NULL,
  counsel_status ENUM('not_started','in_review','approved','changes_required','not_applicable') NOT NULL DEFAULT 'not_started',
  status ENUM('planned','active','expired','removed','cancelled','archived') NOT NULL DEFAULT 'planned',
  internal_notes TEXT NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_governance_appointment_public (public_id),
  KEY idx_investment_governance_appointment_participant (participant_id,status,starts_at),
  KEY idx_investment_governance_appointment_round (round_id,status),
  CONSTRAINT fk_investment_governance_appointment_participant FOREIGN KEY (participant_id) REFERENCES investment_governance_participants(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_governance_appointment_round FOREIGN KEY (round_id) REFERENCES investment_rounds(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_governance_appointment_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_governance_appointment_updater FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_board_meetings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  round_id BIGINT UNSIGNED NULL,
  meeting_type ENUM('regular_board','special_board','committee','investor_update','annual','other') NOT NULL DEFAULT 'regular_board',
  title VARCHAR(220) NOT NULL,
  starts_at DATETIME NOT NULL,
  ends_at DATETIME NULL,
  location VARCHAR(300) NULL,
  meeting_url VARCHAR(1000) NULL,
  status ENUM('planning','agenda_review','packet_preparation','ready','held','minutes_drafted','minutes_approved','archived','cancelled') NOT NULL DEFAULT 'planning',
  confidentiality ENUM('internal','board_only','participants','funded_investors_summary') NOT NULL DEFAULT 'board_only',
  quorum_status ENUM('not_checked','expected','confirmed','not_met','not_applicable') NOT NULL DEFAULT 'not_checked',
  counsel_status ENUM('not_started','in_review','approved','changes_required','not_applicable') NOT NULL DEFAULT 'not_started',
  investor_visible_summary TEXT NULL,
  summary_status ENUM('draft','internal_review','approved','published','archived') NOT NULL DEFAULT 'draft',
  summary_published_at DATETIME NULL,
  internal_notes LONGTEXT NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_board_meeting_public (public_id),
  KEY idx_investment_board_meeting_schedule (starts_at,status),
  KEY idx_investment_board_meeting_round (round_id,status),
  CONSTRAINT fk_investment_board_meeting_round FOREIGN KEY (round_id) REFERENCES investment_rounds(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_board_meeting_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_board_meeting_updater FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_board_meeting_attendees (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  meeting_id BIGINT UNSIGNED NOT NULL,
  participant_id BIGINT UNSIGNED NOT NULL,
  attendance_role ENUM('chair','director','observer','officer','presenter','counsel','secretary','guest','other') NOT NULL DEFAULT 'other',
  attendance_status ENUM('invited','accepted','declined','tentative','attended','absent','excused') NOT NULL DEFAULT 'invited',
  conflict_status ENUM('none_recorded','disclosed','recused','not_applicable') NOT NULL DEFAULT 'none_recorded',
  joined_at DATETIME NULL,
  left_at DATETIME NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_board_attendee (meeting_id,participant_id),
  KEY idx_investment_board_attendee_status (meeting_id,attendance_status),
  CONSTRAINT fk_investment_board_attendee_meeting FOREIGN KEY (meeting_id) REFERENCES investment_board_meetings(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_board_attendee_participant FOREIGN KEY (participant_id) REFERENCES investment_governance_participants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_board_agenda_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  meeting_id BIGINT UNSIGNED NOT NULL,
  sequence_number INT UNSIGNED NOT NULL DEFAULT 1,
  item_type ENUM('opening','approval','discussion','report','resolution','executive_session','closing','other') NOT NULL DEFAULT 'discussion',
  title VARCHAR(220) NOT NULL,
  description TEXT NULL,
  presenter_participant_id BIGINT UNSIGNED NULL,
  planned_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 10,
  approval_required TINYINT(1) NOT NULL DEFAULT 0,
  decision_status ENUM('not_required','pending','approved','declined','tabled','withdrawn') NOT NULL DEFAULT 'not_required',
  decision_summary TEXT NULL,
  confidentiality ENUM('internal','board_only','participants','funded_investors_summary') NOT NULL DEFAULT 'board_only',
  status ENUM('draft','ready','completed','tabled','cancelled') NOT NULL DEFAULT 'draft',
  created_by_user_id BIGINT UNSIGNED NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_board_agenda_public (public_id),
  UNIQUE KEY uq_investment_board_agenda_sequence (meeting_id,sequence_number),
  CONSTRAINT fk_investment_board_agenda_meeting FOREIGN KEY (meeting_id) REFERENCES investment_board_meetings(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_board_agenda_presenter FOREIGN KEY (presenter_participant_id) REFERENCES investment_governance_participants(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_board_agenda_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_board_agenda_updater FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_board_packet_documents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  meeting_id BIGINT UNSIGNED NOT NULL,
  agenda_item_id BIGINT UNSIGNED NULL,
  document_type ENUM('agenda','financial_report','operating_report','resolution','presentation','minutes','legal','supporting','other') NOT NULL DEFAULT 'supporting',
  title VARCHAR(220) NOT NULL,
  external_url VARCHAR(1000) NULL,
  version_number INT UNSIGNED NOT NULL DEFAULT 1,
  confidentiality ENUM('internal','board_only','participants','funded_investors') NOT NULL DEFAULT 'board_only',
  counsel_status ENUM('not_started','in_review','approved','changes_required','not_applicable') NOT NULL DEFAULT 'not_started',
  status ENUM('draft','internal_review','approved','published','superseded','archived') NOT NULL DEFAULT 'draft',
  approved_by_user_id BIGINT UNSIGNED NULL,
  approved_at DATETIME NULL,
  published_at DATETIME NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_board_packet_public (public_id),
  KEY idx_investment_board_packet_meeting (meeting_id,status,version_number),
  CONSTRAINT fk_investment_board_packet_meeting FOREIGN KEY (meeting_id) REFERENCES investment_board_meetings(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_board_packet_agenda FOREIGN KEY (agenda_item_id) REFERENCES investment_board_agenda_items(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_board_packet_approver FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_board_packet_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_board_minute_versions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  meeting_id BIGINT UNSIGNED NOT NULL,
  version_number INT UNSIGNED NOT NULL,
  minutes_text LONGTEXT NOT NULL,
  status ENUM('draft','internal_review','counsel_review','approved','superseded','archived') NOT NULL DEFAULT 'draft',
  counsel_status ENUM('not_started','in_review','approved','changes_required','not_applicable') NOT NULL DEFAULT 'not_started',
  approved_by_user_id BIGINT UNSIGNED NULL,
  approved_at DATETIME NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_board_minutes_public (public_id),
  UNIQUE KEY uq_investment_board_minutes_version (meeting_id,version_number),
  CONSTRAINT fk_investment_board_minutes_meeting FOREIGN KEY (meeting_id) REFERENCES investment_board_meetings(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_board_minutes_approver FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_board_minutes_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_written_consents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  round_id BIGINT UNSIGNED NULL,
  closing_batch_id BIGINT UNSIGNED NULL,
  consent_type ENUM('board','stockholder','officer','committee','financing','compensation','contract','banking','other') NOT NULL DEFAULT 'board',
  title VARCHAR(220) NOT NULL,
  resolution_text LONGTEXT NOT NULL,
  approval_group VARCHAR(180) NOT NULL,
  approval_threshold VARCHAR(180) NULL,
  status ENUM('draft','internal_review','counsel_review','approved_for_execution','collecting','executed','declined','expired','archived') NOT NULL DEFAULT 'draft',
  counsel_status ENUM('not_started','in_review','approved','changes_required','not_applicable') NOT NULL DEFAULT 'not_started',
  effective_at DATETIME NULL,
  response_due_at DATETIME NULL,
  executed_document_reference VARCHAR(220) NULL,
  executed_document_url VARCHAR(1000) NULL,
  internal_notes TEXT NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_written_consent_public (public_id),
  KEY idx_investment_written_consent_status (status,response_due_at),
  CONSTRAINT fk_investment_written_consent_round FOREIGN KEY (round_id) REFERENCES investment_rounds(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_written_consent_batch FOREIGN KEY (closing_batch_id) REFERENCES investment_closing_batches(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_written_consent_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_written_consent_updater FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_consent_participants (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  consent_id BIGINT UNSIGNED NOT NULL,
  participant_id BIGINT UNSIGNED NOT NULL,
  response ENUM('pending','approved','declined','abstained','not_required') NOT NULL DEFAULT 'pending',
  external_signature_reference VARCHAR(220) NULL,
  responded_at DATETIME NULL,
  recorded_by_user_id BIGINT UNSIGNED NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_consent_participant (consent_id,participant_id),
  KEY idx_investment_consent_response (consent_id,response),
  CONSTRAINT fk_investment_consent_participant_consent FOREIGN KEY (consent_id) REFERENCES investment_written_consents(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_consent_participant_person FOREIGN KEY (participant_id) REFERENCES investment_governance_participants(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_consent_participant_recorder FOREIGN KEY (recorded_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_investor_rights (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  round_id BIGINT UNSIGNED NOT NULL,
  investor_user_id BIGINT UNSIGNED NOT NULL,
  right_type ENUM('information','inspection','quarterly_reporting','annual_reporting','budget_delivery','tax_document','pro_rata','major_investor','mfn','board_observer','notice','side_letter','consent_reference','other') NOT NULL,
  title VARCHAR(220) NOT NULL,
  description TEXT NULL,
  source_document_reference VARCHAR(220) NOT NULL,
  source_document_url VARCHAR(1000) NULL,
  cadence ENUM('none','monthly','quarterly','annual','event_driven','custom') NOT NULL DEFAULT 'none',
  custom_cadence VARCHAR(180) NULL,
  starts_at DATE NULL,
  expires_at DATE NULL,
  counsel_status ENUM('not_started','in_review','approved','changes_required','not_applicable') NOT NULL DEFAULT 'not_started',
  status ENUM('draft','active','suspended','expired','terminated','archived') NOT NULL DEFAULT 'draft',
  investor_visible TINYINT(1) NOT NULL DEFAULT 0,
  internal_notes TEXT NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_investor_right_public (public_id),
  KEY idx_investment_investor_right_investor (investor_user_id,round_id,status),
  CONSTRAINT fk_investment_investor_right_round FOREIGN KEY (round_id) REFERENCES investment_rounds(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_investor_right_user FOREIGN KEY (investor_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_investor_right_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_investor_right_updater FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_reporting_obligations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  round_id BIGINT UNSIGNED NOT NULL,
  investor_user_id BIGINT UNSIGNED NULL,
  right_id BIGINT UNSIGNED NULL,
  obligation_type ENUM('quarterly_report','annual_report','annual_budget','tax_documents','material_event_notice','board_meeting_notice','financing_notice','pro_rata_notice','information_request','custom') NOT NULL,
  title VARCHAR(220) NOT NULL,
  reporting_period VARCHAR(120) NULL,
  due_at DATETIME NOT NULL,
  internal_review_due_at DATETIME NULL,
  counsel_review_required TINYINT(1) NOT NULL DEFAULT 0,
  assigned_user_id BIGINT UNSIGNED NULL,
  recipient_scope ENUM('specific_investor','funded_investors','major_investors','rights_holders','board','custom') NOT NULL DEFAULT 'funded_investors',
  recurrence_rule VARCHAR(500) NULL,
  completion_reference VARCHAR(220) NULL,
  portal_publication_status ENUM('not_required','draft','approved','published','archived') NOT NULL DEFAULT 'not_required',
  status ENUM('planned','in_progress','internal_review','counsel_review','ready','completed','overdue','waived','cancelled') NOT NULL DEFAULT 'planned',
  completed_at DATETIME NULL,
  internal_notes TEXT NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_reporting_obligation_public (public_id),
  KEY idx_investment_reporting_obligation_due (status,due_at),
  KEY idx_investment_reporting_obligation_round (round_id,investor_user_id,status),
  CONSTRAINT fk_investment_reporting_obligation_round FOREIGN KEY (round_id) REFERENCES investment_rounds(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_reporting_obligation_investor FOREIGN KEY (investor_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_reporting_obligation_right FOREIGN KEY (right_id) REFERENCES investment_investor_rights(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_reporting_obligation_assignee FOREIGN KEY (assigned_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_reporting_obligation_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_reporting_obligation_updater FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_reporting_obligation_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  obligation_id BIGINT UNSIGNED NOT NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  event_type ENUM('created','status_changed','assigned','deadline_changed','review_requested','published','completed','reopened','waived','note') NOT NULL,
  details_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_reporting_obligation_event_public (public_id),
  KEY idx_investment_reporting_obligation_event (obligation_id,created_at),
  CONSTRAINT fk_investment_reporting_obligation_event_obligation FOREIGN KEY (obligation_id) REFERENCES investment_reporting_obligations(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_reporting_obligation_event_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_holdings_references (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  round_id BIGINT UNSIGNED NOT NULL,
  investor_user_id BIGINT UNSIGNED NOT NULL,
  closing_record_id BIGINT UNSIGNED NOT NULL,
  instrument_type VARCHAR(80) NOT NULL,
  verified_funded_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  closing_batch_reference VARCHAR(220) NULL,
  agreement_reference VARCHAR(220) NULL,
  conversion_or_maturity_reference VARCHAR(220) NULL,
  information_rights_status ENUM('not_reviewed','none_recorded','active','expired','terminated') NOT NULL DEFAULT 'not_reviewed',
  tax_document_status ENUM('not_started','requested','available','delivered','not_applicable') NOT NULL DEFAULT 'not_started',
  latest_reconciliation_public_id CHAR(36) NULL,
  source_snapshot_json JSON NOT NULL,
  generated_by_user_id BIGINT UNSIGNED NULL,
  generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_holdings_reference_public (public_id),
  UNIQUE KEY uq_investment_holdings_reference_record (closing_record_id),
  KEY idx_investment_holdings_reference_investor (investor_user_id,round_id),
  CONSTRAINT fk_investment_holdings_reference_round FOREIGN KEY (round_id) REFERENCES investment_rounds(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_holdings_reference_investor FOREIGN KEY (investor_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_holdings_reference_closing FOREIGN KEY (closing_record_id) REFERENCES investor_closing_records(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_holdings_reference_generator FOREIGN KEY (generated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_tax_documents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  round_id BIGINT UNSIGNED NOT NULL,
  investor_user_id BIGINT UNSIGNED NOT NULL,
  document_type ENUM('w9','w8ben','w8bene','form_1099','schedule_k1','annual_financials','investor_tax_notice','other') NOT NULL,
  reporting_year SMALLINT UNSIGNED NOT NULL,
  title VARCHAR(220) NOT NULL,
  external_provider VARCHAR(180) NULL,
  status ENUM('not_started','requested','preparing_external','internal_review','approved','published','superseded','archived','not_applicable') NOT NULL DEFAULT 'not_started',
  current_version_number INT UNSIGNED NOT NULL DEFAULT 0,
  published_at DATETIME NULL,
  first_viewed_at DATETIME NULL,
  last_viewed_at DATETIME NULL,
  view_count INT UNSIGNED NOT NULL DEFAULT 0,
  created_by_user_id BIGINT UNSIGNED NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_tax_document_public (public_id),
  UNIQUE KEY uq_investment_tax_document_type_year (round_id,investor_user_id,document_type,reporting_year),
  KEY idx_investment_tax_document_investor (investor_user_id,reporting_year,status),
  CONSTRAINT fk_investment_tax_document_round FOREIGN KEY (round_id) REFERENCES investment_rounds(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_tax_document_investor FOREIGN KEY (investor_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_tax_document_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_tax_document_updater FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_tax_document_versions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  tax_document_id BIGINT UNSIGNED NOT NULL,
  version_number INT UNSIGNED NOT NULL,
  external_url VARCHAR(1000) NOT NULL,
  external_reference VARCHAR(220) NULL,
  status ENUM('draft','internal_review','approved','published','superseded','archived') NOT NULL DEFAULT 'draft',
  approved_by_user_id BIGINT UNSIGNED NULL,
  approved_at DATETIME NULL,
  published_at DATETIME NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_tax_document_version_public (public_id),
  UNIQUE KEY uq_investment_tax_document_version_number (tax_document_id,version_number),
  CONSTRAINT fk_investment_tax_document_version_document FOREIGN KEY (tax_document_id) REFERENCES investment_tax_documents(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_tax_document_version_approver FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_tax_document_version_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_material_notices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  round_id BIGINT UNSIGNED NULL,
  notice_type ENUM('new_financing','material_contract','leadership_change','litigation_regulatory','operating_change','acquisition_sale','missed_milestone','capitalization_change','information_rights','board_meeting','other') NOT NULL DEFAULT 'other',
  title VARCHAR(220) NOT NULL,
  body LONGTEXT NOT NULL,
  audience ENUM('funded_investors','major_investors','rights_holders','selected_investors','specific_investors','board','custom') NOT NULL DEFAULT 'funded_investors',
  status ENUM('draft','internal_review','counsel_review','approved','published','archived') NOT NULL DEFAULT 'draft',
  counsel_status ENUM('not_started','in_review','approved','changes_required','not_applicable') NOT NULL DEFAULT 'not_started',
  effective_at DATETIME NULL,
  published_at DATETIME NULL,
  expires_at DATETIME NULL,
  related_document_url VARCHAR(1000) NULL,
  related_document_reference VARCHAR(220) NULL,
  internal_notes TEXT NULL,
  approved_by_user_id BIGINT UNSIGNED NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_material_notice_public (public_id),
  KEY idx_investment_material_notice_publish (round_id,status,published_at),
  CONSTRAINT fk_investment_material_notice_round FOREIGN KEY (round_id) REFERENCES investment_rounds(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_material_notice_approver FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_material_notice_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_investment_material_notice_updater FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS investment_material_notice_recipients (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  notice_id BIGINT UNSIGNED NOT NULL,
  investor_user_id BIGINT UNSIGNED NOT NULL,
  status ENUM('published','viewed','acknowledged','revoked') NOT NULL DEFAULT 'published',
  first_viewed_at DATETIME NULL,
  last_viewed_at DATETIME NULL,
  acknowledged_at DATETIME NULL,
  view_count INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_investment_material_notice_recipient (notice_id,investor_user_id),
  KEY idx_investment_material_notice_recipient_status (investor_user_id,status,updated_at),
  CONSTRAINT fk_investment_material_notice_recipient_notice FOREIGN KEY (notice_id) REFERENCES investment_material_notices(id) ON DELETE CASCADE,
  CONSTRAINT fk_investment_material_notice_recipient_investor FOREIGN KEY (investor_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO schema_migrations (migration_key,description,applied_at)
VALUES ('20260723_investor_governance_information_rights_v5','Adds governance participants and appointments, board meetings and immutable minutes, externally executed consent tracking, counsel-confirmed investor rights, recurring reporting obligations, holdings references, versioned tax documents and governed material notices.',NOW());