-- Microgifter MCP automation foundation v1.
-- Import after database/20260720_task_agent_phase4_v1.sql.
-- Additive, automation-ready control-plane schema. No public MCP endpoint is enabled by this migration.

START TRANSACTION;

CREATE TABLE IF NOT EXISTS mcp_scope_catalog (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  scope_key VARCHAR(120) NOT NULL,
  display_name VARCHAR(160) NOT NULL,
  description VARCHAR(500) NOT NULL,
  operation_class ENUM('read','monitor','recommend','task','draft','approval_gated','bounded_auto','prohibited') NOT NULL DEFAULT 'read',
  active TINYINT(1) NOT NULL DEFAULT 1,
  grantable TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_scope_catalog_key (scope_key),
  KEY idx_mcp_scope_catalog_active (active,grantable,operation_class)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_clients (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  client_key VARCHAR(120) NOT NULL,
  display_name VARCHAR(180) NOT NULL,
  status ENUM('development','active','paused','disabled','revoked') NOT NULL DEFAULT 'development',
  client_type ENUM('first_party','chatgpt','claude','custom','enterprise') NOT NULL DEFAULT 'custom',
  redirect_uris_json JSON NULL,
  allowed_origins_json JSON NULL,
  maximum_operation_class ENUM('read','monitor','recommend','task','draft','approval_gated','bounded_auto') NOT NULL DEFAULT 'read',
  metadata_json JSON NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  disabled_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_clients_public_id (public_id),
  UNIQUE KEY uq_mcp_clients_key (client_key),
  KEY idx_mcp_clients_status (status,client_type,updated_at),
  CONSTRAINT fk_mcp_clients_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_connections (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  client_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  workspace_type VARCHAR(40) NULL,
  workspace_id BIGINT UNSIGNED NULL,
  display_name VARCHAR(180) NOT NULL,
  status ENUM('pending','active','paused','expired','revoked','disabled') NOT NULL DEFAULT 'pending',
  maximum_operation_class ENUM('read','monitor','recommend','task','draft','approval_gated','bounded_auto') NOT NULL DEFAULT 'read',
  token_version INT UNSIGNED NOT NULL DEFAULT 1,
  consented_at DATETIME NULL,
  expires_at DATETIME NULL,
  last_activity_at DATETIME NULL,
  paused_at DATETIME NULL,
  revoked_at DATETIME NULL,
  revoked_by_user_id BIGINT UNSIGNED NULL,
  revocation_reason VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_connections_public_id (public_id),
  KEY idx_mcp_connections_user_status (user_id,status,updated_at),
  KEY idx_mcp_connections_client_status (client_id,status,updated_at),
  KEY idx_mcp_connections_workspace (workspace_type,workspace_id,status),
  CONSTRAINT fk_mcp_connections_client FOREIGN KEY (client_id) REFERENCES mcp_clients(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcp_connections_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcp_connections_revoked_by FOREIGN KEY (revoked_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_connection_scopes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  connection_id BIGINT UNSIGNED NOT NULL,
  scope_key VARCHAR(120) NOT NULL,
  granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_connection_scope (connection_id,scope_key),
  KEY idx_mcp_connection_scopes_active (scope_key,revoked_at,connection_id),
  CONSTRAINT fk_mcp_connection_scopes_connection FOREIGN KEY (connection_id) REFERENCES mcp_connections(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcp_connection_scopes_catalog FOREIGN KEY (scope_key) REFERENCES mcp_scope_catalog(scope_key) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_automation_grants (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  connection_id BIGINT UNSIGNED NOT NULL,
  authorizing_user_id BIGINT UNSIGNED NOT NULL,
  workspace_type VARCHAR(40) NULL,
  workspace_id BIGINT UNSIGNED NULL,
  status ENUM('draft','active','paused','expired','revoked') NOT NULL DEFAULT 'draft',
  maximum_operation_class ENUM('read','monitor','recommend','task','draft','approval_gated','bounded_auto') NOT NULL DEFAULT 'read',
  allowed_tools_json JSON NOT NULL,
  allowed_playbooks_json JSON NOT NULL,
  allowed_trigger_types_json JSON NOT NULL,
  approval_policy ENUM('always','risk_based','grant_based','never_for_allowlisted') NOT NULL DEFAULT 'always',
  risk_ceiling ENUM('low','medium','high','critical') NOT NULL DEFAULT 'low',
  currency CHAR(3) NULL,
  per_run_amount_limit_cents BIGINT UNSIGNED NULL,
  daily_amount_limit_cents BIGINT UNSIGNED NULL,
  lifetime_amount_limit_cents BIGINT UNSIGNED NULL,
  per_run_quantity_limit INT UNSIGNED NULL,
  daily_quantity_limit INT UNSIGNED NULL,
  lifetime_quantity_limit BIGINT UNSIGNED NULL,
  minimum_frequency_seconds INT UNSIGNED NULL,
  maximum_concurrent_runs INT UNSIGNED NOT NULL DEFAULT 1,
  target_policy_json JSON NOT NULL,
  starts_at DATETIME NULL,
  expires_at DATETIME NULL,
  last_used_at DATETIME NULL,
  revocation_version INT UNSIGNED NOT NULL DEFAULT 1,
  revoked_at DATETIME NULL,
  revoked_by_user_id BIGINT UNSIGNED NULL,
  revocation_reason VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_automation_grants_public_id (public_id),
  KEY idx_mcp_automation_grants_connection (connection_id,status,expires_at),
  KEY idx_mcp_automation_grants_user (authorizing_user_id,status,updated_at),
  KEY idx_mcp_automation_grants_workspace (workspace_type,workspace_id,status),
  CONSTRAINT fk_mcp_automation_grants_connection FOREIGN KEY (connection_id) REFERENCES mcp_connections(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcp_automation_grants_user FOREIGN KEY (authorizing_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcp_automation_grants_revoked_by FOREIGN KEY (revoked_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_automations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  grant_id BIGINT UNSIGNED NOT NULL,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  workspace_type VARCHAR(40) NULL,
  workspace_id BIGINT UNSIGNED NULL,
  name VARCHAR(180) NOT NULL,
  playbook_key VARCHAR(160) NOT NULL,
  description VARCHAR(500) NULL,
  status ENUM('draft','pending_approval','active','paused','completed','failed','expired','revoked') NOT NULL DEFAULT 'draft',
  configuration_json JSON NOT NULL,
  timezone VARCHAR(80) NOT NULL DEFAULT 'UTC',
  current_version INT UNSIGNED NOT NULL DEFAULT 1,
  last_run_at DATETIME NULL,
  next_run_at DATETIME NULL,
  completed_at DATETIME NULL,
  failure_code VARCHAR(120) NULL,
  failure_message VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_automations_public_id (public_id),
  KEY idx_mcp_automations_owner (owner_user_id,status,updated_at),
  KEY idx_mcp_automations_grant (grant_id,status,next_run_at),
  KEY idx_mcp_automations_workspace (workspace_type,workspace_id,status),
  CONSTRAINT fk_mcp_automations_grant FOREIGN KEY (grant_id) REFERENCES mcp_automation_grants(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcp_automations_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_automation_triggers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  automation_id BIGINT UNSIGNED NOT NULL,
  trigger_type ENUM('manual','fixed_schedule','recurring_schedule','canonical_event','condition','monitor_threshold') NOT NULL,
  status ENUM('active','paused','expired','revoked') NOT NULL DEFAULT 'active',
  configuration_json JSON NOT NULL,
  next_due_at DATETIME NULL,
  last_fired_at DATETIME NULL,
  fire_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_automation_triggers_public_id (public_id),
  KEY idx_mcp_automation_triggers_due (status,next_due_at,trigger_type),
  KEY idx_mcp_automation_triggers_automation (automation_id,status),
  CONSTRAINT fk_mcp_automation_triggers_automation FOREIGN KEY (automation_id) REFERENCES mcp_automations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_automation_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  automation_id BIGINT UNSIGNED NOT NULL,
  grant_id BIGINT UNSIGNED NOT NULL,
  trigger_id BIGINT UNSIGNED NULL,
  status ENUM('queued','evaluating','waiting_for_approval','approved','executing','succeeded','partially_succeeded','failed','cancelled','dead_lettered') NOT NULL DEFAULT 'queued',
  idempotency_key VARCHAR(190) NOT NULL,
  input_fingerprint CHAR(64) NOT NULL,
  scheduled_at DATETIME NULL,
  queued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  attempt INT UNSIGNED NOT NULL DEFAULT 1,
  maximum_attempts INT UNSIGNED NOT NULL DEFAULT 3,
  lease_owner VARCHAR(190) NULL,
  lease_expires_at DATETIME NULL,
  cancellation_requested_at DATETIME NULL,
  error_code VARCHAR(120) NULL,
  error_message VARCHAR(500) NULL,
  output_summary_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_automation_runs_public_id (public_id),
  UNIQUE KEY uq_mcp_automation_runs_idempotency (idempotency_key),
  KEY idx_mcp_automation_runs_queue (status,scheduled_at,lease_expires_at),
  KEY idx_mcp_automation_runs_automation (automation_id,status,created_at),
  KEY idx_mcp_automation_runs_grant (grant_id,status,created_at),
  CONSTRAINT fk_mcp_automation_runs_automation FOREIGN KEY (automation_id) REFERENCES mcp_automations(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcp_automation_runs_grant FOREIGN KEY (grant_id) REFERENCES mcp_automation_grants(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcp_automation_runs_trigger FOREIGN KEY (trigger_id) REFERENCES mcp_automation_triggers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_automation_actions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  run_id BIGINT UNSIGNED NOT NULL,
  sequence_number INT UNSIGNED NOT NULL,
  tool_name VARCHAR(190) NOT NULL,
  tool_version VARCHAR(40) NOT NULL DEFAULT '1.0',
  operation_class ENUM('read','monitor','recommend','task','draft','approval_gated','bounded_auto','prohibited') NOT NULL,
  risk_level ENUM('low','medium','high','critical') NOT NULL DEFAULT 'low',
  status ENUM('proposed','waiting_for_approval','approved','rejected','executing','succeeded','failed','cancelled','expired') NOT NULL DEFAULT 'proposed',
  approval_required TINYINT(1) NOT NULL DEFAULT 0,
  idempotency_key VARCHAR(190) NOT NULL,
  input_fingerprint CHAR(64) NOT NULL,
  sanitized_input_json JSON NULL,
  fresh_state_token VARCHAR(190) NULL,
  proposed_amount_cents BIGINT UNSIGNED NULL,
  proposed_quantity BIGINT UNSIGNED NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  error_code VARCHAR(120) NULL,
  error_message VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_automation_actions_public_id (public_id),
  UNIQUE KEY uq_mcp_automation_actions_run_sequence (run_id,sequence_number),
  UNIQUE KEY uq_mcp_automation_actions_idempotency (idempotency_key),
  KEY idx_mcp_automation_actions_status (status,approval_required,updated_at),
  KEY idx_mcp_automation_actions_tool (tool_name,status,created_at),
  CONSTRAINT fk_mcp_automation_actions_run FOREIGN KEY (run_id) REFERENCES mcp_automation_runs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_action_approval_links (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  action_id BIGINT UNSIGNED NOT NULL,
  approval_request_id BIGINT UNSIGNED NOT NULL,
  status ENUM('pending','approved','rejected','deferred','expired','cancelled') NOT NULL DEFAULT 'pending',
  linked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  decided_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_action_approval_action (action_id),
  UNIQUE KEY uq_mcp_action_approval_request (approval_request_id),
  KEY idx_mcp_action_approval_status (status,updated_at),
  CONSTRAINT fk_mcp_action_approval_action FOREIGN KEY (action_id) REFERENCES mcp_automation_actions(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcp_action_approval_request FOREIGN KEY (approval_request_id) REFERENCES agent_approval_requests(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_idempotency_keys (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  scope_type ENUM('connection','grant','automation','run','action','tool') NOT NULL,
  scope_public_id CHAR(36) NOT NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  owner_user_id BIGINT UNSIGNED NULL,
  workspace_type VARCHAR(40) NULL,
  workspace_id BIGINT UNSIGNED NULL,
  request_fingerprint CHAR(64) NOT NULL,
  status ENUM('reserved','executing','succeeded','failed','expired') NOT NULL DEFAULT 'reserved',
  resource_type VARCHAR(80) NULL,
  resource_public_id CHAR(36) NULL,
  result_fingerprint CHAR(64) NULL,
  expires_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_idempotency_public_id (public_id),
  UNIQUE KEY uq_mcp_idempotency_scope_key (scope_type,scope_public_id,idempotency_key),
  KEY idx_mcp_idempotency_expiry (status,expires_at),
  KEY idx_mcp_idempotency_owner (owner_user_id,status,updated_at),
  CONSTRAINT fk_mcp_idempotency_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_tool_invocations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  request_id CHAR(36) NOT NULL,
  connection_id BIGINT UNSIGNED NULL,
  client_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NULL,
  workspace_type VARCHAR(40) NULL,
  workspace_id BIGINT UNSIGNED NULL,
  tool_name VARCHAR(190) NOT NULL,
  tool_version VARCHAR(40) NOT NULL DEFAULT '1.0',
  operation_class ENUM('read','monitor','recommend','task','draft','approval_gated','bounded_auto','prohibited') NOT NULL,
  scope_required VARCHAR(120) NULL,
  input_fingerprint CHAR(64) NOT NULL,
  result_status ENUM('success','denied','validation_error','rate_limited','failed') NOT NULL,
  http_status SMALLINT UNSIGNED NOT NULL,
  mcp_error_code VARCHAR(120) NULL,
  denial_reason VARCHAR(255) NULL,
  duration_ms INT UNSIGNED NULL,
  record_count INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_tool_invocations_public_id (public_id),
  UNIQUE KEY uq_mcp_tool_invocations_request_id (request_id),
  KEY idx_mcp_tool_invocations_connection (connection_id,created_at),
  KEY idx_mcp_tool_invocations_tool (tool_name,result_status,created_at),
  KEY idx_mcp_tool_invocations_user (user_id,created_at),
  CONSTRAINT fk_mcp_tool_invocations_connection FOREIGN KEY (connection_id) REFERENCES mcp_connections(id) ON DELETE SET NULL,
  CONSTRAINT fk_mcp_tool_invocations_client FOREIGN KEY (client_id) REFERENCES mcp_clients(id) ON DELETE SET NULL,
  CONSTRAINT fk_mcp_tool_invocations_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_action_receipts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  action_id BIGINT UNSIGNED NOT NULL,
  run_id BIGINT UNSIGNED NOT NULL,
  grant_id BIGINT UNSIGNED NOT NULL,
  status ENUM('attempted','succeeded','failed','cancelled','reconciled') NOT NULL,
  canonical_service VARCHAR(160) NOT NULL,
  canonical_action VARCHAR(160) NOT NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  before_state_token VARCHAR(190) NULL,
  after_state_token VARCHAR(190) NULL,
  result_reference_type VARCHAR(80) NULL,
  result_reference_public_id CHAR(36) NULL,
  amount_cents BIGINT UNSIGNED NULL,
  quantity BIGINT UNSIGNED NULL,
  metadata_json JSON NULL,
  attempted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_action_receipts_public_id (public_id),
  UNIQUE KEY uq_mcp_action_receipts_action_attempt (action_id,idempotency_key),
  KEY idx_mcp_action_receipts_run (run_id,created_at),
  KEY idx_mcp_action_receipts_grant (grant_id,created_at),
  KEY idx_mcp_action_receipts_status (status,created_at),
  CONSTRAINT fk_mcp_action_receipts_action FOREIGN KEY (action_id) REFERENCES mcp_automation_actions(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcp_action_receipts_run FOREIGN KEY (run_id) REFERENCES mcp_automation_runs(id) ON DELETE CASCADE,
  CONSTRAINT fk_mcp_action_receipts_grant FOREIGN KEY (grant_id) REFERENCES mcp_automation_grants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_security_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  connection_id BIGINT UNSIGNED NULL,
  client_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NULL,
  workspace_type VARCHAR(40) NULL,
  workspace_id BIGINT UNSIGNED NULL,
  severity ENUM('info','low','medium','high','critical') NOT NULL DEFAULT 'info',
  event_type VARCHAR(160) NOT NULL,
  message VARCHAR(500) NOT NULL,
  evidence_json JSON NULL,
  ip_hash CHAR(64) NULL,
  user_agent_hash CHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_security_events_public_id (public_id),
  KEY idx_mcp_security_events_severity (severity,created_at),
  KEY idx_mcp_security_events_connection (connection_id,created_at),
  KEY idx_mcp_security_events_user (user_id,created_at),
  CONSTRAINT fk_mcp_security_events_connection FOREIGN KEY (connection_id) REFERENCES mcp_connections(id) ON DELETE SET NULL,
  CONSTRAINT fk_mcp_security_events_client FOREIGN KEY (client_id) REFERENCES mcp_clients(id) ON DELETE SET NULL,
  CONSTRAINT fk_mcp_security_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_rate_limit_buckets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  bucket_key VARCHAR(190) NOT NULL,
  window_started_at DATETIME NOT NULL,
  request_count INT UNSIGNED NOT NULL DEFAULT 0,
  blocked_until DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_rate_limit_bucket (bucket_key,window_started_at),
  KEY idx_mcp_rate_limit_blocked (blocked_until,updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_worker_leases (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  lease_key VARCHAR(190) NOT NULL,
  lease_owner VARCHAR(190) NOT NULL,
  resource_type VARCHAR(80) NOT NULL,
  resource_public_id CHAR(36) NULL,
  acquired_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  heartbeat_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  released_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mcp_worker_leases_key (lease_key),
  KEY idx_mcp_worker_leases_expiry (released_at,expires_at),
  KEY idx_mcp_worker_leases_owner (lease_owner,heartbeat_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO mcp_scope_catalog (scope_key,display_name,description,operation_class,active,grantable)
VALUES
  ('profile:read','Read account context','Read the authorized Microgifter account and workspace context.','read',1,1),
  ('catalog:read','Read published catalog','Search and view currently published Microgifter catalog products.','read',1,1),
  ('merchant:read','Read public merchants','Read privacy-filtered public merchant information.','read',0,0),
  ('campaign:read','Read campaigns','Read authorized campaign status through canonical Microgifter services.','read',0,0),
  ('reward:read','Read rewards','Read authorized reward status through canonical Microgifter services.','read',0,0),
  ('gift:read','Read owned gifts','Read user-owned gift and lifecycle status.','read',0,0),
  ('automation:manage','Manage automations','Create and manage durable automation definitions and grants.','task',0,0),
  ('gift:draft','Create gift drafts','Create reviewable gift drafts without purchase or issuance.','draft',0,0),
  ('campaign:draft','Create campaign drafts','Create reviewable campaign drafts without publication.','draft',0,0),
  ('message:draft','Create message drafts','Create reviewable message drafts without sending.','draft',0,0)
ON DUPLICATE KEY UPDATE
  display_name=VALUES(display_name),
  description=VALUES(description),
  operation_class=VALUES(operation_class),
  active=VALUES(active),
  grantable=VALUES(grantable);

INSERT INTO schema_migrations (migration_key,description,checksum,applied_at)
VALUES (
  '20260720_microgifter_mcp_automation_foundation_v1',
  'Microgifter MCP clients, connections, durable grants, automations, triggers, runs, actions, approvals, idempotency, receipts, security, limits, and worker leases.',
  NULL,
  NOW()
)
ON DUPLICATE KEY UPDATE description=VALUES(description);

COMMIT;
