CREATE TABLE IF NOT EXISTS crm_scheduled_action_batches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  action_type VARCHAR(40) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'scheduled',
  selected_count INT UNSIGNED NOT NULL DEFAULT 0,
  scheduled_count INT UNSIGNED NOT NULL DEFAULT 0,
  processed_count INT UNSIGNED NOT NULL DEFAULT 0,
  skipped_count INT UNSIGNED NOT NULL DEFAULT 0,
  failed_count INT UNSIGNED NOT NULL DEFAULT 0,
  scheduled_at DATETIME NOT NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  payload_json JSON NULL,
  result_summary_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_crm_batch_public_id (public_id),
  UNIQUE KEY uniq_crm_batch_idem (merchant_user_id,idempotency_key),
  KEY idx_crm_batch_merchant_status (merchant_user_id,status,scheduled_at),
  KEY idx_crm_batch_status (status,scheduled_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS crm_scheduled_actions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  batch_id BIGINT UNSIGNED NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  campaign_id BIGINT UNSIGNED NULL,
  contact_id BIGINT UNSIGNED NULL,
  reward_template_id BIGINT UNSIGNED NULL,
  action_type VARCHAR(40) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'scheduled',
  scheduled_at DATETIME NOT NULL,
  locked_at DATETIME NULL,
  processed_at DATETIME NULL,
  failed_at DATETIME NULL,
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  idempotency_key VARCHAR(190) NOT NULL,
  payload_json JSON NULL,
  result_json JSON NULL,
  last_error TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_crm_scheduled_public_id (public_id),
  UNIQUE KEY uniq_crm_scheduled_idem (merchant_user_id,idempotency_key),
  KEY idx_crm_scheduled_due (status,scheduled_at,id),
  KEY idx_crm_scheduled_merchant_status (merchant_user_id,status,scheduled_at),
  KEY idx_crm_scheduled_batch (batch_id,status),
  KEY idx_crm_scheduled_contact (contact_id,status),
  CONSTRAINT fk_crm_scheduled_batch FOREIGN KEY (batch_id) REFERENCES crm_scheduled_action_batches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;