-- Predictive Campaign Studio & Reward Inventory Intelligence Foundation v1
-- Adds recommendation intelligence only. Existing reward_templates and campaigns
-- remain the canonical reward and campaign records.

CREATE TABLE IF NOT EXISTS mg_predictive_campaign_recommendations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  recommendation_type VARCHAR(80) NOT NULL,
  scope_type ENUM('store_trend','customer_segment','individual_customer') NOT NULL DEFAULT 'store_trend',
  target_customer_user_id BIGINT UNSIGNED NULL,
  dedupe_key VARCHAR(190) NOT NULL,
  title VARCHAR(180) NOT NULL,
  summary VARCHAR(500) NOT NULL,
  rationale TEXT NULL,
  audience_name VARCHAR(190) NOT NULL,
  audience_count INT UNSIGNED NOT NULL DEFAULT 0,
  campaign_type VARCHAR(80) NOT NULL,
  reward_strategy ENUM('reuse_existing','create_draft') NOT NULL DEFAULT 'create_draft',
  reward_template_id BIGINT UNSIGNED NULL,
  campaign_id BIGINT UNSIGNED NULL,
  recommended_reward_json JSON NULL,
  recommended_campaign_json JSON NOT NULL,
  segment_rules_json JSON NULL,
  evidence_json JSON NULL,
  projections_json JSON NULL,
  confidence_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  status ENUM('new','approved','materialized','dismissed','expired') NOT NULL DEFAULT 'new',
  generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at DATETIME NULL,
  reviewed_by_user_id BIGINT UNSIGNED NULL,
  materialized_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_predictive_campaign_public_id (public_id),
  UNIQUE KEY uq_predictive_campaign_dedupe (merchant_user_id,dedupe_key),
  KEY idx_predictive_campaign_merchant_status (merchant_user_id,status,generated_at),
  KEY idx_predictive_campaign_reward (reward_template_id),
  KEY idx_predictive_campaign_campaign (campaign_id),
  KEY idx_predictive_campaign_target_customer (target_customer_user_id),
  CONSTRAINT fk_predictive_campaign_merchant FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_predictive_campaign_target_customer FOREIGN KEY (target_customer_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_predictive_campaign_reward FOREIGN KEY (reward_template_id) REFERENCES reward_templates(id) ON DELETE SET NULL,
  CONSTRAINT fk_predictive_campaign_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
  CONSTRAINT fk_predictive_campaign_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
