-- Shared Microgifter Identity v1
CREATE TABLE IF NOT EXISTS developer_identity_authorizations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  app_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  microgifter_user_id BIGINT UNSIGNED NULL,
  external_user_id VARCHAR(255) NULL,
  external_user_hash CHAR(64) NULL,
  authorization_code_hash CHAR(64) NULL,
  state VARCHAR(255) NULL,
  return_url VARCHAR(700) NOT NULL,
  requested_role ENUM('participant','merchant') NOT NULL DEFAULT 'participant',
  granted_role ENUM('participant','merchant') NULL,
  status ENUM('pending','approved','cancelled','expired','exchanged') NOT NULL DEFAULT 'pending',
  profile_json JSON NULL,
  expires_at DATETIME NOT NULL,
  completed_at DATETIME NULL,
  exchanged_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_developer_identity_authorizations_public (public_id),
  UNIQUE KEY uq_developer_identity_authorizations_code (authorization_code_hash),
  KEY idx_developer_identity_authorizations_app_status (app_id,status),
  KEY idx_developer_identity_authorizations_user (microgifter_user_id),
  KEY idx_developer_identity_authorizations_external (app_id,external_user_hash),
  CONSTRAINT fk_identity_authorizations_app FOREIGN KEY (app_id) REFERENCES merchant_developer_apps(id) ON DELETE CASCADE,
  CONSTRAINT fk_identity_authorizations_merchant FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_identity_authorizations_user FOREIGN KEY (microgifter_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS developer_identity_links (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  app_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  microgifter_user_id BIGINT UNSIGNED NOT NULL,
  external_user_id VARCHAR(255) NOT NULL,
  external_user_hash CHAR(64) NOT NULL,
  granted_role ENUM('participant','merchant') NOT NULL DEFAULT 'participant',
  status ENUM('active','revoked') NOT NULL DEFAULT 'active',
  consent_json JSON NULL,
  linked_at DATETIME NOT NULL,
  revoked_at DATETIME NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_developer_identity_links_public (public_id),
  UNIQUE KEY uq_developer_identity_links_external (app_id,external_user_hash),
  KEY idx_developer_identity_links_user (microgifter_user_id,status),
  CONSTRAINT fk_identity_links_app FOREIGN KEY (app_id) REFERENCES merchant_developer_apps(id) ON DELETE CASCADE,
  CONSTRAINT fk_identity_links_merchant FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_identity_links_user FOREIGN KEY (microgifter_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
