-- Stage 12 Merchant CRM foundation
-- One merchant-owned CRM with per-campaign history and source events.

CREATE TABLE IF NOT EXISTS merchant_crm_contacts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  primary_email VARCHAR(255) NULL,
  primary_phone VARCHAR(80) NULL,
  display_name VARCHAR(180) NULL,
  lifecycle_stage ENUM('lead','follower','prospect','customer','supporter','redeemer','inactive','custom') NOT NULL DEFAULT 'lead',
  crm_status ENUM('active','archived','blocked') NOT NULL DEFAULT 'active',
  last_campaign_type VARCHAR(80) NOT NULL DEFAULT 'unknown',
  last_source_type VARCHAR(80) NOT NULL DEFAULT 'unknown',
  first_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_engaged_at DATETIME NULL,
  last_followed_at DATETIME NULL,
  last_purchased_at DATETIME NULL,
  last_reward_issued_at DATETIME NULL,
  last_reward_claimed_at DATETIME NULL,
  last_reward_redeemed_at DATETIME NULL,
  total_purchase_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  total_rewards_issued INT UNSIGNED NOT NULL DEFAULT 0,
  total_rewards_claimed INT UNSIGNED NOT NULL DEFAULT 0,
  total_rewards_redeemed INT UNSIGNED NOT NULL DEFAULT 0,
  source_summary_json JSON NULL,
  tags_json JSON NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_crm_contacts_public_id (public_id),
  UNIQUE KEY uq_merchant_crm_contacts_email (merchant_user_id, primary_email),
  UNIQUE KEY uq_merchant_crm_contacts_user (merchant_user_id, user_id),
  KEY idx_merchant_crm_contacts_merchant_updated (merchant_user_id, updated_at, id),
  KEY idx_merchant_crm_contacts_stage (merchant_user_id, lifecycle_stage, updated_at),
  KEY idx_merchant_crm_contacts_campaign_type (merchant_user_id, last_campaign_type, updated_at),
  CONSTRAINT fk_merchant_crm_contacts_merchant FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_crm_contacts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS merchant_crm_contact_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  crm_contact_id BIGINT UNSIGNED NOT NULL,
  campaign_id BIGINT UNSIGNED NULL,
  campaign_type VARCHAR(80) NOT NULL,
  event_type VARCHAR(90) NOT NULL,
  source_type VARCHAR(80) NOT NULL,
  source_public_id VARCHAR(80) NULL,
  user_id BIGINT UNSIGNED NULL,
  email VARCHAR(255) NULL,
  phone VARCHAR(80) NULL,
  name VARCHAR(180) NULL,
  value_cents BIGINT UNSIGNED NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_crm_contact_events_public_id (public_id),
  KEY idx_merchant_crm_events_contact_created (crm_contact_id, created_at, id),
  KEY idx_merchant_crm_events_merchant_created (merchant_user_id, created_at, id),
  KEY idx_merchant_crm_events_campaign (merchant_user_id, campaign_id, campaign_type, created_at),
  KEY idx_merchant_crm_events_type (merchant_user_id, event_type, created_at),
  CONSTRAINT fk_merchant_crm_events_merchant FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_crm_events_contact FOREIGN KEY (crm_contact_id) REFERENCES merchant_crm_contacts(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_crm_events_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_crm_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS merchant_crm_contact_campaigns (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  crm_contact_id BIGINT UNSIGNED NOT NULL,
  campaign_id BIGINT UNSIGNED NOT NULL,
  campaign_type VARCHAR(80) NOT NULL,
  first_event_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_event_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  event_count INT UNSIGNED NOT NULL DEFAULT 1,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_crm_contact_campaign (crm_contact_id, campaign_id, campaign_type),
  UNIQUE KEY uq_merchant_crm_contact_campaign_public_id (public_id),
  KEY idx_merchant_crm_contact_campaigns_merchant (merchant_user_id, campaign_type, updated_at),
  CONSTRAINT fk_merchant_crm_contact_campaigns_merchant FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_crm_contact_campaigns_contact FOREIGN KEY (crm_contact_id) REFERENCES merchant_crm_contacts(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_crm_contact_campaigns_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS merchant_crm_notes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  crm_contact_id BIGINT UNSIGNED NOT NULL,
  author_user_id BIGINT UNSIGNED NOT NULL,
  note TEXT NOT NULL,
  visibility ENUM('merchant_internal','team') NOT NULL DEFAULT 'merchant_internal',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_crm_notes_public_id (public_id),
  KEY idx_merchant_crm_notes_contact_created (crm_contact_id, created_at),
  CONSTRAINT fk_merchant_crm_notes_merchant FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_crm_notes_contact FOREIGN KEY (crm_contact_id) REFERENCES merchant_crm_contacts(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_crm_notes_author FOREIGN KEY (author_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
