-- Stage 19f: Design Studio assets, export queue, and campaign links
-- Purpose: production asset lifecycle, reliable renderer/export jobs, and campaign linkage uniqueness.
-- Depends on: stage_19b QR library, stage_19c brand kits, stage_19d templates/projects, stage_19e AI queue.

CREATE TABLE IF NOT EXISTS merchant_design_assets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  brand_kit_id BIGINT UNSIGNED NULL,
  project_id BIGINT UNSIGNED NULL,
  template_id BIGINT UNSIGNED NULL,
  qr_code_id BIGINT UNSIGNED NULL,
  ai_job_id BIGINT UNSIGNED NULL,
  parent_asset_id BIGINT UNSIGNED NULL COMMENT 'Parent asset for thumbnails, variants, crops, or regenerated outputs.',
  source_asset_id BIGINT UNSIGNED NULL COMMENT 'Original/source asset used to generate this asset.',
  asset_family_key VARCHAR(120) NULL COMMENT 'Stable grouping key across asset versions.',
  version_number INT UNSIGNED NOT NULL DEFAULT 1,
  asset_type ENUM('logo','image','ai_image','qr_svg','qr_png','proof_pdf','print_pdf','social_png','zip_package','thumbnail','other') NOT NULL DEFAULT 'other',
  name VARCHAR(180) NOT NULL,
  status ENUM('candidate','active','approved','archived','failed') NOT NULL DEFAULT 'active',
  lifecycle_status ENUM('draft','candidate','approved','generated','published','expired','archived','failed') NOT NULL DEFAULT 'draft',
  storage_driver ENUM('external_url','local','s3','generated','pending') NOT NULL DEFAULT 'pending',
  source_url VARCHAR(1000) NULL,
  storage_key VARCHAR(500) NULL,
  public_url VARCHAR(1000) NULL,
  original_filename VARCHAR(255) NULL,
  file_extension VARCHAR(20) NULL,
  mime_type VARCHAR(120) NULL,
  byte_size BIGINT UNSIGNED NULL,
  width_px INT UNSIGNED NULL,
  height_px INT UNSIGNED NULL,
  checksum CHAR(64) NULL,
  renderer_version VARCHAR(80) NULL,
  metadata_json JSON NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  approved_by_user_id BIGINT UNSIGNED NULL,
  generated_at DATETIME NULL,
  approved_at DATETIME NULL,
  published_at DATETIME NULL,
  expires_at DATETIME NULL,
  last_accessed_at DATETIME NULL,
  archived_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_design_assets_public_id (public_id),
  UNIQUE KEY uq_merchant_design_assets_family_version (workspace_id,asset_family_key,version_number),
  KEY idx_merchant_design_assets_workspace (workspace_id,status,asset_type,updated_at),
  KEY idx_merchant_design_assets_lifecycle (workspace_id,lifecycle_status,asset_type,updated_at),
  KEY idx_merchant_design_assets_project (project_id,status,asset_type),
  KEY idx_merchant_design_assets_family (asset_family_key,version_number,status),
  KEY idx_merchant_design_assets_parent (parent_asset_id),
  KEY idx_merchant_design_assets_source (source_asset_id),
  CONSTRAINT fk_merchant_design_assets_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_design_assets_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_assets_brand_kit FOREIGN KEY (brand_kit_id) REFERENCES merchant_brand_kits(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_project FOREIGN KEY (project_id) REFERENCES merchant_design_projects(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_template FOREIGN KEY (template_id) REFERENCES merchant_design_templates(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_qr FOREIGN KEY (qr_code_id) REFERENCES merchant_qr_codes(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_ai_job FOREIGN KEY (ai_job_id) REFERENCES merchant_design_ai_jobs(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_parent FOREIGN KEY (parent_asset_id) REFERENCES merchant_design_assets(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_source FOREIGN KEY (source_asset_id) REFERENCES merchant_design_assets(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_assets_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Production and candidate assets generated/imported by Design Studio.';

CREATE TABLE IF NOT EXISTS merchant_design_export_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NULL,
  output_asset_id BIGINT UNSIGNED NULL,
  export_type ENUM('print_pdf','social_png','qr_svg','qr_png','zip_package','proof') NOT NULL DEFAULT 'proof',
  status ENUM('queued','running','completed','failed','canceled') NOT NULL DEFAULT 'queued',
  priority TINYINT UNSIGNED NOT NULL DEFAULT 5 COMMENT 'Lower value runs first; default is normal priority.',
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts INT UNSIGNED NOT NULL DEFAULT 3,
  locked_at DATETIME NULL,
  locked_by VARCHAR(120) NULL,
  next_attempt_at DATETIME NULL,
  last_attempt_at DATETIME NULL,
  failed_at DATETIME NULL,
  failure_code VARCHAR(80) NULL,
  renderer_version VARCHAR(80) NULL,
  options_json JSON NULL,
  manifest_json JSON NULL,
  error_message VARCHAR(500) NULL,
  requested_by_user_id BIGINT UNSIGNED NOT NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_design_export_jobs_public_id (public_id),
  KEY idx_merchant_design_export_jobs_workspace (workspace_id,status,export_type,created_at),
  KEY idx_merchant_design_export_jobs_queue (status,priority,next_attempt_at,locked_at,created_at),
  KEY idx_merchant_design_export_jobs_project (project_id,status,created_at),
  CONSTRAINT fk_merchant_design_export_jobs_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_design_export_jobs_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_export_jobs_project FOREIGN KEY (project_id) REFERENCES merchant_design_projects(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_export_jobs_output FOREIGN KEY (output_asset_id) REFERENCES merchant_design_assets(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_export_jobs_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Reliable renderer queue for proof, print, social, QR, and package exports.';

CREATE TABLE IF NOT EXISTS merchant_design_campaign_links (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NULL,
  template_id BIGINT UNSIGNED NULL,
  asset_id BIGINT UNSIGNED NULL,
  qr_code_id BIGINT UNSIGNED NULL,
  campaign_type ENUM('promotional_crm','newsletter','contest','landing_page','distribution','product','custom') NOT NULL DEFAULT 'custom',
  campaign_ref VARCHAR(180) NOT NULL,
  campaign_unique_hash CHAR(64) GENERATED ALWAYS AS (SHA2(CONCAT_WS('|',workspace_id,campaign_type,campaign_ref,IFNULL(project_id,0),IFNULL(template_id,0),IFNULL(asset_id,0),IFNULL(qr_code_id,0)),256)) STORED,
  label VARCHAR(180) NULL,
  metadata_json JSON NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_design_campaign_links_public_id (public_id),
  UNIQUE KEY uq_merchant_design_campaign_links_hash (campaign_unique_hash),
  KEY idx_merchant_design_campaign_links_workspace (workspace_id,campaign_type,campaign_ref),
  KEY idx_merchant_design_campaign_links_project (project_id,campaign_type,campaign_ref),
  KEY idx_merchant_design_campaign_links_asset (asset_id,campaign_type,campaign_ref),
  KEY idx_merchant_design_campaign_links_qr (qr_code_id,campaign_type,campaign_ref),
  CONSTRAINT fk_merchant_design_campaign_links_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_design_campaign_links_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_campaign_links_project FOREIGN KEY (project_id) REFERENCES merchant_design_projects(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_campaign_links_template FOREIGN KEY (template_id) REFERENCES merchant_design_templates(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_campaign_links_asset FOREIGN KEY (asset_id) REFERENCES merchant_design_assets(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_campaign_links_qr FOREIGN KEY (qr_code_id) REFERENCES merchant_qr_codes(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_campaign_links_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Links Design Studio outputs to promotional CRM, campaign, product, landing, and distribution records.';

INSERT IGNORE INTO permissions (slug,name,description,created_at) VALUES
('merchant.design_assets.view','View design assets','View exported and generated Design Studio assets.',NOW()),
('merchant.design_assets.manage','Manage design assets','Create design asset records and export jobs.',NOW());

INSERT IGNORE INTO role_permissions (role_id,permission_id,created_at)
SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p
ON p.slug IN ('merchant.design_assets.view','merchant.design_assets.manage')
WHERE r.slug IN ('merchant','admin','super_admin');

INSERT INTO microgifter_schema_migrations (migration_key,migration_group,description,checksum,applied_at,created_at,updated_at)
VALUES ('stage_19f_design_studio_assets_exports_campaigns','design_studio','Create lifecycle-aware design assets, reliable export queue, and unique campaign links.',SHA2('stage_19f_design_studio_assets_exports_campaigns',256),NOW(),NOW(),NOW())
ON DUPLICATE KEY UPDATE updated_at=NOW();
