-- Stage 19 Design Studio Production Foundation
-- Single-file migration for QR library, brand kit scanner, reusable templates, projects,
-- AI presets/jobs, design assets, export jobs, campaign links, and migration tracking.
--
-- Import:
--   mysql -u YOUR_DB_USER -p YOUR_DB_NAME < database/stage_19_design_studio_qr_library.sql
--
-- Notes:
-- - Intended for a fresh Stage 19 install.
-- - If an older draft of Stage 19 was partially imported, compare existing table definitions before rerunning.
-- - Export jobs are queued by this schema; renderer workers are implemented separately.

CREATE TABLE IF NOT EXISTS microgifter_schema_migrations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  migration_key VARCHAR(160) NOT NULL,
  migration_group VARCHAR(80) NOT NULL DEFAULT 'core',
  description VARCHAR(500) NULL,
  checksum CHAR(64) NULL,
  applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_microgifter_schema_migrations_key (migration_key),
  KEY idx_microgifter_schema_migrations_group (migration_group,applied_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Application-level migration ledger.';

CREATE TABLE IF NOT EXISTS merchant_qr_codes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL COMMENT 'Stable public UUID used by APIs.',
  workspace_id BIGINT UNSIGNED NOT NULL COMMENT 'Owning merchant workspace.',
  merchant_user_id BIGINT UNSIGNED NOT NULL COMMENT 'Merchant owner at time of creation.',
  label VARCHAR(180) NOT NULL COMMENT 'Merchant-facing label.',
  qr_type ENUM('claim','lead','campaign','storefront','product','custom') NOT NULL DEFAULT 'claim' COMMENT 'QR intent used by campaigns and Design Studio.',
  status ENUM('draft','active','paused','archived') NOT NULL DEFAULT 'draft' COMMENT 'Only active QR codes redirect publicly.',
  short_code VARCHAR(80) NOT NULL COMMENT 'Public short code used by /qr.php?c=',
  destination_url VARCHAR(1000) NOT NULL COMMENT 'Validated destination URL or relative local path.',
  qr_payload_url VARCHAR(1000) NOT NULL COMMENT 'Public Microgifter redirect URL.',
  campaign_ref VARCHAR(160) NULL COMMENT 'Optional external/internal campaign reference.',
  product_ref VARCHAR(160) NULL COMMENT 'Optional product/offer reference.',
  scan_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  last_scanned_at DATETIME NULL,
  metadata_json JSON NULL COMMENT 'Optional source/context payload.',
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  archived_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_qr_codes_public_id (public_id),
  UNIQUE KEY uq_merchant_qr_codes_short_code (short_code),
  KEY idx_merchant_qr_codes_workspace_status (workspace_id,status,qr_type),
  KEY idx_merchant_qr_codes_merchant_status (merchant_user_id,status,updated_at),
  KEY idx_merchant_qr_codes_campaign (workspace_id,campaign_ref,status),
  CONSTRAINT fk_merchant_qr_codes_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_qr_codes_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_qr_codes_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_qr_codes_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Merchant-owned QR codes used by Design Studio and campaigns.';

CREATE TABLE IF NOT EXISTS merchant_qr_code_scans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  qr_code_id BIGINT UNSIGNED NOT NULL,
  public_id CHAR(36) NOT NULL,
  scanned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip_hash CHAR(64) NULL COMMENT 'HMAC hash only; raw IP is not stored.',
  user_agent_hash CHAR(64) NULL COMMENT 'HMAC hash only; raw UA is not stored.',
  referer_url VARCHAR(1000) NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_qr_code_scans_public_id (public_id),
  KEY idx_merchant_qr_code_scans_code_date (qr_code_id,scanned_at),
  CONSTRAINT fk_merchant_qr_code_scans_code FOREIGN KEY (qr_code_id) REFERENCES merchant_qr_codes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Privacy-preserving QR scan analytics.';

CREATE TABLE IF NOT EXISTS merchant_brand_kits (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL COMMENT 'Stable public UUID used by APIs.',
  workspace_id BIGINT UNSIGNED NOT NULL COMMENT 'Owning merchant workspace.',
  merchant_user_id BIGINT UNSIGNED NOT NULL COMMENT 'Merchant owner at time of creation.',
  name VARCHAR(180) NOT NULL,
  status ENUM('draft','active','archived') NOT NULL DEFAULT 'draft',
  source_url VARCHAR(1000) NULL COMMENT 'Website URL scanned or manually entered source.',
  logo_url VARCHAR(1000) NULL COMMENT 'Preferred candidate logo URL.',
  primary_color CHAR(7) NULL,
  secondary_color CHAR(7) NULL,
  accent_color CHAR(7) NULL,
  palette_json JSON NULL COMMENT 'Array of discovered/approved hex colors.',
  font_json JSON NULL COMMENT 'Future font selections and brand typography rules.',
  social_json JSON NULL COMMENT 'Detected or manually entered social profile links.',
  image_candidates_json JSON NULL COMMENT 'Website image candidates awaiting approval/import.',
  scan_result_json JSON NULL COMMENT 'Raw scanner result summary; no raw HTML stored.',
  scan_status ENUM('not_started','queued','scanned','failed','approved') NOT NULL DEFAULT 'not_started',
  scanned_at DATETIME NULL,
  approved_at DATETIME NULL,
  approved_by_user_id BIGINT UNSIGNED NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  archived_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_brand_kits_public_id (public_id),
  KEY idx_merchant_brand_kits_workspace (workspace_id,status,updated_at),
  KEY idx_merchant_brand_kits_scan_status (workspace_id,scan_status,scanned_at),
  CONSTRAINT fk_merchant_brand_kits_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_brand_kits_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_brand_kits_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_brand_kits_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_brand_kits_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Merchant brand kit sourced from profile data, manual edits, or website scanner.';

CREATE TABLE IF NOT EXISTS merchant_brand_kit_assets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  brand_kit_id BIGINT UNSIGNED NOT NULL,
  asset_role ENUM('logo','favicon','hero_image','product_image','social_image','background','other') NOT NULL DEFAULT 'other',
  source_url VARCHAR(1000) NOT NULL,
  status ENUM('candidate','approved','rejected','imported','archived') NOT NULL DEFAULT 'candidate',
  confidence_score DECIMAL(5,4) NULL COMMENT 'Optional scanner/import confidence from 0.0000 to 1.0000.',
  imported_design_asset_id BIGINT UNSIGNED NULL COMMENT 'Filled after candidate is imported into merchant_design_assets.',
  approved_at DATETIME NULL,
  approved_by_user_id BIGINT UNSIGNED NULL,
  rejected_at DATETIME NULL,
  rejected_by_user_id BIGINT UNSIGNED NULL,
  imported_at DATETIME NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_brand_kit_assets_public_id (public_id),
  UNIQUE KEY uq_merchant_brand_kit_assets_source (brand_kit_id,asset_role,source_url(255)),
  KEY idx_merchant_brand_kit_assets_kit (brand_kit_id,status,asset_role),
  KEY idx_merchant_brand_kit_assets_imported_asset (imported_design_asset_id),
  CONSTRAINT fk_merchant_brand_kit_assets_kit FOREIGN KEY (brand_kit_id) REFERENCES merchant_brand_kits(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_brand_kit_assets_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_brand_kit_assets_rejected_by FOREIGN KEY (rejected_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Logo/image candidates discovered for a merchant brand kit.';

CREATE TABLE IF NOT EXISTS merchant_design_templates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  workspace_id BIGINT UNSIGNED NULL COMMENT 'NULL for system/admin templates; set for merchant-scoped templates.',
  merchant_user_id BIGINT UNSIGNED NULL,
  brand_kit_id BIGINT UNSIGNED NULL,
  parent_template_id BIGINT UNSIGNED NULL COMMENT 'Immediate parent template for derived copies.',
  supersedes_template_id BIGINT UNSIGNED NULL COMMENT 'Previous published version replaced by this version.',
  template_family_key VARCHAR(120) NULL COMMENT 'Stable family/group key across versions.',
  template_scope ENUM('system','admin','merchant') NOT NULL DEFAULT 'merchant',
  template_type ENUM('print','social','digital') NOT NULL DEFAULT 'print',
  category_key VARCHAR(80) NULL,
  format_key VARCHAR(80) NOT NULL,
  version_number INT UNSIGNED NOT NULL DEFAULT 1,
  version_label VARCHAR(80) NULL COMMENT 'Human-readable version such as v1, holiday-v2, or merchant-copy-3.',
  version_notes VARCHAR(500) NULL,
  name VARCHAR(180) NOT NULL,
  description VARCHAR(500) NULL,
  status ENUM('draft','active','archived') NOT NULL DEFAULT 'draft',
  review_status ENUM('not_submitted','pending','approved','rejected','changes_requested') NOT NULL DEFAULT 'not_submitted',
  width_px INT UNSIGNED NULL,
  height_px INT UNSIGNED NULL,
  print_width_in DECIMAL(8,3) NULL,
  print_height_in DECIMAL(8,3) NULL,
  bleed_in DECIMAL(8,3) NULL,
  layout_json JSON NOT NULL,
  default_copy_json JSON NULL,
  render_config_json JSON NULL,
  qr_required TINYINT(1) NOT NULL DEFAULT 1,
  is_presigned TINYINT(1) NOT NULL DEFAULT 0,
  is_featured TINYINT(1) NOT NULL DEFAULT 0,
  is_locked TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Locked templates should only be edited by admin/design owners.',
  signature_hash CHAR(64) NULL,
  signed_at DATETIME NULL,
  submitted_at DATETIME NULL,
  approved_at DATETIME NULL,
  published_at DATETIME NULL,
  approved_by_user_id BIGINT UNSIGNED NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  archived_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_design_templates_public_id (public_id),
  UNIQUE KEY uq_merchant_design_templates_family_version (template_scope,template_family_key,version_number,workspace_id),
  KEY idx_merchant_design_templates_workspace (workspace_id,status,template_type,format_key),
  KEY idx_merchant_design_templates_scope (template_scope,status,review_status,template_type,format_key),
  KEY idx_merchant_design_templates_category (category_key,is_featured,status),
  KEY idx_merchant_design_templates_family (template_family_key,version_number,status),
  CONSTRAINT fk_merchant_design_templates_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_design_templates_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_templates_brand_kit FOREIGN KEY (brand_kit_id) REFERENCES merchant_brand_kits(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_templates_parent FOREIGN KEY (parent_template_id) REFERENCES merchant_design_templates(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_templates_supersedes FOREIGN KEY (supersedes_template_id) REFERENCES merchant_design_templates(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_templates_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_templates_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_templates_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Reusable Design Studio templates with version/family tracking.';

CREATE TABLE IF NOT EXISTS merchant_design_template_reviews (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  template_id BIGINT UNSIGNED NOT NULL,
  review_status ENUM('pending','approved','rejected','changes_requested') NOT NULL DEFAULT 'pending',
  reviewer_user_id BIGINT UNSIGNED NULL,
  notes TEXT NULL,
  checklist_json JSON NULL,
  reviewed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_design_template_reviews_public_id (public_id),
  KEY idx_merchant_design_template_reviews_template (template_id,review_status,created_at),
  CONSTRAINT fk_merchant_design_template_reviews_template FOREIGN KEY (template_id) REFERENCES merchant_design_templates(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_design_template_reviews_reviewer FOREIGN KEY (reviewer_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Admin/design review history for merchant and system templates.';

CREATE TABLE IF NOT EXISTS merchant_design_projects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  brand_kit_id BIGINT UNSIGNED NULL,
  template_id BIGINT UNSIGNED NULL,
  qr_code_id BIGINT UNSIGNED NULL,
  project_type ENUM('print','social','digital') NOT NULL DEFAULT 'print',
  format_key VARCHAR(80) NOT NULL,
  name VARCHAR(180) NOT NULL,
  status ENUM('draft','ready_for_review','approved','exported','archived') NOT NULL DEFAULT 'draft',
  revision_number INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Increment when project canvas changes.',
  source_template_version INT UNSIGNED NULL COMMENT 'Template version used when project was created/saved.',
  canvas_json JSON NOT NULL,
  copy_json JSON NULL,
  media_json JSON NULL,
  print_options_json JSON NULL,
  export_manifest_json JSON NULL,
  last_exported_at DATETIME NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  archived_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_design_projects_public_id (public_id),
  KEY idx_merchant_design_projects_workspace (workspace_id,status,project_type,format_key,updated_at),
  KEY idx_merchant_design_projects_merchant (merchant_user_id,status,updated_at),
  KEY idx_merchant_design_projects_template (template_id,source_template_version,status),
  CONSTRAINT fk_merchant_design_projects_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_design_projects_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_projects_brand_kit FOREIGN KEY (brand_kit_id) REFERENCES merchant_brand_kits(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_projects_template FOREIGN KEY (template_id) REFERENCES merchant_design_templates(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_projects_qr FOREIGN KEY (qr_code_id) REFERENCES merchant_qr_codes(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_projects_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_projects_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Merchant saved Design Studio canvases/projects.';

CREATE TABLE IF NOT EXISTS merchant_design_ai_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NULL,
  brand_kit_id BIGINT UNSIGNED NULL,
  provider_key VARCHAR(80) NULL COMMENT 'AI provider integration key.',
  model_key VARCHAR(120) NULL COMMENT 'Provider model identifier.',
  provider_request_id VARCHAR(180) NULL COMMENT 'External provider request/job id when available.',
  generation_type ENUM('image','copy','layout','variation') NOT NULL DEFAULT 'image',
  prompt_json JSON NOT NULL,
  status ENUM('draft','queued','running','needs_approval','completed','failed','canceled') NOT NULL DEFAULT 'draft',
  approval_status ENUM('not_required','pending','approved','rejected') NOT NULL DEFAULT 'pending',
  priority TINYINT UNSIGNED NOT NULL DEFAULT 5 COMMENT 'Lower value runs first; default is normal priority.',
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts INT UNSIGNED NOT NULL DEFAULT 3,
  locked_at DATETIME NULL COMMENT 'Worker lock timestamp.',
  locked_by VARCHAR(120) NULL COMMENT 'Worker id/process name that owns the lock.',
  next_attempt_at DATETIME NULL,
  last_attempt_at DATETIME NULL,
  failed_at DATETIME NULL,
  failure_code VARCHAR(80) NULL,
  worker_version VARCHAR(80) NULL,
  result_json JSON NULL,
  error_message VARCHAR(500) NULL,
  requested_by_user_id BIGINT UNSIGNED NOT NULL,
  approved_by_user_id BIGINT UNSIGNED NULL,
  output_asset_id BIGINT UNSIGNED NULL COMMENT 'Design asset created by this AI job; FK is intentionally deferred to avoid circular migration dependency.',
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_design_ai_jobs_public_id (public_id),
  KEY idx_merchant_design_ai_jobs_workspace (workspace_id,status,generation_type,created_at),
  KEY idx_merchant_design_ai_jobs_queue (status,priority,next_attempt_at,locked_at,created_at),
  KEY idx_merchant_design_ai_jobs_project (project_id,status,created_at),
  KEY idx_merchant_design_ai_jobs_provider (provider_key,provider_request_id),
  CONSTRAINT fk_merchant_design_ai_jobs_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_design_ai_jobs_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_ai_jobs_project FOREIGN KEY (project_id) REFERENCES merchant_design_projects(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_ai_jobs_brand_kit FOREIGN KEY (brand_kit_id) REFERENCES merchant_brand_kits(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_ai_jobs_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_ai_jobs_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Reliable queue for AI generated Design Studio assets and variations.';

CREATE TABLE IF NOT EXISTS merchant_design_ai_presets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  workspace_id BIGINT UNSIGNED NULL,
  template_scope ENUM('system','admin','merchant') NOT NULL DEFAULT 'system',
  preset_key VARCHAR(120) NOT NULL,
  name VARCHAR(180) NOT NULL,
  category_key VARCHAR(80) NULL,
  generation_type ENUM('image','copy','layout','variation') NOT NULL DEFAULT 'image',
  status ENUM('draft','active','archived') NOT NULL DEFAULT 'active',
  prompt_template_json JSON NOT NULL,
  safety_json JSON NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_design_ai_presets_public_id (public_id),
  UNIQUE KEY uq_merchant_design_ai_presets_public_scope_key (template_scope,preset_key,workspace_id),
  KEY idx_merchant_design_ai_presets_scope (template_scope,status,category_key,generation_type),
  CONSTRAINT fk_merchant_design_ai_presets_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_design_ai_presets_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_ai_presets_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Admin/system/merchant AI prompt presets for Design Studio.';

CREATE TABLE IF NOT EXISTS merchant_design_assets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  brand_kit_id BIGINT UNSIGNED NULL,
  project_id BIGINT UNSIGNED NULL,
  template_id BIGINT UNSIGNED NULL,
  qr_code_id BIGINT UNSIGNED NULL,
  ai_job_id BIGINT UNSIGNED NULL,
  parent_asset_id BIGINT UNSIGNED NULL COMMENT 'Parent asset for thumbnails, variants, crops, or regenerated outputs.',
  source_asset_id BIGINT UNSIGNED NULL COMMENT 'Original/source asset used to generate this asset.',
  asset_family_key VARCHAR(120) NULL COMMENT 'Stable grouping key across asset versions.',
  version_number INT UNSIGNED NOT NULL DEFAULT 1,
  asset_type ENUM('logo','image','ai_image','qr_svg','qr_png','proof_pdf','print_pdf','social_png','zip_package','thumbnail','other') NOT NULL DEFAULT 'other',
  name VARCHAR(180) NOT NULL,
  status ENUM('candidate','active','approved','archived','failed') NOT NULL DEFAULT 'active',
  lifecycle_status ENUM('draft','candidate','approved','generated','published','expired','archived','failed') NOT NULL DEFAULT 'draft',
  storage_driver ENUM('external_url','local','s3','generated','pending') NOT NULL DEFAULT 'pending',
  source_url VARCHAR(1000) NULL,
  storage_key VARCHAR(500) NULL,
  public_url VARCHAR(1000) NULL,
  original_filename VARCHAR(255) NULL,
  file_extension VARCHAR(20) NULL,
  mime_type VARCHAR(120) NULL,
  byte_size BIGINT UNSIGNED NULL,
  width_px INT UNSIGNED NULL,
  height_px INT UNSIGNED NULL,
  checksum CHAR(64) NULL,
  renderer_version VARCHAR(80) NULL,
  metadata_json JSON NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  approved_by_user_id BIGINT UNSIGNED NULL,
  generated_at DATETIME NULL,
  approved_at DATETIME NULL,
  published_at DATETIME NULL,
  expires_at DATETIME NULL,
  last_accessed_at DATETIME NULL,
  archived_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_design_assets_public_id (public_id),
  UNIQUE KEY uq_merchant_design_assets_family_version (workspace_id,asset_family_key,version_number),
  KEY idx_merchant_design_assets_workspace (workspace_id,status,asset_type,updated_at),
  KEY idx_merchant_design_assets_lifecycle (workspace_id,lifecycle_status,asset_type,updated_at),
  KEY idx_merchant_design_assets_project (project_id,status,asset_type),
  KEY idx_merchant_design_assets_family (asset_family_key,version_number,status),
  KEY idx_merchant_design_assets_parent (parent_asset_id),
  KEY idx_merchant_design_assets_source (source_asset_id),
  CONSTRAINT fk_merchant_design_assets_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_design_assets_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_assets_brand_kit FOREIGN KEY (brand_kit_id) REFERENCES merchant_brand_kits(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_project FOREIGN KEY (project_id) REFERENCES merchant_design_projects(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_template FOREIGN KEY (template_id) REFERENCES merchant_design_templates(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_qr FOREIGN KEY (qr_code_id) REFERENCES merchant_qr_codes(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_ai_job FOREIGN KEY (ai_job_id) REFERENCES merchant_design_ai_jobs(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_parent FOREIGN KEY (parent_asset_id) REFERENCES merchant_design_assets(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_source FOREIGN KEY (source_asset_id) REFERENCES merchant_design_assets(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_assets_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_assets_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Production and candidate assets generated/imported by Design Studio.';

CREATE TABLE IF NOT EXISTS merchant_design_export_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NULL,
  output_asset_id BIGINT UNSIGNED NULL,
  export_type ENUM('print_pdf','social_png','qr_svg','qr_png','zip_package','proof') NOT NULL DEFAULT 'proof',
  status ENUM('queued','running','completed','failed','canceled') NOT NULL DEFAULT 'queued',
  priority TINYINT UNSIGNED NOT NULL DEFAULT 5 COMMENT 'Lower value runs first; default is normal priority.',
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts INT UNSIGNED NOT NULL DEFAULT 3,
  locked_at DATETIME NULL,
  locked_by VARCHAR(120) NULL,
  next_attempt_at DATETIME NULL,
  last_attempt_at DATETIME NULL,
  failed_at DATETIME NULL,
  failure_code VARCHAR(80) NULL,
  renderer_version VARCHAR(80) NULL,
  options_json JSON NULL,
  manifest_json JSON NULL,
  error_message VARCHAR(500) NULL,
  requested_by_user_id BIGINT UNSIGNED NOT NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_design_export_jobs_public_id (public_id),
  KEY idx_merchant_design_export_jobs_workspace (workspace_id,status,export_type,created_at),
  KEY idx_merchant_design_export_jobs_queue (status,priority,next_attempt_at,locked_at,created_at),
  KEY idx_merchant_design_export_jobs_project (project_id,status,created_at),
  CONSTRAINT fk_merchant_design_export_jobs_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_design_export_jobs_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_export_jobs_project FOREIGN KEY (project_id) REFERENCES merchant_design_projects(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_export_jobs_output FOREIGN KEY (output_asset_id) REFERENCES merchant_design_assets(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_export_jobs_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Reliable renderer queue for proof, print, social, QR, and package exports.';

CREATE TABLE IF NOT EXISTS merchant_design_campaign_links (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NULL,
  template_id BIGINT UNSIGNED NULL,
  asset_id BIGINT UNSIGNED NULL,
  qr_code_id BIGINT UNSIGNED NULL,
  campaign_type ENUM('promotional_crm','newsletter','contest','landing_page','distribution','product','custom') NOT NULL DEFAULT 'custom',
  campaign_ref VARCHAR(180) NOT NULL,
  campaign_unique_hash CHAR(64) GENERATED ALWAYS AS (SHA2(CONCAT_WS('|',workspace_id,campaign_type,campaign_ref,IFNULL(project_id,0),IFNULL(template_id,0),IFNULL(asset_id,0),IFNULL(qr_code_id,0)),256)) STORED,
  label VARCHAR(180) NULL,
  metadata_json JSON NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_design_campaign_links_public_id (public_id),
  UNIQUE KEY uq_merchant_design_campaign_links_hash (campaign_unique_hash),
  KEY idx_merchant_design_campaign_links_workspace (workspace_id,campaign_type,campaign_ref),
  KEY idx_merchant_design_campaign_links_project (project_id,campaign_type,campaign_ref),
  KEY idx_merchant_design_campaign_links_asset (asset_id,campaign_type,campaign_ref),
  KEY idx_merchant_design_campaign_links_qr (qr_code_id,campaign_type,campaign_ref),
  CONSTRAINT fk_merchant_design_campaign_links_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_design_campaign_links_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_campaign_links_project FOREIGN KEY (project_id) REFERENCES merchant_design_projects(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_campaign_links_template FOREIGN KEY (template_id) REFERENCES merchant_design_templates(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_campaign_links_asset FOREIGN KEY (asset_id) REFERENCES merchant_design_assets(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_campaign_links_qr FOREIGN KEY (qr_code_id) REFERENCES merchant_qr_codes(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_campaign_links_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Links Design Studio outputs to promotional CRM, campaign, product, landing, and distribution records.';

INSERT IGNORE INTO permissions (slug,name,description,created_at) VALUES
('merchant.design_studio.view','View Design Studio','Open the merchant design studio workspace.',NOW()),
('merchant.design_studio.manage','Manage Design Studio','Create, edit, and export merchant design studio assets.',NOW()),
('merchant.brand_kits.view','View brand kits','View merchant brand kits and scanner results.',NOW()),
('merchant.brand_kits.manage','Manage brand kits','Scan websites and manage merchant brand kits.',NOW()),
('merchant.design_templates.view','View design templates','View saved print and social templates.',NOW()),
('merchant.design_templates.manage','Manage design templates','Create and update saved print and social templates.',NOW()),
('merchant.design_templates.admin','Administer design templates','Approve, publish, and feature system design templates.',NOW()),
('merchant.design_projects.view','View design projects','View saved Design Studio projects.',NOW()),
('merchant.design_projects.manage','Manage design projects','Save and update Design Studio projects.',NOW()),
('merchant.design_assets.view','View design assets','View exported and generated Design Studio assets.',NOW()),
('merchant.design_assets.manage','Manage design assets','Create design asset records and export jobs.',NOW()),
('merchant.design_ai.generate','Generate design assets with AI','Request AI-generated Design Studio images, copy, layouts, and variations.',NOW()),
('merchant.design_ai.admin','Administer design AI','Manage AI prompt presets and approve generated asset workflows.',NOW()),
('merchant.qr_library.view','View merchant QR library','View QR codes available to merchant design and campaign tools.',NOW()),
('merchant.qr_library.manage','Manage merchant QR library','Create, update, pause, and archive merchant QR codes.',NOW());

INSERT IGNORE INTO role_permissions (role_id,permission_id,created_at)
SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p
ON p.slug IN ('merchant.design_studio.view','merchant.design_studio.manage','merchant.brand_kits.view','merchant.brand_kits.manage','merchant.design_templates.view','merchant.design_templates.manage','merchant.design_projects.view','merchant.design_projects.manage','merchant.design_assets.view','merchant.design_assets.manage','merchant.design_ai.generate','merchant.qr_library.view','merchant.qr_library.manage')
WHERE r.slug IN ('merchant','admin','super_admin');

INSERT IGNORE INTO role_permissions (role_id,permission_id,created_at)
SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p
ON p.slug IN ('merchant.design_templates.admin','merchant.design_ai.admin')
WHERE r.slug IN ('admin','super_admin');

INSERT IGNORE INTO merchant_design_ai_presets (public_id,template_scope,preset_key,name,category_key,generation_type,status,prompt_template_json,safety_json,created_at,updated_at) VALUES
('90000000-0000-4000-8000-000000000191','system','restaurant-food-promo','Restaurant Food Promo','restaurant','image','active',JSON_OBJECT('prompt','Create a clean, appetizing promotional image for a local restaurant offer. Keep room for headline, CTA, and QR code.','negative','No alcohol focus, no medical claims, no fake coupons.'),JSON_OBJECT('requires_review',true),NOW(),NOW()),
('90000000-0000-4000-8000-000000000192','system','live-event-promo','Live Event Promo','event','image','active',JSON_OBJECT('prompt','Create an energetic local event promotional image with stage-light energy and clear negative space for QR and text.','negative','No copyrighted artist likenesses, no unsafe crowd scenes.'),JSON_OBJECT('requires_review',true),NOW(),NOW()),
('90000000-0000-4000-8000-000000000193','system','fitness-challenge','Fitness Challenge','fitness','image','active',JSON_OBJECT('prompt','Create a bright fitness challenge promotional image for a local gym or studio with motivational energy and space for CTA.','negative','No body-shaming, no medical transformation claims.'),JSON_OBJECT('requires_review',true),NOW(),NOW()),
('90000000-0000-4000-8000-000000000194','system','holiday-gift-card','Holiday Gift Card Promo','holiday','image','active',JSON_OBJECT('prompt','Create a warm seasonal gift-card promotional image for a local merchant with premium retail feel.','negative','Avoid religious specificity unless merchant provides it.'),JSON_OBJECT('requires_review',true),NOW(),NOW()),
('90000000-0000-4000-8000-000000000195','system','local-rewards-campaign','Local Rewards Campaign','rewards','image','active',JSON_OBJECT('prompt','Create a modern local rewards campaign image with community-commerce feel, branded space, CTA, and QR placement.','negative','No fake endorsements or misleading reward values.'),JSON_OBJECT('requires_review',true),NOW(),NOW());

INSERT INTO microgifter_schema_migrations (migration_key,migration_group,description,checksum,applied_at,created_at,updated_at)
VALUES ('stage_19_design_studio_qr_library','design_studio','Single-file Design Studio foundation migration: QR, brand kits, templates, projects, AI queue, assets, exports, campaign links, and permissions.',SHA2('stage_19_design_studio_qr_library',256),NOW(),NOW(),NOW())
ON DUPLICATE KEY UPDATE updated_at=NOW();
