-- Stage 20 Buy-In / Share Market SQL
-- Backs the Buy-In UI, approval queue, enrollment review, and series draft workflow.
-- Additive only: does not recreate core users, events, audit, commerce, gift, wallet, or ledger tables.

CREATE TABLE IF NOT EXISTS share_market_enrollments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  participant_user_id BIGINT UNSIGNED NOT NULL,
  participant_type ENUM('merchant','artist','band','creator','venue') NOT NULL DEFAULT 'merchant',
  legal_name VARCHAR(160) NOT NULL,
  public_name VARCHAR(160) NOT NULL,
  website VARCHAR(255) NULL,
  use_case TEXT NOT NULL,
  utility_plan TEXT NOT NULL,
  status ENUM('not_enrolled','interested','under_review','approved','active','paused','suspended','rejected','closed') NOT NULL DEFAULT 'under_review',
  optional_participation_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  admin_review_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approved_at DATETIME NULL,
  activated_at DATETIME NULL,
  rejected_at DATETIME NULL,
  paused_at DATETIME NULL,
  suspended_at DATETIME NULL,
  closed_at DATETIME NULL,
  reviewed_by_user_id BIGINT UNSIGNED NULL,
  review_note TEXT NULL,
  event_source_id BIGINT UNSIGNED NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_market_enrollments_public_id (public_id),
  UNIQUE KEY uq_share_market_enrollments_participant_user (participant_user_id),
  KEY idx_share_market_enrollments_status (status,submitted_at),
  KEY idx_share_market_enrollments_type_status (participant_type,status),
  KEY idx_share_market_enrollments_reviewed_by (reviewed_by_user_id),
  CONSTRAINT fk_share_market_enrollments_user FOREIGN KEY (participant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_share_market_enrollments_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_market_platform_pools (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  name VARCHAR(160) NOT NULL DEFAULT 'Microgifter Buy-In Master Pool',
  pool_type ENUM('master','reserve','retired') NOT NULL DEFAULT 'master',
  status ENUM('draft','active','paused','frozen','retired') NOT NULL DEFAULT 'draft',
  total_authorized BIGINT UNSIGNED NOT NULL DEFAULT 0,
  total_minted BIGINT UNSIGNED NOT NULL DEFAULT 0,
  total_burned BIGINT UNSIGNED NOT NULL DEFAULT 0,
  total_allocated BIGINT UNSIGNED NOT NULL DEFAULT 0,
  total_available BIGINT UNSIGNED NOT NULL DEFAULT 0,
  proof_hash CHAR(64) NULL,
  proof_hash_published_at DATETIME NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_market_platform_pools_public_id (public_id),
  KEY idx_share_market_platform_pools_type_status (pool_type,status),
  KEY idx_share_market_platform_pools_status (status),
  CONSTRAINT fk_share_market_platform_pools_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_market_credit_treasuries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  enrollment_id BIGINT UNSIGNED NOT NULL,
  participant_user_id BIGINT UNSIGNED NOT NULL,
  status ENUM('draft','active','paused','frozen','closed') NOT NULL DEFAULT 'draft',
  credits_allocated BIGINT UNSIGNED NOT NULL DEFAULT 0,
  credits_available BIGINT UNSIGNED NOT NULL DEFAULT 0,
  credits_assigned BIGINT UNSIGNED NOT NULL DEFAULT 0,
  credits_circulating BIGINT UNSIGNED NOT NULL DEFAULT 0,
  credits_redeemed BIGINT UNSIGNED NOT NULL DEFAULT 0,
  credits_burned BIGINT UNSIGNED NOT NULL DEFAULT 0,
  credits_frozen BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_market_credit_treasuries_public_id (public_id),
  UNIQUE KEY uq_share_market_credit_treasuries_enrollment (enrollment_id),
  KEY idx_share_market_credit_treasuries_user_status (participant_user_id,status),
  KEY idx_share_market_credit_treasuries_status (status),
  CONSTRAINT fk_share_market_credit_treasuries_enrollment FOREIGN KEY (enrollment_id) REFERENCES share_market_enrollments(id) ON DELETE RESTRICT,
  CONSTRAINT fk_share_market_credit_treasuries_user FOREIGN KEY (participant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_share_market_credit_treasuries_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dave_scores (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  target_type ENUM('profile','enrollment','series','merchant','artist','creator','venue') NOT NULL,
  target_public_id VARCHAR(120) NOT NULL,
  formula_version VARCHAR(120) NOT NULL,
  status ENUM('draft','active','locked','under_review','archived') NOT NULL DEFAULT 'active',
  attention_score DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  action_score DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  redemption_score DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  commerce_score DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  distribution_score DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  risk_adjustment DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  confidence_score DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  dave_score DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  calculated_from DATETIME NULL,
  calculated_to DATETIME NULL,
  locked_by_user_id BIGINT UNSIGNED NULL,
  locked_at DATETIME NULL,
  input_snapshot_json JSON NOT NULL,
  output_snapshot_json JSON NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_dave_scores_public_id (public_id),
  KEY idx_dave_scores_target_formula (target_type,target_public_id,formula_version,calculated_to),
  KEY idx_dave_scores_target_status (target_type,target_public_id,status),
  KEY idx_dave_scores_score (dave_score,confidence_score),
  CONSTRAINT fk_dave_scores_locked_by FOREIGN KEY (locked_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_market_series (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id VARCHAR(80) NOT NULL,
  enrollment_id BIGINT UNSIGNED NOT NULL,
  participant_user_id BIGINT UNSIGNED NOT NULL,
  treasury_id BIGINT UNSIGNED NULL,
  name VARCHAR(160) NOT NULL,
  description TEXT NOT NULL,
  state ENUM('draft','submitted','approved','live','paused','frozen','closed','rejected','changes_requested','archived') NOT NULL DEFAULT 'draft',
  supply BIGINT UNSIGNED NOT NULL,
  launch_price_cents BIGINT UNSIGNED NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  max_per_buyer BIGINT UNSIGNED NOT NULL DEFAULT 1,
  redemption_enabled TINYINT(1) NOT NULL DEFAULT 1,
  resale_enabled TINYINT(1) NOT NULL DEFAULT 0,
  reissue_milestone VARCHAR(300) NULL,
  submitted_at DATETIME NULL,
  approved_at DATETIME NULL,
  live_at DATETIME NULL,
  paused_at DATETIME NULL,
  closed_at DATETIME NULL,
  reviewed_by_user_id BIGINT UNSIGNED NULL,
  review_note TEXT NULL,
  dave_score_snapshot_id BIGINT UNSIGNED NULL,
  risk_snapshot_json JSON NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_market_series_public_id (public_id),
  KEY idx_share_market_series_enrollment_state (enrollment_id,state),
  KEY idx_share_market_series_participant_state (participant_user_id,state),
  KEY idx_share_market_series_state_updated (state,updated_at),
  KEY idx_share_market_series_reviewed_by (reviewed_by_user_id),
  CONSTRAINT fk_share_market_series_enrollment FOREIGN KEY (enrollment_id) REFERENCES share_market_enrollments(id) ON DELETE RESTRICT,
  CONSTRAINT fk_share_market_series_participant FOREIGN KEY (participant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_share_market_series_treasury FOREIGN KEY (treasury_id) REFERENCES share_market_credit_treasuries(id) ON DELETE SET NULL,
  CONSTRAINT fk_share_market_series_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_share_market_series_dave_score FOREIGN KEY (dave_score_snapshot_id) REFERENCES dave_scores(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_market_series_redemptions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  series_id BIGINT UNSIGNED NOT NULL,
  redemption_type ENUM('microgift_card','event_ticket','merch','vip_access','digital_download','custom_reward') NOT NULL,
  title VARCHAR(160) NOT NULL,
  details TEXT NOT NULL,
  share_cost BIGINT UNSIGNED NOT NULL,
  inventory_total BIGINT UNSIGNED NULL,
  inventory_remaining BIGINT UNSIGNED NULL,
  status ENUM('draft','submitted','approved','active','paused','retired','rejected') NOT NULL DEFAULT 'draft',
  staff_verification_required TINYINT(1) NOT NULL DEFAULT 0,
  expires_at DATETIME NULL,
  reviewed_by_user_id BIGINT UNSIGNED NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_market_series_redemptions_public_id (public_id),
  KEY idx_share_market_series_redemptions_series_status (series_id,status),
  KEY idx_share_market_series_redemptions_type_status (redemption_type,status),
  CONSTRAINT fk_share_market_series_redemptions_series FOREIGN KEY (series_id) REFERENCES share_market_series(id) ON DELETE CASCADE,
  CONSTRAINT fk_share_market_series_redemptions_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_market_approval_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  request_type ENUM('platform_pool','participant','treasury','series','holder_position','redemption','resale','dave_score','risk','proof_hash') NOT NULL,
  action_key VARCHAR(120) NOT NULL,
  event_type VARCHAR(160) NOT NULL,
  target_type VARCHAR(120) NOT NULL,
  target_public_id VARCHAR(120) NOT NULL,
  requester_user_id BIGINT UNSIGNED NOT NULL,
  status ENUM('awaiting_first_approval','awaiting_second_approval','approved','rejected','cancelled','expired','executed','failed') NOT NULL DEFAULT 'awaiting_first_approval',
  risk_level ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  required_approvals TINYINT UNSIGNED NOT NULL DEFAULT 1,
  approval_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
  expires_at DATETIME NULL,
  manifest_json JSON NOT NULL,
  projection_json JSON NULL,
  payload_hash CHAR(64) NOT NULL,
  previous_event_hash CHAR(64) NULL,
  execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  executed_at DATETIME NULL,
  executed_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_market_approval_requests_public_id (public_id),
  UNIQUE KEY uq_share_market_approval_requests_payload_hash (payload_hash),
  KEY idx_share_market_approval_requests_status (status,expires_at),
  KEY idx_share_market_approval_requests_target (target_type,target_public_id),
  KEY idx_share_market_approval_requests_requester (requester_user_id,status),
  CONSTRAINT fk_share_market_approval_requests_requester FOREIGN KEY (requester_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_share_market_approval_requests_executor FOREIGN KEY (executed_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_market_approval_decisions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  approval_request_id BIGINT UNSIGNED NOT NULL,
  actor_user_id BIGINT UNSIGNED NOT NULL,
  decision ENUM('approve','reject','cancel','escalate','request_freeze','record_expiry') NOT NULL,
  note TEXT NOT NULL,
  payload_hash CHAR(64) NOT NULL,
  previous_event_hash CHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_market_approval_decisions_public_id (public_id),
  UNIQUE KEY uq_share_market_approval_decisions_payload_hash (payload_hash),
  KEY idx_share_market_approval_decisions_request (approval_request_id,created_at),
  KEY idx_share_market_approval_decisions_actor (actor_user_id,created_at),
  CONSTRAINT fk_share_market_approval_decisions_request FOREIGN KEY (approval_request_id) REFERENCES share_market_approval_requests(id) ON DELETE CASCADE,
  CONSTRAINT fk_share_market_approval_decisions_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_market_credit_ledger (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  platform_pool_id BIGINT UNSIGNED NULL,
  treasury_id BIGINT UNSIGNED NULL,
  series_id BIGINT UNSIGNED NULL,
  approval_request_id BIGINT UNSIGNED NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(160) NOT NULL,
  entry_type ENUM('mint','burn','allocate','assign','release','freeze','unfreeze','redeem','reverse','adjust') NOT NULL,
  amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
  balance_after BIGINT UNSIGNED NULL,
  reason_code VARCHAR(120) NOT NULL,
  note TEXT NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  payload_json JSON NOT NULL,
  payload_hash CHAR(64) NOT NULL,
  previous_event_hash CHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_market_credit_ledger_public_id (public_id),
  UNIQUE KEY uq_share_market_credit_ledger_idempotency (idempotency_key),
  UNIQUE KEY uq_share_market_credit_ledger_payload_hash (payload_hash),
  KEY idx_share_market_credit_ledger_pool (platform_pool_id,created_at),
  KEY idx_share_market_credit_ledger_treasury (treasury_id,created_at),
  KEY idx_share_market_credit_ledger_series (series_id,created_at),
  KEY idx_share_market_credit_ledger_event (event_type,created_at),
  CONSTRAINT fk_share_market_credit_ledger_pool FOREIGN KEY (platform_pool_id) REFERENCES share_market_platform_pools(id) ON DELETE SET NULL,
  CONSTRAINT fk_share_market_credit_ledger_treasury FOREIGN KEY (treasury_id) REFERENCES share_market_credit_treasuries(id) ON DELETE SET NULL,
  CONSTRAINT fk_share_market_credit_ledger_series FOREIGN KEY (series_id) REFERENCES share_market_series(id) ON DELETE SET NULL,
  CONSTRAINT fk_share_market_credit_ledger_approval FOREIGN KEY (approval_request_id) REFERENCES share_market_approval_requests(id) ON DELETE SET NULL,
  CONSTRAINT fk_share_market_credit_ledger_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_market_holder_positions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  series_id BIGINT UNSIGNED NOT NULL,
  holder_user_id BIGINT UNSIGNED NOT NULL,
  status ENUM('active','listed','pending_transfer','pending_redemption','redeemed','burned','frozen','locked','reversed') NOT NULL DEFAULT 'active',
  shares_total BIGINT UNSIGNED NOT NULL DEFAULT 0,
  shares_available BIGINT UNSIGNED NOT NULL DEFAULT 0,
  shares_listed BIGINT UNSIGNED NOT NULL DEFAULT 0,
  shares_redeemed BIGINT UNSIGNED NOT NULL DEFAULT 0,
  shares_frozen BIGINT UNSIGNED NOT NULL DEFAULT 0,
  acquisition_source ENUM('primary','transfer','resale','reward','admin_adjustment') NOT NULL DEFAULT 'primary',
  last_activity_at DATETIME NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_market_holder_positions_public_id (public_id),
  UNIQUE KEY uq_share_market_holder_positions_series_holder (series_id,holder_user_id),
  KEY idx_share_market_holder_positions_holder_status (holder_user_id,status),
  KEY idx_share_market_holder_positions_series_status (series_id,status),
  CONSTRAINT fk_share_market_holder_positions_series FOREIGN KEY (series_id) REFERENCES share_market_series(id) ON DELETE RESTRICT,
  CONSTRAINT fk_share_market_holder_positions_holder FOREIGN KEY (holder_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_market_risk_flags (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  target_type ENUM('enrollment','series','holder_position','resale_listing','treasury','pool','dave_score','approval_request') NOT NULL,
  target_public_id VARCHAR(120) NOT NULL,
  severity ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  status ENUM('open','under_review','resolved','dismissed','escalated') NOT NULL DEFAULT 'open',
  reason_code VARCHAR(120) NOT NULL,
  summary VARCHAR(255) NOT NULL,
  details TEXT NULL,
  detected_by ENUM('system','admin','user_report','support','risk_rule') NOT NULL DEFAULT 'system',
  assigned_to_user_id BIGINT UNSIGNED NULL,
  resolved_by_user_id BIGINT UNSIGNED NULL,
  resolved_at DATETIME NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_market_risk_flags_public_id (public_id),
  KEY idx_share_market_risk_flags_target (target_type,target_public_id),
  KEY idx_share_market_risk_flags_status_severity (status,severity,created_at),
  KEY idx_share_market_risk_flags_assignee (assigned_to_user_id,status),
  CONSTRAINT fk_share_market_risk_flags_assignee FOREIGN KEY (assigned_to_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_share_market_risk_flags_resolver FOREIGN KEY (resolved_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_market_resale_listings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  holder_position_id BIGINT UNSIGNED NOT NULL,
  series_id BIGINT UNSIGNED NOT NULL,
  seller_user_id BIGINT UNSIGNED NOT NULL,
  status ENUM('draft','active','paused','cancelled','filled','expired','frozen','rejected') NOT NULL DEFAULT 'draft',
  shares_listed BIGINT UNSIGNED NOT NULL,
  price_per_share_cents BIGINT UNSIGNED NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  platform_fee_bps INT UNSIGNED NOT NULL DEFAULT 0,
  hold_settlement_until DATETIME NULL,
  expires_at DATETIME NULL,
  risk_flag_id BIGINT UNSIGNED NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_market_resale_listings_public_id (public_id),
  KEY idx_share_market_resale_listings_series_status (series_id,status,price_per_share_cents),
  KEY idx_share_market_resale_listings_seller_status (seller_user_id,status),
  KEY idx_share_market_resale_listings_position (holder_position_id,status),
  CONSTRAINT fk_share_market_resale_listings_position FOREIGN KEY (holder_position_id) REFERENCES share_market_holder_positions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_share_market_resale_listings_series FOREIGN KEY (series_id) REFERENCES share_market_series(id) ON DELETE RESTRICT,
  CONSTRAINT fk_share_market_resale_listings_seller FOREIGN KEY (seller_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_share_market_resale_listings_risk_flag FOREIGN KEY (risk_flag_id) REFERENCES share_market_risk_flags(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dave_score_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  dave_score_id BIGINT UNSIGNED NOT NULL,
  event_type ENUM('calculated','recalculated','locked','unlocked','risk_flagged','manual_note') NOT NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  reason_code VARCHAR(120) NULL,
  note TEXT NULL,
  payload_json JSON NOT NULL,
  payload_hash CHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_dave_score_events_public_id (public_id),
  UNIQUE KEY uq_dave_score_events_payload_hash (payload_hash),
  KEY idx_dave_score_events_score_created (dave_score_id,created_at),
  KEY idx_dave_score_events_type (event_type,created_at),
  CONSTRAINT fk_dave_score_events_score FOREIGN KEY (dave_score_id) REFERENCES dave_scores(id) ON DELETE CASCADE,
  CONSTRAINT fk_dave_score_events_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_market_admin_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(160) NOT NULL,
  target_type VARCHAR(120) NOT NULL,
  target_public_id VARCHAR(120) NOT NULL,
  old_state VARCHAR(80) NULL,
  new_state VARCHAR(80) NULL,
  amount BIGINT UNSIGNED NULL,
  reason_code VARCHAR(120) NULL,
  note TEXT NULL,
  ip_address VARCHAR(64) NULL,
  user_agent VARCHAR(255) NULL,
  previous_event_hash CHAR(64) NULL,
  payload_hash CHAR(64) NOT NULL,
  payload_json JSON NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_market_admin_events_public_id (public_id),
  UNIQUE KEY uq_share_market_admin_events_payload_hash (payload_hash),
  KEY idx_share_market_admin_events_target (target_type,target_public_id,created_at),
  KEY idx_share_market_admin_events_actor (actor_user_id,created_at),
  KEY idx_share_market_admin_events_type (event_type,created_at),
  CONSTRAINT fk_share_market_admin_events_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_market_hash_chain_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  chain_key VARCHAR(120) NOT NULL,
  source_table VARCHAR(120) NOT NULL,
  source_public_id VARCHAR(120) NOT NULL,
  previous_hash CHAR(64) NULL,
  payload_hash CHAR(64) NOT NULL,
  merkle_root_hash CHAR(64) NULL,
  checkpoint_status ENUM('prepared','published','failed','superseded') NOT NULL DEFAULT 'prepared',
  published_at DATETIME NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_market_hash_chain_events_public_id (public_id),
  UNIQUE KEY uq_share_market_hash_chain_source (source_table,source_public_id),
  KEY idx_share_market_hash_chain_key_created (chain_key,created_at),
  KEY idx_share_market_hash_chain_status (checkpoint_status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS share_market_series_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  series_id BIGINT UNSIGNED NOT NULL,
  snapshot_date DATE NOT NULL,
  holder_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  circulating_shares BIGINT UNSIGNED NOT NULL DEFAULT 0,
  listed_shares BIGINT UNSIGNED NOT NULL DEFAULT 0,
  redeemed_shares BIGINT UNSIGNED NOT NULL DEFAULT 0,
  average_listing_price_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  redemption_utility_value_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  dave_score DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  risk_score DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  snapshot_json JSON NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_share_market_series_snapshots_public_id (public_id),
  UNIQUE KEY uq_share_market_series_snapshot_day (series_id,snapshot_date),
  KEY idx_share_market_series_snapshots_date (snapshot_date),
  KEY idx_share_market_series_snapshots_score (dave_score,risk_score),
  CONSTRAINT fk_share_market_series_snapshots_series FOREIGN KEY (series_id) REFERENCES share_market_series(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO permissions (slug,name,created_at) VALUES
('share_market.admin','Manage Buy-In Share Market',NOW()),
('share_market.participate','Participate in Buy-In Share Market',NOW()),
('share_market.review','Review Buy-In Share Market',NOW());

INSERT IGNORE INTO role_permissions (role_id,permission_id,created_at)
SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p ON p.slug IN ('share_market.admin','share_market.review')
WHERE r.slug IN ('admin','super_admin');

INSERT IGNORE INTO role_permissions (role_id,permission_id,created_at)
SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p ON p.slug='share_market.participate'
WHERE r.slug IN ('merchant','creator','admin','super_admin');

INSERT INTO schema_migrations (migration_key,description,checksum,applied_at)
VALUES ('stage_20_buy_in_share_market','Buy-In Share Market tables for enrollment, series, approvals, treasury, ledger, holders, resale, risk, DAVE scores, and hash-chain audit.',NULL,NOW())
ON DUPLICATE KEY UPDATE description=VALUES(description);
