-- Stage 19 Design Studio, QR Library, Saved Templates, and Future AI Generation Foundation
-- Adds merchant-owned QR destinations, reusable design templates, saved studio projects, and AI generation job records.

CREATE TABLE IF NOT EXISTS merchant_qr_codes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  label VARCHAR(180) NOT NULL,
  qr_type ENUM('claim','lead','campaign','storefront','product','custom') NOT NULL DEFAULT 'claim',
  status ENUM('draft','active','paused','archived') NOT NULL DEFAULT 'draft',
  short_code VARCHAR(80) NOT NULL,
  destination_url VARCHAR(1000) NOT NULL,
  qr_payload_url VARCHAR(1000) NOT NULL,
  campaign_ref VARCHAR(160) NULL,
  product_ref VARCHAR(160) NULL,
  scan_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  last_scanned_at DATETIME NULL,
  metadata_json JSON NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  archived_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_qr_codes_public_id (public_id),
  UNIQUE KEY uq_merchant_qr_codes_short_code (short_code),
  KEY idx_merchant_qr_codes_workspace_status (workspace_id,status,qr_type),
  KEY idx_merchant_qr_codes_merchant_status (merchant_user_id,status,updated_at),
  CONSTRAINT fk_merchant_qr_codes_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_qr_codes_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_qr_codes_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_qr_codes_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS merchant_qr_code_scans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  qr_code_id BIGINT UNSIGNED NOT NULL,
  public_id CHAR(36) NOT NULL,
  scanned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip_hash CHAR(64) NULL,
  user_agent_hash CHAR(64) NULL,
  referer_url VARCHAR(1000) NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_qr_code_scans_public_id (public_id),
  KEY idx_merchant_qr_code_scans_code_date (qr_code_id,scanned_at),
  CONSTRAINT fk_merchant_qr_code_scans_code FOREIGN KEY (qr_code_id) REFERENCES merchant_qr_codes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS merchant_design_templates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  workspace_id BIGINT UNSIGNED NULL,
  merchant_user_id BIGINT UNSIGNED NULL,
  template_scope ENUM('system','admin','merchant') NOT NULL DEFAULT 'merchant',
  template_type ENUM('print','social','digital') NOT NULL DEFAULT 'print',
  format_key VARCHAR(80) NOT NULL,
  name VARCHAR(180) NOT NULL,
  description VARCHAR(500) NULL,
  status ENUM('draft','active','archived') NOT NULL DEFAULT 'draft',
  width_px INT UNSIGNED NULL,
  height_px INT UNSIGNED NULL,
  print_width_in DECIMAL(8,3) NULL,
  print_height_in DECIMAL(8,3) NULL,
  bleed_in DECIMAL(8,3) NULL,
  layout_json JSON NOT NULL,
  default_copy_json JSON NULL,
  render_config_json JSON NULL,
  qr_required TINYINT(1) NOT NULL DEFAULT 1,
  is_presigned TINYINT(1) NOT NULL DEFAULT 0,
  signature_hash CHAR(64) NULL,
  signed_at DATETIME NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  archived_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_design_templates_public_id (public_id),
  KEY idx_merchant_design_templates_workspace (workspace_id,status,template_type,format_key),
  KEY idx_merchant_design_templates_scope (template_scope,status,template_type,format_key),
  CONSTRAINT fk_merchant_design_templates_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_design_templates_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_templates_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_templates_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS merchant_design_projects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  template_id BIGINT UNSIGNED NULL,
  qr_code_id BIGINT UNSIGNED NULL,
  project_type ENUM('print','social','digital') NOT NULL DEFAULT 'print',
  format_key VARCHAR(80) NOT NULL,
  name VARCHAR(180) NOT NULL,
  status ENUM('draft','ready_for_review','approved','exported','archived') NOT NULL DEFAULT 'draft',
  canvas_json JSON NOT NULL,
  copy_json JSON NULL,
  media_json JSON NULL,
  print_options_json JSON NULL,
  export_manifest_json JSON NULL,
  last_exported_at DATETIME NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  archived_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_design_projects_public_id (public_id),
  KEY idx_merchant_design_projects_workspace (workspace_id,status,project_type,format_key,updated_at),
  KEY idx_merchant_design_projects_merchant (merchant_user_id,status,updated_at),
  CONSTRAINT fk_merchant_design_projects_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_design_projects_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_projects_template FOREIGN KEY (template_id) REFERENCES merchant_design_templates(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_projects_qr FOREIGN KEY (qr_code_id) REFERENCES merchant_qr_codes(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_projects_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_projects_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS merchant_design_ai_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  workspace_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NULL,
  provider_key VARCHAR(80) NULL,
  model_key VARCHAR(120) NULL,
  generation_type ENUM('image','copy','layout','variation') NOT NULL DEFAULT 'image',
  prompt_json JSON NOT NULL,
  status ENUM('draft','queued','running','needs_approval','completed','failed','canceled') NOT NULL DEFAULT 'draft',
  approval_status ENUM('not_required','pending','approved','rejected') NOT NULL DEFAULT 'pending',
  result_json JSON NULL,
  error_message VARCHAR(500) NULL,
  requested_by_user_id BIGINT UNSIGNED NOT NULL,
  approved_by_user_id BIGINT UNSIGNED NULL,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_design_ai_jobs_public_id (public_id),
  KEY idx_merchant_design_ai_jobs_workspace (workspace_id,status,generation_type,created_at),
  KEY idx_merchant_design_ai_jobs_project (project_id,status,created_at),
  CONSTRAINT fk_merchant_design_ai_jobs_workspace FOREIGN KEY (workspace_id) REFERENCES merchant_workspaces(id) ON DELETE CASCADE,
  CONSTRAINT fk_merchant_design_ai_jobs_merchant_user FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_ai_jobs_project FOREIGN KEY (project_id) REFERENCES merchant_design_projects(id) ON DELETE SET NULL,
  CONSTRAINT fk_merchant_design_ai_jobs_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_design_ai_jobs_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO permissions (slug,name,description,created_at) VALUES
('merchant.design_studio.view','View Design Studio','Open the merchant design studio workspace.',NOW()),
('merchant.design_studio.manage','Manage Design Studio','Create, edit, and export merchant design studio assets.',NOW()),
('merchant.design_templates.view','View design templates','View saved print and social templates.',NOW()),
('merchant.design_templates.manage','Manage design templates','Create and update saved print and social templates.',NOW()),
('merchant.design_projects.view','View design projects','View saved Design Studio projects.',NOW()),
('merchant.design_projects.manage','Manage design projects','Save and update Design Studio projects.',NOW()),
('merchant.design_ai.generate','Generate design assets with AI','Request AI-generated Design Studio images, copy, layouts, and variations.',NOW()),
('merchant.qr_library.view','View merchant QR library','View QR codes available to merchant design and campaign tools.',NOW()),
('merchant.qr_library.manage','Manage merchant QR library','Create, update, pause, and archive merchant QR codes.',NOW());

INSERT IGNORE INTO role_permissions (role_id,permission_id,created_at)
SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p
ON p.slug IN ('merchant.design_studio.view','merchant.design_studio.manage','merchant.design_templates.view','merchant.design_templates.manage','merchant.design_projects.view','merchant.design_projects.manage','merchant.design_ai.generate','merchant.qr_library.view','merchant.qr_library.manage')
WHERE r.slug IN ('merchant','admin','super_admin');
