-- DEPRECATED: Wallet and Redemption Experience v1
--
-- Do not import this file.
--
-- Microgifter reward records in wallet_items are an internal staging layer.
-- Customer ownership is created through the canonical flow:
--
--   wallet_items -> Microgift instance -> PPPM item -> Action Center Inbox
--
-- Standalone wallet claim tokens and wallet-specific support cases are not
-- part of the production authority model. This file intentionally performs
-- no schema changes and remains only as a compatibility tombstone for older
-- deployment checklists that referenced its filename.
