<?php
declare(strict_types=1);

function mg_campaign_followup_uuid(): string { $b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4)); }
function mg_campaign_followup_delay(string $preset,int $customMinutes=0): int { return match($preset){'1_hour'=>3600,'6_hours'=>21600,'1_day'=>86400,'15_days'=>1296000,'custom'=>max(60,$customMinutes*60),default=>3600}; }
function mg_campaign_followup_install(PDO $pdo): void
{
 $pdo->exec("CREATE TABLE IF NOT EXISTS campaign_followup_rules (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(36) NOT NULL,merchant_user_id BIGINT UNSIGNED NOT NULL,campaign_id BIGINT UNSIGNED NOT NULL,name VARCHAR(160) NOT NULL,trigger_event VARCHAR(90) NOT NULL,delay_preset ENUM('1_hour','6_hours','1_day','15_days','custom') NOT NULL DEFAULT '1_hour',custom_delay_minutes INT UNSIGNED NULL,delay_seconds INT UNSIGNED NOT NULL DEFAULT 3600,channel ENUM('email','microgifter_message','both') NOT NULL DEFAULT 'email',message_mode ENUM('automatic','custom') NOT NULL DEFAULT 'automatic',subject VARCHAR(180) NULL,body TEXT NULL,status ENUM('active','paused','archived') NOT NULL DEFAULT 'active',metadata_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_campaign_followup_rules_public_id(public_id),KEY idx_campaign_followup_rules_campaign(campaign_id,status,trigger_event),CONSTRAINT fk_campaign_followup_rules_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,CONSTRAINT fk_campaign_followup_rules_merchant FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS campaign_followup_jobs (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(36) NOT NULL,dedupe_key VARCHAR(190) NOT NULL,rule_id BIGINT UNSIGNED NOT NULL,merchant_user_id BIGINT UNSIGNED NOT NULL,campaign_id BIGINT UNSIGNED NOT NULL,contact_id BIGINT UNSIGNED NULL,wallet_item_id BIGINT UNSIGNED NULL,trigger_event VARCHAR(90) NOT NULL,status ENUM('queued','processing','sent','skipped','failed','cancelled') NOT NULL DEFAULT 'queued',due_at DATETIME NOT NULL,payload_json JSON NULL,attempt_count INT UNSIGNED NOT NULL DEFAULT 0,last_error VARCHAR(500) NULL,sent_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_campaign_followup_jobs_public_id(public_id),UNIQUE KEY uq_campaign_followup_jobs_dedupe(dedupe_key),KEY idx_campaign_followup_jobs_due(status,due_at),KEY idx_campaign_followup_jobs_campaign(campaign_id,status,due_at),CONSTRAINT fk_campaign_followup_jobs_rule FOREIGN KEY (rule_id) REFERENCES campaign_followup_rules(id) ON DELETE CASCADE,CONSTRAINT fk_campaign_followup_jobs_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,CONSTRAINT fk_campaign_followup_jobs_contact FOREIGN KEY (contact_id) REFERENCES campaign_contacts(id) ON DELETE SET NULL,CONSTRAINT fk_campaign_followup_jobs_wallet FOREIGN KEY (wallet_item_id) REFERENCES wallet_items(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 try{$pdo->exec("ALTER TABLE campaign_followup_jobs ADD COLUMN dedupe_key VARCHAR(190) NOT NULL DEFAULT '' AFTER public_id");}catch(Throwable){}
 try{$pdo->exec("ALTER TABLE campaign_followup_jobs ADD UNIQUE KEY uq_campaign_followup_jobs_dedupe(dedupe_key)");}catch(Throwable){}
}
function mg_campaign_followup_schedule(PDO $pdo,array $input): array
{
 $merchantId=(int)($input['merchant_user_id']??0);$campaignId=(int)($input['campaign_id']??0);$contactId=isset($input['contact_id'])?(int)$input['contact_id']:null;$walletId=isset($input['wallet_item_id'])?(int)$input['wallet_item_id']:null;$trigger=trim((string)($input['trigger_event']??''));
 if($merchantId<1||$campaignId<1||$trigger==='')return ['scheduled'=>0,'skipped'=>true];
 try{if(!$pdo->inTransaction())mg_campaign_followup_install($pdo);$rules=$pdo->prepare("SELECT * FROM campaign_followup_rules WHERE merchant_user_id=? AND campaign_id=? AND trigger_event=? AND status='active'");$rules->execute([$merchantId,$campaignId,$trigger]);$rows=$rules->fetchAll(PDO::FETCH_ASSOC);$count=0;
  foreach($rows as $rule){$due=date('Y-m-d H:i:s',time()+(int)$rule['delay_seconds']);$dedupe='rule:'.$rule['public_id'].':contact:'.($contactId?:0).':wallet:'.($walletId?:0).':event:'.$trigger;$payload=['trigger_event'=>$trigger,'context'=>$input['context']??[],'rule_id'=>(string)$rule['public_id'],'message_mode'=>(string)$rule['message_mode'],'channel'=>(string)$rule['channel']];$stmt=$pdo->prepare("INSERT IGNORE INTO campaign_followup_jobs (public_id,dedupe_key,rule_id,merchant_user_id,campaign_id,contact_id,wallet_item_id,trigger_event,status,due_at,payload_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?, 'queued',?,?,NOW(),NOW())");$stmt->execute([mg_campaign_followup_uuid(),$dedupe,(int)$rule['id'],$merchantId,$campaignId,$contactId,$walletId,$trigger,$due,json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);$count+=$stmt->rowCount()>0?1:0;}
  return ['scheduled'=>$count,'rules'=>count($rows)];
 }catch(Throwable $e){mg_security_log('warning','campaign.followup_schedule_failed','Campaign follow-up scheduling failed.',['exception_class'=>$e::class,'message'=>$e->getMessage(),'campaign_id'=>$campaignId,'trigger_event'=>$trigger],$merchantId);return ['scheduled'=>0,'schema_ready'=>false];}
}
