<?php
declare(strict_types=1);

require_once dirname(__DIR__, 2) . '/bootstrap.php';
require_once dirname(__DIR__, 2) . '/rewards/_zero_value_bridge.php';
require_once dirname(__DIR__, 3) . '/includes/merchant-crm.php';
require_once __DIR__ . '/_limits.php';
require_once __DIR__ . '/_participation_policy.php';

function mg_media_reward_uuid_v2(): string { $b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4)); }
function mg_media_reward_rules_v2(mixed $json): array { $d=is_string($json)&&trim($json)!==''?json_decode($json,true):null;return is_array($d)?$d:[]; }
function mg_media_reward_expiry_v2(array $template): ?string { $rule=(string)($template['expiration_rule']??'none');if(($rule==='fixed_date'||$rule==='event_date')&&!empty($template['expires_at']))return(string)$template['expires_at'];if($rule==='after_issue'&&!empty($template['expiration_days']))return date('Y-m-d H:i:s',time()+((int)$template['expiration_days']*86400));return null; }
function mg_media_reward_image_v2(array $template): string { $m=is_string($template['metadata_json']??null)&&trim((string)$template['metadata_json'])!==''?json_decode((string)$template['metadata_json'],true):null;if(!is_array($m))return'';$p=is_array($m['media_pack']??null)?$m['media_pack']:[];return trim((string)($m['reward_image_url']??$p['cover_image_url']??'')); }
function mg_media_reward_event_v2(PDO $pdo,array $campaign,?int $walletId,?int $contactId,string $type,array $context): void { $s=$pdo->prepare('INSERT INTO campaign_events (public_id,merchant_user_id,campaign_id,wallet_item_id,contact_id,event_type,event_context_json,created_at) VALUES (?,?,?,?,?,?,?,NOW())');$s->execute([mg_media_reward_uuid_v2(),(int)$campaign['merchant_user_id'],(int)$campaign['id'],$walletId,$contactId,$type,json_encode($context,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]); }
function mg_media_reward_milestones_v2(array $rules,string $noun): array { $rows=is_array($rules['milestones']??null)?$rules['milestones']:[];if(!$rows)$rows=[['percent'=>max(1,min(100,(int)($rules['required_percent']??80))),'reward_template_id'=>'','label'=>'Completion gift']];$out=[];foreach($rows as $r){if(!is_array($r))continue;$p=max(1,min(100,(int)($r['percent']??0)));$out[$p]=['percent'=>$p,'reward_template_id'=>strtolower(trim((string)($r['reward_template_id']??''))),'label'=>trim((string)($r['label']??''))?:($p.'% '.$noun)];}ksort($out);return array_values($out); }
function mg_media_reward_template_v2(PDO $pdo,int $merchantId,int $fallbackId,string $publicId): array { if($publicId!==''&&strlen($publicId)===36&&preg_match('/^[a-f0-9-]{36}$/',$publicId)===1){$s=$pdo->prepare("SELECT * FROM reward_templates WHERE public_id=? AND merchant_user_id=? AND status='active' LIMIT 1 FOR UPDATE");$s->execute([$publicId,$merchantId]);$t=$s->fetch(PDO::FETCH_ASSOC);if($t)return$t;} $s=$pdo->prepare("SELECT * FROM reward_templates WHERE id=? AND merchant_user_id=? AND status='active' LIMIT 1 FOR UPDATE");$s->execute([$fallbackId,$merchantId]);$t=$s->fetch(PDO::FETCH_ASSOC);if(!$t)mg_fail('Milestone reward is unavailable.',409);return$t; }
function mg_media_reward_already_v2(PDO $pdo,int $campaignId,int $contactId,int $percent,string $source): bool { $s=$pdo->prepare("SELECT id FROM wallet_items WHERE campaign_id=? AND contact_id=? AND source_type=? AND JSON_UNQUOTE(JSON_EXTRACT(metadata_json,'$.milestone_percent'))=? AND status<>'cancelled' LIMIT 1");$s->execute([$campaignId,$contactId,$source,(string)$percent]);return(bool)$s->fetchColumn(); }
function mg_media_reward_issue_v2(PDO $pdo,array $campaign,array $contact,?int $userId,array $template,int $percent,float $progress,array $context,string $source,string $noun): array
{
    if($template['quantity_limit']!==null&&(int)$template['issued_count']>=(int)$template['quantity_limit'])mg_fail('A milestone reward has reached its inventory limit.',409);
    $walletPublicId=mg_media_reward_uuid_v2();$expiresAt=mg_media_reward_expiry_v2($template);$image=mg_media_reward_image_v2($template);
    $stamp=mg_public_campaign_debit_reward_stamp($pdo,$campaign+['reward_template_public_id'=>(string)$template['public_id']],$walletPublicId,$source,['contact_id'=>(string)$contact['public_id'],'milestone_percent'=>$percent,'progress_percent'=>$progress,'reward_image_url'=>$image]+$context);
    $metadata=['campaign_type'=>$source,'reward_template_id'=>(string)$template['public_id'],'milestone_percent'=>$percent,'progress_percent'=>$progress,'reward_image_url'=>$image,'stamp_ledger_entry_id'=>$stamp['entry']['entry_id']??null,'pppm_destination'=>'inbox']+$context;
    $s=$pdo->prepare('INSERT INTO wallet_items (public_id,user_id,contact_id,merchant_user_id,reward_template_id,campaign_id,source_type,source_id,status,value_cents_snapshot,currency_snapshot,title_snapshot,metadata_json,issued_at,expires_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),?,NOW(),NOW())');
    $s->execute([$walletPublicId,$userId,(int)$contact['id'],(int)$campaign['merchant_user_id'],(int)$template['id'],(int)$campaign['id'],$source,(string)$contact['public_id'],'issued',(int)($template['value_amount_cents']??0),(string)($template['currency']??'USD'),(string)$template['title'],json_encode($metadata,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),$expiresAt]);
    $walletDbId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE campaigns SET issued_count=issued_count+1, updated_at=NOW() WHERE id=?')->execute([(int)$campaign['id']]);$pdo->prepare('UPDATE reward_templates SET issued_count=issued_count+1, updated_at=NOW() WHERE id=?')->execute([(int)$template['id']]);
    $bridge=null;if($userId){$bridge=mg_zero_reward_issue_from_wallet($pdo,['merchant_user_id'=>(int)$campaign['merchant_user_id'],'recipient_user_id'=>$userId,'wallet_item_db_id'=>$walletDbId,'wallet_item_public_id'=>$walletPublicId,'campaign_public_id'=>(string)$campaign['public_id'],'reward_template_public_id'=>(string)$template['public_id'],'source_type'=>$source,'source_reference'=>$walletPublicId,'title'=>(string)$template['title'],'description'=>$template['description']??$campaign['description']??null,'expires_at'=>$expiresAt,'terms'=>['campaign_type'=>$source,'milestone_percent'=>$percent,'reward_image_url'=>$image]]);}
    mg_media_reward_event_v2($pdo,$campaign,$walletDbId,(int)$contact['id'],$source.'.issued',$metadata+['pppm_bridge'=>$bridge]);
    return ['wallet_item_id'=>$walletPublicId,'reward_title'=>(string)$template['title'],'reward_image_url'=>$image,'percent'=>$percent,'expires_at'=>$expiresAt,'pppm_bridge'=>$bridge,'pppm_destination'=>'inbox','inbox_url'=>'/inbox.php'];
}
function mg_media_reward_progress_v2(string $campaignType,array $config): void
{
    mg_require_method('POST');$input=mg_input();$pdo=mg_db();$ref=strtolower(trim((string)($input['campaign_id']??$input['campaign']??'')));$email=strtolower(trim((string)($input['email']??'')));$name=trim((string)($input['name']??''));$phone=trim((string)($input['phone']??''));$progress=max(0,min(100,(float)($input['progress_percent']??0)));
    if($ref===''||$email===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||mb_strlen($email)>255||mb_strlen($name)>180||mb_strlen($phone)>60)mg_fail('Invalid reward progress.',422);
    try{$pdo->beginTransaction();$s=$pdo->prepare("SELECT c.*, rt.id reward_template_db_id, rt.public_id reward_template_public_id FROM campaigns c INNER JOIN reward_templates rt ON rt.id=c.reward_template_id WHERE c.status='active' AND c.campaign_type=? AND (c.public_id=? OR c.public_slug=?) LIMIT 1 FOR UPDATE");$s->execute([$campaignType,$ref,$ref]);$campaign=$s->fetch(PDO::FETCH_ASSOC);if(!$campaign){$pdo->rollBack();mg_fail('Campaign is not available.',404);} $rules=mg_media_reward_rules_v2($campaign['rules_json']??null);
        $providerField=$config['provider_field'];$postedProvider=strtolower(trim((string)($input[$config['input_provider']]??$config['default_provider'])));$expectedProvider=(string)($rules[$providerField]??$config['default_provider']);if(!in_array($expectedProvider,$config['providers'],true))$expectedProvider=$config['default_provider'];if($postedProvider!==$expectedProvider){$pdo->rollBack();mg_fail('Media source does not match this campaign.',422);}
        foreach(($config['match']??[]) as $ruleKey=>$inputKey){$expected=trim((string)($rules[$ruleKey]??''));$actual=trim((string)($input[$inputKey]??''));if($expected!==''&&$actual!==''&&$expected!==$actual){$pdo->rollBack();mg_fail('Media item does not match this campaign.',422);}}
        $now=time();if(!empty($campaign['starts_at'])&&strtotime((string)$campaign['starts_at'])>$now){$pdo->rollBack();mg_fail('Campaign has not started yet.',409);}if(!empty($campaign['ends_at'])&&strtotime((string)$campaign['ends_at'])<$now){$pdo->rollBack();mg_fail('Campaign has ended.',409);}if($campaign['quantity_limit']!==null&&(int)$campaign['issued_count']>=(int)$campaign['quantity_limit']){$pdo->rollBack();mg_fail('Campaign reward limit has been reached.',409);}
        $merchantId=(int)$campaign['merchant_user_id'];$campaignId=(int)$campaign['id'];$policy=mg_public_campaign_policy_resolve($pdo,$rules,$campaignType,$email);$userId=$policy['user_id']===null?null:(int)$policy['user_id'];if(mg_public_campaign_limit_count($pdo,'campaign_id',$campaignId,$userId,$email)>=max(1,(int)($campaign['per_user_limit']??1))){$pdo->rollBack();mg_fail('You have already participated in this campaign.',409);}
        $existing=$pdo->prepare('SELECT id,public_id FROM campaign_contacts WHERE campaign_id=? AND email=? LIMIT 1 FOR UPDATE');$existing->execute([$campaignId,$email]);$row=$existing->fetch(PDO::FETCH_ASSOC);$publicId=$row?(string)$row['public_id']:mg_media_reward_uuid_v2();$metadata=['campaign_type'=>$campaignType,'max_progress_percent'=>$progress,'email'=>$email,'participation_policy'=>$policy,'user_agent'=>substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,255),'ip'=>mg_client_ip()];foreach(($config['context_inputs']??[]) as $key=>$field)$metadata[$key]=$input[$field]??($rules[$key]??'');
        $up=$pdo->prepare("INSERT INTO campaign_contacts (public_id,merchant_user_id,campaign_id,user_id,email,phone,name,source,opt_in_status,metadata_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE user_id=VALUES(user_id), phone=VALUES(phone), name=VALUES(name), source=VALUES(source), metadata_json=VALUES(metadata_json), updated_at=NOW()");$up->execute([$publicId,$merchantId,$campaignId,$userId,$email,$phone!==''?$phone:null,$name!==''?$name:null,$campaignType,'opted_in',json_encode($metadata,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);
        $cl=$pdo->prepare('SELECT id,public_id FROM campaign_contacts WHERE campaign_id=? AND email=? LIMIT 1 FOR UPDATE');$cl->execute([$campaignId,$email]);$contact=$cl->fetch(PDO::FETCH_ASSOC);if(!$contact){$pdo->rollBack();mg_fail('Campaign contact could not be prepared.',500);}mg_merchant_crm_record_event($pdo,['merchant_user_id'=>$merchantId,'campaign_id'=>$campaignId,'campaign_type'=>$campaignType,'event_type'=>$campaignType.'.progress','source_type'=>$campaignType,'source_public_id'=>(string)$contact['public_id'],'user_id'=>$userId,'email'=>$email,'phone'=>$phone,'name'=>$name,'metadata'=>$metadata]);mg_media_reward_event_v2($pdo,$campaign,null,(int)$contact['id'],$campaignType.'.progress',$metadata+['progress_percent'=>$progress]);
        $remaining=max(0,max(1,(int)($campaign['per_user_limit']??1))-mg_public_campaign_limit_count($pdo,'campaign_id',$campaignId,$userId,$email));$issued=[];foreach(mg_media_reward_milestones_v2($rules,$config['noun']) as $m){if(count($issued)>=$remaining)break;$percent=(int)$m['percent'];if($progress+0.0001<$percent)continue;if(mg_media_reward_already_v2($pdo,$campaignId,(int)$contact['id'],$percent,$campaignType))continue;$template=mg_media_reward_template_v2($pdo,$merchantId,(int)$campaign['reward_template_db_id'],(string)$m['reward_template_id']);$issued[]=mg_media_reward_issue_v2($pdo,$campaign,$contact,$userId,$template,$percent,$progress,$metadata,$campaignType,$config['noun']);}
        $pdo->commit();mg_ok(['campaign_id'=>(string)$campaign['public_id'],'contact_id'=>(string)$contact['public_id'],'progress_percent'=>$progress,'issued_rewards'=>$issued,'milestones'=>mg_media_reward_milestones_v2($rules,$config['noun']),'participation_policy'=>$policy],$issued?ucfirst($config['label']).' reward unlocked and sent to your Microgifter Inbox.':ucfirst($config['label']).' progress recorded.');
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();mg_security_log('error',$campaignType.'.progress_failed','Unable to record media reward progress.',['exception_class'=>$e::class,'message'=>$e->getMessage()]);mg_fail('Unable to record reward progress.',500);} }
