<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/bootstrap.php';
require_once dirname(__DIR__, 2) . '/rewards/_zero_value_bridge.php';
require_once dirname(__DIR__, 3) . '/includes/merchant-crm.php';
require_once __DIR__ . '/_limits.php';
require_once __DIR__ . '/_security.php';
require_once __DIR__ . '/_followups.php';
require_once __DIR__ . '/_merchant_notifications.php';

function mg_qr_campaign_uuid(): string { $b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4)); }
function mg_qr_campaign_expiry(array $t): ?string { $r=(string)($t['expiration_rule']??'none'); if($r==='fixed_date'||$r==='event_date')return $t['expires_at']?:null; if($r==='after_issue'&&!empty($t['expiration_days']))return date('Y-m-d H:i:s',time()+((int)$t['expiration_days']*86400)); return null; }
function mg_qr_campaign_event(PDO $pdo,int $merchantId,int $campaignId,?int $walletItemId,?int $contactId,string $eventType,array $context=[]): void { $stmt=$pdo->prepare('INSERT INTO campaign_events (public_id,merchant_user_id,campaign_id,wallet_item_id,contact_id,event_type,event_context_json,created_at) VALUES (?,?,?,?,?,?,?,NOW())');$stmt->execute([mg_qr_campaign_uuid(),$merchantId,$campaignId,$walletItemId,$contactId,$eventType,json_encode($context,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);mg_campaign_followup_schedule($pdo,['merchant_user_id'=>$merchantId,'campaign_id'=>$campaignId,'contact_id'=>$contactId,'wallet_item_id'=>$walletItemId,'trigger_event'=>$eventType,'context'=>$context]); }
function mg_qr_campaign_find_user(PDO $pdo,string $email): ?int { $stmt=$pdo->prepare("SELECT id FROM users WHERE email=? AND status='active' LIMIT 1");$stmt->execute([$email]);$id=(int)($stmt->fetchColumn()?:0);return $id>0?$id:null; }
function mg_qr_campaign_bridge(PDO $pdo,array $c,array $contact,int $walletDbId,string $walletPublicId,?int $userId,?string $expiresAt): ?array { if(!$userId)return null; return mg_zero_reward_issue_from_wallet($pdo,['merchant_user_id'=>(int)$c['merchant_user_id'],'recipient_user_id'=>$userId,'recipient_external_id'=>(string)($contact['public_id']??''),'wallet_item_db_id'=>$walletDbId,'wallet_item_public_id'=>$walletPublicId,'campaign_public_id'=>(string)$c['public_id'],'reward_template_public_id'=>(string)$c['reward_template_public_id'],'source_type'=>'qr_scan','source_reference'=>$walletPublicId,'source_line_reference'=>(string)($contact['public_id']??$walletPublicId),'title'=>(string)$c['reward_template_title'],'description'=>$c['description']??null,'currency'=>(string)($c['currency']??'USD'),'display_value_cents'=>(int)($c['value_amount_cents']??0),'expires_at'=>$expiresAt,'redemption_instructions'=>$c['redemption_instructions']??null,'terms'=>['campaign_type'=>'qr_reward_drop']]); }

mg_require_method('POST');
$input=mg_input();$pdo=mg_db();
$campaignRef=strtolower(trim((string)($input['campaign_id']??$input['campaign']??'')));$qrToken=trim((string)($input['qr_token']??$input['token']??''));$email=strtolower(trim((string)($input['email']??'')));$name=trim((string)($input['name']??$input['full_name']??''));$phone=trim((string)($input['phone']??''));
if(($campaignRef===''&&$qrToken==='')||$email===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||mb_strlen($email)>255||mb_strlen($name)>180||mb_strlen($phone)>60)mg_fail('Invalid QR pickup submission.',422);
mg_public_campaign_throttle('qr_pickup',$campaignRef!==''?$campaignRef:$qrToken,$email);
try{
 $pdo->beginTransaction();
 $sql="SELECT c.*,rt.id reward_template_db_id,rt.public_id reward_template_public_id,rt.title reward_template_title,rt.description reward_template_description,rt.redemption_instructions,rt.value_amount_cents,rt.currency,rt.expiration_rule,rt.expiration_days,rt.expires_at,rt.quantity_limit reward_template_quantity_limit,rt.issued_count reward_template_issued_count,rt.per_user_limit reward_template_per_user_limit FROM campaigns c INNER JOIN reward_templates rt ON rt.id=c.reward_template_id WHERE c.campaign_type='qr_reward_drop' AND c.status='active' AND rt.status='active' AND ((?<>'' AND c.qr_code_token=?) OR (?<>'' AND c.public_id=?)) LIMIT 1";
 $stmt=$pdo->prepare($sql);$stmt->execute([$qrToken,$qrToken,$campaignRef,$campaignRef]);$campaign=$stmt->fetch();
 if(!$campaign){$pdo->rollBack();mg_fail('QR reward drop is not available.',404);} $now=time();
 if(!empty($campaign['starts_at'])&&strtotime((string)$campaign['starts_at'])>$now){$pdo->rollBack();mg_fail('QR reward drop has not started yet.',409);} if(!empty($campaign['ends_at'])&&strtotime((string)$campaign['ends_at'])<$now){$pdo->rollBack();mg_fail('QR reward drop has ended.',409);} if($campaign['quantity_limit']!==null&&(int)$campaign['issued_count']>=(int)$campaign['quantity_limit']){$pdo->rollBack();mg_fail('QR reward drop limit has been reached.',409);} if($campaign['reward_template_quantity_limit']!==null&&(int)$campaign['reward_template_issued_count']>=(int)$campaign['reward_template_quantity_limit']){$pdo->rollBack();mg_fail('Reward template limit has been reached.',409);}
 $merchantId=(int)$campaign['merchant_user_id'];$campaignId=(int)$campaign['id'];$campaignType=(string)$campaign['campaign_type'];$rewardTemplateId=(int)$campaign['reward_template_db_id'];$userId=mg_qr_campaign_find_user($pdo,$email);$source='qr_scan';
 $existingContactStmt=$pdo->prepare('SELECT id,public_id FROM campaign_contacts WHERE campaign_id=? AND email=? LIMIT 1 FOR UPDATE');$existingContactStmt->execute([$campaignId,$email]);$isNewContact=!$existingContactStmt->fetch(PDO::FETCH_ASSOC);
 $contactPublicId=mg_qr_campaign_uuid();$meta=['campaign_type'=>$campaignType,'campaign_public_id'=>(string)$campaign['public_id'],'qr_token_present'=>$qrToken!=='','ip'=>mg_client_ip()];
 $contactStmt=$pdo->prepare('INSERT INTO campaign_contacts (public_id,merchant_user_id,campaign_id,user_id,email,phone,name,source,opt_in_status,metadata_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE user_id=VALUES(user_id),phone=VALUES(phone),name=VALUES(name),metadata_json=VALUES(metadata_json),updated_at=NOW()');
 $contactStmt->execute([$contactPublicId,$merchantId,$campaignId,$userId,$email,$phone!==''?$phone:null,$name!==''?$name:null,$source,'unknown',json_encode($meta,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);
 $lookup=$pdo->prepare('SELECT id,public_id FROM campaign_contacts WHERE campaign_id=? AND email=? LIMIT 1');$lookup->execute([$campaignId,$email]);$contact=$lookup->fetch();$contactId=(int)$contact['id'];
 $crm=mg_merchant_crm_record_event($pdo,['merchant_user_id'=>$merchantId,'campaign_id'=>$campaignId,'campaign_type'=>$campaignType,'event_type'=>'qr.scanned','source_type'=>$source,'source_public_id'=>(string)$contact['public_id'],'user_id'=>$userId,'email'=>$email,'phone'=>$phone,'name'=>$name,'metadata'=>$meta]);
 $merchantNotification=mg_public_campaign_notify_merchant_contact($pdo,$campaign,$contact,$email,$name,$phone,$source,$crm,$isNewContact);
 mg_qr_campaign_event($pdo,$merchantId,$campaignId,null,$contactId,'qr.scanned',['email'=>$email,'campaign_type'=>$campaignType,'merchant_crm'=>$crm,'merchant_notification'=>$merchantNotification]);
 $expiresAt=mg_qr_campaign_expiry($campaign);$existingStmt=$pdo->prepare("SELECT id,public_id,status FROM wallet_items WHERE campaign_id=? AND contact_id=? AND source_type='qr_scan' AND status<>'cancelled' ORDER BY id DESC LIMIT 1");$existingStmt->execute([$campaignId,$contactId]);$existing=$existingStmt->fetch();
 if($existing){$bridge=mg_qr_campaign_bridge($pdo,$campaign,$contact,(int)$existing['id'],(string)$existing['public_id'],$userId,$expiresAt);$pdo->commit();mg_ok(['contact_id'=>(string)$contact['public_id'],'wallet_item_id'=>(string)$existing['public_id'],'wallet_status'=>(string)$existing['status'],'already_issued'=>true,'pppm_bridge'=>$bridge,'merchant_crm'=>$crm,'merchant_notification'=>$merchantNotification],'QR reward already added.');}
 mg_public_campaign_enforce_reward_limits($pdo,$campaign,$userId,$email);
 $walletPublicId=mg_qr_campaign_uuid();$stampLedger=mg_public_campaign_debit_reward_stamp($pdo,$campaign,$walletPublicId,$source,['contact_id'=>(string)$contact['public_id'],'email'=>$email,'qr_token_present'=>$qrToken!=='']);$walletMetadata=['campaign_type'=>$campaignType,'reward_template_id'=>(string)$campaign['reward_template_public_id'],'stamp_ledger_entry_id'=>$stampLedger['entry']['entry_id']??null];$walletStmt=$pdo->prepare('INSERT INTO wallet_items (public_id,user_id,contact_id,merchant_user_id,reward_template_id,campaign_id,source_type,source_id,status,value_cents_snapshot,currency_snapshot,title_snapshot,metadata_json,issued_at,expires_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),?,NOW(),NOW())');
 $walletStmt->execute([$walletPublicId,$userId,$contactId,$merchantId,$rewardTemplateId,$campaignId,$source,(string)$contact['public_id'],'issued',(int)$campaign['value_amount_cents'],(string)$campaign['currency'],(string)$campaign['reward_template_title'],json_encode($walletMetadata,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),$expiresAt]);$walletDbId=(int)$pdo->lastInsertId();
 $pdo->prepare('UPDATE campaigns SET issued_count=issued_count+1,updated_at=NOW() WHERE id=?')->execute([$campaignId]);$pdo->prepare('UPDATE reward_templates SET issued_count=issued_count+1,updated_at=NOW() WHERE id=?')->execute([$rewardTemplateId]);$bridge=mg_qr_campaign_bridge($pdo,$campaign,$contact,$walletDbId,$walletPublicId,$userId,$expiresAt);mg_qr_campaign_event($pdo,$merchantId,$campaignId,$walletDbId,$contactId,'wallet_item.issued',['wallet_item_id'=>$walletPublicId,'campaign_type'=>$campaignType,'pppm_bridge'=>$bridge,'merchant_crm'=>$crm,'merchant_notification'=>$merchantNotification,'stamp_ledger_entry_id'=>$stampLedger['entry']['entry_id']??null]);
 $pdo->commit();mg_ok(['contact_id'=>(string)$contact['public_id'],'wallet_item_id'=>$walletPublicId,'wallet_status'=>'issued','already_issued'=>false,'reward_title'=>(string)$campaign['reward_template_title'],'expires_at'=>$expiresAt,'pppm_bridge'=>$bridge,'merchant_crm'=>$crm,'merchant_notification'=>$merchantNotification,'stamp_ledger'=>$stampLedger],'QR reward added to wallet.',201);
}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();mg_security_log('error','public.qr_pickup.failed','Unable to process QR reward pickup.',['exception_class'=>$error::class,'message'=>$error->getMessage()]);mg_fail('Unable to process QR reward pickup.',500);}
