<?php
declare(strict_types=1);

function mg_recipe_draft_is_payload(array $payload): bool
{
    return (string)($payload['source'] ?? '') === 'merchant_agent_chat_creative_draft';
}

function mg_recipe_draft_campaign_type(array $payload): string
{
    $value = (string)($payload['recommended_campaign_type'] ?? $payload['campaign_type'] ?? $payload['draft_type'] ?? 'agent_offer');
    $map = [
        'newsletter_signup' => 'newsletter_signup',
        'contest_giveaway' => 'contest_giveaway',
        'qr_reward_drop' => 'qr_reward_drop',
        'referral_reward' => 'referral_reward',
        'birthday_vip' => 'birthday_vip',
        'agent_offer' => 'agent_offer',
        'newsletter' => 'newsletter_signup',
        'contest' => 'contest_giveaway',
        'qr_drop' => 'qr_reward_drop',
        'flash_drop' => 'agent_offer',
        'social_engagement' => 'contest_giveaway',
        'social_engagement_challenge' => 'contest_giveaway',
        'prepurchase_campaign' => 'agent_offer',
        'winback_campaign' => 'agent_offer',
        'local_event_promo' => 'qr_reward_drop',
        'ugc_story_campaign' => 'contest_giveaway',
        'loyalty_milestone' => 'birthday_vip',
        'partner_cross_merchant' => 'referral_reward',
    ];
    return $map[$value] ?? 'agent_offer';
}

function mg_recipe_draft_reward_type(array $payload): string
{
    $value = (string)($payload['recommended_reward_type'] ?? $payload['reward_type'] ?? 'custom');
    $map = [
        'dollar_credit' => 'dollar_credit',
        'free_item' => 'free_item',
        'discount' => 'discount',
        'perk_upgrade' => 'perk_upgrade',
        'event_reward' => 'event_reward',
        'custom' => 'custom',
        'prepurchase_credit' => 'dollar_credit',
        'service_upgrade' => 'perk_upgrade',
        'vip_access' => 'event_reward',
        'membership_perk' => 'perk_upgrade',
    ];
    return $map[$value] ?? 'custom';
}

function mg_recipe_draft_title(array $item, array $payload, string $fallback = 'Agent recipe draft'): string
{
    return mg_ai_plan_short($payload['draft_title'] ?? $payload['title'] ?? $item['title'] ?? $fallback, 180) ?: $fallback;
}

function mg_recipe_draft_body(array $item, array $payload): string
{
    return mg_ai_plan_short($payload['draft_body'] ?? $payload['description'] ?? $item['reason'] ?? 'Recipe draft generated by Merchant Agent.', 3000);
}

function mg_recipe_draft_normalized_campaign_payload(array $item, array $payload): array
{
    $body = mg_recipe_draft_body($item, $payload);
    $description = trim($body . "\n\n" .
        (!empty($payload['recommended_campaign_type']) ? 'Recommended campaign type: ' . (string)$payload['recommended_campaign_type'] . "\n" : '') .
        (!empty($payload['recommended_reward_type']) ? 'Recommended reward type: ' . (string)$payload['recommended_reward_type'] . "\n" : '') .
        (!empty($payload['recipe_key']) ? 'Recipe key: ' . (string)$payload['recipe_key'] : ''));
    return array_merge($payload, [
        'title' => mg_recipe_draft_title($item, $payload, 'Agent campaign draft'),
        'campaign_type' => mg_recipe_draft_campaign_type($payload),
        'description' => mg_ai_plan_short($description, 2000),
        'form_headline' => mg_recipe_draft_title($item, $payload, 'Agent campaign draft'),
        'form_description' => mg_ai_plan_short($body, 2000),
        'success_message' => 'Thanks — this campaign draft is ready for merchant review.',
        'agent_discoverable' => false,
    ]);
}

function mg_recipe_draft_normalized_reward_payload(array $item, array $payload): array
{
    $rewardType = mg_recipe_draft_reward_type($payload);
    $valueType = $rewardType === 'discount' ? 'percent' : ($rewardType === 'free_item' ? 'free_item' : ($rewardType === 'dollar_credit' ? 'fixed_amount' : 'custom'));
    return array_merge($payload, [
        'title' => mg_ai_plan_short(($payload['reward_title'] ?? '') ?: ('Reward for ' . mg_recipe_draft_title($item, $payload)), 180),
        'description' => mg_recipe_draft_body($item, $payload),
        'reward_type' => $rewardType,
        'value_type' => $valueType,
        'redemption_instructions' => mg_recipe_draft_body($item, $payload),
        'agent_summary' => mg_ai_plan_short(mg_recipe_draft_body($item, $payload), 500),
        'agent_categories' => ['recipe_draft'],
        'agent_use_cases' => ['campaign_recipe'],
    ]);
}

function mg_recipe_draft_artifacts(array $payload): array
{
    $rows = [];
    foreach ((is_array($payload['draft_artifacts'] ?? null) ? $payload['draft_artifacts'] : []) as $index => $artifact) {
        if (is_string($artifact)) {
            $body = mg_ai_plan_short($artifact, 3000);
            if ($body !== '') $rows[] = ['title' => 'Draft artifact ' . ($index + 1), 'body' => $body, 'channel' => 'general'];
            continue;
        }
        if (!is_array($artifact)) continue;
        $body = mg_ai_plan_short($artifact['body'] ?? $artifact['copy'] ?? $artifact['text'] ?? $artifact['content'] ?? $artifact['instructions'] ?? '', 3000);
        if ($body === '') continue;
        $rows[] = ['title' => mg_ai_plan_short($artifact['title'] ?? $artifact['label'] ?? $artifact['type'] ?? $artifact['channel'] ?? 'Draft artifact', 180), 'body' => $body, 'channel' => mg_ai_plan_short($artifact['channel'] ?? $artifact['type'] ?? 'general', 60)];
    }
    return $rows;
}

function mg_recipe_draft_message_event(PDO $pdo, int $merchantId, array $item, array $payload, string $body, string $title, string $channel): array
{
    $itemId = (string)$item['public_id'];
    $approvalId = function_exists('mg_agent_approval_id') ? mg_agent_approval_id($merchantId, 'ai_plan', $itemId) : ('agq_' . substr(hash('sha256', $merchantId . '|ai_plan|' . $itemId), 0, 24));
    $messageId = 'amd_' . substr(hash('sha256', $merchantId . '|recipe|' . $itemId . '|' . $channel . '|' . $title . '|' . $body), 0, 24);
    $eventId = mg_automation_record_event($pdo, $merchantId, 'crm.agent.message.draft.created', [
        'message_draft_id' => $messageId,
        'execution_id' => 'air_' . substr(hash('sha256', $merchantId . '|ai-result|' . $itemId), 0, 24),
        'approval_id' => $approvalId,
        'playbook_key' => (string)$item['action_key'],
        'playbook_title' => $title,
        'customer_name' => '',
        'customer_email' => '',
        'campaign_title' => mg_recipe_draft_title($item, $payload),
        'draft_body' => $body,
        'message_body' => $body,
        'message_channel' => $channel,
        'why' => mg_recipe_draft_body($item, $payload),
        'guardrail_applied' => 'Created from an approved recipe draft. Merchant still controls editing and final use.',
        'expected_action' => 'Review this recipe-generated draft before customer-facing use.',
        'source' => 'recipe_draft_execution_adapter',
        'ai_plan_item_id' => $itemId,
        'recipe_key' => (string)($payload['recipe_key'] ?? ''),
        'draft_type' => (string)($payload['draft_type'] ?? ''),
    ], null, null);
    return ['resource_type' => 'message_draft', 'resource_id' => $messageId, 'event_id' => $eventId, 'url' => '/merchant-agent-messages.php', 'status' => 'message_draft_created', 'channel' => $channel];
}

function mg_recipe_draft_execute(PDO $pdo, int $merchantId, array $item, array $payload): array
{
    $draftType = (string)($payload['draft_type'] ?? 'campaign');
    $resources = [];
    if ($draftType === 'reward') {
        $reward = mg_ai_plan_create_reward_template_draft($pdo, $merchantId, $item, mg_recipe_draft_normalized_reward_payload($item, $payload));
        return $reward + ['resources' => [$reward]];
    }
    if (in_array($draftType, ['sms','email','newsletter'], true) || (string)$item['action_key'] === 'create_message_draft') {
        $message = mg_recipe_draft_message_event($pdo, $merchantId, $item, $payload, mg_recipe_draft_body($item, $payload), mg_recipe_draft_title($item, $payload), $draftType ?: 'message');
        return $message + ['resources' => [$message]];
    }
    if ($draftType === 'campaign_package' || !empty($payload['recommended_reward_type'])) {
        $resources[] = mg_ai_plan_create_reward_template_draft($pdo, $merchantId, $item, mg_recipe_draft_normalized_reward_payload($item, $payload));
    }
    $campaign = mg_ai_plan_create_campaign_draft($pdo, $merchantId, $item, mg_recipe_draft_normalized_campaign_payload($item, $payload));
    $resources[] = $campaign;
    $artifacts = mg_recipe_draft_artifacts($payload);
    if ($artifacts === []) $artifacts[] = ['title' => mg_recipe_draft_title($item, $payload), 'body' => mg_recipe_draft_body($item, $payload), 'channel' => (string)($payload['message_channel'] ?? 'campaign')];
    foreach (array_slice($artifacts, 0, $draftType === 'campaign_package' ? 6 : 3) as $artifact) {
        $resources[] = mg_recipe_draft_message_event($pdo, $merchantId, $item, $payload, (string)$artifact['body'], (string)$artifact['title'], strtolower((string)$artifact['channel'] ?: 'general'));
    }
    if ($draftType === 'campaign_package') return ['resource_type' => 'campaign_package', 'resource_id' => (string)$item['public_id'], 'url' => '/merchant-agent-execution.php', 'status' => 'package_drafts_created', 'resources' => $resources];
    return $campaign + ['resources' => $resources];
}

function mg_recipe_draft_review_item(PDO $pdo, array $user, array $item, array $input): array
{
    $merchantId = (int)$user['id'];
    $actorId = $merchantId;
    $note = mg_ai_plan_short($input['note'] ?? '', 1000);
    $payload = mg_ai_plan_json($item['suggested_payload_json'] ?? null);
    if (!mg_recipe_draft_is_payload($payload)) mg_fail('This AI item is not a recipe draft.', 422);
    $pdo->beginTransaction();
    try {
        $locked = mg_ai_plan_item_owned($pdo, $merchantId, (string)$item['public_id'], true);
        if (!in_array((string)$locked['status'], ['recommended','deferred','failed'], true)) throw new RuntimeException('Recommendation is not available for review.');
        mg_ai_plan_record_review_event($pdo, $merchantId, 'merchant.ai_plan_item.approved', $locked, ['status' => 'approved', 'merchant_note' => $note, 'decided_by_user_id' => $actorId, 'recipe_draft' => true]);
        $execution = mg_recipe_draft_execute($pdo, $merchantId, $locked, $payload);
        $pdo->prepare('UPDATE ai_merchant_plan_items SET status=\'executed\', updated_at=NOW() WHERE id=?')->execute([(int)$locked['id']]);
        mg_ai_plan_record_review_event($pdo, $merchantId, 'merchant.ai_plan_item.executed', $locked, ['status' => 'executed', 'merchant_note' => $note, 'execution' => $execution, 'decided_by_user_id' => $actorId, 'recipe_draft' => true]);
        mg_ai_plan_update_parent_status($pdo, (int)$locked['plan_id']);
        $fresh = mg_ai_plan_item_owned($pdo, $merchantId, (string)$item['public_id'], false);
        mg_audit('merchant.recipe_draft_executed', 'ai_merchant_plan_item', ['plan_id' => (string)($locked['plan_public_id'] ?? ''), 'item_id' => (string)$locked['public_id'], 'action_key' => (string)$locked['action_key'], 'execution' => $execution], $merchantId);
        $pdo->commit();
        return mg_ai_plan_public_item($fresh, $execution);
    } catch (Throwable $error) {
        if ($pdo->inTransaction()) $pdo->rollBack();
        mg_security_log('error', 'merchant.recipe_draft_review_failed', 'Recipe draft review failed.', ['exception_class' => $error::class, 'item_id' => (string)$item['public_id']], $merchantId);
        mg_fail('Unable to execute recipe draft: ' . $error->getMessage(), 500);
    }
}
