<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/package-entitlements.php';

final class MgAiCreditException extends RuntimeException
{
    public function __construct(string $message, private readonly int $httpStatus = 402, private readonly array $details = []) { parent::__construct($message); }
    public function httpStatus(): int { return $this->httpStatus; }
    public function details(): array { return $this->details; }
}

function mg_ai_credit_table_exists(PDO $pdo, string $table): bool
{
    static $cache=[]; $key=spl_object_id($pdo).':'.$table;
    if(array_key_exists($key,$cache))return $cache[$key];
    try{$stmt=$pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$stmt->execute([$table]);return $cache[$key]=((int)$stmt->fetchColumn()>0);}catch(Throwable){return $cache[$key]=false;}
}
function mg_ai_credit_schema_ready(PDO $pdo): bool { return mg_ai_credit_table_exists($pdo,'ai_user_credit_accounts')&&mg_ai_credit_table_exists($pdo,'ai_credit_ledger')&&mg_ai_credit_table_exists($pdo,'ai_usage_events'); }
function mg_ai_credit_provider_key(mixed $value): string { $value=strtolower(trim((string)$value));return preg_match('/^[a-z0-9][a-z0-9._-]{0,79}$/',$value)===1?$value:'anthropic'; }
function mg_ai_credit_nullable_int(mixed $value,int $max=2000000000): ?int { if($value===null||$value==='')return null;$parsed=filter_var($value,FILTER_VALIDATE_INT);return $parsed===false?null:max(0,min($max,(int)$parsed)); }
function mg_ai_credit_int(mixed $value,int $max=2000000000): int { return mg_ai_credit_nullable_int($value,$max)??0; }
function mg_ai_credit_uuid(): string
{
    if(function_exists('mg_public_uuid'))return mg_public_uuid();
    $bytes=random_bytes(16);$bytes[6]=chr((ord($bytes[6])&0x0f)|0x40);$bytes[8]=chr((ord($bytes[8])&0x3f)|0x80);
    return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($bytes),4));
}
function mg_ai_credit_user(PDO $pdo,int $userId): array
{
    $stmt=$pdo->prepare('SELECT id,email,display_name,full_name,status FROM users WHERE id=? LIMIT 1');$stmt->execute([$userId]);$user=$stmt->fetch(PDO::FETCH_ASSOC);
    if(!is_array($user))throw new RuntimeException('User not found.');
    $roles=$pdo->prepare('SELECT r.slug FROM roles r INNER JOIN user_roles ur ON ur.role_id=r.id WHERE ur.user_id=? ORDER BY r.slug');$roles->execute([$userId]);
    $user['roles']=array_values(array_map('strval',$roles->fetchAll(PDO::FETCH_COLUMN)?:[]));return $user;
}
function mg_ai_credit_package_context(PDO $pdo,int $userId): array { return mg_user_package_context($pdo,mg_ai_credit_user($pdo,$userId)); }
function mg_ai_credit_package_policy(array $context): array
{
    $limits=is_array($context['limits']??null)?$context['limits']:[];$hasMonthly=array_key_exists('ai_tokens_monthly_included',$limits);$raw=$hasMonthly?$limits['ai_tokens_monthly_included']:0;
    $unlimited=$hasMonthly&&$raw===null;$monthly=$unlimited?null:mg_ai_credit_int($raw);
    return ['package_id'=>(string)($context['package_id']??'free'),'package_name'=>(string)($context['package_name']??'Free'),'status'=>(string)($context['status']??'free'),'monthly_tokens'=>$monthly,'unlimited'=>$unlimited,
        'daily_limit'=>array_key_exists('ai_tokens_daily_limit',$limits)?mg_ai_credit_nullable_int($limits['ai_tokens_daily_limit']):null,
        'weekly_limit'=>array_key_exists('ai_tokens_weekly_limit',$limits)?mg_ai_credit_nullable_int($limits['ai_tokens_weekly_limit']):null,
        'monthly_limit'=>array_key_exists('ai_tokens_monthly_limit',$limits)?mg_ai_credit_nullable_int($limits['ai_tokens_monthly_limit']):$monthly];
}
function mg_ai_credit_period(array $context): array
{
    $utc=new DateTimeZone('UTC');$subscription=is_array($context['subscription']??null)?$context['subscription']:[];
    try{$start=!empty($subscription['current_period_start'])?new DateTimeImmutable((string)$subscription['current_period_start'],$utc):null;$end=!empty($subscription['current_period_end'])?new DateTimeImmutable((string)$subscription['current_period_end'],$utc):null;}catch(Throwable){$start=null;$end=null;}
    if(!$start||!$end||$end<=$start){$now=new DateTimeImmutable('now',$utc);$start=$now->modify('first day of this month')->setTime(0,0,0);$end=$start->modify('+1 month');}
    return ['start'=>$start,'end'=>$end];
}
function mg_ai_credit_legacy_policy(PDO $pdo,int $userId,string $providerKey): array
{
    if(!mg_ai_credit_table_exists($pdo,'campaign_events'))return [];
    try{$stmt=$pdo->prepare("SELECT event_context_json FROM campaign_events WHERE merchant_user_id=? AND event_type='merchant.ai_user_limits.updated' ORDER BY id DESC LIMIT 1");$stmt->execute([$userId]);$decoded=json_decode((string)($stmt->fetchColumn()?:''),true);if(!is_array($decoded))return [];if(!empty($decoded['provider_key'])&&(string)$decoded['provider_key']!==$providerKey)return [];return $decoded;}catch(Throwable){return [];}
}
function mg_ai_credit_account(PDO $pdo,int $userId,string $providerKey='anthropic'): array
{
    $providerKey=mg_ai_credit_provider_key($providerKey);if(!mg_ai_credit_schema_ready($pdo))return [];$legacy=mg_ai_credit_legacy_policy($pdo,$userId,$providerKey);
    $stmt=$pdo->prepare('INSERT IGNORE INTO ai_user_credit_accounts (user_id,provider_key,enabled,requests_per_hour,requests_per_day,note,created_at,updated_at) VALUES (?,?,?,?,?,?,NOW(),NOW())');
    $stmt->execute([$userId,$providerKey,array_key_exists('enabled',$legacy)?(!empty($legacy['enabled'])?1:0):1,mg_ai_credit_nullable_int($legacy['requests_per_hour']??null,1000000),mg_ai_credit_nullable_int($legacy['requests_per_day']??null,1000000),mb_substr(trim((string)($legacy['note']??'')),0,500)?:null]);
    $stmt=$pdo->prepare('SELECT * FROM ai_user_credit_accounts WHERE user_id=? AND provider_key=? LIMIT 1');$stmt->execute([$userId,$providerKey]);return $stmt->fetch(PDO::FETCH_ASSOC)?:[];
}
function mg_ai_credit_ledger_write(PDO $pdo,array $entry): void
{
    $stmt=$pdo->prepare('INSERT INTO ai_credit_ledger (public_id,user_id,provider_key,provider_id,model_id,entry_type,token_delta,package_token_delta,manual_token_delta,input_tokens,output_tokens,source_type,source_reference,idempotency_key,actor_user_id,metadata_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())');
    $stmt->execute([mg_ai_credit_uuid(),(int)$entry['user_id'],mg_ai_credit_provider_key($entry['provider_key']??'anthropic'),$entry['provider_id']??null,$entry['model_id']??null,(string)$entry['entry_type'],(int)($entry['token_delta']??0),(int)($entry['package_token_delta']??0),(int)($entry['manual_token_delta']??0),(int)($entry['input_tokens']??0),(int)($entry['output_tokens']??0),mb_substr(trim((string)($entry['source_type']??'system')),0,80),($ref=mb_substr(trim((string)($entry['source_reference']??'')),0,190))!==''?$ref:null,($key=mb_substr(trim((string)($entry['idempotency_key']??'')),0,190))!==''?$key:null,isset($entry['actor_user_id'])?(int)$entry['actor_user_id']:null,!empty($entry['metadata'])?json_encode($entry['metadata'],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE):null]);
}
function mg_ai_credit_sync_account(PDO $pdo,int $userId,string $providerKey='anthropic'): array
{
    $providerKey=mg_ai_credit_provider_key($providerKey);$row=mg_ai_credit_account($pdo,$userId,$providerKey);if($row===[])return [];$context=mg_ai_credit_package_context($pdo,$userId);$policy=mg_ai_credit_package_policy($context);$period=mg_ai_credit_period($context);$start=$period['start']->format('Y-m-d H:i:s');$end=$period['end']->format('Y-m-d H:i:s');
    $oldAllocated=$row['package_tokens_allocated']===null?null:(int)$row['package_tokens_allocated'];$oldRemaining=$row['package_tokens_remaining']===null?null:(int)$row['package_tokens_remaining'];$newAllocated=$policy['unlimited']?null:(int)$policy['monthly_tokens'];
    $periodChanged=(string)($row['package_id']??'')!==$policy['package_id']||(string)($row['package_period_start']??'')!==$start||(string)($row['package_period_end']??'')!==$end;$allocationChanged=!$periodChanged&&$oldAllocated!==$newAllocated;
    if($periodChanged||$allocationChanged){if($periodChanged)$newRemaining=$newAllocated;elseif($newAllocated===null)$newRemaining=null;else{$used=($oldAllocated!==null&&$oldRemaining!==null)?max(0,$oldAllocated-$oldRemaining):0;$newRemaining=max(0,$newAllocated-$used);} $stmt=$pdo->prepare('UPDATE ai_user_credit_accounts SET package_id=?,package_period_start=?,package_period_end=?,package_tokens_allocated=?,package_tokens_remaining=?,updated_at=NOW() WHERE user_id=? AND provider_key=?');$stmt->execute([$policy['package_id'],$start,$end,$newAllocated,$newRemaining,$userId,$providerKey]);$delta=($newRemaining??0)-($oldRemaining??0);$idempotency=implode(':',['package',$userId,$providerKey,$policy['package_id'],$start,$end,$newAllocated===null?'unlimited':$newAllocated]);try{mg_ai_credit_ledger_write($pdo,['user_id'=>$userId,'provider_key'=>$providerKey,'entry_type'=>$periodChanged?'package_refill':'package_adjustment','token_delta'=>$periodChanged?($newAllocated??0):$delta,'package_token_delta'=>$periodChanged?($newAllocated??0):$delta,'source_type'=>'subscription_package','source_reference'=>$policy['package_id'],'idempotency_key'=>$idempotency,'metadata'=>['period_start'=>$start,'period_end'=>$end,'unlimited'=>$newAllocated===null,'allocation_changed'=>$allocationChanged]]);}catch(PDOException $error){if((string)$error->getCode()!=='23000')throw $error;}$row=mg_ai_credit_account($pdo,$userId,$providerKey);}
    $row['_context']=$context;$row['_policy']=$policy;return $row;
}
function mg_ai_credit_token_usage(PDO $pdo,int $userId,string $providerKey,DateTimeImmutable $since): int { $stmt=$pdo->prepare("SELECT COALESCE(SUM(ABS(token_delta)),0) FROM ai_credit_ledger WHERE user_id=? AND provider_key=? AND entry_type='usage_debit' AND created_at>=?");$stmt->execute([$userId,$providerKey,$since->format('Y-m-d H:i:s')]);return (int)$stmt->fetchColumn(); }
function mg_ai_credit_request_usage(PDO $pdo,int $userId,string $providerKey,DateTimeImmutable $since): int { try{$stmt=$pdo->prepare("SELECT COALESCE(SUM(request_units),0) FROM ai_usage_events e INNER JOIN ai_providers p ON p.id=e.provider_id WHERE e.user_id=? AND p.provider_key=? AND e.request_status='allowed' AND e.created_at>=?");$stmt->execute([$userId,$providerKey,$since->format('Y-m-d H:i:s')]);return (int)$stmt->fetchColumn();}catch(Throwable){return 0;} }
function mg_ai_credit_effective_limit(mixed $custom,mixed $package): ?int { return $custom!==null?mg_ai_credit_nullable_int($custom):mg_ai_credit_nullable_int($package); }
function mg_ai_credit_snapshot(PDO $pdo,int $userId,string $providerKey='anthropic'): array
{
    $providerKey=mg_ai_credit_provider_key($providerKey);
    if(!mg_ai_credit_schema_ready($pdo))return ['schema_ready'=>false,'enabled'=>true,'can_use'=>true,'unmetered'=>true,'provider_key'=>$providerKey,'package'=>['id'=>'legacy','name'=>'Legacy access','status'=>'unmetered','monthly_tokens'=>null,'unlimited'=>true],'available_tokens'=>null,'package_tokens_allocated'=>null,'package_tokens_remaining'=>null,'manual_tokens_remaining'=>0,'usage'=>['day'=>0,'week'=>0,'month'=>0],'limits'=>['day'=>null,'week'=>null,'month'=>null],'request_usage'=>['hour'=>0,'day'=>0],'request_limits'=>['hour'=>null,'day'=>null],'message'=>'AI credit migration has not been imported; legacy request limits remain active.'];
    $row=mg_ai_credit_sync_account($pdo,$userId,$providerKey);$context=is_array($row['_context']??null)?$row['_context']:mg_ai_credit_package_context($pdo,$userId);$policy=is_array($row['_policy']??null)?$row['_policy']:mg_ai_credit_package_policy($context);$utc=new DateTimeZone('UTC');$now=new DateTimeImmutable('now',$utc);$dayStart=$now->setTime(0,0,0);$weekStart=$dayStart->modify('monday this week');try{$monthStart=new DateTimeImmutable((string)$row['package_period_start'],$utc);}catch(Throwable){$monthStart=$now->modify('first day of this month')->setTime(0,0,0);} 
    $usage=['day'=>mg_ai_credit_token_usage($pdo,$userId,$providerKey,$dayStart),'week'=>mg_ai_credit_token_usage($pdo,$userId,$providerKey,$weekStart),'month'=>mg_ai_credit_token_usage($pdo,$userId,$providerKey,$monthStart)];$limits=['day'=>mg_ai_credit_effective_limit($row['daily_token_limit']??null,$policy['daily_limit']),'week'=>mg_ai_credit_effective_limit($row['weekly_token_limit']??null,$policy['weekly_limit']),'month'=>mg_ai_credit_effective_limit($row['monthly_token_limit']??null,$policy['monthly_limit'])];$unlimited=$row['package_tokens_remaining']===null&&$policy['unlimited'];$available=$unlimited?null:max(0,(int)($row['package_tokens_remaining']??0)+(int)($row['manual_tokens_remaining']??0));$requestLimits=['hour'=>$row['requests_per_hour']===null?null:(int)$row['requests_per_hour'],'day'=>$row['requests_per_day']===null?null:(int)$row['requests_per_day']];$requestUsage=['hour'=>mg_ai_credit_request_usage($pdo,$userId,$providerKey,$now->modify('-1 hour')),'day'=>mg_ai_credit_request_usage($pdo,$userId,$providerKey,$now->modify('-1 day'))];
    $block='';if(empty($row['enabled']))$block='disabled';elseif($available!==null&&$available<1)$block='balance';elseif($limits['day']!==null&&$usage['day']>=$limits['day'])$block='daily_limit';elseif($limits['week']!==null&&$usage['week']>=$limits['week'])$block='weekly_limit';elseif($limits['month']!==null&&$usage['month']>=$limits['month'])$block='monthly_limit';elseif($requestLimits['hour']!==null&&$requestUsage['hour']>=$requestLimits['hour'])$block='request_hour';elseif($requestLimits['day']!==null&&$requestUsage['day']>=$requestLimits['day'])$block='request_day';
    return ['schema_ready'=>true,'enabled'=>!empty($row['enabled']),'can_use'=>$block==='','block_reason'=>$block,'provider_key'=>$providerKey,'package'=>['id'=>$policy['package_id'],'name'=>$policy['package_name'],'status'=>$policy['status'],'monthly_tokens'=>$policy['monthly_tokens'],'unlimited'=>$policy['unlimited']],'available_tokens'=>$available,'package_tokens_allocated'=>$row['package_tokens_allocated']===null?null:(int)$row['package_tokens_allocated'],'package_tokens_remaining'=>$row['package_tokens_remaining']===null?null:(int)$row['package_tokens_remaining'],'manual_tokens_remaining'=>(int)($row['manual_tokens_remaining']??0),'custom_limits'=>['day'=>$row['daily_token_limit']===null?null:(int)$row['daily_token_limit'],'week'=>$row['weekly_token_limit']===null?null:(int)$row['weekly_token_limit'],'month'=>$row['monthly_token_limit']===null?null:(int)$row['monthly_token_limit']],'limits'=>$limits,'usage'=>$usage,'request_limits'=>$requestLimits,'request_usage'=>$requestUsage,'period'=>['start'=>(string)($row['package_period_start']??''),'end'=>(string)($row['package_period_end']??'')],'note'=>(string)($row['note']??''),'updated_at'=>(string)($row['updated_at']??'')];
}
function mg_ai_credit_preflight(PDO $pdo,int $userId,string $providerKey='anthropic',int $minimumTokens=1,string $source='ai_request'): array
{
    $snapshot=mg_ai_credit_snapshot($pdo,$userId,$providerKey);if(empty($snapshot['schema_ready']))return $snapshot;$minimumTokens=max(1,$minimumTokens);if(empty($snapshot['enabled']))throw new MgAiCreditException('AI access is disabled for this account.',402,['scope'=>'ai_disabled','ai_credits'=>$snapshot]);foreach(['day'=>'daily','week'=>'weekly','month'=>'monthly'] as $key=>$label){$limit=$snapshot['limits'][$key]??null;$used=(int)($snapshot['usage'][$key]??0);if($limit!==null&&($used+$minimumTokens)>(int)$limit)throw new MgAiCreditException('The '.$label.' AI token allowance has been reached.',402,['scope'=>'ai_'.$key.'_limit','ai_credits'=>$snapshot,'source'=>$source]);}foreach(['hour','day'] as $key){$limit=$snapshot['request_limits'][$key]??null;$used=(int)($snapshot['request_usage'][$key]??0);if($limit!==null&&$used>=(int)$limit)throw new MgAiCreditException('The AI request limit for this account has been reached.',429,['scope'=>'ai_request_'.$key,'ai_credits'=>$snapshot,'source'=>$source]);}if($snapshot['available_tokens']!==null&&(int)$snapshot['available_tokens']<$minimumTokens)throw new MgAiCreditException('This account does not have enough AI token credits for another request.',402,['scope'=>'ai_credit_balance','ai_credits'=>$snapshot,'source'=>$source]);return $snapshot;
}
function mg_ai_credit_consume(PDO $pdo,int $userId,int $providerId,?int $modelId,string $providerKey,int $inputTokens,int $outputTokens,string $sourceType,string $sourceReference='',array $metadata=[]): array
{
    $providerKey=mg_ai_credit_provider_key($providerKey);$inputTokens=max(0,$inputTokens);$outputTokens=max(0,$outputTokens);$total=max(1,$inputTokens+$outputTokens);if(!mg_ai_credit_schema_ready($pdo))return mg_ai_credit_snapshot($pdo,$userId,$providerKey);$owns=!$pdo->inTransaction();if($owns)$pdo->beginTransaction();try{mg_ai_credit_sync_account($pdo,$userId,$providerKey);$stmt=$pdo->prepare('SELECT * FROM ai_user_credit_accounts WHERE user_id=? AND provider_key=? LIMIT 1 FOR UPDATE');$stmt->execute([$userId,$providerKey]);$account=$stmt->fetch(PDO::FETCH_ASSOC)?:[];$idempotency=$sourceReference!==''?implode(':',['usage',$userId,$providerKey,$sourceType,$sourceReference]):'';if($idempotency!==''){$check=$pdo->prepare('SELECT id FROM ai_credit_ledger WHERE idempotency_key=? LIMIT 1');$check->execute([$idempotency]);if($check->fetchColumn()){if($owns)$pdo->commit();return mg_ai_credit_snapshot($pdo,$userId,$providerKey);}}$packageUnlimited=$account['package_tokens_remaining']===null;$packageRemaining=$packageUnlimited?null:(int)$account['package_tokens_remaining'];$manualRemaining=(int)($account['manual_tokens_remaining']??0);$packageUsed=$packageUnlimited?$total:min($total,max(0,$packageRemaining));$remaining=max(0,$total-$packageUsed);$manualUsed=min($remaining,max(0,$manualRemaining));$overage=max(0,$remaining-$manualUsed);$newPackage=$packageUnlimited?null:max(0,$packageRemaining-$packageUsed);$newManual=max(0,$manualRemaining-$manualUsed);$update=$pdo->prepare('UPDATE ai_user_credit_accounts SET package_tokens_remaining=?,manual_tokens_remaining=?,updated_at=NOW() WHERE user_id=? AND provider_key=?');$update->execute([$newPackage,$newManual,$userId,$providerKey]);mg_ai_credit_ledger_write($pdo,['user_id'=>$userId,'provider_key'=>$providerKey,'provider_id'=>$providerId,'model_id'=>$modelId,'entry_type'=>'usage_debit','token_delta'=>-$total,'package_token_delta'=>-$packageUsed,'manual_token_delta'=>-$manualUsed,'input_tokens'=>$inputTokens,'output_tokens'=>$outputTokens,'source_type'=>$sourceType,'source_reference'=>$sourceReference,'idempotency_key'=>$idempotency,'metadata'=>$metadata+['overage_tokens'=>$overage,'package_unlimited'=>$packageUnlimited]]);if($owns)$pdo->commit();}catch(Throwable $error){if($owns&&$pdo->inTransaction())$pdo->rollBack();throw $error;}return mg_ai_credit_snapshot($pdo,$userId,$providerKey);
}
function mg_ai_credit_save_policy(PDO $pdo,int $userId,string $providerKey,array $input,int $adminUserId): array
{
    if(!mg_ai_credit_schema_ready($pdo))throw new MgAiCreditException('Import the AI user-credit migration before editing credit policy.',503,['scope'=>'ai_credit_schema']);$providerKey=mg_ai_credit_provider_key($providerKey);mg_ai_credit_sync_account($pdo,$userId,$providerKey);$stmt=$pdo->prepare('UPDATE ai_user_credit_accounts SET enabled=?,daily_token_limit=?,weekly_token_limit=?,monthly_token_limit=?,requests_per_hour=?,requests_per_day=?,note=?,updated_by_user_id=?,updated_at=NOW() WHERE user_id=? AND provider_key=?');$stmt->execute([!array_key_exists('enabled',$input)||!empty($input['enabled'])?1:0,mg_ai_credit_nullable_int($input['daily_token_limit']??null),mg_ai_credit_nullable_int($input['weekly_token_limit']??null),mg_ai_credit_nullable_int($input['monthly_token_limit']??null),mg_ai_credit_nullable_int($input['requests_per_hour']??null,1000000),mg_ai_credit_nullable_int($input['requests_per_day']??null,1000000),mb_substr(trim((string)($input['note']??'')),0,500)?:null,$adminUserId,$userId,$providerKey]);return mg_ai_credit_snapshot($pdo,$userId,$providerKey);
}
function mg_ai_credit_grant(PDO $pdo,int $userId,string $providerKey,int $tokens,int $adminUserId,string $note=''): array
{
    $tokens=mg_ai_credit_int($tokens);if($tokens<1)throw new InvalidArgumentException('Token credit must be greater than 0.');if(!mg_ai_credit_schema_ready($pdo))throw new MgAiCreditException('Import the AI user-credit migration before granting tokens.',503,['scope'=>'ai_credit_schema']);$providerKey=mg_ai_credit_provider_key($providerKey);$owns=!$pdo->inTransaction();if($owns)$pdo->beginTransaction();try{mg_ai_credit_sync_account($pdo,$userId,$providerKey);$stmt=$pdo->prepare('UPDATE ai_user_credit_accounts SET manual_tokens_remaining=manual_tokens_remaining+?,updated_by_user_id=?,updated_at=NOW() WHERE user_id=? AND provider_key=?');$stmt->execute([$tokens,$adminUserId,$userId,$providerKey]);mg_ai_credit_ledger_write($pdo,['user_id'=>$userId,'provider_key'=>$providerKey,'entry_type'=>'admin_grant','token_delta'=>$tokens,'manual_token_delta'=>$tokens,'source_type'=>'admin_credit_grant','source_reference'=>'admin:'.$adminUserId,'actor_user_id'=>$adminUserId,'metadata'=>['note'=>mb_substr(trim($note),0,500)]]);if($owns)$pdo->commit();}catch(Throwable $error){if($owns&&$pdo->inTransaction())$pdo->rollBack();throw $error;}return mg_ai_credit_snapshot($pdo,$userId,$providerKey);
}
function mg_ai_credit_recent_ledger(PDO $pdo,int $userId,int $limit=12): array
{
    if(!mg_ai_credit_schema_ready($pdo))return [];$limit=max(1,min(50,$limit));$stmt=$pdo->prepare("SELECT public_id,provider_key,entry_type,token_delta,package_token_delta,manual_token_delta,input_tokens,output_tokens,source_type,source_reference,actor_user_id,metadata_json,created_at FROM ai_credit_ledger WHERE user_id=? ORDER BY id DESC LIMIT {$limit}");$stmt->execute([$userId]);return array_map(static function(array $row):array{$metadata=json_decode((string)($row['metadata_json']??''),true);return ['id'=>(string)$row['public_id'],'provider_key'=>(string)$row['provider_key'],'entry_type'=>(string)$row['entry_type'],'token_delta'=>(int)$row['token_delta'],'package_token_delta'=>(int)$row['package_token_delta'],'manual_token_delta'=>(int)$row['manual_token_delta'],'input_tokens'=>(int)$row['input_tokens'],'output_tokens'=>(int)$row['output_tokens'],'source_type'=>(string)$row['source_type'],'source_reference'=>(string)($row['source_reference']??''),'actor_user_id'=>$row['actor_user_id']!==null?(int)$row['actor_user_id']:null,'metadata'=>is_array($metadata)?$metadata:[],'created_at'=>(string)$row['created_at']];},$stmt->fetchAll(PDO::FETCH_ASSOC)?:[]);
}
