<?php
declare(strict_types=1);
return [
    'release_key' => 'microgifter_mcp_automation_definitions_phase4b_v1',
    'phase' => 'mcp_automation_definitions_phase4b',
    'depends_on' => ['microgifter_mcp_automation_grants_phase4a_v1'],
    'required_migrations' => [
        '20260720_microgifter_mcp_automation_foundation_v1',
        '20260720_mcp_external_agent_authorization_phase2a_v1',
        '20260720_mcp_approval_gated_drafts_phase3a_v1',
        '20260720_mcp_approved_draft_conversion_phase3b_v1',
    ],
    'new_migrations' => [],
    'operation_ceiling' => 'owner_definition_and_manual_simulation_only',
    'runtime_execution_enabled' => false,
    'scheduler_enabled' => false,
    'worker_enabled' => false,
    'allowed_trigger_types' => ['manual'],
    'simulation_action_status' => 'proposed',
    'action_receipts_created' => false,
    'capabilities' => [
        'owner_scoped_automation_definition_creation',
        'grant_bound_fixed_playbook_selection',
        'draft_activate_pause_resume_and_revoke_lifecycle',
        'manual_policy_simulation',
        'durable_simulation_run_history',
        'proposed_action_evidence_without_execution',
        'grant_scope_workspace_limit_and_target_revalidation',
        'audit_event_and_security_evidence',
    ],
    'prohibited' => [
        'schedule_creation',
        'canonical_event_trigger_registration',
        'queue_or_worker_execution',
        'canonical_command_invocation',
        'action_receipt_creation',
        'external_effect_action',
        'purchase_or_charge',
        'gift_issuance_or_delivery',
        'campaign_publication_or_scheduling',
        'message_sending',
        'reward_activation_or_fulfillment',
        'node_runtime_activation',
        'production_key_generation',
    ],
];
