<?php
declare(strict_types=1);

return [
    'release_key' => 'microgifter_mcp_phase1_foundation_v1',
    'program' => 'microgifter_platform_phase5',
    'phase' => 'mcp_phase1_foundation',
    'depends_on' => [
        'microgifter_mcp_phase0_contract_v1',
        'task_agent_phase4_v1',
    ],
    'required_migrations' => [
        '20260720_microgifter_mcp_automation_foundation_v1.sql',
    ],
    'service_root' => 'services/mcp/',
    'runtime' => [
        'language' => 'typescript',
        'node' => '>=20',
        'enabled_by_default' => false,
        'public_http_enabled' => false,
        'oauth_enabled' => false,
        'scheduler_enabled' => false,
        'worker_enabled' => false,
        'write_tools_enabled' => false,
        'bounded_automation_enabled' => false,
    ],
    'control_plane_tables' => [
        'mcp_scope_catalog',
        'mcp_clients',
        'mcp_connections',
        'mcp_connection_scopes',
        'mcp_automation_grants',
        'mcp_automations',
        'mcp_automation_triggers',
        'mcp_automation_runs',
        'mcp_automation_actions',
        'mcp_action_approval_links',
        'mcp_idempotency_keys',
        'mcp_tool_invocations',
        'mcp_action_receipts',
        'mcp_security_events',
        'mcp_rate_limit_buckets',
        'mcp_worker_leases',
    ],
    'operation_classes' => [
        'read',
        'monitor',
        'recommend',
        'task',
        'draft',
        'approval_gated',
        'bounded_auto',
        'prohibited',
    ],
    'automation_statuses' => [
        'draft',
        'pending_approval',
        'active',
        'paused',
        'completed',
        'failed',
        'expired',
        'revoked',
    ],
    'run_statuses' => [
        'queued',
        'evaluating',
        'waiting_for_approval',
        'approved',
        'executing',
        'succeeded',
        'partially_succeeded',
        'failed',
        'cancelled',
        'dead_lettered',
    ],
    'trigger_types' => [
        'manual',
        'fixed_schedule',
        'recurring_schedule',
        'canonical_event',
        'condition',
        'monitor_threshold',
    ],
    'initial_active_scopes' => [
        'profile:read',
        'catalog:read',
    ],
    'initial_tool_contracts' => [
        'microgifter.account.get_connection_context',
        'microgifter.catalog.search',
        'microgifter.catalog.get_item',
    ],
    'ports' => [
        'AutomationRepository',
        'CanonicalBridge',
        'AutomationQueue',
        'WorkerLeaseRepository',
    ],
    'boundaries' => [
        'foundation_disabled_by_default',
        'no_public_http_endpoint',
        'no_external_oauth',
        'no_active_scheduler_or_worker',
        'no_write_tool_execution',
        'no_bounded_automation_execution',
        'no_node_database_credentials',
        'canonical_php_bridge_required',
        'durable_grant_required_for_unattended_execution',
        'existing_approval_center_remains_authoritative',
        'no_generic_sql_file_shell_callback_webhook_or_url_tools',
        'no_unbounded_autonomous_mode',
    ],
];
