<?php
declare(strict_types=1);

return [
    'release_key' => 'microgifter_mcp_automation_schedules_phase4c_v1',
    'phase' => 'mcp_automation_schedules_phase4c',
    'depends_on' => [
        'microgifter_mcp_automation_definitions_phase4b_v1',
    ],
    'required_migrations' => [
        '20260720_microgifter_mcp_automation_foundation_v1',
        '20260720_mcp_external_agent_authorization_phase2a_v1',
        '20260720_mcp_approval_gated_drafts_phase3a_v1',
        '20260720_mcp_approved_draft_conversion_phase3b_v1',
    ],
    'new_migrations' => [],
    'operation_ceiling' => 'owner_scheduled_simulation_control_only',
    'runtime_execution_enabled' => false,
    'background_scheduler_enabled' => false,
    'worker_enabled' => false,
    'allowed_trigger_types' => ['manual', 'fixed_schedule', 'recurring_schedule'],
    'trigger_fire_mode' => 'owner_manual_due_evaluation',
    'minimum_recurring_interval_seconds' => 3600,
    'maximum_due_batch' => 10,
    'action_status' => 'proposed',
    'action_receipts_created' => 0,
    'capabilities' => [
        'owner_schedule_authority_configuration',
        'fixed_simulation_due_records',
        'recurring_simulation_due_records',
        'timezone_aware_first_due_conversion',
        'owner_manual_due_evaluation',
        'grant_policy_revalidation_at_fire_time',
        'deterministic_scheduled_run_idempotency',
        'fixed_trigger_expiration',
        'recurring_trigger_due_advancement',
        'scheduled_simulation_history',
    ],
    'prohibited' => [
        'cron_or_background_scheduler',
        'queue_or_worker_execution',
        'automatic_trigger_firing',
        'canonical_command_invocation',
        'action_receipt_creation',
        'external_effect_action',
        'purchase_or_charge',
        'gift_issuance_or_delivery',
        'campaign_publication_or_scheduling',
        'message_sending',
        'reward_activation_or_fulfillment',
        'node_runtime_activation',
        'production_key_generation',
    ],
];
