<?php
declare(strict_types=1);

return [
    'release_key' => 'microgifter_mcp_external_agent_authorization_phase2a_v1',
    'program' => 'microgifter_platform_phase5',
    'phase' => 'mcp_external_agent_authorization_phase2a',
    'depends_on' => [
        'microgifter_mcp_phase1_foundation_v1',
        'microgifter_mcp_phase1_protocol_v1',
        'microgifter_mcp_phase1_canonical_bridge_v1',
        'microgifter_mcp_phase1_provisioning_console_v1',
        'microgifter_mcp_production_vps_deployment_v1',
    ],
    'required_migrations' => [
        '20260720_mcp_external_agent_authorization_phase2a_v1',
    ],
    'oauth_profile' => 'oauth_2_1_public_clients_pkce_s256',
    'resource_uri' => 'https://mcp.microgifter.com/mcp',
    'authorization_issuer' => 'https://microgifter.com',
    'capabilities' => [
        'authorization_server_metadata',
        'protected_resource_metadata',
        'authorization_code_grant',
        'pkce_s256',
        'resource_indicators',
        'exact_redirect_uri_matching',
        'dynamic_client_registration_optional',
        'admin_client_preregistration',
        'user_consent',
        'workspace_selection',
        'hashed_access_tokens',
        'rotating_refresh_tokens',
        'refresh_reuse_family_revocation',
        'token_revocation',
        'dynamic_connection_resolution',
        'user_ai_connection_management',
    ],
    'security' => [
        'raw_tokens_never_persisted',
        'php_remains_authorization_authority',
        'node_receives_no_database_credentials',
        'bridge_hmac_and_replay_protection',
        'short_lived_access_tokens',
        'refresh_rotation',
        'connection_token_version_invalidation',
        'read_only_scope_catalog',
        'csrf_protected_user_consent',
        'csrf_protected_user_revocation',
        'https_required_except_loopback_redirects',
    ],
    'boundaries' => [
        'read_only_tools_only',
        'no_write_capable_tools',
        'no_scheduler_or_worker',
        'no_autonomous_purchases',
        'no_production_connection_claim_until_public_endpoint_deployed',
    ],
];
