<?php
declare(strict_types=1);

return [
    'release_key' => 'microgifter_mcp_production_vps_deployment_v1',
    'program' => 'microgifter_platform_phase5',
    'phase' => 'mcp_production_vps_deployment',
    'depends_on' => [
        'microgifter_mcp_phase1_foundation_v1',
        'microgifter_mcp_phase1_protocol_v1',
        'microgifter_mcp_phase1_canonical_bridge_v1',
        'microgifter_mcp_phase1_provisioning_console_v1',
    ],
    'required_migrations' => [],
    'node_engine' => '>=20',
    'public_endpoint' => 'https://mcp.microgifter.com/mcp',
    'internal_listener' => '127.0.0.1:8787',
    'health_endpoints' => ['/health', '/ready'],
    'deployment_modes' => ['systemd', 'docker_compose'],
    'capabilities' => [
        'production_environment_validation',
        'structured_json_logging',
        'liveness_and_readiness',
        'bridge_backed_readiness',
        'graceful_request_draining',
        'systemd_process_supervision',
        'docker_multi_stage_runtime',
        'nginx_tls_reverse_proxy',
        'atomic_release_installation',
        'automatic_restart_rollback',
        'authenticated_smoke_test',
    ],
    'security' => [
        'loopback_only_internal_listener',
        'explicit_production_allowed_hosts',
        'https_public_origin_required',
        'non_root_service_user',
        'systemd_sandboxing',
        'docker_capabilities_dropped',
        'docker_read_only_filesystem',
        'secrets_external_to_repository',
        'no_node_database_credentials',
        'health_payloads_exclude_secrets',
        'logs_redact_sensitive_fields',
    ],
    'boundaries' => [
        'phase1_read_only_tools_only',
        'no_external_oauth',
        'no_scheduler_or_worker',
        'no_direct_database_access_from_node',
        'no_firewall_mutation_by_installer',
        'no_certificate_issuance_by_installer',
    ],
];
