<?php
declare(strict_types=1);

/**
 * Canonical Microgifter migration manifest.
 */
return [
    'ordered_files' => [
        'stage_1_identity.sql',
        'stage_1_repair_03M.sql',
        'stage_1_security_hardening_03N.sql',
        'stage_1_security_hardening_03N_3.sql',
        'stage_1_high_volume_foundation_03O.sql',
        'stage_1_delivery_events_03R.sql',
        'stage_1_foundation_closure.sql',
        '02A_user_models_identity_profiles.sql',
        '02C_model_default_roles_seed.sql',
        '02D_public_profiles_schema.sql',
        '02G_sales_model_and_crm_schema.sql',
        '02I_sales_presence_and_employee_chat.sql',
        'stage_3_agent_persistence.sql',
        'stage_3_gift_activity_persistence.sql',
        'stage_3_gift_lifecycle.sql',
        'stage_3_merchant_claim_codes.sql',
        'stage_3_pppm_core.sql',
        'stage_3_pppm_activity_layer.sql',
        'stage_3_pppm_delivery_assignment.sql',
        'stage_4_product_asset_foundation.sql',
        'stage_4b_builder_persistence.sql',
        'stage_4c_feed_stream_storefronts.sql',
        'stage_4d_digital_fulfillment_media.sql',
        'stage_4e_distribution_external_inputs.sql',
        'stage_public_distribution_api_foundation.sql',
        'stage_public_distribution_api_account_links_note.sql',
        'stage_public_distribution_api_webhooks.sql',
        'stage_public_distribution_api_quotas.sql',
        'stage_public_distribution_api_sandbox.sql',
        'stage_4f_future_demand_intelligence.sql',
        'stage_5a_merchant_workspace.sql',
        'stage_5c_storefront_management.sql',
        'stage_5d_merchant_pppm_operations.sql',
        'stage_5e_merchant_distribution_operations.sql',
        'stage_5f_merchant_intelligence_reporting.sql',
        'stage_5g_claim_operations.sql',
        'stage_5h_notifications_messaging_alerts.sql',
        'stage_5i_message_crm_ops.sql',
        'stage_5i_payments_checkout_reconciliation.sql',
        'stage_v1c_checkout_session_intent_authority.sql',
        'stage_v1f_stripe_payments.sql',
        'stage_3_commerce_microgift_fulfillment.sql',
        'stage_5j_foundation_reconciliation.sql',
        'stage_7b_money_engine.sql',
        'stage_8b_entitlements_library.sql',
        'stage_8c_entitlement_lifecycle.sql',
        'stage_9b_microgift_engine.sql',
        'stage_9c_microgift_lifecycle.sql',
        'stage_9d_microgift_operations.sql',
        'stage_10b_location_claim_authority.sql',
        'stage_10c_atomic_claim_redemption_inbox.sql',
        'stage_10d_merchant_claim_operations.sql',
        'stage_10e_outbox_dashboard_policies_retention.sql',
        'stage_10f_architecture_deployment_action_center.sql',
        'stage_11g_action_center_durable_messaging.sql',
        'stage_v1d_transfer_conversations.sql',
        'schema_v2_action_center_crm_addendum.sql',
        'stage_11h_backend_hardening.sql',
        'stage_12_universal_tips.sql',
        'stage_12a_tip_financial_integrity.sql',
        'stage_12d_tip_recovery.sql',
        'stage_13_subscriptions_monetization.sql',
        'stage_13b_subscription_package_changes.sql',
        'stage_14_posts_feed_social.sql',
        'stage_14b_social_content.sql',
        'stage_15_psr_demand_intelligence.sql',
        'stage_15c_prepaid_demand_commitments.sql',
        'stage_16_agent_execution_orchestration.sql',
        'stage_17_multi_agent_swarms.sql',
        'stage_17b_demand_signal_agent_orchestration.sql',
        'stage_17_stamp_ledger.sql',
        'stage_17b_stamp_purchases.sql',
        'stage_17c_stamp_package_assignments.sql',
        'stage_18_production_hardening_launch_readiness.sql',
        'stage_18b_demand_orchestration_operations.sql',
        'stage_18c_demand_orchestration_recovery.sql',
        'stage_18c2_demand_orchestration_retention.sql',
        'stage_18d_profile_moderation.sql',
        'stage_18e_engagement_mutations.sql',
        'stage_18f_pppm_publish_distribution.sql',
        'stage_18g_pppm_resend_timeline.sql',
        'stage_18h_feed_media_assets.sql',
        'stage_18i_recipient_notifications.sql',
        'stage_12_campaigns_reward_templates.sql',
        'stage_12b_campaign_events_agent_context.sql',
        'stage_12j_campaign_feature_sql_hardening.sql',
        'stage_12k_reward_media_packs.sql',
        'stage_12l_reward_media_pack_schema_repair.sql',
        'stage_12_merchant_crm.sql',
        'stage_12_campaign_followups.sql',
        'stage_12_message_delivery_campaign_suppression.sql',
        'stage_12_crm_reward_invites.sql',
        'stage_12_crm_message_account_link_repair.sql',
        'stage_18j_content_moderation.sql',
        'stage_18k_admin_account_management.sql',
        'stage_18l_admin_commerce_operations.sql',
        'stage_18l2_admin_commerce_permission_split.sql',
        'stage_18m_admin_merchant_catalog_operations.sql',
        'stage_18n_admin_user_notes.sql',
        'stage_18o_admin_queue_notes.sql',
        'stage_18p_admin_queue_notifications.sql',
        'stage_18q_admin_notifications_center.sql',
        'stage_18r_admin_queue_sla_routing.sql',
        'stage_18s_admin_queue_playbooks.sql',
        'stage_18t_admin_case_timeline.sql',
        'stage_18u_admin_resolution_reporting.sql',
        'stage_18v_admin_queue_automation.sql',
        'stage_18w_admin_operations_command.sql',
        'stage_18x_admin_ops_incidents.sql',
        'stage_18y_admin_incident_reviews.sql',
        'stage_18z_admin_incident_analytics.sql',
        'stage_18aa_admin_predictive_ops.sql',
        'stage_18ac_claim_voucher_tokens.sql',
        'stage_18ah_wallet_claim_integrity.sql',
        'stage_18ad_scanner_trust_operations.sql',
        'stage_18ae_scanner_operations_control.sql',
        'stage_18af_redemption_finance_disputes.sql',
        'stage_18ag_subscription_billing_value_reconciliation.sql',
        'stage_19_ai_provider_models.sql',
        'stage_19b_ai_permission_guard.sql',
        'stage_19c_claude_sonnet_merchant_agent_planner.sql',
        'stage_19_merchant_market_snapshots.sql',
        'stage_20_agent_store_canvas.sql',
        'stage_20b_store_canvas_trigger_zones.sql',
        'stage_20c_store_canvas_trigger_analytics_stamps.sql',
        'stage_20d_store_canvas_automation_rules.sql',
        'stage_20_buy_in_share_market.sql',
        'stage_21_buy_in_execution_audit_scaffolding.sql',
        'stage_22_buy_in_evidence_candidates.sql',
        'stage_23_buy_in_final_reviewer_acknowledgements.sql',
        'stage_24_buy_in_handoff_archives.sql',
        'stage_25_pwa_notifications.sql',
        'stage_26_merchant_branded_pwa.sql',
        'stage_v1_release_trigger_portability.sql',
    ],
    'coverage_markers' => [
        'stage_9e4_consolidated_stage1_to_stage9_upgrade' => 'stage_9d_microgift_operations.sql',
        'stage_11h_backend_hardening' => 'schema_v2_action_center_crm_addendum.sql',
        'stage_v1_release_trigger_portability' => 'stage_v1_release_trigger_portability.sql',
    ],
    'manual_only' => [
        '03Z_bootstrap_super_admin_user1.sql' => 'Manual operator import only.',
        'microgifter_complete_production_update_v1c_v1release.sql' => 'Manual consolidated production bundle.',
        'stage_12_campaign_features_full_import.sql' => 'Manual Stage 12 campaign import.',
        'stage_12_crm_followups_full_import.sql' => 'Manual Stage 12 CRM import.',
        'stage_17_all_stamp_system.sql' => 'Manual consolidated Stamp system import.',
        'stage_19_design_studio_qr_library.sql' => 'Manual Stage 19 Design Studio import.',
        'stage_19_design_studio_campaign_links_import_fix.sql' => 'Manual Stage 19 recovery import.',
    ],
];
