<?php
declare(strict_types=1);

return [
    'version' => '1.0.0',
    'name' => 'Microgifter Production Launch Certification v1',
    'target_branch' => 'integration-from-repair-20260628',
    'automated_target' => 'All required automated gates pass on the exact candidate head.',
    'launch_target' => 'Automated certification plus completed production manual sign-off.',
    'scope_exclusions' => [
        'Accessibility Center and WCAG controls are tracked separately and are not part of this certification package.',
    ],
    'required_files' => [
        'composer.json',
        'composer.lock',
        'config/migrations.php',
        'config/production-launch-certification-v1.php',
        'scripts/validate_production_launch_contract_v1.php',
        'scripts/write_production_launch_gate_evidence_v1.php',
        'scripts/build_production_launch_evidence_v1.php',
        'docs/production-launch-certification-v1.md',
        'docs/production-launch-manual-evidence-template-v1.json',
        '.github/workflows/production-launch-certification-v1.yml',
        'scripts/validate_migration_manifest.php',
        'scripts/build_full_upgrade_sql.php',
        'scripts/validate_database_migration_status.php',
        'scripts/audit_repository_production_quality.php',
        'scripts/recovery_baseline.sh',
        'scripts/validate_database_backup_restore.sh',
        'scripts/build_release_artifact.sh',
        'scripts/validate_release_rollback.sh',
        'scripts/validate_checkout_capture_behavior.php',
        'scripts/validate_lifecycle_completion.php',
        'scripts/check_media_storage.php',
        'api/health.php',
        'tests/phpunit/SecurityFoundationTest.php',
        'tests/browser/v1-release-golden-path.spec.js',
        'terms.php',
        'privacy.php',
        'notification-preferences.php',
        '.github/workflows/recovery-baseline.yml',
        '.github/workflows/release-package-validation.yml',
        '.github/workflows/browser-validation.yml',
    ],
    'required_composer_scripts' => [
        'test-security',
        'test-frontend-contracts',
        'test-money-behavior',
        'test-microgift-behavior',
        'test-pppm-resend-behavior',
        'audit-product-pppm-golden-path-gate',
        'test-checkout-fulfillment',
        'test-lifecycle-completion',
        'test-active-recovery',
        'audit-repository-quality',
        'validate-launch-contract',
        'build-launch-summary',
        'build-release',
        'validate-backup-restore',
        'validate-release-rollback',
        'migrate',
    ],
    'content_contracts' => [
        'terms.php' => [
            'Terms of Service',
            'merchant',
            'gift',
            'refund',
        ],
        'privacy.php' => [
            'Privacy Policy',
            'does not sell',
            'retain',
            'delete',
        ],
        'scripts/validate_database_backup_restore.sh' => [
            'single-transaction',
            'restore',
            'sha256',
            'validate_database_migration_status.php',
        ],
        'scripts/validate_release_rollback.sh' => [
            'rollback',
            'RELEASE.json',
            'database_downgrade_policy',
        ],
        'scripts/validate_checkout_capture_behavior.php' => [
            'capture_replay',
            'ledger_balanced',
            'microgifts_issued',
            'notifications_once',
        ],
        '.github/workflows/production-launch-certification-v1.yml' => [
            'integration-from-repair-20260628',
            'database_mysql_8',
            'database_mariadb_10_11',
            'backup_restore_mysql_8',
            'release_reproducibility',
            'release_rollback',
            'browser_chromium',
        ],
    ],
    'required_automated_gates' => [
        'contract_php_82' => ['weight' => 5, 'label' => 'Launch contract on PHP 8.2'],
        'contract_php_83' => ['weight' => 5, 'label' => 'Launch contract on PHP 8.3'],
        'repository_quality' => ['weight' => 10, 'label' => 'Repository production-quality gate'],
        'migration_manifest' => ['weight' => 10, 'label' => 'Canonical migration manifest and upgrade build'],
        'database_mysql_8' => ['weight' => 15, 'label' => 'MySQL 8 migration, security, commerce, gifting, and recovery'],
        'database_mariadb_10_11' => ['weight' => 15, 'label' => 'MariaDB 10.11 migration, security, commerce, gifting, and recovery'],
        'backup_restore_mysql_8' => ['weight' => 10, 'label' => 'Consistent backup and isolated restore'],
        'release_reproducibility' => ['weight' => 10, 'label' => 'Reproducible candidate release package'],
        'release_rollback' => ['weight' => 10, 'label' => 'Candidate and rollback package validation'],
        'browser_chromium' => ['weight' => 10, 'label' => 'Production browser golden-path smoke test'],
    ],
    'manual_signoffs' => [
        'production_environment' => 'Production secrets, HTTPS, trusted proxy, sessions, storage, cron/worker, and health configuration verified.',
        'payment_provider' => 'Live payment credentials, webhook delivery, authorization/capture, refund, dispute, and duplicate-event behavior verified.',
        'email_delivery' => 'SPF, DKIM, DMARC, transactional sender, bounce handling, and critical customer/merchant messages verified in production.',
        'legal_review' => 'Terms, privacy, refund/cancellation, gift expiration/unclaimed value, merchant terms, AI disclosures, and investor statements reviewed by qualified counsel.',
        'feature_scope' => 'Launch, pilot, beta, and disabled features explicitly approved; unfinished features are hidden or clearly labeled.',
        'backup_retention' => 'Production database and persistent-media backups, retention, encryption, access control, and off-host storage verified.',
        'restore_drill' => 'A real production-like database and media restoration drill completed with recovery time recorded.',
        'support_operations' => 'Support contact, account recovery, refund process, incident owners, escalation levels, and first-week monitoring schedule approved.',
        'deployment_rollback' => 'Candidate commit, release artifact, migration set, predeployment snapshot, rollback artifact, and operator rollback steps approved.',
    ],
];
