<?php
declare(strict_types=1);
require_once __DIR__ . '/_claims.php';
mg_require_method('GET');
$user=mg_require_permission('merchant.claims.view');$pdo=mg_db();$workspace=mg_claim_workspace($pdo,$user);
$status=trim((string)($_GET['status']??'all'));$location=trim((string)($_GET['location']??'all'));$q=trim((string)($_GET['q']??''));
$sql="SELECT gc.public_id claim_id,g.public_id gift_id,pi.public_id pppm_id,g.title,g.value_cents,g.currency,g.status gift_status,gc.status claim_status,gc.failed_attempts,gc.locked_at,gc.verified_at,gc.redeemed_at,gc.expires_at,ml.public_id location_id,ml.name location_name,mcc.label code_label,mcc.code_last4,COUNT(DISTINCT gce.id) exception_count FROM gift_claims gc INNER JOIN gifts g ON g.id=gc.gift_id INNER JOIN gift_merchant_eligibility e ON e.gift_id=g.id AND e.merchant_user_id=? LEFT JOIN merchant_locations ml ON ml.id=gc.location_id LEFT JOIN merchant_claim_codes mcc ON mcc.id=gc.merchant_claim_code_id LEFT JOIN pppm_legacy_gift_map lgm ON lgm.gift_id=g.id LEFT JOIN pppm_items pi ON pi.id=lgm.pppm_item_id LEFT JOIN merchant_claim_exceptions gce ON gce.claim_id=gc.id AND gce.status NOT IN ('resolved','closed') WHERE 1=1";$params=[(int)$user['id']];
if($status!=='all'){$sql.=' AND gc.status=?';$params[]=$status;}if($location!=='all'){$sql.=' AND ml.public_id=?';$params[]=$location;}if($q!==''){$like='%'.$q.'%';$sql.=' AND (g.public_id LIKE ? OR pi.public_id LIKE ? OR gc.public_id LIKE ? OR g.title LIKE ?)';array_push($params,$like,$like,$like,$like);}$sql.=' GROUP BY gc.id,g.id,pi.id,ml.id,mcc.id ORDER BY gc.updated_at DESC,gc.id DESC LIMIT 500';$stmt=$pdo->prepare($sql);$stmt->execute($params);
$counts=$pdo->prepare("SELECT COUNT(DISTINCT gc.id) total,SUM(gc.status='pending') pending,SUM(gc.status='verified') verified,SUM(gc.status='redeemed') redeemed,SUM(gc.status='locked') locked,SUM(gc.status='expired') expired FROM gift_claims gc INNER JOIN gifts g ON g.id=gc.gift_id INNER JOIN gift_merchant_eligibility e ON e.gift_id=g.id WHERE e.merchant_user_id=?");$counts->execute([(int)$user['id']]);
$locations=$pdo->prepare("SELECT ml.public_id,ml.name,ml.status,COUNT(DISTINCT mcc.id) code_count,SUM(mcc.status='active') active_codes FROM merchant_locations ml LEFT JOIN merchant_claim_codes mcc ON mcc.location_id=ml.id AND mcc.merchant_user_id=? WHERE ml.workspace_id=? GROUP BY ml.id ORDER BY ml.is_primary DESC,ml.name");$locations->execute([(int)$user['id'],(int)$workspace['id']]);
$codes=$pdo->prepare("SELECT mcc.public_id,mcc.label,mcc.code_last4,mcc.status,mcc.valid_from,mcc.valid_until,mcc.usage_limit,mcc.usage_count,ml.public_id location_id,ml.name location_name FROM merchant_claim_codes mcc INNER JOIN merchant_locations ml ON ml.id=mcc.location_id WHERE mcc.merchant_user_id=? AND ml.workspace_id=? ORDER BY ml.name,mcc.label");$codes->execute([(int)$user['id'],(int)$workspace['id']]);
$exceptions=$pdo->prepare("SELECT mce.public_id,mce.exception_type,mce.status,mce.priority,mce.summary,mce.created_at,g.public_id gift_id,pi.public_id pppm_id FROM merchant_claim_exceptions mce INNER JOIN gift_claims gc ON gc.id=mce.claim_id INNER JOIN gifts g ON g.id=gc.gift_id LEFT JOIN pppm_items pi ON pi.id=mce.pppm_item_id WHERE mce.merchant_user_id=? AND mce.status NOT IN ('resolved','closed') ORDER BY FIELD(mce.priority,'urgent','high','normal','low'),mce.updated_at DESC LIMIT 50");$exceptions->execute([(int)$user['id']]);
mg_ok(['counts'=>$counts->fetch()?:[],'claims'=>$stmt->fetchAll(),'locations'=>$locations->fetchAll(),'claim_codes'=>$codes->fetchAll(),'exceptions'=>$exceptions->fetchAll()]);
