<?php declare(strict_types=1); ?>
<section class="mg-merchant-heading"><div><span class="mg-eyebrow">Future demand intelligence</span><h1>Intelligence &amp; reporting</h1><p>Compare campaigns, products, locations, engagement, PPPM conversion, forecasts, alerts, and operational performance.</p></div><div class="mg-heading-actions"><button class="mg-btn mg-btn-soft" type="button" data-run-forecast>Run forecast</button><button class="mg-btn mg-btn-primary" type="button" data-open-export>Export report</button></div></section>
<div class="mg-intelligence-toolbar"><label>From<input type="date" data-intelligence-from></label><label>To<input type="date" data-intelligence-to></label><button class="mg-btn mg-btn-primary" type="button" data-intelligence-apply>Apply range</button></div>
<div class="mg-merchant-kpis" data-intelligence-kpis></div>
<div class="mg-intelligence-grid">
<section class="mg-app-panel mg-span-2"><div class="mg-app-panel-head"><div><h2>Demand and lifecycle trend</h2><p>Issued units, value, opens, claims, and redemptions by day.</p></div></div><div class="mg-app-panel-body"><div class="mg-chart" data-intelligence-chart></div></div></section>
<section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>PPPM funnel</h2><p>Movement from creation to redemption.</p></div></div><div class="mg-app-panel-body"><div data-intelligence-funnel></div></div></section>
<section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Intelligence scores</h2><p>Demand, engagement, fulfillment, redemption, and growth.</p></div></div><div class="mg-app-panel-body"><div data-intelligence-scores></div></div></section>
<section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Top products</h2><p>Issued value and conversion by product.</p></div></div><div class="mg-app-panel-body"><div data-intelligence-products></div></div></section>
<section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Campaign performance</h2><p>Program output and conversion.</p></div></div><div class="mg-app-panel-body"><div data-intelligence-campaigns></div></div></section>
<section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Location performance</h2><p>Claims, redemptions, and redemption speed.</p></div></div><div class="mg-app-panel-body"><div data-intelligence-locations></div></div></section>
<section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Forecast</h2><p>Latest demand forecast with confidence range.</p></div></div><div class="mg-app-panel-body"><div data-intelligence-forecast></div></div></section>
<section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Alerts</h2><p>Open demand and performance signals.</p></div></div><div class="mg-app-panel-body"><div data-intelligence-alerts></div></div></section>
<section class="mg-app-panel mg-span-2"><div class="mg-app-panel-head"><div><h2>Saved reports &amp; exports</h2><p>Reusable views, privacy-safe exports, and scheduled-report foundations.</p></div></div><div class="mg-app-panel-body"><div class="mg-report-layout"><form class="mg-merchant-form" data-report-form><label>Report name<input name="name" required></label><label>Report type<select name="report_type"><option value="overview">Overview</option><option value="campaigns">Campaigns</option><option value="products">Products</option><option value="locations">Locations</option><option value="pppm_funnel">PPPM funnel</option><option value="engagement">Engagement</option><option value="forecast">Forecast</option></select></label><button class="mg-btn mg-btn-soft" type="submit">Save current report</button><div data-report-status></div></form><div><h3>Saved reports</h3><div data-saved-reports></div><h3>Exports</h3><div data-report-exports></div></div></div></div></section>
</div>
