<?php
declare(strict_types=1);
?>
<section class="mg-merchant-heading mg-redemption-heading">
  <div><span class="mg-eyebrow">Reward Operations</span><h1>Redeem customer rewards.</h1><p>Enter the customer’s short-lived claim code, confirm redemption, and resolve wallet support cases from one merchant-scoped workspace.</p></div>
  <div class="mg-heading-actions"><a class="mg-btn mg-btn-soft" href="/merchant-claims.php">Claims</a><button class="mg-btn mg-btn-primary" type="button" data-redemption-refresh>Refresh</button></div>
</section>
<section class="mg-campaign-kpis" aria-label="Redemption metrics"><article><span>Active codes</span><strong data-redemption-kpi-active>—</strong><small>Waiting for redemption</small></article><article><span>Redeemed</span><strong data-redemption-kpi-used>—</strong><small>Completed claim codes</small></article><article><span>Expired</span><strong data-redemption-kpi-expired>—</strong><small>Customer must refresh</small></article><article><span>Support cases</span><strong data-redemption-kpi-support>—</strong><small>Open or in progress</small></article></section>
<div class="mg-redemption-grid" data-wallet-redemptions>
  <section class="mg-app-panel"><div class="mg-app-panel-head"><div><span class="mg-eyebrow">Redeem Reward</span><h2>Enter claim code</h2><p>Codes are single-use and expire automatically.</p></div></div><div class="mg-app-panel-body"><form class="mg-redemption-form" data-redemption-form><label>12-character claim code<input name="claim_code" inputmode="text" autocomplete="one-time-code" maxlength="14" placeholder="ABCD-EFGH-JKLM" required></label><div class="mg-form-status" data-redemption-status role="status" aria-live="polite"></div><button class="mg-btn mg-btn-primary" type="submit">Redeem reward</button></form><div class="mg-redemption-result" data-redemption-result hidden></div></div></section>
  <section class="mg-app-panel"><div class="mg-app-panel-head"><div><span class="mg-eyebrow">Recent Activity</span><h2>Claim-code history</h2></div></div><div class="mg-app-panel-body"><div class="mg-redemption-list" data-redemption-list></div></div></section>
</div>
<section class="mg-app-panel mg-support-queue"><div class="mg-app-panel-head"><div><span class="mg-eyebrow">Reward Support</span><h2>Customer support queue</h2><p>Resolve issues with claim codes, expired rewards, missing rewards, and merchant redemption.</p></div></div><div class="mg-app-panel-body"><div class="mg-support-case-list" data-support-case-list></div></div></section>
<dialog class="mg-redemption-dialog" data-support-resolution-dialog><form class="mg-redemption-dialog-card" data-support-resolution-form><button type="button" data-support-resolution-close aria-label="Close support case">×</button><span class="mg-eyebrow">Resolve Support Case</span><h2 data-support-resolution-title>Reward support</h2><input type="hidden" name="support_case_id"><label>Resolution note<textarea name="resolution_note" required minlength="3" maxlength="5000" rows="6" placeholder="Explain what was fixed or what the customer should do next."></textarea></label><div class="mg-form-status" data-support-resolution-status role="status" aria-live="polite"></div><button class="mg-btn mg-btn-primary" type="submit">Resolve case</button></form></dialog>
