<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/bootstrap.php';
final class MgControlException extends RuntimeException{public function __construct(string $message,public readonly int $httpStatus=409){parent::__construct($message);}}
function mg_control_install(PDO $pdo): void{
 $pdo->exec("CREATE TABLE IF NOT EXISTS control_action_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(36) NOT NULL,idempotency_key VARCHAR(190) NOT NULL,fingerprint CHAR(64) NOT NULL,actor_user_id BIGINT UNSIGNED NOT NULL,target_type VARCHAR(80) NOT NULL,target_id BIGINT UNSIGNED NOT NULL,action_type VARCHAR(100) NOT NULL,reason VARCHAR(500) NOT NULL,before_json JSON NULL,after_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_control_action_public_id(public_id),UNIQUE KEY uq_control_action_idempotency(idempotency_key),KEY idx_control_action_target(target_type,target_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS control_resource_states (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,target_type VARCHAR(80) NOT NULL,target_id BIGINT UNSIGNED NOT NULL,state VARCHAR(80) NOT NULL,reason VARCHAR(500) NULL,updated_by_user_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_control_resource(target_type,target_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("INSERT INTO permissions (slug,name,description,created_at) VALUES ('control.user.status','Control user status','Change user status',NOW()),('control.merchant.status','Control merchant status','Change merchant status',NOW()),('control.moderation','Control moderation','Moderate resources',NOW()),('control.support.note','Control support note','Record support note',NOW()),('control.finance.override','Control finance override','Authorize finance override',NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name)");
}
function mg_control_ensure(PDO $pdo): void{if(!$pdo->inTransaction())mg_control_install($pdo);}function mg_control_json(array $v): string{return json_encode($v,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}function mg_control_scalar(PDO $pdo,string $sql,array $p=[]): mixed{$s=$pdo->prepare($sql);$s->execute($p);return $s->fetchColumn();}
function mg_control_has(PDO $pdo,int $userId,string $permission): bool{$sql="SELECT COUNT(*) FROM user_roles ur INNER JOIN roles r ON r.id=ur.role_id LEFT JOIN role_permissions rp ON rp.role_id=r.id LEFT JOIN permissions p ON p.id=rp.permission_id WHERE ur.user_id=? AND (r.slug='super_admin' OR p.slug=?)";return (int)mg_control_scalar($pdo,$sql,[$userId,$permission])>0;}
function mg_control_require(PDO $pdo,int $userId,string $permission): void{if(!mg_control_has($pdo,$userId,$permission))throw new MgControlException('Control action is not permitted.',403);}
function mg_control_permission(string $targetType,string $action): string{if($action==='note')return 'control.support.note';if($action==='finance')return 'control.finance.override';if($targetType==='user')return 'control.user.status';if($targetType==='merchant')return 'control.merchant.status';return 'control.moderation';}
function mg_control_fingerprint(array $input): string{return hash('sha256',mg_control_json(['actor'=>(int)($input['actor_user_id']??0),'target_type'=>(string)($input['target_type']??''),'target_id'=>(int)($input['target_id']??0),'action'=>(string)($input['action_type']??''),'state'=>(string)($input['desired_state']??''),'reason'=>(string)($input['reason']??'') ]));}
function mg_control_apply(PDO $pdo,array $input,?callable $failureHook=null): array{
 mg_control_ensure($pdo);$key=trim((string)($input['idempotency_key']??''));$actor=(int)($input['actor_user_id']??0);$type=(string)($input['target_type']??'');$target=(int)($input['target_id']??0);$action=(string)($input['action_type']??'');$state=(string)($input['desired_state']??'');$reason=trim((string)($input['reason']??''));
 if($key===''||$actor<1||$target<1||$type===''||$action===''||$reason==='')throw new MgControlException('Invalid control action.',422);$fingerprint=mg_control_fingerprint($input);$owns=!$pdo->inTransaction();if($owns)$pdo->beginTransaction();
 try{$existing=$pdo->prepare('SELECT * FROM control_action_events WHERE idempotency_key=? LIMIT 1 FOR UPDATE');$existing->execute([$key]);if($row=$existing->fetch(PDO::FETCH_ASSOC)){if(!hash_equals((string)$row['fingerprint'],$fingerprint))throw new MgControlException('Control action conflicts with recorded request.',409);if($owns)$pdo->commit();return ['action_id'=>$row['public_id'],'duplicate'=>true];}
  mg_control_require($pdo,$actor,mg_control_permission($type,$action));$before=[];$after=[];
  if($type==='user'||$type==='merchant'){$s=$pdo->prepare('SELECT id,email,status FROM users WHERE id=? LIMIT 1 FOR UPDATE');$s->execute([$target]);$before=$s->fetch(PDO::FETCH_ASSOC)?:[];if(!$before)throw new MgControlException('Target account not found.',404);if(!in_array($state,['active','disabled'],true))throw new MgControlException('Unsupported account state.',422);$pdo->prepare('UPDATE users SET status=?,updated_at=NOW() WHERE id=?')->execute([$state,$target]);$after=['status'=>$state];}
  elseif($action==='note'){$before=['state'=>(string)mg_control_scalar($pdo,'SELECT state FROM control_resource_states WHERE target_type=? AND target_id=?',[$type,$target])];$after=['note_recorded'=>true];}
  elseif($action==='moderate'){if(!in_array($state,['approved','held','rejected'],true))throw new MgControlException('Unsupported moderation state.',422);$before=['state'=>(string)mg_control_scalar($pdo,'SELECT state FROM control_resource_states WHERE target_type=? AND target_id=?',[$type,$target])];$pdo->prepare('INSERT INTO control_resource_states (target_type,target_id,state,reason,updated_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE state=VALUES(state),reason=VALUES(reason),updated_by_user_id=VALUES(updated_by_user_id),updated_at=NOW()')->execute([$type,$target,$state,$reason,$actor]);$after=['state'=>$state];}
  elseif($action==='finance'){$after=['authorized'=>true,'state'=>$state];}else throw new MgControlException('Unsupported control action.',422);
  $public=mg_public_uuid();$pdo->prepare('INSERT INTO control_action_events (public_id,idempotency_key,fingerprint,actor_user_id,target_type,target_id,action_type,reason,before_json,after_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,NOW())')->execute([$public,$key,$fingerprint,$actor,$type,$target,$action,$reason,mg_control_json($before),mg_control_json($after)]);mg_audit('control.action_applied',$type,['action_id'=>$public,'action_type'=>$action,'target_id'=>$target,'reason'=>$reason],$actor);if($failureHook)$failureHook('after_audit',['action_id'=>$public]);if($owns)$pdo->commit();return ['action_id'=>$public,'duplicate'=>false];
 }catch(Throwable $e){if($owns&&$pdo->inTransaction())$pdo->rollBack();throw $e;}
}
