<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/bootstrap.php';
require_once dirname(__DIR__,2) . '/includes/reviews-case-studies.php';
$pdo=mg_db();$user=mg_rcs_admin_user();$actorId=(int)$user['id'];if(!mg_rcs_admin_can_manage($user))mg_fail('Administrative management permission required.',403);
if($_SERVER['REQUEST_METHOD']==='GET'){
 $q=trim((string)($_GET['q']??''));$args=[];$where=["p.profile_type='merchant'"];
 if($q!==''){$like='%'.$q.'%';$where[]='(p.display_name LIKE ? OR p.slug LIKE ? OR p.headline LIKE ? OR p.location_label LIKE ? OR u.email LIKE ?)';array_push($args,$like,$like,$like,$like,$like);}
 $sql="SELECT p.id,p.public_id,p.user_id,p.slug,p.display_name,p.headline,p.location_label,p.status,p.visibility,u.email,f.public_id case_study_id,f.status case_status,f.display_order,f.hero_featured,f.title,f.subtitle,f.challenge_text,f.solution_text,f.outcomes_json,f.testimonial_text,f.testimonial_name,f.testimonial_role,f.internal_notes FROM public_profiles p INNER JOIN users u ON u.id=p.user_id LEFT JOIN featured_case_studies f ON f.profile_id=p.id WHERE ".implode(' AND ',$where)." ORDER BY (f.id IS NOT NULL) DESC,p.display_name ASC LIMIT 100";
 $stmt=$pdo->prepare($sql);$stmt->execute($args);$profiles=array_map(static function(array $r):array{return ['profile_id'=>(string)$r['public_id'],'user_id'=>(int)$r['user_id'],'slug'=>(string)$r['slug'],'display_name'=>(string)$r['display_name'],'headline'=>(string)($r['headline']??''),'location'=>(string)($r['location_label']??''),'email'=>(string)$r['email'],'profile_status'=>(string)$r['status'],'visibility'=>(string)$r['visibility'],'case_study'=>!empty($r['case_study_id'])?['id'=>(string)$r['case_study_id'],'status'=>(string)$r['case_status'],'display_order'=>(int)$r['display_order'],'hero_featured'=>!empty($r['hero_featured']),'title'=>$r['title'],'subtitle'=>$r['subtitle'],'challenge'=>$r['challenge_text'],'solution'=>$r['solution_text'],'outcomes'=>mg_rcs_decode($r['outcomes_json'],[]),'testimonial_text'=>$r['testimonial_text'],'testimonial_name'=>$r['testimonial_name'],'testimonial_role'=>$r['testimonial_role'],'internal_notes'=>$r['internal_notes']]:null];},$stmt->fetchAll(PDO::FETCH_ASSOC));
 mg_ok(['profiles'=>$profiles]);
}
mg_require_method('POST');$input=mg_input();mg_require_csrf_for_write($input);$profileRef=strtolower(trim((string)($input['profile_id']??'')));$profileStmt=$pdo->prepare('SELECT id,user_id,public_id,display_name,slug FROM public_profiles WHERE public_id=? OR slug=? LIMIT 1');$profileStmt->execute([$profileRef,$profileRef]);$profile=$profileStmt->fetch(PDO::FETCH_ASSOC);if(!$profile)mg_fail('Merchant profile not found.',404);
$status=strtolower(trim((string)($input['status']??'draft')));if(!in_array($status,['draft','published','hidden','archived'],true))mg_fail('Invalid case study status.',422);
$payload=['status'=>$status,'display_order'=>(int)($input['display_order']??100),'hero_featured'=>!empty($input['hero_featured'])?1:0,'title'=>trim((string)($input['title']??''))?:null,'subtitle'=>trim((string)($input['subtitle']??''))?:null,'challenge_text'=>trim((string)($input['challenge']??''))?:null,'solution_text'=>trim((string)($input['solution']??''))?:null,'outcomes_json'=>mg_rcs_json(array_values(array_filter(array_map('trim',(array)($input['outcomes']??[]))))),'testimonial_text'=>trim((string)($input['testimonial_text']??''))?:null,'testimonial_name'=>trim((string)($input['testimonial_name']??''))?:null,'testimonial_role'=>trim((string)($input['testimonial_role']??''))?:null,'internal_notes'=>trim((string)($input['internal_notes']??''))?:null];
try{$pdo->beginTransaction();if($payload['hero_featured'])$pdo->exec('UPDATE featured_case_studies SET hero_featured=0 WHERE hero_featured=1');$existing=$pdo->prepare('SELECT * FROM featured_case_studies WHERE profile_id=? LIMIT 1 FOR UPDATE');$existing->execute([(int)$profile['id']]);$before=$existing->fetch(PDO::FETCH_ASSOC);
 if($before){$caseId=(int)$before['id'];$caseRef=(string)$before['public_id'];$pdo->prepare('UPDATE featured_case_studies SET status=?,display_order=?,hero_featured=?,title=?,subtitle=?,challenge_text=?,solution_text=?,outcomes_json=?,testimonial_text=?,testimonial_name=?,testimonial_role=?,internal_notes=?,published_at=IF(?="published",COALESCE(published_at,NOW()),published_at),updated_by_user_id=?,updated_at=NOW() WHERE id=?')->execute([$payload['status'],$payload['display_order'],$payload['hero_featured'],$payload['title'],$payload['subtitle'],$payload['challenge_text'],$payload['solution_text'],$payload['outcomes_json'],$payload['testimonial_text'],$payload['testimonial_name'],$payload['testimonial_role'],$payload['internal_notes'],$payload['status'],$actorId,$caseId]);}
 else{$caseRef=mg_rcs_uuid();$pdo->prepare('INSERT INTO featured_case_studies (public_id,profile_id,merchant_user_id,status,display_order,hero_featured,title,subtitle,challenge_text,solution_text,outcomes_json,testimonial_text,testimonial_name,testimonial_role,internal_notes,published_at,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,IF(?="published",NOW(),NULL),?,?,NOW(),NOW())')->execute([$caseRef,(int)$profile['id'],(int)$profile['user_id'],$payload['status'],$payload['display_order'],$payload['hero_featured'],$payload['title'],$payload['subtitle'],$payload['challenge_text'],$payload['solution_text'],$payload['outcomes_json'],$payload['testimonial_text'],$payload['testimonial_name'],$payload['testimonial_role'],$payload['internal_notes'],$payload['status'],$actorId,$actorId]);$caseId=(int)$pdo->lastInsertId();}
 mg_rcs_audit($pdo,['actor_user_id'=>$actorId,'merchant_user_id'=>(int)$profile['user_id'],'case_study_id'=>$caseId,'action'=>'admin.case_study.saved','before'=>$before,'after'=>$payload,'metadata'=>['profile_slug'=>$profile['slug'],'source'=>'case_studies_admin']]);$pdo->commit();mg_ok(['case_study_id'=>$caseRef,'profile_slug'=>$profile['slug']],'Case study saved.');
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();mg_security_log('error','admin.case_studies.failed','Unable to save case study.',['message'=>$e->getMessage()],$actorId);mg_fail('Unable to save case study.',500);}