<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/bootstrap.php';
mg_require_method('GET');
$user=mg_require_api_user();$roles=is_array($user['roles']??null)?$user['roles']:[];$perms=is_array($user['permissions']??null)?$user['permissions']:[];
if(!in_array('super_admin',$roles,true)&&!in_array('merchant.design_assets.view',$perms,true))mg_fail('Permission denied.',403);
$root=dirname(__DIR__,2);$checks=[];$add=function($s,$m,$c=[])use(&$checks){$checks[]=['status'=>$s,'message'=>$m,'context'=>$c];};$pass=function($m,$c=[])use($add){$add('pass',$m,$c);};$fail=function($m,$c=[])use($add){$add('fail',$m,$c);};
$files=['design-studio.php','qr.php','api/merchant/qr-library.php','api/merchant/design-export.php','api/merchant/design-campaign-links.php','api/merchant/design-studio-assets.php','api/merchant/brand-kit.php','api/admin/design-export-worker.php','includes/design-studio-renderer.php','assets/js/design-studio.js','assets/css/design-studio.css','assets/css/design-studio-wiring.css','api/public/campaigns/qr-pickup.php','api/merchant/campaign-activity.php'];
foreach($files as $file){is_file($root.'/'.$file)?$pass('File exists: '.$file):$fail('Missing file: '.$file);} 
$contracts=[
 'api/merchant/qr-library.php'=>['mg_qr_resolve_campaign_destination','mg_qr_campaign_path','campaign_public_id','landing_page_url'],
 'qr.php'=>['mg_qr_scan_campaign_event','merchant_qr_code_scans','qr.scanned','campaign_events'],
 'api/merchant/design-campaign-links.php'=>['mg_dcl_campaign','landing_page_url','merchant_design_campaign_links','qr_payload_url'],
 'api/merchant/design-export.php'=>['create_qr_asset','link_campaign','merchant_design_export_jobs','renderer_required'],
 'api/admin/design-export-worker.php'=>['render_next','active_partial','renderer_not_implemented','MG_DESIGN_RENDERER_VERSION'],
 'includes/design-studio-renderer.php'=>['qr_svg','proof','renderer_not_implemented','merchant_design_assets'],
 'assets/js/design-studio.js'=>['createQr','createQrAsset','linkCampaign','queueExport'],
 'api/public/campaigns/qr-pickup.php'=>['qr.scanned','qr_scan','wallet_item.issued','merchant_crm'],
];
foreach($contracts as $file=>$needles){$path=$root.'/'.$file;if(!is_file($path))continue;$content=file_get_contents($path)?:'';foreach($needles as $needle){str_contains($content,$needle)?$pass('Contract found in '.$file.': '.$needle):$fail('Missing contract in '.$file.': '.$needle);}}
try{$pdo=mg_db();$tables=['merchant_qr_codes','merchant_qr_code_scans','merchant_design_projects','merchant_design_assets','merchant_design_export_jobs','merchant_design_campaign_links','merchant_brand_kits','merchant_brand_kit_assets','campaigns','campaign_events','campaign_contacts','wallet_items'];foreach($tables as $table){$stmt=$pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$stmt->execute([$table]);((int)$stmt->fetchColumn()>0)?$pass('Table exists: '.$table):$fail('Missing table: '.$table);} $columns=['merchant_qr_codes'=>['public_id','workspace_id','merchant_user_id','label','qr_type','short_code','destination_url','qr_payload_url','campaign_ref','scan_count','last_scanned_at'],'merchant_qr_code_scans'=>['public_id','qr_code_id','ip_hash','user_agent_hash','referer_url','metadata_json','scanned_at'],'merchant_design_assets'=>['public_id','workspace_id','merchant_user_id','qr_code_id','asset_type','name','status','storage_driver','source_url','public_url','metadata_json'],'merchant_design_export_jobs'=>['public_id','workspace_id','merchant_user_id','project_id','output_asset_id','export_type','status','manifest_json','error_message'],'merchant_design_campaign_links'=>['public_id','workspace_id','merchant_user_id','project_id','qr_code_id','campaign_type','campaign_ref','label','metadata_json'],'campaign_events'=>['public_id','merchant_user_id','campaign_id','event_type','event_context_json']];foreach($columns as $table=>$cols){foreach($cols as $col){$stmt=$pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?');$stmt->execute([$table,$col]);((int)$stmt->fetchColumn()>0)?$pass('Column exists: '.$table.'.'.$col):$fail('Missing column: '.$table.'.'.$col);}}}catch(Throwable $e){$fail('Database audit failed.',['exception_class'=>$e::class,'message'=>$e->getMessage()]);}
$failures=array_values(array_filter($checks,static fn($c)=>$c['status']==='fail'));$score=count($checks)===0?0:(int)round(((count($checks)-count($failures))/count($checks))*10);mg_ok(['score'=>$score,'status'=>count($failures)===0?'passed':'failed','summary'=>['checks'=>count($checks),'passed'=>count($checks)-count($failures),'failed'=>count($failures)],'checks'=>$checks],count($failures)===0?'Design Studio, QR, campaign link, and export audit passed.':'Design QR campaign audit has failures.');
