<?php
declare(strict_types=1);
require_once __DIR__.'/_catalog.php';

final class MgCatalogPublishException extends RuntimeException
{
    public function __construct(string $message, public readonly int $httpStatus=409){parent::__construct($message);}
}

function mg_catalog_publish_install(PDO $pdo): void
{
    $pdo->exec("CREATE TABLE IF NOT EXISTS catalog_publish_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(36) NOT NULL,idempotency_key VARCHAR(190) NOT NULL,fingerprint CHAR(64) NOT NULL,actor_user_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NOT NULL,version_id BIGINT UNSIGNED NULL,event_type VARCHAR(80) NOT NULL,before_json JSON NULL,after_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_catalog_publish_events_public_id(public_id),UNIQUE KEY uq_catalog_publish_events_key(idempotency_key),KEY idx_catalog_publish_events_product(product_id,event_type,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $pdo->exec("CREATE TABLE IF NOT EXISTS catalog_moderation_states (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,product_id BIGINT UNSIGNED NOT NULL,state ENUM('pending','approved','held','rejected') NOT NULL DEFAULT 'pending',reason VARCHAR(500) NULL,updated_by_user_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_catalog_moderation_product(product_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $pdo->exec("INSERT INTO permissions (slug,name,description,created_at) VALUES ('catalog.products.moderate','Moderate catalog products','Review catalog product publication state.',NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name)");
}
function mg_catalog_publish_ensure(PDO $pdo): void{if(!$pdo->inTransaction())mg_catalog_publish_install($pdo);}function mg_catalog_pub_json(array $v): string{return json_encode($v,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}function mg_catalog_pub_scalar(PDO $pdo,string $sql,array $params=[]): mixed{$stmt=$pdo->prepare($sql);$stmt->execute($params);return $stmt->fetchColumn();}
function mg_catalog_pub_has_permission(PDO $pdo,int $userId,string $permission): bool{$sql="SELECT COUNT(*) FROM user_roles ur INNER JOIN roles r ON r.id=ur.role_id LEFT JOIN role_permissions rp ON rp.role_id=r.id LEFT JOIN permissions p ON p.id=rp.permission_id WHERE ur.user_id=? AND (r.slug='super_admin' OR p.slug=?)";return (int)mg_catalog_pub_scalar($pdo,$sql,[$userId,$permission])>0;}
function mg_catalog_pub_require(PDO $pdo,int $userId,string $permission): void{if(!mg_catalog_pub_has_permission($pdo,$userId,$permission))throw new MgCatalogPublishException('Catalog action is not permitted.',403);}
function mg_catalog_pub_fingerprint(array $input): string{return hash('sha256',mg_catalog_pub_json(['actor'=>(int)($input['actor_user_id']??0),'product'=>(string)($input['product_public_id']??''),'version'=>(string)($input['version_public_id']??''),'event'=>(string)($input['event_type']??''),'state'=>(string)($input['state']??''),'reason'=>(string)($input['reason']??'')]));}
function mg_catalog_pub_event(PDO $pdo,array $input,array $before,array $after): array{
    $key=trim((string)($input['idempotency_key']??''));if($key==='')throw new MgCatalogPublishException('Missing idempotency key.',422);$fp=mg_catalog_pub_fingerprint($input);
    $check=$pdo->prepare('SELECT * FROM catalog_publish_events WHERE idempotency_key=? LIMIT 1 FOR UPDATE');$check->execute([$key]);if($row=$check->fetch(PDO::FETCH_ASSOC)){if(!hash_equals((string)$row['fingerprint'],$fp))throw new MgCatalogPublishException('Catalog event conflicts with recorded request.',409);return ['event_id'=>$row['public_id'],'duplicate'=>true];}
    $public=mg_public_uuid();$pdo->prepare('INSERT INTO catalog_publish_events (public_id,idempotency_key,fingerprint,actor_user_id,product_id,version_id,event_type,before_json,after_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,NOW())')->execute([$public,$key,$fp,(int)$input['actor_user_id'],(int)$after['product_id'],isset($after['version_id'])?(int)$after['version_id']:null,(string)$input['event_type'],mg_catalog_pub_json($before),mg_catalog_pub_json($after)]);return ['event_id'=>$public,'duplicate'=>false];
}
function mg_catalog_publish_version(PDO $pdo,array $input,?callable $failureHook=null): array{
    mg_catalog_publish_ensure($pdo);$actor=(int)($input['actor_user_id']??0);mg_catalog_pub_require($pdo,$actor,'catalog.products.publish');$owns=!$pdo->inTransaction();if($owns)$pdo->beginTransaction();
    try{$product=mg_catalog_product_for_update($pdo,(int)$input['merchant_user_id'],(string)$input['product_public_id']);$stmt=$pdo->prepare('SELECT * FROM catalog_product_versions WHERE public_id=? AND product_id=? LIMIT 1 FOR UPDATE');$stmt->execute([(string)$input['version_public_id'],(int)$product['id']]);$version=$stmt->fetch(PDO::FETCH_ASSOC);if(!$version)throw new MgCatalogPublishException('Catalog version not found.',404);$before=['product_status'=>$product['status'],'version_status'=>$version['version_status']];
        if((string)$version['version_status']!=='published'){$pdo->prepare("UPDATE catalog_product_versions SET version_status='published',published_at=NOW() WHERE id=?")->execute([(int)$version['id']]);$pdo->prepare("UPDATE catalog_products SET status='review',current_version_id=?,updated_at=NOW() WHERE id=?")->execute([(int)$version['id'],(int)$product['id']]);$pdo->prepare("INSERT INTO catalog_moderation_states (product_id,state,reason,updated_by_user_id,created_at,updated_at) VALUES (?,'pending','publication submitted',?,NOW(),NOW()) ON DUPLICATE KEY UPDATE state='pending',reason='publication submitted',updated_by_user_id=VALUES(updated_by_user_id),updated_at=NOW()")->execute([(int)$product['id'],$actor]);}
        if($failureHook)$failureHook('after_publish',['product_id'=>(int)$product['id']]);$event=mg_catalog_pub_event($pdo,$input+['event_type'=>'publish'], $before, ['product_id'=>(int)$product['id'],'version_id'=>(int)$version['id'],'version_status'=>'published','product_status'=>'review']);mg_audit('catalog.version_published','catalog_product',['product_id'=>(int)$product['id'],'version_id'=>(int)$version['id']],$actor);if($owns)$pdo->commit();return $event+['status'=>'review'];
    }catch(Throwable $e){if($owns&&$pdo->inTransaction())$pdo->rollBack();throw $e;}}
function mg_catalog_moderate_product(PDO $pdo,array $input): array{
    mg_catalog_publish_ensure($pdo);$actor=(int)($input['actor_user_id']??0);mg_catalog_pub_require($pdo,$actor,'catalog.products.moderate');$owns=!$pdo->inTransaction();if($owns)$pdo->beginTransaction();
    try{$stmt=$pdo->prepare('SELECT * FROM catalog_products WHERE public_id=? LIMIT 1 FOR UPDATE');$stmt->execute([(string)$input['product_public_id']]);$product=$stmt->fetch(PDO::FETCH_ASSOC);if(!$product)throw new MgCatalogPublishException('Catalog product not found.',404);$state=(string)($input['state']??'');if(!in_array($state,['approved','held','rejected'],true))throw new MgCatalogPublishException('Unsupported moderation state.',422);$before=['status'=>$product['status']];$status=$state==='approved'?'published':'review';$publishedAt=$state==='approved'?',published_at=NOW()':'';$pdo->prepare("UPDATE catalog_products SET status=?$publishedAt,updated_at=NOW() WHERE id=?")->execute([$status,(int)$product['id']]);$pdo->prepare('INSERT INTO catalog_moderation_states (product_id,state,reason,updated_by_user_id,created_at,updated_at) VALUES (?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE state=VALUES(state),reason=VALUES(reason),updated_by_user_id=VALUES(updated_by_user_id),updated_at=NOW()')->execute([(int)$product['id'],$state,(string)($input['reason']??''),$actor]);$event=mg_catalog_pub_event($pdo,$input+['event_type'=>'moderate','version_public_id'=>''], $before, ['product_id'=>(int)$product['id'],'state'=>$state,'status'=>$status]);mg_audit('catalog.product_moderated','catalog_product',['product_id'=>(int)$product['id'],'state'=>$state],$actor);if($owns)$pdo->commit();return $event+['status'=>$status,'state'=>$state];
    }catch(Throwable $e){if($owns&&$pdo->inTransaction())$pdo->rollBack();throw $e;}}
