<?php
declare(strict_types=1);
require_once __DIR__ . '/_intelligence.php';
$method=strtoupper($_SERVER['REQUEST_METHOD']??'GET');
$user=mg_require_permission($method==='GET'?'intelligence.dashboard.view':'intelligence.forecasts.manage');$pdo=mg_db();
if($method==='GET'){
 $stmt=$pdo->prepare('SELECT dfr.public_id,dfm.model_key,dfm.model_type,dfm.target_metric,cp.public_id product_id,dfr.as_of_date,dfr.horizon_days,dfr.status,dfr.metrics_json,dfr.started_at,dfr.completed_at FROM demand_forecast_runs dfr INNER JOIN demand_forecast_models dfm ON dfm.id=dfr.model_id LEFT JOIN catalog_products cp ON cp.id=dfr.product_id WHERE dfr.merchant_user_id=? ORDER BY dfr.created_at DESC LIMIT 100');$stmt->execute([(int)$user['id']]);mg_ok(['runs'=>$stmt->fetchAll()]);
}
if($method!=='POST')mg_fail('Method not allowed.',405);
$input=mg_input();mg_require_csrf_for_write($input);$modelKey=trim((string)($input['model_key']??'global_items_seasonal'));$productId=trim((string)($input['product_id']??''))?:null;$asOf=mg_intelligence_date((string)($input['as_of_date']??''),date('Y-m-d'));$horizon=max(1,min(365,(int)($input['horizon_days']??30)));
$modelStmt=$pdo->prepare("SELECT * FROM demand_forecast_models WHERE model_key=? AND status='active' AND (merchant_user_id IS NULL OR merchant_user_id=?) ORDER BY merchant_user_id DESC LIMIT 1");$modelStmt->execute([$modelKey,(int)$user['id']]);$model=$modelStmt->fetch();if(!$model)mg_fail('Forecast model not found.',404);
$productDbId=null;if($productId){$stmt=$pdo->prepare('SELECT id FROM catalog_products WHERE public_id=? AND merchant_user_id=? LIMIT 1');$stmt->execute([$productId,(int)$user['id']]);$productDbId=$stmt->fetchColumn();if(!$productDbId)mg_fail('Product not found.',404);}
$windowStart=date('Y-m-d',strtotime($asOf.' -'.((int)$model['training_window_days']-1).' days'));$metric=(string)$model['target_metric'];$column=match($metric){'items_issued'=>'items_issued','issued_value_cents'=>'issued_value_cents','claims'=>'claims','redemptions'=>'redemptions',default=>'opens'};
$sql="SELECT metric_date,SUM({$column}) metric_value FROM demand_fact_daily WHERE merchant_user_id=? AND metric_date BETWEEN ? AND ?";$params=[(int)$user['id'],$windowStart,$asOf];if($productDbId){$sql.=' AND product_id=?';$params[]=(int)$productDbId;}$sql.=' GROUP BY metric_date ORDER BY metric_date';$historyStmt=$pdo->prepare($sql);$historyStmt->execute($params);$rows=$historyStmt->fetchAll();$history=array_map(static fn(array $row):float=>(float)$row['metric_value'],$rows);$paramsJson=json_decode((string)$model['parameters_json'],true)?:[];$checksum=hash('sha256',json_encode([$history,$model['model_version'],$asOf,$horizon,$productId],JSON_UNESCAPED_SLASHES));$runId=mg_intelligence_uuid();
$pdo->beginTransaction();try{$pdo->prepare("INSERT INTO demand_forecast_runs (public_id,model_id,merchant_user_id,product_id,as_of_date,horizon_days,status,training_window_start,training_window_end,input_checksum,started_at,created_at) VALUES (?,?,?,?,?,?,'running',?,?,?,NOW(),NOW())")->execute([$runId,(int)$model['id'],(int)$user['id'],$productDbId?:null,$asOf,$horizon,$windowStart,$asOf,$checksum]);$runDbId=(int)$pdo->lastInsertId();$predictions=mg_intelligence_forecast_series($history,$horizon,(string)$model['model_type'],$paramsJson);$insert=$pdo->prepare('INSERT INTO demand_forecast_points (forecast_run_id,forecast_date,predicted_value,lower_bound,upper_bound,created_at) VALUES (?,?,?,?,?,NOW())');$mult=(float)($paramsJson['confidence_multiplier']??1.96);foreach($predictions as $i=>$prediction){[$low,$high]=mg_intelligence_interval($history,(float)$prediction,$mult);$insert->execute([$runDbId,date('Y-m-d',strtotime($asOf.' +'.($i+1).' days')),$prediction,$low,$high]);}$mae=null;if(count($history)>=14){$split=max(1,count($history)-7);$train=array_slice($history,0,$split);$actual=array_slice($history,$split);$back=mg_intelligence_forecast_series($train,count($actual),(string)$model['model_type'],$paramsJson);$errors=[];foreach($actual as $i=>$value)$errors[]=abs($value-($back[$i]??0));$mae=$errors?array_sum($errors)/count($errors):null;}$metrics=['history_points'=>count($history),'forecast_points'=>$horizon,'mae'=>$mae,'model_type'=>$model['model_type']];$pdo->prepare("UPDATE demand_forecast_runs SET status='completed',metrics_json=?,completed_at=NOW() WHERE id=?")->execute([json_encode($metrics,JSON_UNESCAPED_SLASHES),$runDbId]);$pdo->commit();mg_audit('intelligence.forecast_completed','demand_forecast_run',['run_id'=>$runId,'model_key'=>$modelKey],(int)$user['id']);mg_ok(['run_id'=>$runId,'metrics'=>$metrics,'points'=>$horizon],'Forecast completed.',201);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();mg_fail('Unable to run forecast.',500);}
