CREATE TABLE IF NOT EXISTS carts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  status ENUM('active','converted','abandoned','expired','cleared') NOT NULL DEFAULT 'active',
  currency CHAR(3) NULL,
  subtotal_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  discount_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  tax_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  platform_fee_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  total_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  expires_at DATETIME NULL,
  converted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_carts_public_id (public_id),
  KEY idx_carts_user_status (user_id,status,updated_at),
  CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  cart_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  product_version_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  title_snapshot VARCHAR(240) NOT NULL,
  unit_amount_cents BIGINT UNSIGNED NOT NULL,
  currency CHAR(3) NOT NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  line_total_cents BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cart_items_public_id (public_id),
  UNIQUE KEY uq_cart_items_version (cart_id,product_version_id),
  KEY idx_cart_items_cart (cart_id,id),
  CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE CASCADE,
  CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES catalog_products(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cart_items_version FOREIGN KEY (product_version_id) REFERENCES catalog_product_versions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cart_items_merchant FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS checkout_drafts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  cart_id BIGINT UNSIGNED NOT NULL,
  buyer_user_id BIGINT UNSIGNED NOT NULL,
  merchant_user_id BIGINT UNSIGNED NOT NULL,
  currency CHAR(3) NOT NULL,
  subtotal_cents BIGINT UNSIGNED NOT NULL,
  discount_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  tax_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  platform_fee_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  total_cents BIGINT UNSIGNED NOT NULL,
  items_json JSON NOT NULL,
  status ENUM('open','converted','expired','cancelled','invalidated') NOT NULL DEFAULT 'open',
  idempotency_key VARCHAR(190) NOT NULL,
  expires_at DATETIME NOT NULL,
  converted_order_id BIGINT UNSIGNED NULL,
  converted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_checkout_drafts_public_id (public_id),
  UNIQUE KEY uq_checkout_drafts_idempotency (buyer_user_id,idempotency_key),
  KEY idx_checkout_drafts_buyer (buyer_user_id,status,expires_at),
  CONSTRAINT fk_checkout_drafts_cart FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_checkout_drafts_buyer FOREIGN KEY (buyer_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_checkout_drafts_merchant FOREIGN KEY (merchant_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_checkout_drafts_order FOREIGN KEY (converted_order_id) REFERENCES commerce_orders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_fee_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  rule_version VARCHAR(80) NOT NULL DEFAULT 'stage5j-zero-fee-v1',
  percentage_basis_points INT UNSIGNED NOT NULL DEFAULT 0,
  fixed_fee_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  minimum_fee_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  maximum_fee_cents BIGINT UNSIGNED NULL,
  calculated_fee_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  inputs_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_order_fee_snapshots_public_id (public_id),
  UNIQUE KEY uq_order_fee_snapshots_order (order_id),
  CONSTRAINT fk_order_fee_snapshots_order FOREIGN KEY (order_id) REFERENCES commerce_orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_status_history (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  status_domain ENUM('order','payment','fulfillment') NOT NULL,
  from_status VARCHAR(50) NULL,
  to_status VARCHAR(50) NOT NULL,
  actor_type ENUM('user','merchant','admin','system','provider') NOT NULL DEFAULT 'system',
  actor_user_id BIGINT UNSIGNED NULL,
  reason_code VARCHAR(100) NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_order_status_history_public_id (public_id),
  KEY idx_order_status_history_order (order_id,created_at,id),
  CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id) REFERENCES commerce_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_status_history_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS receipts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  receipt_number VARCHAR(64) NOT NULL,
  status ENUM('pending','finalized','void') NOT NULL DEFAULT 'pending',
  currency CHAR(3) NOT NULL,
  subtotal_cents BIGINT UNSIGNED NOT NULL,
  discount_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  tax_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  platform_fee_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  total_cents BIGINT UNSIGNED NOT NULL,
  buyer_snapshot_json JSON NOT NULL,
  merchant_snapshot_json JSON NOT NULL,
  items_snapshot_json JSON NOT NULL,
  finalized_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_receipts_public_id (public_id),
  UNIQUE KEY uq_receipts_order (order_id),
  UNIQUE KEY uq_receipts_number (receipt_number),
  CONSTRAINT fk_receipts_order FOREIGN KEY (order_id) REFERENCES commerce_orders(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_audit_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(120) NOT NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  payload_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_order_audit_events_public_id (public_id),
  KEY idx_order_audit_events_order (order_id,created_at,id),
  CONSTRAINT fk_order_audit_events_order FOREIGN KEY (order_id) REFERENCES commerce_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_audit_events_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;