<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require_once dirname(__DIR__).'/api/bootstrap.php';require_once dirname(__DIR__).'/includes/creator-campaigns.php';$pdo=mg_db();function ccp8m(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
$tables=mg_creator_campaign_payout_required_tables();$p=implode(',',array_fill(0,count($tables),'?'));$stmt=$pdo->prepare("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN ({$p})");$stmt->execute($tables);ccp8m((int)$stmt->fetchColumn()===count($tables),'Phase 8 tables are incomplete.');
$permissions=['merchant.creator_payouts.view','merchant.creator_payouts.manage','merchant.creator_disputes.manage','creator.campaign_payouts.view_own','creator.campaign_disputes.manage_own'];$p=implode(',',array_fill(0,count($permissions),'?'));$stmt=$pdo->prepare("SELECT COUNT(*) FROM permissions WHERE slug IN ({$p})");$stmt->execute($permissions);ccp8m((int)$stmt->fetchColumn()===count($permissions),'Phase 8 permissions are incomplete.');
$stmt=$pdo->query("SELECT COUNT(DISTINCT index_name) FROM information_schema.statistics WHERE table_schema=DATABASE() AND ((table_name='creator_campaign_payout_items' AND index_name='uq_cc_payout_item_active_reservation') OR (table_name='creator_campaign_disputes' AND index_name='uq_cc_dispute_active_source') OR (table_name='creator_campaign_payouts' AND index_name='uq_cc_payout_idempotency')) AND non_unique=0");ccp8m((int)$stmt->fetchColumn()===3,'Payout or dispute uniqueness controls are incomplete.');
$stmt=$pdo->query("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN ('creator_campaign_tax_filings','creator_campaign_bank_accounts','creator_campaign_mcp_executions')");ccp8m((int)$stmt->fetchColumn()===0,'Out-of-scope tax, bank, or MCP tables were created.');
echo json_encode(['ok'=>true,'tables'=>count($tables),'permissions'=>count($permissions),'payout_item_uniqueness'=>true,'active_dispute_uniqueness'=>true,'automatic_transfers'=>false],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR).PHP_EOL;
