<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit('Not found.');}
require_once dirname(__DIR__).'/api/communications/_delivery.php';
function mg_delivery_assert(bool $c,string $m): void {if(!$c)throw new RuntimeException($m);}
function mg_delivery_scalar(PDO $pdo,string $sql,array $p=[]): mixed {$s=$pdo->prepare($sql);$s->execute($p);return $s->fetchColumn();}
function mg_delivery_row(PDO $pdo,string $sql,array $p=[]): array {$s=$pdo->prepare($sql);$s->execute($p);return $s->fetch(PDO::FETCH_ASSOC)?:[];}
function mg_delivery_case(array $b,array $o): array {return array_replace_recursive($b,$o);}
$pdo=mg_db();mg_delivery_install_schema($pdo);$runId='delivery_'.bin2hex(random_bytes(8));
$summary=['suite'=>'messaging_delivery_retry_reconciliation_behavior','run_id'=>$runId,'event_queued'=>false,'event_replay'=>false,'conflict_rejected'=>false,'snapshots_immutable'=>false,'claim_exclusive'=>false,'success_terminal'=>false,'transient_retry'=>false,'retry_exhausted'=>false,'permanent_failed'=>false,'suppression_enforced'=>false,'security_not_suppressed'=>false,'callback_replay'=>false,'callback_conflict_rejected'=>false,'secrets_redacted'=>false,'forced_failure_rolled_back'=>false,'fixtures_clean'=>false];
$pdo->beginTransaction();
try{
    $recipient=710001;$base=['recipient_user_id'=>$recipient,'channel'=>'email','template_key'=>'gift_ready','event_type'=>'microgift.ready','category'=>'transactional','payload'=>['subject'=>'Gift ready','private_token'=>'private-'.$runId,'safe'=>'visible'],'recipient_snapshot'=>['email'=>$runId.'@example.test'],'idempotency_key'=>'message:'.$runId.':primary'];
    $created=mg_delivery_enqueue($pdo,$base);mg_delivery_assert(!$created['duplicate']&&$created['status']==='queued','Message was not queued.');$summary['event_queued']=true;
    $replay=mg_delivery_enqueue($pdo,$base);mg_delivery_assert($replay['duplicate']===true&&$replay['job_id']===$created['job_id'],'Exact message replay was not idempotent.');$summary['event_replay']=true;
    $conflict=false;try{mg_delivery_enqueue($pdo,mg_delivery_case($base,['payload'=>['safe'=>'changed']]));}catch(MgDeliveryException $e){$conflict=$e->httpStatus===409;}mg_delivery_assert($conflict,'Conflicting message replay was accepted.');$summary['conflict_rejected']=true;
    $job=mg_delivery_row($pdo,'SELECT * FROM message_delivery_jobs WHERE public_id=?',[$created['job_id']]);mg_delivery_assert((string)$job['template_key']==='gift_ready'&&str_contains((string)$job['payload_snapshot_json'],'visible'),'Snapshot was not captured.');$summary['snapshots_immutable']=true;mg_delivery_assert(!str_contains((string)$job['payload_snapshot_json'],'private-'.$runId),'Private value leaked into snapshot.');$summary['secrets_redacted']=true;
    $claim=mg_delivery_claim_next($pdo);mg_delivery_assert($claim&&$claim['public_id']===$created['job_id'],'Queued job was not claimed.');$secondClaim=mg_delivery_claim_next($pdo);mg_delivery_assert(!$secondClaim||$secondClaim['public_id']!==$created['job_id'],'Claimed job was claimed twice.');$summary['claim_exclusive']=true;
    $success=mg_delivery_process_job($pdo,$claim,['status'=>'success','provider_key'=>'sandbox','provider_message_id'=>'pm-'.$runId]);mg_delivery_assert($success['status']==='delivered','Success did not deliver.');$successReplay=mg_delivery_process_job($pdo,$claim,['status'=>'success','provider_key'=>'sandbox','provider_message_id'=>'pm-'.$runId]);mg_delivery_assert($successReplay['duplicate']===true,'Delivered replay was not idempotent.');$summary['success_terminal']=true;
    $retry=mg_delivery_enqueue($pdo,mg_delivery_case($base,['idempotency_key'=>'message:'.$runId.':retry','template_key'=>'retry_notice','max_attempts'=>2]));$retryJob=mg_delivery_row($pdo,'SELECT * FROM message_delivery_jobs WHERE public_id=?',[$retry['job_id']]);mg_delivery_process_job($pdo,$retryJob,['status'=>'transient_failure','provider_key'=>'sandbox','error_message'=>'Temporary','retry_after_seconds'=>0]);mg_delivery_assert((string)mg_delivery_scalar($pdo,'SELECT status FROM message_delivery_jobs WHERE public_id=?',[$retry['job_id']])==='retrying','Transient failure did not retry.');$summary['transient_retry']=true;$retryJob=mg_delivery_row($pdo,'SELECT * FROM message_delivery_jobs WHERE public_id=?',[$retry['job_id']]);mg_delivery_process_job($pdo,$retryJob,['status'=>'transient_failure','provider_key'=>'sandbox','error_message'=>'Still down','retry_after_seconds'=>0]);mg_delivery_assert((string)mg_delivery_scalar($pdo,'SELECT status FROM message_delivery_jobs WHERE public_id=?',[$retry['job_id']])==='dead_letter','Retry exhaustion did not dead-letter.');$summary['retry_exhausted']=true;
    $perm=mg_delivery_enqueue($pdo,mg_delivery_case($base,['idempotency_key'=>'message:'.$runId.':perm','template_key'=>'perm_notice']));$permJob=mg_delivery_row($pdo,'SELECT * FROM message_delivery_jobs WHERE public_id=?',[$perm['job_id']]);mg_delivery_process_job($pdo,$permJob,['status'=>'permanent_failure','provider_key'=>'sandbox','error_message'=>'Bad address']);mg_delivery_assert((string)mg_delivery_scalar($pdo,'SELECT status FROM message_delivery_jobs WHERE public_id=?',[$perm['job_id']])==='failed','Permanent failure did not fail.');$summary['permanent_failed']=true;
    $pdo->prepare("INSERT INTO message_suppression_rules (user_id,channel,category,status,created_at) VALUES (?,?,?,'active',NOW()) ON DUPLICATE KEY UPDATE status='active'")->execute([$recipient,'email','marketing']);$suppressed=mg_delivery_enqueue($pdo,mg_delivery_case($base,['idempotency_key'=>'message:'.$runId.':suppressed','template_key'=>'marketing_notice','category'=>'marketing']));mg_delivery_assert($suppressed['status']==='suppressed','Suppression was not enforced.');$summary['suppression_enforced']=true;$security=mg_delivery_enqueue($pdo,mg_delivery_case($base,['idempotency_key'=>'message:'.$runId.':security','template_key'=>'security_notice','category'=>'security']));mg_delivery_assert($security['status']==='queued','Security delivery was suppressed.');$summary['security_not_suppressed']=true;
    $callback=mg_delivery_process_callback($pdo,'sandbox','cb-'.$runId,'delivered',['job_id'=>$created['job_id'],'provider_message_id'=>'pm-'.$runId]);mg_delivery_assert(!$callback['duplicate'],'Initial callback was duplicate.');$callbackReplay=mg_delivery_process_callback($pdo,'sandbox','cb-'.$runId,'delivered',['job_id'=>$created['job_id'],'provider_message_id'=>'pm-'.$runId]);mg_delivery_assert($callbackReplay['duplicate']===true,'Callback replay was not idempotent.');$summary['callback_replay']=true;$callbackConflict=false;try{mg_delivery_process_callback($pdo,'sandbox','cb-'.$runId,'bounced',['job_id'=>$created['job_id'],'provider_message_id'=>'other']);}catch(MgDeliveryException $e){$callbackConflict=$e->httpStatus===409;}mg_delivery_assert($callbackConflict,'Conflicting callback replay was accepted.');$summary['callback_conflict_rejected']=true;
    $beforeEvents=(int)mg_delivery_scalar($pdo,'SELECT COUNT(*) FROM message_events');$pdo->exec('SAVEPOINT forced_delivery_failure');$forced=false;try{mg_delivery_enqueue($pdo,mg_delivery_case($base,['idempotency_key'=>'message:'.$runId.':forced','template_key'=>'forced_notice']),static function(string $stage): void {if($stage==='after_event')throw new RuntimeException('Forced delivery failure.');});}catch(Throwable){$forced=true;$pdo->exec('ROLLBACK TO SAVEPOINT forced_delivery_failure');}mg_delivery_assert($forced&&(int)mg_delivery_scalar($pdo,'SELECT COUNT(*) FROM message_events')===$beforeEvents,'Forced failure left message state.');$summary['forced_failure_rolled_back']=true;
    $pdo->rollBack();$pdo->prepare('DELETE FROM message_provider_callbacks WHERE provider_event_id LIKE ?')->execute(['%'.$runId]);$pdo->prepare('DELETE a FROM message_delivery_attempts a INNER JOIN message_delivery_jobs j ON j.id=a.job_id INNER JOIN message_events e ON e.id=j.message_event_id WHERE e.event_key LIKE ?')->execute(['%'.$runId.'%']);$pdo->prepare('DELETE j FROM message_delivery_jobs j INNER JOIN message_events e ON e.id=j.message_event_id WHERE e.event_key LIKE ?')->execute(['%'.$runId.'%']);$pdo->prepare('DELETE FROM message_events WHERE event_key LIKE ?')->execute(['%'.$runId.'%']);$pdo->prepare('DELETE FROM message_suppression_rules WHERE user_id=?')->execute([$recipient]);mg_delivery_assert((int)mg_delivery_scalar($pdo,'SELECT COUNT(*) FROM message_events WHERE event_key LIKE ?',['%'.$runId.'%'])===0,'Message fixtures remain.');$summary['fixtures_clean']=true;
    fwrite(STDOUT,json_encode($summary,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL);
}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();$summary['error']=$error->getMessage();fwrite(STDERR,json_encode($summary,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES).PHP_EOL);throw $error;}
