<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require_once dirname(__DIR__).'/api/bootstrap.php';
require_once dirname(__DIR__).'/includes/creator-campaigns.php';
function cc2(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
function cc2id():string{$h=bin2hex(random_bytes(16));return substr($h,0,8).'-'.substr($h,8,4).'-4'.substr($h,13,3).'-a'.substr($h,17,3).'-'.substr($h,20,12);}
$pdo=mg_db();$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$s=substr(bin2hex(random_bytes(8)),0,12);
$start=gmdate('Y-m-d H:i:s',time()+604800);$end=gmdate('Y-m-d H:i:s',time()+3196800);$deadline=gmdate('Y-m-d H:i:s',time()+432000);
$pdo->prepare("INSERT INTO users(email,password_hash,full_name,display_name,status,created_at,updated_at) VALUES(?,?,?,?,'active',NOW(),NOW())")->execute(["cc2-{$s}@example.test",password_hash('BuilderValidation!42',PASSWORD_DEFAULT),'CC2 Validation','CC2 Validation']);$uid=(int)$pdo->lastInsertId();$user=['id'=>$uid,'roles'=>['admin'],'permissions'=>[]];
$pdo->prepare("INSERT INTO merchant_workspaces(public_id,merchant_user_id,display_name,default_currency,timezone,status,eligibility_status,onboarding_percent,created_at,updated_at) VALUES(?,?,?,'USD','UTC','active','eligible',100,NOW(),NOW())")->execute([cc2id(),$uid,'CC2 Workspace']);
$productPublic=cc2id();$pdo->prepare("INSERT INTO catalog_products(public_id,merchant_user_id,product_type,slug,status,current_version_id,created_by_user_id,published_at,created_at,updated_at) VALUES(?,?,'gift',?,'published',NULL,?,NOW(),NOW(),NOW())")->execute([$productPublic,$uid,"cc2-product-{$s}",$uid]);$pid=(int)$pdo->lastInsertId();
$versionPublic=cc2id();$pdo->prepare("INSERT INTO catalog_product_versions(public_id,product_id,version_number,version_status,title,description,unit_value_cents,currency,checksum,created_by_user_id,published_at,created_at) VALUES(?,?,1,'published',?,'Validation product',2500,'USD',?,?,NOW(),NOW())")->execute([$versionPublic,$pid,'Builder Validation Gift',hash('sha256',$s),$uid]);$vid=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE catalog_products SET current_version_id=? WHERE id=?')->execute([$vid,$pid]);
$assetPublic=cc2id();$pdo->prepare("INSERT INTO catalog_assets(public_id,owner_user_id,asset_type,storage_provider,storage_key,original_filename,mime_type,status,created_at,updated_at) VALUES(?,?,'image','persistent_local',?,?,'image/jpeg','ready',NOW(),NOW())")->execute([$assetPublic,$uid,"cc2/{$s}/cover.jpg","cc2-{$s}.jpg"]);
$rewardPublic=cc2id();$pdo->prepare("INSERT INTO reward_templates(public_id,merchant_user_id,title,description,reward_type,value_type,value_amount_cents,currency,status,created_at,updated_at) VALUES(?,?,?,'Validation reward','custom','custom',0,'USD','active',NOW(),NOW())")->execute([$rewardPublic,$uid,'Builder Validation Reward']);
$created=mg_creator_campaign_create_draft($pdo,$user,['idempotency_key'=>"create-{$s}",'internal_reference'=>"CC2-{$s}",'title'=>'Builder Validation','description'=>'Initial draft','objective'=>'Product sales','category'=>'Hospitality','access_mode'=>'open','timezone'=>'UTC']);cc2(empty($created['idempotent_replay']),'Create replayed');$c=$created['campaign'];$public=(string)$c['public_id'];
$c=mg_creator_campaign_builder_save_step($pdo,$user,$public,1,['expected_lock_version'=>(int)$c['lock_version'],'internal_reference'=>"CC2-{$s}",'title'=>'Builder Validation','description'=>'Complete creator-facing campaign brief.','objective'=>'Product sales','category'=>'Hospitality','access_mode'=>'open','timezone'=>'UTC','starts_at'=>$start,'ends_at'=>$end,'application_deadline_at'=>$deadline,'geographic_scope'=>['label'=>'Phoenix or remote'],'cover_asset_public_id'=>$assetPublic,'campaign_manager_key'=>'owner']);$oldLock=(int)$c['lock_version'];cc2($c['cover_asset_public_id']===$assetPublic,'Asset hydration failed');
$c=mg_creator_campaign_builder_save_step($pdo,$user,$public,2,['expected_lock_version'=>(int)$c['lock_version'],'campaign_focus'=>'single_product','featured_reward_public_id'=>$rewardPublic,'creator_product_access'=>'provided','creator_landing_url'=>'https://microgifter.com/store.php?s=validation','products'=>[['product_public_id'=>$productPublic,'version_public_id'=>$versionPublic,'relationship_type'=>'primary','sort_order'=>0]]]);cc2(count($c['products'])===1,'Product save failed');
$rule=['rule_type'=>'location','operator_key'=>'contains','value'=>'Phoenix','is_required'=>true,'sort_order'=>0];$question=['prompt'=>'Why are you a strong fit?','question_type'=>'long_text','options'=>[],'is_required'=>true,'sort_order'=>0];
$c=mg_creator_campaign_builder_save_step($pdo,$user,$public,3,['expected_lock_version'=>(int)$c['lock_version'],'access_mode'=>'open','maximum_approved_creators'=>25,'maximum_applications'=>250,'automatic_acceptance'=>false,'existing_creator_preference'=>'preferred','application_deadline_at'=>$deadline,'eligibility_rules'=>[$rule],'application_questions'=>[$question]]);$v=$c['builder_validation'];cc2(($v['phase2_score']??0)===100&&!empty($v['phase2_ready'])&&empty($v['publish_ready']),'Readiness contract failed');
$stale=false;try{mg_creator_campaign_builder_save_step($pdo,$user,$public,1,['expected_lock_version'=>$oldLock,'internal_reference'=>"CC2-{$s}",'title'=>'Stale','description'=>'Rejected','objective'=>'Product sales','category'=>'Hospitality','access_mode'=>'open','timezone'=>'UTC']);}catch(DomainException){$stale=true;}cc2($stale,'Stale lock accepted');
$autoUnlocked=false;try{$c=mg_creator_campaign_builder_save_step($pdo,$user,$public,3,['expected_lock_version'=>(int)$c['lock_version'],'access_mode'=>'open','maximum_approved_creators'=>25,'maximum_applications'=>250,'automatic_acceptance'=>true,'existing_creator_preference'=>'preferred','application_deadline_at'=>$deadline,'eligibility_rules'=>[$rule],'application_questions'=>[$question]]);$autoUnlocked=!empty($c['automatic_acceptance']);}catch(DomainException){$autoUnlocked=false;}cc2($autoUnlocked,'Automatic acceptance did not unlock after Creator Participation was installed.');
$key="duplicate-{$s}";$copy=mg_creator_campaign_builder_duplicate($pdo,$user,$public,$key);$replay=mg_creator_campaign_builder_duplicate($pdo,$user,$public,$key);cc2($copy['public_id']===$replay['public_id']&&$copy['public_id']!==$public,'Duplicate idempotency failed');cc2(count($copy['products'])===1&&count($copy['eligibility_rules'])===1&&count($copy['application_questions'])===1,'Duplicate children missing');
fwrite(STDOUT,json_encode(['ok'=>true,'campaign_id'=>$public,'duplicate_campaign_id'=>$copy['public_id'],'phase2_score'=>$v['phase2_score'],'phase2_ready'=>$v['phase2_ready'],'publish_ready'=>$v['publish_ready'],'stale_lock_rejected'=>$stale,'automatic_acceptance_enabled'=>$autoUnlocked],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL);
