<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$root=dirname(__DIR__);$checks=[];
$read=static function(string $path)use($root):string{$file=$root.'/'.ltrim($path,'/');return is_file($file)?(string)file_get_contents($file):'';};
$add=static function(string $label,bool $ok)use(&$checks):void{$checks[]=['label'=>$label,'passed'=>$ok,'points'=>$ok?4:0];};
$has=static fn(string $content,string $needle):bool=>str_contains($content,$needle);
$sql=$read('database/20260722_creator_campaign_crm_lifecycle_v12_single_install.sql');
$definitions=$read('includes/creator-campaigns/crm-definitions.php');
$repository=$read('includes/creator-campaigns/crm-repository.php');
$service=$read('includes/creator-campaigns/crm-service.php');
$query=$read('includes/creator-campaigns/crm-query.php');
$bootstrap=$read('includes/creator-campaigns/bootstrap.php');
$participation=$read('includes/creator-campaigns/participation-repository.php');
$tracking=$read('includes/creator-campaigns/tracking-service.php');
$api=$read('api/merchant/creator-campaign-crm.php');
$view=$read('includes/merchant-creator-campaign-crm-view.php');
$route=$read('merchant-creator-crm.php');
$workspaceJs=$read('assets/js/merchant-creator-campaign-crm-v12.js');
$workspaceCss=$read('assets/css/creator-campaign-crm-v12.css');
$bridge=$read('includes/merchant-crm-creator-campaign-bridge.php');
$crmApi=$read('api/merchant/merchant-crm.php');
$crmPage=$read('merchant-crm.php');
$crmBridgeJs=$read('assets/js/merchant-crm-creator-campaign-bridge-v12.js');
$docs=$read('docs/creator-campaigns/CREATOR_CAMPAIGN_PHASE12_CRM.md');
$overview=$read('includes/merchant-creator-campaigns-view.php');
$detail=$read('includes/merchant-creator-campaign-detail-view.php');

$add('Additive Phase 12 bridge tables',$has($sql,'merchant_crm_creator_campaign_events')&&$has($sql,'merchant_crm_contact_creator_campaigns')&&$has($sql,'merchant_crm_creator_campaign_projection_runs'));
$add('Legacy campaign relationship table remains untouched',!$has($sql,'ALTER TABLE merchant_crm_contact_campaigns')&&$has($sql,'does not alter or reuse the legacy'));
$add('Creator Campaign foreign keys are explicit',$has($sql,'REFERENCES creator_campaigns(id)')&&$has($sql,'fk_merchant_crm_contact_cc_campaign'));
$add('View and manage permissions are installed',$has($sql,'merchant.creator_crm.view')&&$has($sql,'merchant.creator_crm.manage'));
$add('Projection source idempotency is enforced',$has($sql,'uq_merchant_crm_cc_event_source')&&$has($repository,'mg_creator_campaign_crm_reserve_projection'));
$add('Canonical contact identity remains authoritative',$has($sql,'REFERENCES merchant_crm_contacts(id)')&&$has($service,'mg_merchant_crm_record_event'));
$add('Generic CRM events never receive Creator Campaign database IDs',$has($service,"'campaign_id'=>null")&&$has($service,"'campaign_type'=>'creator_campaign'"));
$add('Anonymous tracking identity is rejected',$has($definitions,"'resolved' => $userId > 0 || $email !== null || $phone !== null")&&$has($service,"'identity_unresolved'"));
$add('Privacy-safe tracking hashes are not promoted',$has($docs,'session, visitor, and request hashes remain tracking-only identifiers'));
$add('Nested source transactions use savepoints',$has($service,'SAVEPOINT ')&&$has($service,'ROLLBACK TO SAVEPOINT'));
$add('Projection failure is fail-open and security logged',$has($service,'participation_projection_failed')&&$has($service,'tracking_projection_failed'));
$add('Participation lifecycle projects in real time',substr_count($participation,'mg_creator_campaign_crm_project_participation_event_safe')>=3);
$add('Accepted conversions project in real time',substr_count($tracking,'mg_creator_campaign_crm_project_tracking_event_safe')>=2);
$add('Customer lifecycle roles are explicit',$has($definitions,"'purchase' => 'customer'")&&$has($definitions,"'claim' => 'claimant'")&&$has($definitions,"'redemption' => 'redeemer'"));
$add('Creator partner stage does not downgrade customers',$has($repository,"$relationshipType === 'creator_partner' && $stage === 'lead'"));
$add('Bounded idempotent reconciliation is implemented',$has($service,'mg_creator_campaign_crm_reconcile')&&$has($service,'max(1,min(500,$limit))')&&$has($service,"projection_status IN ('failed','pending')"));
$add('Projection runs are auditable',$has($repository,'mg_creator_campaign_crm_create_run')&&$has($repository,'mg_creator_campaign_crm_complete_run'));
$add('Merchant API separates reads and CSRF writes',$has($api,"$method === 'GET'")&&$has($api,'mg_require_csrf_for_write')&&$has($api,"$action === 'sync'"));
$add('Merchant CRM lifecycle workspace is operational',$has($route,'mg-app-shell')&&$has($view,'data-cccrm')&&$has($workspaceJs,"/api/merchant/creator-campaign-crm.php"));
$add('Workspace supports campaign and relationship filtering',$has($view,'relationship_type')&&$has($view,'lifecycle_stage')&&$has($query,'mg_creator_campaign_crm_list'));
$add('Canonical Merchant CRM API is enriched',$has($crmApi,'mg_merchant_crm_creator_campaign_enrich_directory')&&$has($bridge,'creator_campaign_relationships'));
$add('Canonical-only Creator partners are visible',$has($crmBridgeJs,'canonical_only: true')&&$has($crmBridgeJs,'appendCanonicalOnly'));
$add('Unsupported legacy actions are safely removed',$has($crmBridgeJs,"[data-view-timeline],[data-crm-message],[data-crm-gift]")&&$has($crmBridgeJs,'data-open-creator-campaign'));
$add('Creator Campaign navigation links to CRM',$has($overview,'/merchant-creator-crm.php')&&$has($detail,'/merchant-creator-crm.php')&&$has($crmPage,'merchant-crm-creator-campaign-bridge-v12.js'));
$add('Responsive UI and deployment documentation are complete',$has($workspaceCss,'@media(max-width:760px)')&&$has($docs,'**SQL status: Not imported.**')&&!$has($docs,'automatic outbound marketing enrollment'));

$total=array_sum(array_column($checks,'points'));$failed=array_values(array_filter($checks,static fn(array $check):bool=>!$check['passed']));
foreach($checks as $check)echo sprintf("[%s] %s (%d/4)\n",$check['passed']?'PASS':'FAIL',$check['label'],$check['points']);
echo sprintf("\nCreator Campaign Phase 12 CRM score: %d/100\n",$total);
if($total!==100||$failed!==[])exit(1);
