<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require_once dirname(__DIR__).'/api/bootstrap.php';
require_once dirname(__DIR__).'/includes/creator-campaigns.php';
$pdo=mg_db();function ccdv4_assert(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
$tables=mg_creator_campaign_deliverable_required_tables();$placeholders=implode(',',array_fill(0,count($tables),'?'));$stmt=$pdo->prepare("SELECT table_name FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN ({$placeholders})");$stmt->execute($tables);ccdv4_assert(count($stmt->fetchAll(PDO::FETCH_COLUMN)?:[])===count($tables),'Phase 4 tables are incomplete.');
$permissions=['merchant.creator_deliverables.view','merchant.creator_deliverables.manage','merchant.creator_submissions.view','merchant.creator_submissions.review','creator.campaign_deliverables.view_own','creator.campaign_submissions.manage_own'];$p=implode(',',array_fill(0,count($permissions),'?'));$stmt=$pdo->prepare("SELECT COUNT(*) FROM permissions WHERE slug IN ({$p})");$stmt->execute($permissions);ccdv4_assert((int)$stmt->fetchColumn()===count($permissions),'Phase 4 permissions are incomplete.');
$columns=['campaign_id','participant_id','campaign_deliverable_id','agreement_version_id','creator_user_id','status','lock_version'];$p=implode(',',array_fill(0,count($columns),'?'));$stmt=$pdo->prepare("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='creator_campaign_participant_deliverables' AND column_name IN ({$p})");$stmt->execute($columns);ccdv4_assert((int)$stmt->fetchColumn()===count($columns),'Assignment integrity columns are incomplete.');
$stmt=$pdo->query("SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='creator_campaign_participant_deliverables' AND index_name='uq_cc_participant_deliverable_assignment' AND non_unique=0");ccdv4_assert((int)$stmt->fetchColumn()>=1,'One assignment per participant and deliverable is not enforced.');
$stmt=$pdo->query("SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='creator_campaign_submission_revisions' AND index_name='uq_cc_submission_revision_number' AND non_unique=0");ccdv4_assert((int)$stmt->fetchColumn()>=1,'Submission revision numbers are not immutable and unique.');
$stmt=$pdo->query("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN ('creator_campaign_compensation_rules','creator_campaign_earning_events','creator_campaign_budget_ledger','creator_campaign_payouts','creator_campaign_disputes')");ccdv4_assert((int)$stmt->fetchColumn()===0,'Financial or dispute tables were created prematurely.');
echo json_encode(['ok'=>true,'tables'=>count($tables),'permissions'=>count($permissions),'agreement_version_assignments'=>true,'immutable_revisions'=>true,'publication_proof'=>true,'phase5_compatible'=>true,'later_phase_tables'=>0],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;
