<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require_once dirname(__DIR__).'/api/bootstrap.php';
require_once dirname(__DIR__).'/includes/creator-campaigns.php';
$pdo=mg_db();
function ccm9m(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
$tables=mg_creator_campaign_message_required_tables();$p=implode(',',array_fill(0,count($tables),'?'));$stmt=$pdo->prepare("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN ({$p})");$stmt->execute($tables);ccm9m((int)$stmt->fetchColumn()===count($tables),'Phase 9 canonical or bridge tables are incomplete.');
$permissions=['merchant.creator_messages.view','merchant.creator_messages.manage','merchant.creator_notes.manage','creator.campaign_messages.view_own','creator.campaign_messages.send_own'];$p=implode(',',array_fill(0,count($permissions),'?'));$stmt=$pdo->prepare("SELECT COUNT(*) FROM permissions WHERE slug IN ({$p})");$stmt->execute($permissions);ccm9m((int)$stmt->fetchColumn()===count($permissions),'Phase 9 permissions are incomplete.');
$stmt=$pdo->query("SELECT COUNT(DISTINCT index_name) FROM information_schema.statistics WHERE table_schema=DATABASE() AND ((table_name='creator_campaign_message_contexts' AND index_name IN('uq_cc_message_context_thread','uq_cc_message_context_participant')) OR (table_name='creator_campaign_message_links' AND index_name IN('uq_cc_message_link_message','uq_cc_message_link_idempotency')) OR (table_name='creator_campaign_internal_notes' AND index_name='uq_cc_internal_note_idempotency')) AND non_unique=0");ccm9m((int)$stmt->fetchColumn()===5,'Phase 9 uniqueness and idempotency controls are incomplete.');
$stmt=$pdo->query("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='messages' AND column_name IN('source_type','source_reference','moderation_status')");ccm9m((int)$stmt->fetchColumn()===3,'Canonical message source or moderation columns are incomplete.');
$stmt=$pdo->query("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN('creator_campaign_messages','creator_campaign_notifications','creator_campaign_notification_jobs','creator_campaign_attachment_blobs')");ccm9m((int)$stmt->fetchColumn()===0,'Phase 9 created a duplicate messaging, notification, or attachment store.');
$stmt=$pdo->query("SELECT COUNT(*) FROM role_permissions rp INNER JOIN roles r ON r.id=rp.role_id INNER JOIN permissions p ON p.id=rp.permission_id WHERE r.slug='creator' AND p.slug IN('gift.message.send','notification.view')");ccm9m((int)$stmt->fetchColumn()===2,'Creator role cannot use the canonical Messages or Notifications center.');
echo json_encode(['ok'=>true,'tables'=>count($tables),'permissions'=>count($permissions),'canonical_messages_reused'=>true,'canonical_notifications_reused'=>true,'creator_center_access'=>true,'duplicate_stores'=>false],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR).PHP_EOL;
