<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$root=dirname(__DIR__);$score=0;$checks=[];function ccp8(bool $ok,int $points,string $label):void{global $score,$checks;$checks[]=['ok'=>$ok,'points'=>$points,'label'=>$label];if($ok)$score+=$points;}
$sql=file_get_contents($root.'/database/20260722_creator_campaign_payouts_disputes_v8_single_install.sql')?:'';$defs=file_get_contents($root.'/includes/creator-campaigns/payout-definitions.php')?:'';$repo=file_get_contents($root.'/includes/creator-campaigns/payout-repository.php')?:'';$service=file_get_contents($root.'/includes/creator-campaigns/payout-service.php')?:'';$query=file_get_contents($root.'/includes/creator-campaigns/payout-query.php')?:'';$merchantApi=file_get_contents($root.'/api/merchant/creator-campaign-payouts.php')?:'';$creatorApi=file_get_contents($root.'/api/creator/campaign-payouts.php')?:'';$workflow=file_get_contents($root.'/.github/workflows/creator-campaign-payouts-v8.yml')?:'';
ccp8(count(array_filter(['creator_campaign_payout_profiles','creator_campaign_payouts','creator_campaign_payout_items','creator_campaign_payout_events','creator_campaign_disputes','creator_campaign_dispute_events'],fn($t)=>str_contains($sql,$t)))===6,10,'Six canonical payout and dispute tables');
ccp8(str_contains($sql,"status ENUM('incomplete','pending_review','eligible','blocked')")&&str_contains($sql,'uq_cc_payout_profile_creator_currency'),7,'Currency-specific eligibility profiles');
ccp8(str_contains($sql,'active_reservation_key')&&str_contains($sql,'uq_cc_payout_item_active_reservation'),10,'One active payout claim per reservation');
ccp8(str_contains($sql,'uq_cc_payout_idempotency')&&str_contains($sql,'creator_campaign_payout_events')&&str_contains($sql,'uq_cc_payout_event_idempotency'),10,'Idempotent payouts and immutable events');
ccp8(str_contains($defs,"'draft'=>['approved','cancelled']")&&str_contains($defs,"'paid'=>['reversed']")&&str_contains($service,'mg_creator_campaign_payout_assert_transition'),8,'Guarded payout status transitions');
ccp8(str_contains($service,'mg_creator_campaign_assert_transaction_boundary')&&str_contains($service,'beginTransaction')&&str_contains($service,'rollBack')&&str_contains($repo,'FOR UPDATE'),8,'Atomic transactions and locked reads');
ccp8(str_contains($service,"status='paid'")&&str_contains($service,"status='released'")&&str_contains($service,"status='reversed'"),8,'Payout item paid, release, and reversal lifecycle');
ccp8(str_contains($sql,'active_source_key')&&str_contains($sql,'uq_cc_dispute_active_source'),8,'One active dispute per source');
ccp8(str_contains($sql,'creator_campaign_dispute_events')&&str_contains($repo,'mg_creator_campaign_dispute_append_event')&&str_contains($sql,'uq_cc_dispute_event_idempotency'),7,'Immutable dispute event history');
ccp8(str_contains($merchantApi,'mg_require_csrf_for_write')&&str_contains($creatorApi,'mg_require_csrf_for_write')&&str_contains($service,'creator.campaign_disputes.manage_own')&&str_contains($query,'creator.campaign_payouts.view_own'),8,'Merchant and Creator authorization/ownership');
ccp8(!str_contains(strtolower($service),'stripe')&&!str_contains(strtolower($service),'curl_')&&!str_contains($sql,'creator_campaign_tax_filings')&&!str_contains($sql,'creator_campaign_bank_accounts')&&!str_contains($sql,'creator_campaign_mcp'),6,'No automatic provider transfer, tax, bank-secret, or MCP execution');
ccp8(str_contains($workflow,"php: ['8.2','8.3']")&&str_contains($workflow,'Apply Phase 6 SQL')&&str_contains($workflow,'Apply Phase 7 SQL')&&str_contains($workflow,'Apply Phase 8 SQL')&&str_contains($workflow,'mysql-lifecycle'),6,'PHP matrix and clean Phase 6→7→8 chain');
$merchantPage=file_get_contents($root.'/merchant-creator-payouts.php')?:'';$creatorPage=file_get_contents($root.'/creator-campaign-payouts.php')?:'';ccp8(str_contains($merchantPage,'mg-app-shell')&&str_contains($merchantPage,'app-sidebar.php')&&str_contains($creatorPage,'mg-account-layout')&&str_contains($creatorPage,'account-sidebar.php'),4,'Authenticated merchant and Creator app layouts');
echo json_encode(['score'=>$score,'max'=>100,'rating'=>$score===100?'10/10':number_format($score/10,1).'/10','checks'=>$checks],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;if($score!==100)exit(1);
