<?php
declare(strict_types=1);

$root=dirname(__DIR__);
$read=static fn(string $path):string=>is_file($root.'/'.$path)?(string)file_get_contents($root.'/'.$path):'';
$files=[
 'merchant-loyalty-quest-creative.php','includes/merchant-loyalty-quest-creative-view.php','assets/css/loyalty-quest-creative-studio.css','assets/js/loyalty-quest-creative-studio.js',
 'api/merchant/loyalty-quest-creative.php','api/merchant/loyalty-quest-qr.php','api/public/loyalty-quest/embed.php','api/public/loyalty-quest/media.php','assets/js/loyalty-quest-embed.js',
 'api/merchant/campaign-media-image-upload.php','includes/design-studio-renderer.php','includes/merchant-navigation.php','includes/merchant-workspace.php','includes/merchant-view.php',
 '.github/workflows/quest-media-promotional-assets-validation.yml',
];
$checks=[];foreach($files as $file)$checks[]=['name'=>'file:'.$file,'ok'=>is_file($root.'/'.$file)];
$page=$read('merchant-loyalty-quest-creative.php');$view=$read('includes/merchant-loyalty-quest-creative-view.php');$css=$read('assets/css/loyalty-quest-creative-studio.css');$js=$read('assets/js/loyalty-quest-creative-studio.js');$api=$read('api/merchant/loyalty-quest-creative.php');$qr=$read('api/merchant/loyalty-quest-qr.php');$embedApi=$read('api/public/loyalty-quest/embed.php');$mediaApi=$read('api/public/loyalty-quest/media.php');$embedJs=$read('assets/js/loyalty-quest-embed.js');$upload=$read('api/merchant/campaign-media-image-upload.php');$renderer=$read('includes/design-studio-renderer.php');$nav=$read('includes/merchant-navigation.php');$workspace=$read('includes/merchant-workspace.php');$router=$read('includes/merchant-view.php');$detail=$read('api/public/loyalty-quest/detail.php');
$checks[]=['name'=>'authenticated merchant studio','ok'=>str_contains($page,"merchantView='quest_creative'")&&str_contains($page,'includes/merchant-workspace.php')&&str_contains($router,'merchant-loyalty-quest-creative-view.php')&&str_contains($nav,"'quest_creative' => 'loyalty_quests'")&&str_contains($workspace,'mg_merchant_navigation_sidebar($merchantView)')];
$checks[]=['name'=>'merchant-scoped creative API','ok'=>str_contains($api,'mg_merchant_require_permission')&&str_contains($api,"merchant.campaigns.view' : 'merchant.campaigns.manage")&&substr_count($api,'merchant_user_id')>=6&&str_contains($api,"campaign_type='loyalty_quest'")];
$checks[]=['name'=>'CSRF and audit','ok'=>str_contains($api,'mg_require_csrf_for_write')&&str_contains($api,'merchant.loyalty_quest_creative_saved')&&str_contains($upload,'mg_require_csrf_for_write')];
$checks[]=['name'=>'merchant-owned media authority','ok'=>str_contains($api,'FROM catalog_assets WHERE public_id=? AND owner_user_id=?')&&str_contains($api,"asset_type='image'")&&str_contains($api,"status='ready'")&&str_contains($upload,'INSERT INTO catalog_assets')];
$checks[]=['name'=>'safe image upload','ok'=>str_contains($upload,'8388608')&&str_contains($upload,"'image/jpeg' => 'jpg'")&&str_contains($upload,"'image/png' => 'png'")&&str_contains($upload,"'image/webp' => 'webp'")&&str_contains($upload,'hash_file')];
$checks[]=['name'=>'external image safety','ok'=>str_contains($api,"parts['scheme']")&&str_contains($api,"!== 'https'")&&str_contains($api,'Image URLs cannot contain credentials.')&&str_contains($api,'mb_strlen($url) > 700')];
$checks[]=['name'=>'campaign rule persistence','ok'=>str_contains($api,"rules['creative']")&&str_contains($api,"rules['cover_image_url']")&&str_contains($api,"rules['cover_image_asset_id']")&&str_contains($api,'UPDATE campaigns SET rules_json=?')];
$checks[]=['name'=>'public cover URL authority','ok'=>str_contains($api,'mg_lqc_public_cover_url')&&str_contains($api,'/api/public/loyalty-quest/media.php?campaign=')&&str_contains($mediaApi,'ca.owner_user_id=c.merchant_user_id')&&str_contains($mediaApi,"visibility!=='public'")&&str_contains($mediaApi,'hash_equals($assetId')];
$checks[]=['name'=>'public media is image-only and stream-safe','ok'=>str_contains($mediaApi,"['image/jpeg','image/png','image/webp']")&&str_contains($mediaApi,'mg_storage_resolve_asset_path')&&str_contains($mediaApi,'X-Content-Type-Options: nosniff')&&str_contains($mediaApi,'Access-Control-Allow-Origin: *')];
$checks[]=['name'=>'public quest consumes creative cover','ok'=>str_contains($detail,"'cover_image_url'")||str_contains($detail,'mg_lqd_image')];
$checks[]=['name'=>'real QR renderer','ok'=>str_contains($qr,'mg_design_renderer_qr_svg')&&str_contains($renderer,'function mg_design_renderer_qr_svg')&&str_contains($renderer,'MG_DESIGN_QR_ECC_CODEWORDS')&&str_contains($renderer,'mg_design_qr_remainder')];
$checks[]=['name'=>'merchant QR ownership','ok'=>str_contains($qr,'merchant_user_id=?')&&str_contains($qr,"campaign_type='loyalty_quest'")&&str_contains($qr,"mg_merchant_require_permission('merchant.campaigns.view')")];
$checks[]=['name'=>'five promotional formats','ok'=>str_contains($js,'social:[1080,1080]')&&str_contains($js,'story:[1080,1920]')&&str_contains($js,'poster:[1200,1800]')&&str_contains($js,'table_tent:[1200,1500]')&&str_contains($js,'email:[1200,600]')];
$checks[]=['name'=>'downloadable PNG and QR','ok'=>str_contains($js,'canvas.toBlob')&&str_contains($js,"'image/png'")&&str_contains($view,'data-lqc-download')&&str_contains($view,'data-lqc-qr-download')&&str_contains($qr,'Content-Disposition')];
$checks[]=['name'=>'creative composition','ok'=>str_contains($js,'coverDraw')&&str_contains($js,'drawQr')&&str_contains($js,'wrap(')&&str_contains($js,'reward_title')&&str_contains($js,'merchant_name')];
$checks[]=['name'=>'host-friendly embed','ok'=>str_contains($api,'data-microgifter-loyalty-quest')&&str_contains($embedJs,'microgifter-loyalty-quest-card')&&!str_contains($embedJs,'attachShadow')&&!str_contains($embedJs,'iframe')&&str_contains($view,'Host-friendly quest card')];
$checks[]=['name'=>'public embed safety','ok'=>str_contains($embedApi,'Access-Control-Allow-Origin: *')&&str_contains($embedApi,"c.status='active'")&&str_contains($embedApi,"visibility!=='public'")&&str_contains($embedApi,"preg_match('/^[a-z0-9_-]+$/',")];
$checks[]=['name'=>'embed has sanitized public data','ok'=>str_contains($embedApi,"'title'")&&str_contains($embedApi,"'merchant'")&&str_contains($embedApi,"'reward_title'")&&str_contains($embedApi,"'cta'")&&!str_contains($embedApi,'qr_code_token')];
$checks[]=['name'=>'accessible responsive studio','ok'=>str_contains($view,'aria-live="polite"')&&str_contains($view,'aria-label="Loyalty Quest promotional artwork preview"')&&str_contains($css,':focus-visible')&&preg_match('/@media\(max-width:760px\)/',$css)===1];
$checks[]=['name'=>'blank artwork fallback','ok'=>str_contains($js,'placeholder(')&&str_contains($detail,'loyalty-quest-placeholder.svg')];
$checks[]=['name'=>'no new SQL required','ok'=>!is_file($root.'/database/loyalty_quest_creative_studio_v1.sql')&&!str_contains($api,'CREATE TABLE')&&!str_contains($api,'ALTER TABLE')];
$failed=array_values(array_filter($checks,static fn(array $check):bool=>!$check['ok']));$score=max(0,10-count($failed)*.4);
echo json_encode(['ok'=>$failed===[],'score'=>number_format($score,1).'/10','checks'=>$checks,'failed'=>$failed],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES).PHP_EOL;exit($failed===[]?0:1);
