-- Stage 9B Microgift Engine foundation

CREATE TABLE IF NOT EXISTS microgift_templates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  owner_type ENUM('user','creator','merchant','organization','enterprise') NOT NULL,
  owner_user_id BIGINT UNSIGNED NULL,
  owner_reference_id BIGINT UNSIGNED NULL,
  name VARCHAR(190) NOT NULL,
  slug VARCHAR(190) NOT NULL,
  description TEXT NULL,
  gift_type ENUM('value','product','digital','discount','experience','reward') NOT NULL DEFAULT 'value',
  status ENUM('draft','active','retired','suspended') NOT NULL DEFAULT 'draft',
  visibility ENUM('private','unlisted','public') NOT NULL DEFAULT 'private',
  default_currency CHAR(3) NOT NULL DEFAULT 'USD',
  active_version_id BIGINT UNSIGNED NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_microgift_templates_public_id (public_id),
  UNIQUE KEY uq_microgift_templates_owner_slug (owner_type, owner_user_id, owner_reference_id, slug),
  KEY idx_microgift_templates_owner_status (owner_type, owner_user_id, owner_reference_id, status),
  CONSTRAINT fk_microgift_templates_owner_user FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_microgift_templates_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS microgift_template_versions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  template_id BIGINT UNSIGNED NOT NULL,
  version_number INT UNSIGNED NOT NULL,
  status ENUM('draft','published','retired') NOT NULL DEFAULT 'draft',
  title VARCHAR(190) NOT NULL,
  description TEXT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  face_value_cents BIGINT UNSIGNED NULL,
  product_id BIGINT UNSIGNED NULL,
  product_version_id BIGINT UNSIGNED NULL,
  recipient_policy ENUM('purchaser','named_user','external_recipient','open_claim','workplace_assigned') NOT NULL DEFAULT 'open_claim',
  claim_policy_json JSON NULL,
  redemption_policy_json JSON NULL,
  location_policy_json JSON NULL,
  expiration_policy_json JSON NULL,
  terms_snapshot_json JSON NULL,
  future_demand_metadata_json JSON NULL,
  published_at DATETIME NULL,
  published_by_user_id BIGINT UNSIGNED NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_microgift_template_versions_public_id (public_id),
  UNIQUE KEY uq_microgift_template_versions_number (template_id, version_number),
  KEY idx_microgift_template_versions_status (template_id, status, version_number),
  CONSTRAINT fk_microgift_template_versions_template FOREIGN KEY (template_id) REFERENCES microgift_templates(id) ON DELETE RESTRICT,
  CONSTRAINT fk_microgift_template_versions_published_by FOREIGN KEY (published_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_microgift_template_versions_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE microgift_templates
  ADD CONSTRAINT fk_microgift_templates_active_version FOREIGN KEY (active_version_id) REFERENCES microgift_template_versions(id) ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS microgift_instances (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  template_id BIGINT UNSIGNED NOT NULL,
  template_version_id BIGINT UNSIGNED NOT NULL,
  status ENUM('issued','delivered','claim_pending','claimed','redeemable','redeemed','expired','cancelled','revoked','replaced') NOT NULL DEFAULT 'issued',
  source_type VARCHAR(80) NOT NULL,
  source_reference VARCHAR(190) NOT NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  issuer_user_id BIGINT UNSIGNED NOT NULL,
  owner_user_id BIGINT UNSIGNED NULL,
  recipient_user_id BIGINT UNSIGNED NULL,
  recipient_reference VARCHAR(255) NULL,
  commerce_order_item_id BIGINT UNSIGNED NULL,
  pppm_item_id BIGINT UNSIGNED NULL,
  legacy_gift_id BIGINT UNSIGNED NULL,
  replaced_by_instance_id BIGINT UNSIGNED NULL,
  title_snapshot VARCHAR(190) NOT NULL,
  description_snapshot TEXT NULL,
  currency CHAR(3) NOT NULL,
  face_value_cents BIGINT UNSIGNED NULL,
  product_id BIGINT UNSIGNED NULL,
  product_version_id BIGINT UNSIGNED NULL,
  recipient_policy VARCHAR(40) NOT NULL,
  claim_policy_json JSON NULL,
  redemption_policy_json JSON NULL,
  location_policy_json JSON NULL,
  expiration_policy_json JSON NULL,
  terms_snapshot_json JSON NULL,
  metadata_json JSON NULL,
  issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  delivered_at DATETIME NULL,
  claimed_at DATETIME NULL,
  redeemed_at DATETIME NULL,
  expires_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  revoked_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_microgift_instances_public_id (public_id),
  UNIQUE KEY uq_microgift_instances_idempotency (idempotency_key),
  UNIQUE KEY uq_microgift_instances_legacy_gift (legacy_gift_id),
  UNIQUE KEY uq_microgift_instances_pppm_item (pppm_item_id),
  KEY idx_microgift_instances_owner_status (owner_user_id, status, created_at),
  KEY idx_microgift_instances_recipient_status (recipient_user_id, status, created_at),
  KEY idx_microgift_instances_source (source_type, source_reference),
  CONSTRAINT fk_microgift_instances_template FOREIGN KEY (template_id) REFERENCES microgift_templates(id) ON DELETE RESTRICT,
  CONSTRAINT fk_microgift_instances_version FOREIGN KEY (template_version_id) REFERENCES microgift_template_versions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_microgift_instances_issuer FOREIGN KEY (issuer_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_microgift_instances_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_microgift_instances_recipient FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_microgift_instances_legacy_gift FOREIGN KEY (legacy_gift_id) REFERENCES gifts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_microgift_instances_replacement FOREIGN KEY (replaced_by_instance_id) REFERENCES microgift_instances(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS microgift_credentials (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  instance_id BIGINT UNSIGNED NOT NULL,
  purpose ENUM('claim','redeem') NOT NULL DEFAULT 'claim',
  status ENUM('active','verified','consumed','locked','expired','revoked','rotated') NOT NULL DEFAULT 'active',
  code_hash CHAR(64) NOT NULL,
  code_prefix VARCHAR(8) NOT NULL,
  code_last4 CHAR(4) NOT NULL,
  failed_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 5,
  locked_at DATETIME NULL,
  verified_at DATETIME NULL,
  consumed_at DATETIME NULL,
  expires_at DATETIME NULL,
  rotated_to_credential_id BIGINT UNSIGNED NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_microgift_credentials_public_id (public_id),
  UNIQUE KEY uq_microgift_credentials_active_purpose (instance_id, purpose, status),
  KEY idx_microgift_credentials_lookup (code_prefix, code_last4, status),
  CONSTRAINT fk_microgift_credentials_instance FOREIGN KEY (instance_id) REFERENCES microgift_instances(id) ON DELETE RESTRICT,
  CONSTRAINT fk_microgift_credentials_rotated_to FOREIGN KEY (rotated_to_credential_id) REFERENCES microgift_credentials(id) ON DELETE RESTRICT,
  CONSTRAINT fk_microgift_credentials_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS microgift_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  instance_id BIGINT UNSIGNED NULL,
  template_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(100) NOT NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  source_type VARCHAR(80) NULL,
  source_reference VARCHAR(190) NULL,
  payload_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_microgift_events_public_id (public_id),
  KEY idx_microgift_events_instance_created (instance_id, created_at),
  KEY idx_microgift_events_template_created (template_id, created_at),
  KEY idx_microgift_events_type_created (event_type, created_at),
  CONSTRAINT fk_microgift_events_instance FOREIGN KEY (instance_id) REFERENCES microgift_instances(id) ON DELETE RESTRICT,
  CONSTRAINT fk_microgift_events_template FOREIGN KEY (template_id) REFERENCES microgift_templates(id) ON DELETE RESTRICT,
  CONSTRAINT fk_microgift_events_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO permissions (slug, name, description, created_at) VALUES
('microgift.templates.manage', 'Manage Microgift templates', 'Create, version, publish, retire, and inspect owned Microgift templates.', NOW()),
('microgift.instances.issue', 'Issue Microgift instances', 'Issue canonical Microgift instances from published templates.', NOW()),
('microgift.instances.view', 'View Microgift instances', 'View authorized Microgift instance details.', NOW());

INSERT IGNORE INTO role_permissions (role_id, permission_id, created_at)
SELECT r.id, p.id, NOW()
FROM roles r
JOIN permissions p ON p.slug IN ('microgift.templates.manage','microgift.instances.issue','microgift.instances.view')
WHERE r.slug IN ('merchant','admin','super_admin');
