-- Microgifter Stage 1 Delivery Event Foundation 03R
-- Import after database/stage_1_high_volume_foundation_03O.sql

CREATE TABLE IF NOT EXISTS delivery_event_types (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_key VARCHAR(120) NOT NULL,
  category VARCHAR(80) NOT NULL,
  description VARCHAR(255) NULL,
  is_terminal TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_delivery_event_types_key (event_key),
  KEY idx_delivery_event_types_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS delivery_status_transitions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  from_status VARCHAR(80) NOT NULL,
  to_status VARCHAR(80) NOT NULL,
  event_key VARCHAR(120) NOT NULL,
  requires_actor TINYINT(1) NOT NULL DEFAULT 0,
  requires_idempotency TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_delivery_transition (from_status, to_status, event_key),
  KEY idx_delivery_transition_event (event_key),
  CONSTRAINT fk_delivery_transition_event FOREIGN KEY (event_key) REFERENCES delivery_event_types(event_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS delivery_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(26) NOT NULL,
  aggregate_type VARCHAR(80) NOT NULL,
  aggregate_id BIGINT UNSIGNED NULL,
  aggregate_public_id CHAR(26) NULL,
  account_id BIGINT UNSIGNED NULL,
  store_id BIGINT UNSIGNED NULL,
  owner_user_id BIGINT UNSIGNED NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  event_key VARCHAR(120) NOT NULL,
  from_status VARCHAR(80) NULL,
  to_status VARCHAR(80) NULL,
  idempotency_key VARCHAR(160) NULL,
  request_id VARCHAR(80) NULL,
  source VARCHAR(80) NOT NULL DEFAULT 'api',
  payload_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_delivery_events_public_id (public_id),
  UNIQUE KEY uq_delivery_events_idempotency (aggregate_type, aggregate_public_id, event_key, idempotency_key),
  KEY idx_delivery_events_aggregate (aggregate_type, aggregate_id, id),
  KEY idx_delivery_events_public_aggregate (aggregate_type, aggregate_public_id, id),
  KEY idx_delivery_events_account (account_id, id),
  KEY idx_delivery_events_owner (owner_user_id, id),
  KEY idx_delivery_events_event_key (event_key, id),
  KEY idx_delivery_events_created (created_at),
  CONSTRAINT fk_delivery_events_event_key FOREIGN KEY (event_key) REFERENCES delivery_event_types(event_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO delivery_event_types (event_key, category, description, is_terminal) VALUES
('gift.created', 'gift', 'Gift created as durable state.', 0),
('gift.updated', 'gift', 'Gift details updated.', 0),
('gift.validated', 'delivery', 'Gift passed delivery validation.', 0),
('gift.sent', 'delivery', 'Gift entered sent state.', 0),
('gift.delivery.delayed', 'delivery', 'Gift delivery was delayed.', 0),
('gift.delivery.failed', 'delivery', 'Gift delivery attempt failed.', 0),
('gift.delivery.retried', 'delivery', 'Gift delivery was retried.', 0),
('gift.notification.queued', 'notification', 'Gift notification was queued.', 0),
('gift.notification.sent', 'notification', 'Gift notification was sent.', 0),
('gift.notification.failed', 'notification', 'Gift notification failed.', 0),
('gift.notification.opened', 'notification', 'Gift notification was opened.', 0),
('gift.opened', 'recipient', 'Recipient opened gift.', 0),
('gift.viewed', 'recipient', 'Recipient viewed gift content.', 0),
('gift.claim.started', 'claim', 'Gift claim started.', 0),
('gift.claim.verified', 'claim', 'Gift claim verified.', 0),
('gift.claim.confirmed', 'claim', 'Gift claim confirmed.', 0),
('gift.claim.rejected', 'claim', 'Gift claim rejected.', 1),
('gift.fulfillment.started', 'fulfillment', 'Fulfillment started.', 0),
('gift.fulfilled', 'fulfillment', 'Gift fulfilled.', 1),
('gift.fulfillment.failed', 'fulfillment', 'Gift fulfillment failed.', 0),
('gift.verification.required', 'verification', 'Verification required.', 0),
('gift.verification.passed', 'verification', 'Verification passed.', 0),
('gift.verification.failed', 'verification', 'Verification failed.', 0),
('gift.fraud_review.required', 'verification', 'Fraud review required.', 0),
('gift.fraud_review.cleared', 'verification', 'Fraud review cleared.', 0),
('gift.fraud_review.blocked', 'verification', 'Fraud review blocked.', 1),
('gift.expired', 'gift', 'Gift expired.', 1),
('gift.cancelled', 'gift', 'Gift cancelled.', 1),
('gift.failed', 'gift', 'Gift failed.', 1);

INSERT IGNORE INTO delivery_status_transitions (from_status, to_status, event_key, requires_actor, requires_idempotency) VALUES
('draft', 'created', 'gift.created', 1, 1),
('created', 'validated', 'gift.validated', 0, 1),
('validated', 'sent', 'gift.sent', 1, 1),
('sent', 'opened', 'gift.opened', 0, 1),
('opened', 'claim_started', 'gift.claim.started', 0, 1),
('claim_started', 'claim_verified', 'gift.claim.verified', 0, 1),
('claim_verified', 'claimed', 'gift.claim.confirmed', 0, 1),
('claimed', 'fulfilled', 'gift.fulfilled', 1, 1),
('created', 'cancelled', 'gift.cancelled', 1, 1),
('validated', 'cancelled', 'gift.cancelled', 1, 1),
('sent', 'cancelled', 'gift.cancelled', 1, 1),
('created', 'expired', 'gift.expired', 0, 1),
('validated', 'expired', 'gift.expired', 0, 1),
('sent', 'expired', 'gift.expired', 0, 1),
('opened', 'expired', 'gift.expired', 0, 1),
('claim_started', 'expired', 'gift.expired', 0, 1),
('created', 'failed', 'gift.failed', 0, 1),
('validated', 'failed', 'gift.failed', 0, 1),
('sent', 'failed', 'gift.failed', 0, 1),
('claim_started', 'failed', 'gift.failed', 0, 1);
