<?php
declare(strict_types=1);
?>
<section class="mg-app-shell mg-automation-shell">
  <?php require dirname(__DIR__) . '/agent-sidebar.php'; ?>
  <main class="mg-app-workspace mg-automation-workspace">
    <header class="mg-automation-hero">
      <div><span class="mg-automation-eyebrow">MCP Phase 4B · simulation control</span><h1>Automation definitions</h1><p>Create owner-controlled definitions under an active grant, activate them separately, and run manual policy simulations that record proposed actions without executing Microgifter commands.</p></div>
      <nav class="mg-automation-hero-actions"><a href="/account-agent-automations.php">Automation grants</a><a href="/account-agent-drafts.php">Agent drafts</a><a href="/account-agent-handoffs.php">Handoff status</a></nav>
    </header>
    <aside class="mg-automation-runtime-boundary"><strong>Simulation-only deployment state</strong><p>Node.js, security keys, schedules, queues, workers, canonical command execution, action receipts, and external effects remain disabled. A simulation only evaluates policy and records proposed actions.</p></aside>
    <?php if ($notice !== ''): ?><div class="mg-automation-alert is-success"><?= mg_e($notice) ?></div><?php endif; ?>
    <?php if ($errorMessage !== ''): ?><div class="mg-automation-alert is-error"><?= mg_e($errorMessage) ?></div><?php endif; ?>
    <section class="mg-automation-stats"><article><strong><?= (int)$summary['total'] ?></strong><span>Definitions</span></article><article><strong><?= (int)$summary['active'] ?></strong><span>Active</span></article><article><strong><?= (int)$summary['draft'] ?></strong><span>Draft</span></article><article><strong><?= (int)$summary['paused'] ?></strong><span>Paused</span></article><article><strong><?= (int)$summary['simulations'] ?></strong><span>Simulations</span></article></section>

    <details class="mg-automation-create"<?= $definitions === [] ? ' open' : '' ?>><summary><span>Create a simulation definition</span><small>Requires an active Phase 4A grant.</small></summary>
      <?php if (!$schemaReady): ?><div class="mg-automation-empty"><strong>Automation schema unavailable</strong><p>Import the existing MCP automation foundation migration.</p></div>
      <?php elseif ($activeGrants === []): ?><div class="mg-automation-empty"><strong>No active automation grants</strong><p>Create and activate a bounded grant first.</p><a href="/account-agent-automations.php">Manage grants</a></div>
      <?php else: ?><form method="post" class="mg-automation-form"><input type="hidden" name="csrf_token" value="<?= mg_e(mg_csrf_token()) ?>"><input type="hidden" name="action" value="create_definition">
        <section><header><span>1</span><div><h2>Definition</h2><p>Choose one active grant and one playbook already allowed by it.</p></div></header><div class="mg-automation-form-grid"><label>Active grant<select name="grant_id" required><option value="">Select grant</option><?php foreach ($activeGrants as $grant): ?><option value="<?= mg_e((string)$grant['id']) ?>"><?= mg_e((string)$grant['label']) ?> · <?= mg_e((string)$grant['maximum_operation_class']) ?></option><?php endforeach; ?></select></label><label>Playbook<select name="playbook_key" required><option value="">Select playbook</option><?php foreach ($playbookCatalog as $key=>$playbook): ?><option value="<?= mg_e($key) ?>"><?= mg_e((string)$playbook['label']) ?></option><?php endforeach; ?></select></label><label>Automation name<input name="name" minlength="3" maxlength="180" required placeholder="Weekly campaign draft review"></label><label>Risk level<select name="risk_level"><option value="low">Low</option><option value="medium">Medium</option></select></label></div><label>Description<input name="description" maxlength="500" placeholder="Optional owner-facing description"></label><label>Simulation objective<textarea name="objective" minlength="10" maxlength="1000" rows="3" required placeholder="Describe what the agent should evaluate or prepare during the simulation."></textarea></label></section>
        <section><header><span>2</span><div><h2>Proposed limits and targets</h2><p>These values are evaluated against the grant. No command receives them.</p></div></header><div class="mg-automation-form-grid"><label>Proposed amount, cents<input name="proposed_amount_cents" type="number" min="0" max="100000000"></label><label>Proposed quantity<input name="proposed_quantity" type="number" min="0" max="1000000"></label><label>Product UUID<input name="product_id" maxlength="36"></label><label>Campaign UUID<input name="campaign_id" maxlength="36"></label><label>Reward-template UUID<input name="reward_template_id" maxlength="36"></label><label><input type="hidden" name="recipient_is_existing_contact" value="0"><input name="recipient_is_existing_contact" type="checkbox" value="1" checked> Recipient is an existing authorized contact</label></div></section>
        <footer><div><strong>Phase 4B boundary</strong><span>Manual simulation only · proposed actions only · zero action receipts</span></div><button type="submit">Create draft definition</button></footer>
      </form><?php endif; ?>
    </details>

    <section class="mg-automation-list-section"><header><div><span class="mg-automation-eyebrow">Owner definitions</span><h2>Defined automations</h2></div><p>Activation enables manual simulation only. It does not start a scheduler.</p></header>
      <?php if ($definitions === []): ?><div class="mg-automation-empty"><strong>No automation definitions yet</strong><p>Create one above after activating a grant.</p></div><?php else: ?><div class="mg-automation-list"><?php foreach ($definitions as $definition): $config=$definition['configuration']; ?><article class="mg-automation-card is-<?= mg_e((string)$definition['status']) ?>"><header><div><span><?= mg_e(strtoupper((string)$definition['playbook_key'])) ?></span><h3><?= mg_e((string)$definition['name']) ?></h3><p><?= mg_e((string)($config['objective'] ?? $definition['description'])) ?></p></div><strong><?= mg_e(ucfirst((string)$definition['status'])) ?></strong></header><dl><div><dt>Grant</dt><dd><?= mg_e((string)$definition['grant']['status']) ?></dd></div><div><dt>Connection</dt><dd><?= mg_e((string)$definition['connection']['name']) ?></dd></div><div><dt>Trigger</dt><dd>manual · <?= mg_e((string)($definition['trigger']['status'] ?? 'missing')) ?></dd></div><div><dt>Runs</dt><dd><?= (int)$definition['run_count'] ?></dd></div><div><dt>Proposed actions</dt><dd><?= (int)$definition['action_count'] ?></dd></div><div><dt>Last simulation</dt><dd><?= mg_e((string)($definition['last_run_at'] ?? 'Never')) ?></dd></div></dl>
        <?php if ((string)$definition['status'] === 'active'): ?><form method="post" class="mg-automation-simulate-form"><input type="hidden" name="csrf_token" value="<?= mg_e(mg_csrf_token()) ?>"><input type="hidden" name="action" value="simulate_definition"><input type="hidden" name="automation_id" value="<?= mg_e((string)$definition['id']) ?>"><button type="submit">Run safe simulation</button></form><?php endif; ?>
        <?php if ((string)$definition['status'] !== 'revoked'): ?><form method="post" class="mg-automation-actions"><input type="hidden" name="csrf_token" value="<?= mg_e(mg_csrf_token()) ?>"><input type="hidden" name="action" value="transition_definition"><input type="hidden" name="automation_id" value="<?= mg_e((string)$definition['id']) ?>"><label>Action reason<input name="reason" minlength="5" maxlength="255" value="Owner-managed Phase 4B definition action" required></label><div><?php if ((string)$definition['status']==='draft'): ?><button name="transition" value="activate" type="submit">Activate</button><?php endif; ?><?php if ((string)$definition['status']==='active'): ?><button class="is-secondary" name="transition" value="pause" type="submit">Pause</button><?php endif; ?><?php if ((string)$definition['status']==='paused'): ?><button name="transition" value="resume" type="submit">Resume</button><?php endif; ?><button class="is-danger" name="transition" value="revoke" type="submit" onclick="return confirm('Permanently revoke this definition?');">Revoke</button></div></form><?php endif; ?></article><?php endforeach; ?></div><?php endif; ?>
    </section>

    <section class="mg-automation-list-section"><header><div><span class="mg-automation-eyebrow">Durable evidence</span><h2>Simulation run history</h2></div><p>Each completed simulation records policy output and proposed actions. No action receipt means nothing was attempted.</p></header><?php if ($runs===[]): ?><div class="mg-automation-empty"><strong>No simulations yet</strong><p>Activate a definition and run its manual simulation.</p></div><?php else: ?><div class="mg-simulation-history"><?php foreach ($runs as $run): ?><article><header><div><strong><?= mg_e((string)$run['automation']['name']) ?></strong><span><?= mg_e((string)$run['playbook_key']) ?></span></div><em><?= mg_e((string)$run['status']) ?></em></header><dl><div><dt>Run</dt><dd><code><?= mg_e((string)$run['id']) ?></code></dd></div><div><dt>Completed</dt><dd><?= mg_e((string)($run['completed_at'] ?? '—')) ?></dd></div><div><dt>Proposed actions</dt><dd><?= (int)$run['action_count'] ?></dd></div><div><dt>Receipts</dt><dd><?= (int)($run['summary']['action_receipts_created'] ?? 0) ?></dd></div></dl><p><?= !empty($run['summary']['execution_attempted']) ? 'Execution attempted' : 'Simulation only; no execution attempted.' ?></p></article><?php endforeach; ?></div><?php endif; ?></section>
    <aside class="mg-automation-safety"><strong>No scheduler or canonical action path exists in Phase 4B</strong><p>Definitions and simulations prepare the durable control plane for later phases. They cannot publish, send, purchase, issue, activate, fulfill, charge, enqueue, or call a canonical command service.</p></aside>
  </main>
</section>
