<?php
declare(strict_types=1);
?>
<section class="mg-app-shell mg-automation-shell">
  <?php require dirname(__DIR__) . '/agent-sidebar.php'; ?>
  <main class="mg-app-workspace mg-automation-workspace mg-operations-workspace">
    <header class="mg-automation-hero mg-operations-hero">
      <div><span class="mg-automation-eyebrow">MCP Phase 4D · operations and emergency controls</span><h1>Automation operations</h1><p>Inspect the owner-scoped automation control plane, request cancellation, pause one connection, or stop every active automation grant. These controls remain PHP-only and execution-disabled.</p></div>
      <nav class="mg-automation-hero-actions" aria-label="Agent MCP automation workspaces"><a href="/account-agent-automations.php">Grants</a><a href="/account-agent-automation-definitions.php">Definitions</a><a href="/account-agent-automation-schedules.php">Schedules</a><a class="is-active" href="/account-agent-automation-operations.php" aria-current="page">Operations</a></nav>
    </header>
    <aside class="mg-automation-runtime-boundary mg-operations-boundary"><strong>Fail-closed operations layer</strong><p>No Node.js runtime, public MCP transport, scheduler, queue worker, security key, canonical command, or external-effect action is enabled. Emergency controls only pause authority, clear due records, and request cancellation.</p></aside>
    <?php if ($notice !== ''): ?><div class="mg-automation-alert is-success"><?= mg_e($notice) ?></div><?php endif; ?>
    <?php if ($errorMessage !== ''): ?><div class="mg-automation-alert is-error"><?= mg_e($errorMessage) ?></div><?php endif; ?>

    <section class="mg-automation-stats mg-operations-stats" aria-label="MCP automation operations summary">
      <article><strong><?= $grantTotal ?></strong><span>Grants</span><small><?= $activeGrantCount ?> active</small></article>
      <article><strong><?= $definitionTotal ?></strong><span>Definitions</span><small><?= (int)($snapshot['counts']['definitions']['active'] ?? 0) ?> active</small></article>
      <article><strong><?= $runTotal ?></strong><span>Runs</span><small><?= (int)$snapshot['counts']['cancellation_requests'] ?> cancellation requests</small></article>
      <article><strong><?= $proposedActionCount ?></strong><span>Proposed actions</span><small>Approval required</small></article>
      <article class="<?= (int)$snapshot['counts']['receipts'] > 0 ? 'is-critical' : '' ?>"><strong><?= (int)$snapshot['counts']['receipts'] ?></strong><span>Action receipts</span><small>Expected: zero</small></article>
      <article><strong><?= (int)$snapshot['counts']['due_schedules'] ?></strong><span>Due schedules</span><small>Manual evaluation only</small></article>
    </section>

    <section class="mg-operations-control-grid">
      <article class="mg-operations-control-card is-emergency"><header><span>Owner-wide kill switch</span><h2>Emergency pause all automation</h2></header><p>Pauses every active owner grant, definition, and trigger. It clears future due times and requests cancellation for mutable runs. Resuming remains an explicit, individual owner action.</p><form method="post"><input type="hidden" name="csrf_token" value="<?= mg_e(mg_csrf_token()) ?>"><input type="hidden" name="action" value="emergency_pause_all"><label>Emergency reason<input name="reason" minlength="8" maxlength="255" required placeholder="Why all automation authority must stop"></label><label class="mg-operations-confirm"><input type="checkbox" name="confirm" value="1" required> I understand that schedules will be paused and due times cleared.</label><button type="submit"<?= $activeGrantCount < 1 ? ' disabled' : '' ?>>Pause all active automation</button></form></article>
      <article class="mg-operations-control-card"><header><span>Connection isolation</span><h2>Pause one AI connection</h2></header><p>Stops grants, definitions, schedules, and mutable runs tied to one owner-authorized MCP connection without changing unrelated connections.</p><?php if ($snapshot['connections'] === []): ?><div class="mg-automation-empty"><strong>No MCP connections</strong><p>No connection-scoped control is available.</p></div><?php else: ?><form method="post"><input type="hidden" name="csrf_token" value="<?= mg_e(mg_csrf_token()) ?>"><input type="hidden" name="action" value="pause_connection"><label>Connection<select name="connection_id" required><option value="">Select connection</option><?php foreach($snapshot['connections'] as $connection): ?><option value="<?= mg_e((string)$connection['id']) ?>"><?= mg_e((string)$connection['display_name']) ?> · <?= mg_e((string)$connection['status']) ?></option><?php endforeach; ?></select></label><label>Pause reason<input name="reason" minlength="8" maxlength="255" required placeholder="Why this connection must stop"></label><label class="mg-operations-confirm"><input type="checkbox" name="confirm" value="1" required> Pause all automation attached to this connection.</label><button type="submit">Pause connection automation</button></form><?php endif; ?></article>
    </section>

    <section class="mg-automation-list-section mg-operations-health-section"><header><div><span class="mg-automation-eyebrow">Authority health</span><h2>Operational health</h2></div><p>Health findings are owner-scoped and derived from live connection, client, grant, run, and receipt state.</p></header><?php if ($snapshot['health'] === []): ?><div class="mg-operations-healthy"><strong>No control-plane warnings detected</strong><p>Current records remain inside the Phase 4D simulation-only boundary.</p></div><?php else: ?><div class="mg-operations-health-list"><?php foreach($snapshot['health'] as $item): ?><article class="is-<?= mg_e((string)$item['severity']) ?>"><strong><?= mg_e((string)$item['label']) ?></strong><p><?= mg_e((string)$item['message']) ?></p></article><?php endforeach; ?></div><?php endif; ?></section>

    <section class="mg-automation-list-section"><header><div><span class="mg-automation-eyebrow">Run control</span><h2>Recent automation runs</h2></div><p>Cancellation requests are durable evidence for future workers. Completed simulations remain immutable history.</p></header><?php if($snapshot['runs']===[]): ?><div class="mg-automation-empty"><strong>No automation runs</strong><p>Manual or scheduled simulations will appear here.</p></div><?php else: ?><div class="mg-operations-run-list"><?php foreach($snapshot['runs'] as $run): ?><article class="mg-operations-run-card is-<?= mg_e((string)$run['status']) ?>"><header><div><strong><?= mg_e((string)$run['automation']['name']) ?></strong><code><?= mg_e((string)$run['id']) ?></code></div><em><?= mg_e((string)$run['status']) ?></em></header><dl><div><dt>Trigger</dt><dd><?= mg_e((string)($run['trigger']['type'] ?? 'manual')) ?></dd></div><div><dt>Created</dt><dd><?= mg_e((string)$run['created_at']) ?></dd></div><div><dt>Actions</dt><dd><?= (int)$run['action_count'] ?></dd></div><div><dt>Receipts</dt><dd><?= (int)$run['receipt_count'] ?></dd></div><div><dt>Cancellation</dt><dd><?= mg_e((string)($run['cancellation_requested_at'] ?? 'Not requested')) ?></dd></div></dl><?php if($run['cancellable']): ?><form method="post" class="mg-operations-cancel-form"><input type="hidden" name="csrf_token" value="<?= mg_e(mg_csrf_token()) ?>"><input type="hidden" name="action" value="cancel_run"><input type="hidden" name="run_id" value="<?= mg_e((string)$run['id']) ?>"><input name="reason" minlength="8" maxlength="255" required value="Owner requested Phase 4D run cancellation"><button type="submit">Request cancellation</button></form><?php else: ?><p class="mg-operations-terminal">Terminal or already cancellation-requested; no execution control remains.</p><?php endif; ?></article><?php endforeach; ?></div><?php endif; ?></section>

    <section class="mg-automation-list-section"><header><div><span class="mg-automation-eyebrow">Security evidence</span><h2>Recent automation control events</h2></div><p>Emergency pauses, lifecycle changes, simulations, and cancellation requests are retained in the MCP security ledger.</p></header><?php if($snapshot['events']===[]): ?><div class="mg-automation-empty"><strong>No automation security events</strong><p>Owner control events will appear here.</p></div><?php else: ?><div class="mg-operations-event-list"><?php foreach($snapshot['events'] as $event): ?><article class="is-<?= mg_e((string)$event['severity']) ?>"><div><strong><?= mg_e((string)$event['type']) ?></strong><span><?= mg_e((string)$event['created_at']) ?></span></div><p><?= mg_e((string)$event['message']) ?></p></article><?php endforeach; ?></div><?php endif; ?></section>
    <aside class="mg-automation-safety"><strong>Phase 4D stops authority; it does not execute work</strong><p>The operations dashboard prepares the control and evidence layer required before a future VPS worker can exist. There is still no publication, sending, purchase, issuance, delivery, reward activation, fulfillment, charging, or background processing.</p></aside>
  </main>
</section>
