<?php
declare(strict_types=1);
use PHPUnit\Framework\TestCase;
final class CreatorCampaignDeliverablesV4ContractTest extends TestCase
{
    private string $root;
    protected function setUp():void{$this->root=dirname(__DIR__,2);}
    private function source(string $path):string{$value=file_get_contents($this->root.'/'.$path);self::assertIsString($value,$path);return $value;}
    public function testNormalizedDeliverableSchema():void{$sql=$this->source('database/20260721_creator_campaign_deliverables_v4.sql');foreach(['creator_campaign_deliverables','creator_campaign_participant_deliverables','creator_campaign_submissions','creator_campaign_submission_revisions','creator_campaign_assets'] as $table)self::assertStringContainsString('CREATE TABLE IF NOT EXISTS '.$table,$sql);}
    public function testAssignmentsAreGovernedByAcceptedAgreementVersion():void{$sql=$this->source('database/20260721_creator_campaign_deliverables_v4.sql');$service=$this->source('includes/creator-campaigns/deliverable-service.php');self::assertStringContainsString('agreement_version_id BIGINT UNSIGNED NOT NULL',$sql);self::assertStringContainsString('latest_accepted_version_id',$service);self::assertStringContainsString("p.status='active'",$service);}
    public function testSubmissionRevisionHistoryIsImmutable():void{$sql=$this->source('database/20260721_creator_campaign_deliverables_v4.sql');$repo=$this->source('includes/creator-campaigns/deliverable-repository.php');self::assertStringContainsString('uq_cc_submission_revision_number',$sql);self::assertStringContainsString('INSERT INTO creator_campaign_submission_revisions',$repo);self::assertStringNotContainsString('UPDATE creator_campaign_submission_revisions',$repo);}
    public function testCreatorAndMerchantLifecycles():void{$service=$this->source('includes/creator-campaigns/submission-service.php');self::assertStringContainsString('submission_save_creator',$service);self::assertStringContainsString('submission_withdraw_creator',$service);self::assertStringContainsString('publication_proof_creator',$service);self::assertStringContainsString('submission_review_merchant',$service);foreach(['revision_requested','approved','rejected','verified'] as $status)self::assertStringContainsString($status,$service);}
    public function testAuthorizationAndCsrf():void{$context=$this->source('includes/creator-campaigns/deliverable-context.php');$submissionService=$this->source('includes/creator-campaigns/submission-service.php');$merchant=$this->source('api/merchant/creator-campaign-deliverables.php');$creator=$this->source('api/creator/campaign-deliverables.php');self::assertStringContainsString('merchant.creator_deliverables',$context.$merchant);self::assertStringContainsString('creator.campaign_submissions.manage_own',$context.$submissionService);self::assertStringContainsString('mg_require_csrf_for_write',$merchant);self::assertStringContainsString('mg_require_csrf_for_write',$creator);}
    public function testNoLaterPhaseTrackingOrFinanceTables():void{$sql=$this->source('database/20260721_creator_campaign_deliverables_v4.sql');self::assertDoesNotMatchRegularExpression('/CREATE TABLE IF NOT EXISTS creator_campaign_(tracking|attribution|compensation|earning|budget|payout|dispute)/',$sql);}
}
