<?php
declare(strict_types=1);
use PHPUnit\Framework\TestCase;
final class MultiAgentRuntimeMemoryV1ContractTest extends TestCase
{
 public function testAgentOwnedRuntimeSchemaIsIsolatedFromDefaultPersonalAgentTables():void{$root=dirname(__DIR__,2);$sql=file_get_contents($root.'/database/20260719_multi_agent_runtime_memory_v1.sql');self::assertIsString($sql);foreach(['multi_agent_threads','multi_agent_messages','multi_agent_memory','multi_agent_onboarding','multi_agent_drafts'] as $table)self::assertStringContainsString('CREATE TABLE IF NOT EXISTS '.$table,$sql);self::assertStringContainsString('FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE',$sql);self::assertStringContainsString('UNIQUE KEY uq_multi_agent_memory_agent_key (agent_id,memory_key)',$sql);self::assertStringContainsString("'agent.specialized.use'",$sql);}
 public function testRuntimeRoutesOwnedAgentsThroughSeparateThreadsMemoryAndCredits():void{$root=dirname(__DIR__,2);$service=file_get_contents($root.'/includes/multi-agent-runtime.php');$api=file_get_contents($root.'/api/agents/runtime.php');self::assertIsString($service);self::assertIsString($api);foreach(['mg_agent_require_owned','mg_require_csrf_for_write','mg_multi_agent_runtime_chat','multi_agent_onboarding','multi_agent_memory','multi_agent_drafts'] as $marker)self::assertStringContainsString($marker,$api);foreach(['mg_ai_credit_preflight','mg_ai_credit_consume',"'birthday_occasion'","'local_shopping'","'merchant_campaign'",'explicit confirmation'] as $marker)self::assertStringContainsString($marker,$service);}
 public function testSelectedAgentUsesOnePersistentChatCanvasWithTabbedManagement():void{$root=dirname(__DIR__,2);$workspace=file_get_contents($root.'/includes/personal-agent/multi-agent-workspace.php');$script=file_get_contents($root.'/assets/js/multi-agent-runtime.js');$layout=file_get_contents($root.'/assets/css/task-agent-single-chat-v1.css');$page=file_get_contents($root.'/agent.php');foreach([$workspace,$script,$layout,$page] as $value)self::assertIsString($value);foreach(['data-agent-runtime-messages','data-agent-runtime-composer','data-agent-onboarding-form','data-agent-memory-list','data-agent-manage-open','data-agent-manage-tab="manage"','data-agent-manage-tab="settings"','data-agent-action="duplicate"'] as $marker)self::assertStringContainsString($marker,$workspace);self::assertStringNotContainsString('data-agent-thread-list',$workspace);self::assertStringNotContainsString('data-agent-new-thread',$workspace);foreach(['/api/agents/runtime.php',"action:'chat'","action:'onboarding'","action:'save_draft'",'stopImmediatePropagation'] as $marker)self::assertStringContainsString($marker,$script);self::assertStringContainsString('.mg-agent-runtime-composer{position:relative!important',$layout);self::assertStringContainsString('display:grid!important',$layout);self::assertStringContainsString('safe-area-inset-bottom',$layout);self::assertStringContainsString('/assets/js/multi-agent-runtime.js?v=1.5.0',$page);self::assertStringContainsString('/assets/css/task-agent-single-chat-v1.css?v=1.0.0',$page);}
}
