<?php
declare(strict_types=1);
use PHPUnit\Framework\TestCase;
final class Stage5EDistributionOperationsTest extends TestCase
{
 public function testSchemaDefinesEligibilityAndBatchTables():void{$sql=file_get_contents(dirname(__DIR__,2).'/database/stage_5e_merchant_distribution_operations.sql');self::assertIsString($sql);self::assertStringContainsString('distribution_eligibility_decisions',$sql);self::assertStringContainsString('distribution_assignment_batches',$sql);self::assertStringContainsString('distribution_assignment_batch_items',$sql);}
 public function testDashboardAndProgramQueriesAreMerchantScoped():void{foreach(['distribution-dashboard.php','distribution-program.php'] as $file){$source=file_get_contents(dirname(__DIR__,2).'/api/merchant/'.$file);self::assertIsString($source);self::assertStringContainsString('merchant_user_id',$source);self::assertStringContainsString("mg_require_permission('merchant.distribution.view')",$source);}}
 public function testEligibilityUpdatesAreAuditedAndProtected():void{$source=file_get_contents(dirname(__DIR__,2).'/api/merchant/distribution-eligibility.php');self::assertIsString($source);self::assertStringContainsString("mg_require_permission('merchant.distribution.eligibility.manage')",$source);self::assertStringContainsString('mg_require_csrf_for_write',$source);self::assertStringContainsString('distribution_eligibility_decisions',$source);self::assertStringContainsString('distribution.eligibility_updated',$source);}
 public function testAssignmentBatchesRequireEligibleRecipients():void{$source=file_get_contents(dirname(__DIR__,2).'/api/merchant/distribution-batch.php');self::assertIsString($source);self::assertStringContainsString("eligibility_status IN ('eligible','selected')",$source);self::assertStringContainsString('distribution_assignment_batches',$source);self::assertStringContainsString('distribution_assignment_batch_items',$source);self::assertStringContainsString('distribution.assignment_batch_created',$source);}
 public function testStage5EReusesExistingDistributionLifecycle():void{$js=file_get_contents(dirname(__DIR__,2).'/assets/js/merchant-distribution.js');self::assertIsString($js);self::assertStringContainsString('/api/distribution/programs.php',$js);self::assertStringContainsString('/api/merchant/distribution-eligibility.php',$js);self::assertStringContainsString('/api/merchant/distribution-batch.php',$js);}
 public function testMerchantPagesReuseSharedShell():void{foreach(['merchant-distribution.php','merchant-distribution-program.php'] as $file){$source=file_get_contents(dirname(__DIR__,2).'/'.$file);self::assertIsString($source);self::assertStringContainsString('includes/merchant-workspace.php',$source);}}
}
