<?php declare(strict_types=1); ?>
<section class="mg-ccpayout-shell" data-ccpayout-merchant>
<header class="mg-ccpayout-head"><div><a href="/merchant-creator-affiliate-operations.php">← Affiliate Operations</a><span>Creator Affiliate Finance</span><h1>Payout Records & Disputes</h1><p>Approve provider-neutral payout records, record externally confirmed outcomes, reverse records, and resolve disputes. Payout policy, Creator readiness, and reconciliation are managed in Affiliate Operations.</p></div><div class="mg-action-row"><a class="mg-btn" href="/merchant-creator-affiliate-operations.php">Operations Center</a><a class="mg-btn" href="/merchant-creator-messages.php">Messages</a><button class="mg-btn" type="button" data-ccpayout-profile>Eligibility Profile</button><button class="mg-btn mg-btn-primary" type="button" data-ccpayout-create>Create Payout</button></div></header>
<section class="mg-ccpayout-metrics" data-ccpayout-metrics></section>
<nav class="mg-ccpayout-tabs"><button class="is-active" data-ccpayout-tab="payouts">Payouts</button><button data-ccpayout-tab="profiles">Eligibility</button><button data-ccpayout-tab="disputes">Disputes</button></nav>
<div class="mg-ccpayout-state" data-ccpayout-state>Loading payout workspace…</div><section class="mg-ccpayout-list" data-ccpayout-list></section>
<dialog data-ccpayout-profile-dialog><form data-ccpayout-profile-form><header><h2>Payout Eligibility</h2><button type="button" data-ccpayout-close>×</button></header><label>Participant public ID<input name="participant_id" required></label><label>Currency<input name="currency" value="USD" maxlength="3" required></label><label>Status<select name="status"><option value="pending_review">Pending review</option><option value="eligible">Eligible</option><option value="blocked">Blocked</option><option value="incomplete">Incomplete</option></select></label><label>Method label<input name="method_label" maxlength="120" placeholder="Merchant-approved payment method"></label><label>Creator-specific minimum payout (minor units)<input name="minimum_payout_minor" type="number" min="0" value="0"></label><label>Eligibility note<textarea name="eligibility_note" rows="4" maxlength="2000"></textarea></label><div><button type="button" class="mg-btn" data-ccpayout-close>Cancel</button><button class="mg-btn mg-btn-primary" type="submit">Save Eligibility</button></div></form></dialog>
<dialog data-ccpayout-create-dialog><form data-ccpayout-create-form><header><h2>Create Payout Record</h2><button type="button" data-ccpayout-close>×</button></header><label>Participant public ID<input name="participant_id" required></label><label>Currency<input name="currency" value="USD" maxlength="3" required></label><label>Idempotency key<input name="idempotency_key" required></label><p>All eligible committed reservations that satisfy the active policy hold and minimum will be scheduled. The record begins in Draft and still requires approval.</p><div><button type="button" class="mg-btn" data-ccpayout-close>Cancel</button><button class="mg-btn mg-btn-primary" type="submit">Create Payout</button></div></form></dialog>
<dialog data-ccpayout-dispute-dialog><form data-ccpayout-dispute-form><header><h2>Open Dispute</h2><button type="button" data-ccpayout-close>×</button></header><label>Source type<select name="source_type"><option value="payout">Payout</option><option value="reservation">Reservation</option><option value="earning">Earning</option></select></label><label>Source public ID<input name="source_public_id" required></label><label>Reason<textarea name="reason" rows="5" maxlength="2000" required></textarea></label><div><button type="button" class="mg-btn" data-ccpayout-close>Cancel</button><button class="mg-btn mg-btn-primary" type="submit">Open Dispute</button></div></form></dialog>
</section>
