<?php
declare(strict_types=1);
$placeholderViews=[];
if($merchantView==='overview'): ?>
<section class="mg-merchant-heading"><div><span class="mg-eyebrow">Merchant workspace</span><h1 data-merchant-name>Workspace overview</h1><p>Operate products, locations, PPPM delivery, distribution, claims, and intelligence from one consistent shell.</p></div><span class="mg-status-badge" data-merchant-eligibility>Checking eligibility</span></section><div class="mg-merchant-kpis" data-merchant-kpis></div><div class="mg-merchant-grid"><section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Activation steps</h2><p>Complete the foundational setup before controlled beta access.</p></div><a href="/merchant-onboarding.php">View all</a></div><div class="mg-app-panel-body"><div data-merchant-step-list></div></div></section><section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Workspace readiness</h2><p>Products, programs, locations, team, and payment preparation.</p></div></div><div class="mg-app-panel-body"><div data-merchant-readiness></div></div></section></div>
<?php elseif($merchantView==='onboarding'): ?><section class="mg-merchant-heading"><div><span class="mg-eyebrow">Activation</span><h1>Merchant onboarding</h1><p>Finish the ordered setup path and verify the workspace before beta launch.</p></div></section><section class="mg-app-panel"><div class="mg-app-panel-body"><div class="mg-onboarding-list" data-merchant-onboarding></div></div></section>
<?php elseif($merchantView==='products'): require __DIR__.'/merchant-products-view.php'; ?>
<?php elseif($merchantView==='product_detail'): require __DIR__.'/merchant-product-detail-view.php'; ?>
<?php elseif($merchantView==='media'): require __DIR__.'/merchant-media-view.php'; ?>
<?php elseif($merchantView==='storefront'): require __DIR__.'/merchant-storefront-view.php'; ?>
<?php elseif($merchantView==='storefront_preview'): require __DIR__.'/merchant-storefront-preview-view.php'; ?>
<?php elseif($merchantView==='pppm'): require __DIR__.'/merchant-pppm-view.php'; ?>
<?php elseif($merchantView==='pppm_item'): require __DIR__.'/merchant-pppm-item-view.php'; ?>
<?php elseif($merchantView==='distribution'): require __DIR__.'/merchant-distribution-view.php'; ?>
<?php elseif($merchantView==='distribution_program'): require __DIR__.'/merchant-distribution-program-view.php'; ?>
<?php elseif($merchantView==='developer_api'): ?>
<section class="mg-merchant-heading"><div><span class="mg-eyebrow">Developer platform</span><h1>Developer API</h1><p>Create merchant developer apps, connect them to Distribution Programs, review credentials, and send developers to the public docs.</p></div><div class="mg-heading-actions"><a class="mg-btn mg-btn-soft" href="/developer-docs.php">Public docs</a><a class="mg-btn mg-btn-soft" href="/docs/stage-api-8-sandbox-flow.md">Sandbox guide</a></div></section>
<div class="mg-merchant-kpis" data-dev-api-kpis></div>
<div class="mg-program-detail mg-dev-api-onboarding" style="margin-bottom:14px"><section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Developer setup checklist</h2><p>Guided app setup from first program through sandbox testing and live readiness.</p></div><span class="mg-status-badge" data-dev-api-readiness>Loading</span></div><div class="mg-app-panel-body"><div data-dev-api-onboarding></div></div></section><aside class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Recommended flow</h2><p>Keep test and live work separate.</p></div></div><div class="mg-app-panel-body"><div class="mg-health-row"><span><strong>1. Test app</strong><br><small>Create a test app and credential first.</small></span><a href="#developer-app-editor">Start</a></div><div class="mg-health-row"><span><strong>2. Sandbox reward</strong><br><small>Run the sandbox linked-account and reward issue flow.</small></span><a href="/docs/stage-api-8-sandbox-flow.md">Guide</a></div><div class="mg-health-row"><span><strong>3. Webhooks</strong><br><small>Configure callback delivery before live launch.</small></span><a href="/docs/stage-api-5-developer-webhooks.md">Docs</a></div></div></aside></div>
<div class="mg-program-detail mg-dev-api-launch-qa" style="margin-bottom:14px"><section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Live launch QA</h2><p>Preflight checks for live developer apps, credentials, webhook signing, and endpoint policy.</p></div><span class="mg-status-badge" data-dev-api-launch-status>Loading</span></div><div class="mg-app-panel-body"><div data-dev-api-launch-qa></div></div></section></div>
<div class="mg-program-detail mg-dev-api-analytics" style="margin-bottom:14px"><section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>API analytics</h2><p>Request volume, errors, rate limits, sandbox activity, and webhook visibility.</p></div></div><div class="mg-app-panel-body"><div class="mg-merchant-kpis" data-dev-api-analytics-kpis></div><div data-dev-api-daily></div></div></section><section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Usage by app and key</h2><p>Seven-day request visibility by developer app and credential.</p></div></div><div class="mg-app-panel-body"><div data-dev-api-app-usage></div><div data-dev-api-key-usage style="margin-top:14px"></div></div></section></div>
<div class="mg-program-detail mg-dev-api-analytics" style="margin-bottom:14px"><section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Current quota windows</h2><p>Active minute, day, and month request buckets.</p></div></div><div class="mg-app-panel-body"><div data-dev-api-quota-buckets></div></div></section><section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Webhook events</h2><p>Seven-day lifecycle event delivery status.</p></div></div><div class="mg-app-panel-body"><div data-dev-api-webhook-analytics></div></div></section></div>
<div id="developer-app-editor" class="mg-distribution-layout mg-dev-api-layout" data-dev-api-workspace><section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Developer apps</h2><p>External games, websites, apps, and partner systems allowed to request Microgift reward issuance.</p></div></div><div class="mg-app-panel-body"><div data-dev-api-apps></div></div></section><aside class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>App editor</h2><p>Attach an app to a default program and choose its access scope.</p></div></div><div class="mg-app-panel-body"><form class="mg-merchant-form" data-dev-api-form><input type="hidden" name="app_id"><label>App name<input name="name" required maxlength="180" placeholder="Game rewards app"></label><div class="mg-grid-2"><label>Environment<select name="environment"><option value="test">Test</option><option value="live">Live</option></select></label><label>Status<select name="status"><option value="active">Active</option><option value="draft">Draft</option><option value="paused">Paused</option><option value="revoked">Revoked</option></select></label></div><label>Default Distribution Program<select name="default_program_id" data-dev-api-programs><option value="">No default program</option></select></label><label>Allowed origins<textarea name="allowed_origins" rows="3" placeholder="https://example.app"></textarea></label><label>Webhook URL<input name="webhook_url" type="url" placeholder="https://example.app/microgifter/webhook"></label><div class="mg-form-status" data-dev-api-status></div><button class="mg-btn mg-btn-primary" type="submit">Save developer app</button></form></div></aside></div>
<div id="developer-credentials" class="mg-program-detail mg-dev-api-detail" style="margin-top:14px"><section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Access credentials</h2><p>Credential values are shown once at creation; store them server-side.</p></div></div><div class="mg-app-panel-body"><form class="mg-merchant-form mg-dev-credential-form" data-dev-credential-form><div class="mg-grid-2"><label>Developer app<select name="app_id" data-dev-credential-apps><option value="">Select app</option></select></label><label>Credential name<input name="name" maxlength="180" placeholder="Server credential"></label></div><div class="mg-form-status" data-dev-credential-status></div><button class="mg-btn mg-btn-primary" type="submit">Create credential</button></form><div data-dev-credential-secret></div><div data-dev-api-keys></div></div></section><section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Recent API requests</h2><p>Latest public API request log entries.</p></div></div><div class="mg-app-panel-body"><div data-dev-api-logs></div></div></section></div><script src="/assets/js/merchant-developer-api-analytics.js"></script>
<?php elseif($merchantView==='intelligence'): require __DIR__.'/merchant-intelligence-view.php'; ?>
<?php elseif($merchantView==='claims'): require __DIR__.'/merchant-claims-view.php'; ?>
<?php elseif($merchantView==='claim_detail'): require __DIR__.'/merchant-claim-detail-view.php'; ?>
<?php elseif($merchantView==='payments'): require __DIR__.'/merchant-payments-view.php'; ?>
<?php elseif($merchantView==='settings'): ?><section class="mg-merchant-heading"><div><span class="mg-eyebrow">Configuration</span><h1>Business settings</h1><p>Manage the identity and defaults used across products, locations, claims, and future commerce.</p></div></section><section class="mg-app-panel"><div class="mg-app-panel-body"><form class="mg-merchant-form" data-merchant-settings-form><div class="mg-grid-2"><label>Display name<input name="display_name" required></label><label>Legal name<input name="legal_name"></label></div><div class="mg-grid-2"><label>Business type<input name="business_type"></label><label>Website<input name="website_url" type="url"></label></div><div class="mg-grid-2"><label>Support email<input name="support_email" type="email"></label><label>Support phone<input name="support_phone"></label></div><div class="mg-grid-2"><label>Default currency<select name="default_currency"><option>USD</option><option>CAD</option><option>EUR</option><option>GBP</option></select></label><label>Timezone<input name="timezone" value="UTC"></label></div><div class="mg-form-status" data-merchant-form-status></div><button class="mg-btn mg-btn-primary" type="submit">Save business settings</button></form></div></section>
<?php elseif($merchantView==='locations'): require __DIR__.'/merchant-locations-view.php'; ?>
<?php elseif($merchantView==='team'): ?><section class="mg-merchant-heading"><div><span class="mg-eyebrow">Access</span><h1>Merchant team</h1><p>Invite staff and assign workspace roles.</p></div></section><div class="mg-merchant-grid"><section class="mg-app-panel"><div class="mg-app-panel-body"><div data-team-list></div></div></section><section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Invite member</h2></div></div><div class="mg-app-panel-body"><form class="mg-merchant-form" data-team-form><label>Email<input name="email" type="email" required></label><label>Display name<input name="display_name"></label><label>Role<select name="role_key"><option value="admin">Admin</option><option value="manager">Manager</option><option value="location_staff">Location staff</option><option value="claims_staff">Claims staff</option><option value="analyst">Analyst</option><option value="viewer">Viewer</option></select></label><div class="mg-form-status" data-team-status></div><button class="mg-btn mg-btn-primary" type="submit">Record invitation</button></form></div></section></div>
<?php elseif(isset($placeholderViews[$merchantView])): ?><section class="mg-merchant-heading"><div><span class="mg-eyebrow">Merchant workspace</span><h1><?= mg_e(ucwords(str_replace('_',' ',$merchantView))) ?></h1><p><?= mg_e($placeholderViews[$merchantView]) ?></p></div></section><section class="mg-app-panel"><div class="mg-app-panel-body"><div class="mg-empty-state"><strong>Workspace route reserved</strong><p>The operating module will be connected in its planned Stage 5 subphase.</p></div></div></section>
<?php endif; ?>
