<?php declare(strict_types=1); ?>
<section class="mg-ccp-shell" data-ccp-merchant>
  <header class="mg-cc-page-head"><div><a class="mg-cc-back" href="/merchant-creator-campaigns.php">← Creator Campaigns</a><span class="mg-eyebrow">Creator Campaign Participation · Phase 3</span><h1>Participation Workspace</h1><p>Review applications, invite creators, manage participants, issue immutable agreements, and inspect the campaign activity timeline.</p></div><div class="mg-action-row"><a class="mg-btn mg-btn-soft" href="/merchant-creator-deliverables.php">Deliverables & Content</a><a class="mg-btn mg-btn-soft" href="/merchant-creator-tracking.php">Tracking & Attribution</a><button class="mg-btn mg-btn-primary" type="button" data-ccp-open-invite>Invite Creator</button></div></header>
  <section class="mg-ccp-metrics" data-ccp-metrics></section>
  <nav class="mg-ccp-tabs" aria-label="Creator participation views">
    <button type="button" class="is-active" data-ccp-tab="applications">Applications</button>
    <button type="button" data-ccp-tab="invitations">Invitations</button>
    <button type="button" data-ccp-tab="participants">Participants</button>
    <button type="button" data-ccp-tab="agreements">Agreements</button>
    <button type="button" data-ccp-tab="directory">Creator Directory</button>
    <button type="button" data-ccp-tab="timeline">Activity</button>
  </nav>
  <form class="mg-ccp-filters" data-ccp-filters><label class="is-wide">Search<input type="search" name="search" maxlength="120" placeholder="Creator, campaign, or email"></label><label>Campaign<select name="campaign_id" data-ccp-campaign-filter><option value="">All campaigns</option></select></label><label>Status<select name="status" data-ccp-status-filter><option value="">All statuses</option></select></label><button class="mg-btn mg-btn-soft" type="submit">Apply</button></form>
  <div class="mg-ccp-live" data-ccp-live role="status" aria-live="polite"></div>
  <section class="mg-ccp-state" data-ccp-loading><strong>Loading participation workspace</strong><span>Preparing applications, invitations, participants, and agreements.</span></section>
  <section class="mg-ccp-state mg-hidden" data-ccp-error role="alert"><strong>Unable to load participation</strong><span data-ccp-error-message></span><button type="button" class="mg-btn mg-btn-soft" data-ccp-retry>Try Again</button></section>
  <section class="mg-ccp-list mg-hidden" data-ccp-list></section>
  <footer class="mg-cc-pagination mg-hidden" data-ccp-pagination><span data-ccp-page-label></span><div><button type="button" class="mg-btn mg-btn-ghost" data-ccp-prev>Previous</button><button type="button" class="mg-btn mg-btn-soft" data-ccp-next>Next</button></div></footer>

  <dialog class="mg-ccp-dialog" data-ccp-invite-dialog><form class="mg-ccp-dialog-card" data-ccp-invite-form><header><div><span class="mg-eyebrow">Existing Creator Account</span><h2>Invite Creator</h2></div><button type="button" class="mg-ccp-close" data-ccp-close-invite aria-label="Close">×</button></header><label>Campaign<select name="campaign_id" data-ccp-invite-campaign required></select></label><label>Creator<select name="creator_profile_id" data-ccp-invite-creator required><option value="">Choose creator</option></select></label><label>Response deadline<input type="datetime-local" name="response_deadline_at"></label><label>Invitation message<textarea name="invitation_message" rows="4" maxlength="8000"></textarea></label><label>Internal note<textarea name="internal_note" rows="3" maxlength="8000"></textarea></label><div class="mg-ccp-dialog-actions"><button type="button" class="mg-btn mg-btn-ghost" data-ccp-close-invite>Cancel</button><button type="submit" class="mg-btn mg-btn-primary">Send Invitation</button></div></form></dialog>

  <dialog class="mg-ccp-dialog" data-ccp-review-dialog><section class="mg-ccp-dialog-card"><header><div><span class="mg-eyebrow">Application Review</span><h2 data-ccp-review-title>Creator application</h2></div><button type="button" class="mg-ccp-close" data-ccp-close-review aria-label="Close">×</button></header><div data-ccp-review-content></div><form data-ccp-review-form><input type="hidden" name="application_id"><input type="hidden" name="expected_lock_version"><label>Decision reason<textarea name="reason" rows="3" maxlength="1000"></textarea></label><label>Internal note<textarea name="internal_note" rows="3" maxlength="16000"></textarea></label><div class="mg-ccp-review-actions"><button type="button" class="mg-btn mg-btn-soft" data-review-action="start_review">Start Review</button><button type="button" class="mg-btn mg-btn-soft" data-review-action="request_information">Request Info</button><button type="button" class="mg-btn mg-btn-danger" data-review-action="decline">Decline</button><button type="button" class="mg-btn mg-btn-primary" data-review-action="approve">Approve + Offer Version 1</button></div></form></section></dialog>

  <dialog class="mg-ccp-dialog" data-ccp-agreement-dialog><form class="mg-ccp-dialog-card mg-ccp-agreement-card" data-ccp-agreement-form><header><div><span class="mg-eyebrow">Immutable Agreement</span><h2>Offer Agreement Version</h2></div><button type="button" class="mg-ccp-close" data-ccp-close-agreement aria-label="Close">×</button></header><input type="hidden" name="participant_id"><label>Summary<input name="summary" maxlength="1000" required></label><label>Terms<textarea name="terms_text" rows="7" maxlength="32000" required></textarea></label><div class="mg-ccp-detail-grid"><label>Deliverables<textarea name="deliverables" rows="3"></textarea></label><label>Compensation<textarea name="compensation" rows="3"></textarea></label><label>Content rights<textarea name="content_rights" rows="3"></textarea></label><label>Disclosures<textarea name="disclosures" rows="3"></textarea></label><label>Cancellation<textarea name="cancellation" rows="3"></textarea></label><label>Reversal<textarea name="reversal" rows="3"></textarea></label></div><label>Creator-specific terms<textarea name="creator_specific" rows="3"></textarea></label><label>Change summary<textarea name="change_summary" rows="2" maxlength="2000"></textarea></label><label class="mg-ccp-check"><input type="checkbox" name="requires_reacceptance" checked> Require creator acceptance for this version</label><div class="mg-ccp-dialog-actions"><button type="button" class="mg-btn mg-btn-ghost" data-ccp-close-agreement>Cancel</button><button type="submit" class="mg-btn mg-btn-primary">Offer Immutable Version</button></div></form></dialog>
</section>
