<?php declare(strict_types=1); $programId=trim((string)($_GET['id']??'')); ?>
<section class="mg-merchant-heading"><div><span class="mg-eyebrow">Campaign detail</span><h1 data-distribution-program-title>Loading program</h1><p data-distribution-program-subtitle><?= mg_e($programId) ?></p></div><a class="mg-btn mg-btn-soft" href="/merchant-distribution.php">Back to programs</a></section>
<div class="mg-program-detail" data-program-detail data-program-id="<?= mg_e($programId) ?>">
<section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Program overview</h2><p>Budget, timing, recipients, allocations, and issuance state.</p></div></div><div class="mg-app-panel-body"><div class="mg-program-facts" data-program-facts></div></div></section>
<section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Program products</h2><p>Active PPPM templates for this campaign.</p></div></div><div class="mg-app-panel-body"><div data-program-products></div></div></section>
<section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Eligibility</h2><p>Update recipient eligibility and selection status.</p></div></div><div class="mg-app-panel-body"><div class="mg-bulk-actions"><select data-eligibility-status><option value="eligible">Eligible</option><option value="ineligible">Ineligible</option><option value="selected">Selected</option><option value="disqualified">Disqualified</option></select><input data-eligibility-reason placeholder="Reason"><button class="mg-btn mg-btn-soft" type="button" data-eligibility-apply>Apply to selected</button></div><div class="mg-recipient-list" data-recipient-list></div></div></section>
<section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Assignment batch</h2><p>Queue PPPM assignments for selected recipients.</p></div></div><div class="mg-app-panel-body"><form class="mg-merchant-form" data-batch-form><label>Batch name<input name="name" value="Campaign assignment batch"></label><div class="mg-grid-2"><label>PPPM template<select name="template_id" data-batch-template></select></label><label>Quantity each<input name="quantity" type="number" min="1" max="100" value="1"></label></div><label>Method<select name="allocation_method"><option value="batch">Batch</option><option value="direct">Direct</option><option value="random">Random</option><option value="weighted_random">Weighted random</option><option value="ranked">Ranked</option><option value="api">API</option></select></label><div class="mg-form-status" data-batch-status></div><button class="mg-btn mg-btn-primary" type="submit">Queue selected recipients</button></form><div data-batch-list></div></div></section>
<section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Allocations and issuance</h2><p>Track allocation status and issuance jobs.</p></div></div><div class="mg-app-panel-body"><div data-allocation-list></div></div></section>
<section class="mg-app-panel"><div class="mg-app-panel-head"><div><h2>Input sources</h2><p>Connected ecommerce, API, webhook, gaming, workplace, contest, and CSV sources.</p></div></div><div class="mg-app-panel-body"><div data-source-list></div></div></section>
</div>
