<?php declare(strict_types=1); ?>
<section class="mg-ccmsg-shell" data-ccmsg-merchant>
<header class="mg-ccmsg-head"><div><a href="/merchant-creator-payouts.php">← Payouts & Disputes</a><span>Creator Campaign Operations · Phase 9</span><h1>Messages & Notifications</h1><p>Use Microgifter’s canonical Messages center and preference-aware notification delivery for Creator Campaign communication.</p></div></header>
<section class="mg-ccmsg-metrics" data-ccmsg-metrics></section>
<nav class="mg-ccmsg-tabs"><button class="is-active" data-ccmsg-tab="threads">Campaign Threads</button><button data-ccmsg-tab="notes">Internal Notes</button></nav>
<div class="mg-ccmsg-state" data-ccmsg-state>Loading campaign communications…</div><section class="mg-ccmsg-list" data-ccmsg-list></section>
<dialog data-ccmsg-send-dialog><form data-ccmsg-send-form><header><h2>Send Campaign Message</h2><button type="button" data-ccmsg-close>×</button></header><input type="hidden" name="participant_id"><label>Context<select name="context_type"><option value="campaign">Campaign</option><option value="deliverable">Deliverable</option><option value="submission">Submission</option><option value="earning">Earning</option><option value="payout">Payout</option><option value="dispute">Dispute</option></select></label><label>Context reference<input name="context_public_id" maxlength="80" placeholder="Optional public ID"></label><label>Message<textarea name="body" rows="7" maxlength="8000" required></textarea></label><div><button type="button" class="mg-btn" data-ccmsg-close>Cancel</button><button class="mg-btn mg-btn-primary" type="submit">Send through Messages</button></div></form></dialog>
<dialog data-ccmsg-note-dialog><form data-ccmsg-note-form><header><h2>Add Merchant-Only Note</h2><button type="button" data-ccmsg-close>×</button></header><input type="hidden" name="participant_id"><label>Context<select name="context_type"><option value="campaign">Campaign</option><option value="participant">Participant</option><option value="deliverable">Deliverable</option><option value="submission">Submission</option><option value="earning">Earning</option><option value="payout">Payout</option><option value="dispute">Dispute</option></select></label><label>Context reference<input name="context_public_id" maxlength="80" placeholder="Optional public ID"></label><label>Internal note<textarea name="body" rows="7" maxlength="12000" required></textarea></label><p class="mg-ccmsg-private">This note is never inserted into the Creator-visible message thread.</p><div><button type="button" class="mg-btn" data-ccmsg-close>Cancel</button><button class="mg-btn mg-btn-primary" type="submit">Save Internal Note</button></div></form></dialog>
</section>
