<?php
declare(strict_types=1);

function mg_task_agent_context_snapshot(PDO $pdo,int $userId,int $horizonDays=90):array{
 $contacts=mg_personal_agent_contacts($pdo,$userId,250);$upcoming=mg_personal_agent_upcoming_dates($pdo,$userId,$horizonDays,100);$plans=mg_personal_agent_plans($pdo,$userId,'all',100);$reminders=mg_personal_agent_reminders($pdo,$userId,'scheduled',100);$map=[];foreach($contacts as $c)$map[(string)($c['id']??'')]=$c;
 $missing=array_values(array_filter($contacts,static fn(array $c):bool=>($c['type']??'')==='contact'&&empty($c['birthdate'])));$budgets=array_values(array_filter($contacts,static fn(array $c):bool=>$c['budget_min']!==null||$c['budget_max']!==null));
 return ['source'=>'system','used_ai'=>false,'horizon_days'=>max(1,min(365,$horizonDays)),'summary'=>['contacts'=>count($contacts),'upcoming_dates'=>count($upcoming),'missing_birthdays'=>count($missing),'active_plans'=>count(array_filter($plans,static fn(array $p):bool=>!in_array($p['status']??'',['completed','cancelled'],true))),'scheduled_reminders'=>count($reminders),'contacts_with_budgets'=>count($budgets)],'upcoming'=>array_slice($upcoming,0,12),'missing_birthdays'=>array_slice(array_map(static fn(array $c):array=>['id'=>(string)($c['id']??''),'name'=>(string)($c['display_name']??'Contact'),'relationship'=>(string)($c['relationship']??''),'list_names'=>(string)($c['list_names']??'')],$missing),0,12),'contacts_by_id'=>$map,'plans'=>array_slice($plans,0,12),'reminders'=>array_slice($reminders,0,12)];
}
function mg_task_agent_plan_payload(array $event,array $snapshot):array{
 $id=(string)($event['contact_id']??'');$contact=is_array($snapshot['contacts_by_id'][$id]??null)?$snapshot['contacts_by_id'][$id]:[];$name=trim((string)($event['contact_name']??$contact['display_name']??'Contact'));$label=trim((string)($event['label']??'Occasion'));
 return ['context_type'=>'contact','context_id'=>$id,'title'=>$name.' — '.$label.' gift plan','occasion_type'=>(string)($event['type']??'important_date'),'occasion_label'=>$label,'target_date'=>(string)($event['event_date']??''),'budget_min'=>$contact['budget_min']??null,'budget_max'=>$contact['budget_max']??null,'currency'=>'USD','notes'=>'Draft created from the Birthday & Occasion task agent. Review preferences, restrictions, merchant availability, timing, and delivery before approval.','source'=>'important_date','recommendation'=>['recipient'=>$name,'relationship'=>(string)($event['relationship']??$contact['relationship']??''),'interests'=>(string)($contact['interests']??''),'gift_preferences'=>(string)($contact['gift_preferences']??''),'system_generated'=>true,'used_ai'=>false]];
}
function mg_task_agent_reminder_payload(array $event):array{
 $name=trim((string)($event['contact_name']??'Contact'));$label=trim((string)($event['label']??'Occasion'));$date=(string)($event['event_date']??'');$days=max(0,min(365,(int)($event['reminder_days_before']??14)));
 try{$when=(new DateTimeImmutable($date.' 09:00:00',new DateTimeZone('UTC')))->modify('-'.$days.' days');}catch(Throwable){$when=new DateTimeImmutable('+1 day 09:00:00',new DateTimeZone('UTC'));}
 if($when<=new DateTimeImmutable('now',new DateTimeZone('UTC')))$when=new DateTimeImmutable('+1 hour',new DateTimeZone('UTC'));
 return ['context_type'=>'contact','context_id'=>(string)($event['contact_id']??''),'reminder_type'=>'gift_planning','title'=>'Plan for '.$name.' — '.$label,'remind_at'=>$when->format('Y-m-d H:i:s'),'notes'=>'System-created in-app planning reminder for '.$label.' on '.$date.'. No gift, message, purchase, or delivery is scheduled.'];
}
function mg_task_agent_opportunity_cards(array $snapshot):array{
 $cards=[];foreach(array_slice($snapshot['upcoming']??[],0,6) as $event){$name=trim((string)($event['contact_name']??'Contact'));$label=trim((string)($event['label']??'Occasion'));$days=max(0,(int)($event['days_until']??0));$timing=$days===0?'Today':($days===1?'Tomorrow':$days.' days away');
  $cards[]=['type'=>'gift_plan','title'=>$name.' — '.$label,'body'=>$timing.'. Save an approval-first plan using stored budget and preferences.','action'=>'save_draft','prompt'=>'Create a gift plan for '.$name."'s ".strtolower($label).'.','review_payload'=>['canonical_plan'=>mg_task_agent_plan_payload($event,$snapshot)]];
  $cards[]=['type'=>'reminder','title'=>'Remind me to plan for '.$name,'body'=>'Create an in-app planning reminder before '.$label.'.','action'=>'save_reminder','review_payload'=>['canonical_reminder'=>mg_task_agent_reminder_payload($event)]];
 }return array_slice($cards,0,8);
}
function mg_task_agent_reminder_cards(array $reminders):array{
 return array_map(static fn(array $r):array=>['type'=>'reminder','title'=>(string)($r['title']??'Reminder'),'body'=>(string)($r['remind_at']??''),'action'=>'manage_reminder','review_payload'=>['reminder_id'=>(string)($r['id']??'')]],array_slice($reminders,0,12));
}
function mg_task_agent_system_response(string $message,array $snapshot):?array{
 $text=mb_strtolower(trim($message));if($text==='')return null;$upcoming=$snapshot['upcoming']??[];$missing=$snapshot['missing_birthdays']??[];$summary=$snapshot['summary']??[];
 if(preg_match('/\b(create|set|add|schedule)\b/u',$text)&&preg_match('/\b(reminder|remind me)\b/u',$text)){$selected=null;foreach($upcoming as $event){$name=mb_strtolower((string)($event['contact_name']??''));if($name!==''&&str_contains($text,$name)){$selected=$event;break;}}if(!$selected)$selected=$upcoming[0]??null;if(!$selected)return ['reply'=>'Add a contact birthday or important date before creating a planning reminder.','cards'=>[],'system_intent'=>'create_reminder'];return ['reply'=>'I prepared an in-app planning reminder from the saved occasion date. Review and save it; no gift, message, purchase, or delivery will occur.','cards'=>[['type'=>'reminder','title'=>'Create planning reminder','body'=>'The reminder uses the saved lead time and occasion date.','action'=>'save_reminder','review_payload'=>['canonical_reminder'=>mg_task_agent_reminder_payload($selected)]]],'system_intent'=>'create_reminder'];}
 if(preg_match('/\b(create|build|start|prepare|draft)\b/u',$text)&&preg_match('/\b(gift plan|plan|birthday|occasion)\b/u',$text)){$selected=null;foreach($upcoming as $event){$name=mb_strtolower((string)($event['contact_name']??''));if($name!==''&&str_contains($text,$name)){$selected=$event;break;}}if(!$selected)$selected=$upcoming[0]??null;if(!$selected)return ['reply'=>'Add a contact birthday or important date before creating an occasion-based gift plan.','cards'=>[],'system_intent'=>'gift_plan_draft'];$cards=mg_task_agent_opportunity_cards(['upcoming'=>[$selected],'contacts_by_id'=>$snapshot['contacts_by_id']??[]]);return ['reply'=>'I prepared an approval-first gift-plan draft from saved Microgifter data. Review it before saving; no purchase, message, or delivery will occur.','cards'=>$cards,'system_intent'=>'gift_plan_draft'];}
 if(preg_match('/\b(birthday|birthdays|occasion|occasions|important dates?|upcoming)\b/u',$text)){if(!$upcoming)return ['reply'=>'You do not have any saved birthdays or important dates in the next '.(int)($snapshot['horizon_days']??90).' days.','cards'=>[],'system_intent'=>'upcoming_dates'];$lines=[];foreach(array_slice($upcoming,0,10) as $e)$lines[]=(string)($e['contact_name']??'Contact').' — '.(string)($e['label']??'Occasion').' on '.(string)($e['event_date']??'').' ('.(int)($e['days_until']??0).' days)';return ['reply'=>"Here are your upcoming saved dates:\n\n".implode("\n",$lines),'cards'=>mg_task_agent_opportunity_cards($snapshot),'system_intent'=>'upcoming_dates'];}
 if(str_contains($text,'missing birthday')||str_contains($text,'without birthday')){if(!$missing)return ['reply'=>'Every private contact currently has a saved birthday.','cards'=>[],'system_intent'=>'missing_birthdays'];$names=array_map(static fn(array $c):string=>(string)($c['name']??'Contact'),array_slice($missing,0,20));return ['reply'=>count($missing)." contacts are missing birthdays:\n\n".implode("\n",$names),'cards'=>[],'system_intent'=>'missing_birthdays'];}
 if(preg_match('/\b(summary|overview|brief|status)\b/u',$text))return ['reply'=>sprintf('You have %d contacts, %d upcoming dates, %d contacts missing birthdays, %d active gift plans, and %d scheduled reminders.',(int)($summary['contacts']??0),(int)($summary['upcoming_dates']??0),(int)($summary['missing_birthdays']??0),(int)($summary['active_plans']??0),(int)($summary['scheduled_reminders']??0)),'cards'=>mg_task_agent_opportunity_cards($snapshot),'system_intent'=>'overview'];
 if(preg_match('/\b(reminder|reminders)\b/u',$text)&&(str_contains($text,'show')||str_contains($text,'list')||str_contains($text,'upcoming'))){$r=$snapshot['reminders']??[];if(!$r)return ['reply'=>'You do not have any scheduled gifting reminders.','cards'=>[],'system_intent'=>'reminders'];$lines=array_map(static fn(array $x):string=>(string)($x['title']??'Reminder').' — '.(string)($x['remind_at']??''),array_slice($r,0,20));return ['reply'=>"Here are your scheduled reminders:\n\n".implode("\n",$lines),'cards'=>mg_task_agent_reminder_cards($r),'system_intent'=>'reminders'];}
 return null;
}
