<?php
declare(strict_types=1);
require __DIR__ . '/app.php';
$config = lqr_config();
$state = lqr_load_state();
$quests = lqr_quests();
$section = preg_replace('/[^a-z_]/', '', (string)($_GET['section'] ?? 'dashboard')) ?: 'dashboard';
function lq_portal_stats(array $state, array $quests): array{
  $users=is_array($state['users']??null)?$state['users']:[]; $linked=0;$completed=0;$rewards=0;$claimed=0;
  foreach($users as $u){if(!is_array($u))continue;if(!empty($u['linked_account_id']))$linked++;$completed+=count(is_array($u['completed_quests']??null)?$u['completed_quests']:[]);foreach((array)($u['rewards']??[]) as $r){if(!is_array($r))continue;$rewards++;if(($r['claim_status']??'')==='claimed_in_quest_app')$claimed++;}}
  return ['total_users'=>count($users),'linked_users'=>$linked,'active_quests'=>count($quests),'quest_completions'=>$completed,'rewards'=>$rewards,'claims'=>$claimed,'events'=>count((array)($state['events']??[]))];
}
function lq_nav(string $section): string{
  $items=['dashboard'=>['⌂','Dashboard'],'quests'=>['◈','Quests'],'users'=>['☏','Users'],'wallets'=>['◉','Wallets'],'claims'=>['◇','Claims'],'events'=>['◷','Events'],'settings'=>['⚙','Settings']];$out='';
  foreach($items as $key=>$item){$out.='<a class="lq-side-link '.($section===$key?'active':'').'" href="admin-portal.php?section='.lqr_h($key).'"><span class="lq-side-icon">'.$item[0].'</span><span class="lq-side-label">'.lqr_h($item[1]).'</span></a>';}
  return $out;
}
function lq_kpi(string $label,int $value): string{return '<div class="lq-kpi"><span>'.lqr_h($label).'</span><strong>'.number_format($value).'</strong></div>';}
$stats=lq_portal_stats($state,$quests);
$users=is_array($state['users']??null)?$state['users']:[];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quest Admin Portal</title><link rel="stylesheet" href="assets/portal.css"></head><body class="lq-portal">
<?php if (empty($_SESSION['lqr_admin_authed'])): ?><main class="lq-cover"><section class="lq-cover-hero"><span class="lq-eyebrow">Developer Portal</span><h1>Quest admin portal</h1><p>Sign into the existing admin backend first, then return to this styled portal.</p><a class="lq-btn primary" href="admin.php">Admin sign in</a></section><aside class="lq-cover-side"><div class="lq-panel"><h2>Portal preview</h2><p>This page uses the expanding left rail, KPI cards, quick actions, QR scan panels, and geolocation capture.</p></div></aside></main><?php exit; endif; ?>
<div class="lq-shell"><header class="lq-topbar"><div class="lq-brand"><span class="lq-logo">LQ</span><span>Developer Portal</span></div><div class="lq-top-actions"><a class="lq-icon-btn" href="admin-portal.php?section=claims">☏<span class="lq-badge"><?= number_format((int)$stats['claims']) ?></span></a><a class="lq-upgrade" href="index.php">User App</a><span class="lq-user-pill"><span class="lq-avatar">A</span><?= lqr_h((string)($_SESSION['lqr_admin_username'] ?? 'Admin')) ?></span></div></header><aside class="lq-sidebar"><?= lq_nav($section) ?><span class="lq-side-spacer"></span><a class="lq-side-link" href="cover.php"><span class="lq-side-icon">LQ</span><span class="lq-side-label">Launch app</span></a></aside><main class="lq-main"><section class="lq-page-head"><span class="lq-eyebrow">Developer Portal</span><h1><?= lqr_h(ucwords(str_replace('_',' ',$section))) ?></h1><p>Review quest activity, users, wallet rewards, QR scans, claim geolocation, and Microgifter reporting from one dashboard.</p></section>
<?php if($section==='dashboard'): ?><div class="lq-kpis"><?= lq_kpi('Total users',(int)$stats['total_users']) ?><?= lq_kpi('Linked users',(int)$stats['linked_users']) ?><?= lq_kpi('Rewards',(int)$stats['rewards']) ?><?= lq_kpi('Claims',(int)$stats['claims']) ?></div><div class="lq-layout"><section class="lq-card"><div class="lq-card-head"><div><h2>Project requests</h2><p>Current Quest app activity and claim pipeline.</p></div><span class="lq-pill pink">Active</span></div><div class="lq-stack"><?php foreach(array_slice((array)($state['events']??[]),0,8) as $e): if(!is_array($e))continue; ?><div class="lq-item"><div><h3><?= lqr_h((string)$e['type']) ?></h3><div class="lq-meta"><?= lqr_h((string)$e['message']) ?><br><?= lqr_h((string)$e['at']) ?></div></div><span class="lq-pill">Event</span></div><?php endforeach; ?></div></section><aside class="lq-side-panel"><section class="lq-panel"><h2>Quick actions</h2><a class="lq-link-row" href="admin-portal.php?section=quests">Quest builder <span>→</span></a><a class="lq-link-row" href="admin-portal.php?section=users">Customers <span>→</span></a><a class="lq-link-row" href="admin-portal.php?section=claims">Claims <span>→</span></a><a class="lq-link-row" href="wallet.php">User wallet <span>→</span></a></section><section class="lq-panel"><h2>Admin QR / Geo</h2><div class="lq-qr-box" data-lq-qr-box><input class="lq-input" data-lq-qr-manual placeholder="Paste venue/prize QR"><button class="lq-btn dark" data-lq-start-qr>Scan QR</button><video class="lq-qr-video" playsinline></video><div class="lq-qr-result" data-lq-qr-result>No QR captured.</div></div><div data-lq-geo-box><button class="lq-btn soft" data-lq-capture-geo>Capture location</button><div class="lq-qr-result" data-lq-geo-result>No location captured.</div></div></section></aside></div>
<?php elseif($section==='quests'): ?><div class="lq-layout"><section class="lq-card"><h2>Quest catalog</h2><div class="lq-stack"><?php foreach($quests as $key=>$q): ?><div class="lq-item"><div><h3><?= lqr_h((string)$q['title']) ?></h3><div class="lq-meta"><?= lqr_h($key) ?> · <?= lqr_h((string)$q['event_type']) ?><br><?= lqr_h((string)$q['description']) ?><br><strong><?= lqr_h((string)$q['reward_label']) ?></strong></div></div><div class="lq-actions"><a class="lq-btn soft" href="admin.php?section=quests&edit=<?= urlencode((string)$key) ?>">Edit in backend</a></div></div><?php endforeach; ?></div></section><aside class="lq-panel"><h2>Create / edit quests</h2><p>The styled portal links into the existing admin backend for write actions while preserving the current save logic.</p><a class="lq-btn primary" href="admin.php?section=quests">Open quest editor</a></aside></div>
<?php elseif($section==='users'): ?><section class="lq-card"><h2>User accounts</h2><div class="lq-stack"><?php foreach($users as $id=>$u): if(!is_array($u))continue; ?><div class="lq-item"><div><h3><?= lqr_h((string)$u['display_name']) ?></h3><div class="lq-meta"><?= lqr_h((string)$u['email']) ?> · <?= lqr_h((string)$id) ?><br>External <code><?= lqr_h((string)$u['external_user_id']) ?></code><br>Microgifter <code><?= lqr_h((string)($u['linked_account_id'] ?: 'not linked')) ?></code></div></div><a class="lq-btn soft" href="admin.php?section=users">Manage</a></div><?php endforeach; ?></div></section>
<?php elseif($section==='wallets'||$section==='claims'): ?><section class="lq-card"><h2><?= $section==='claims'?'Claim pipeline':'Wallet records' ?></h2><div class="lq-stack"><?php foreach($users as $id=>$u): if(!is_array($u))continue; foreach((array)($u['rewards']??[]) as $questId=>$r): if(!is_array($r))continue; ?><div class="lq-item"><div><h3><?= lqr_h((string)($quests[$questId]['title'] ?? $questId)) ?></h3><div class="lq-meta"><?= lqr_h((string)($u['email'] ?? $id)) ?><br>Reward <code><?= lqr_h((string)($r['reward_id'] ?? '')) ?></code><br>Status <?= lqr_h((string)($r['status'] ?? 'unknown')) ?> · Claim <?= lqr_h((string)($r['claim_status'] ?? 'available')) ?> · Report <?= lqr_h((string)($r['claim_report_status'] ?? 'not_reported')) ?></div></div><form method="post" action="admin.php?section=claims" data-lq-geo-box data-lq-qr-box><input type="hidden" name="user_id" value="<?= lqr_h((string)$id) ?>"><input type="hidden" name="quest_id" value="<?= lqr_h((string)$questId) ?>"><input type="hidden" name="geo_lat"><input type="hidden" name="geo_lng"><input type="hidden" name="geo_accuracy"><input type="hidden" name="geo_captured_at"><input type="hidden" name="qr_payload"><input class="lq-input" data-lq-qr-manual placeholder="Claim QR / prize code"><div class="lq-actions"><button class="lq-btn soft" data-lq-start-qr>Scan QR</button><button class="lq-btn soft" data-lq-capture-geo>Geo</button><button class="lq-btn primary" name="action" value="mark_claim_reported">Mark reported</button></div><video class="lq-qr-video" playsinline></video><div class="lq-qr-result" data-lq-qr-result></div><div class="lq-qr-result" data-lq-geo-result></div></form></div><?php endforeach; endforeach; ?></div></section>
<?php elseif($section==='events'): ?><section class="lq-card"><h2>Event log</h2><div class="lq-stack"><?php foreach((array)($state['events']??[]) as $e): if(!is_array($e))continue; ?><div class="lq-item"><div><h3><?= lqr_h((string)$e['type']) ?></h3><div class="lq-meta"><?= lqr_h((string)$e['at']) ?><br><?= lqr_h((string)$e['message']) ?></div></div><span class="lq-pill">Event</span></div><?php endforeach; ?></div></section>
<?php else: ?><div class="lq-grid-3"><section class="lq-panel"><h2>Storage</h2><div class="lq-row"><span>Driver</span><strong><?= lqr_h((string)($config['storage']['driver'] ?? 'json')) ?></strong></div><div class="lq-row"><span>SQL</span><strong>database/local_quest_rewards.sql</strong></div></section><section class="lq-panel"><h2>Microgifter</h2><div class="lq-row"><span>Base</span><strong><?= lqr_h((string)$config['base_url']) ?></strong></div><div class="lq-row"><span>Mode</span><strong><?= lqr_h((string)$config['mode']) ?></strong></div></section><section class="lq-panel"><h2>Backend</h2><p>Write actions currently post to <code>admin.php</code>. The portal is the styled dashboard layer.</p></section></div><?php endif; ?>
</main></div><script src="assets/portal.js"></script></body></html>
