<?php
declare(strict_types=1);
require __DIR__ . '/app.php';
$config = lqr_config();
$appUrl = rtrim((string)($config['app_public_url'] ?? ''), '/');
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Local Quest Rewards Demo | Microgifter</title>
<link rel="stylesheet" href="assets/portal.css">
<style>
.lq-demo-hero{position:relative;overflow:hidden;background:radial-gradient(circle at 15% 20%,rgba(255,255,255,.16),transparent 24%),linear-gradient(135deg,#101828 0%,#211816 45%,#4b1729 100%);color:#fff;border-radius:18px;padding:42px;margin-bottom:22px;box-shadow:var(--lq-shadow)}.lq-demo-hero h1{font-size:clamp(42px,7vw,82px);line-height:.9;letter-spacing:-.08em;margin:14px 0}.lq-demo-hero p{color:#ffe6ef;max-width:900px;font-size:17px}.lq-demo-orbit{position:absolute;right:-120px;top:-120px;width:360px;height:360px;border:1px solid rgba(255,255,255,.18);border-radius:50%}.lq-demo-orbit:after{content:'';position:absolute;inset:70px;border:1px dashed rgba(255,255,255,.22);border-radius:50%}.lq-demo-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.lq-demo-card{background:#fff;border:1px solid var(--lq-border);border-radius:14px;padding:20px;box-shadow:var(--lq-shadow)}.lq-demo-card h2{margin:0 0 8px}.lq-demo-card p{color:var(--lq-muted);margin:0}.lq-demo-flow{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin-top:22px}.lq-demo-flow article{background:#fff;border:1px solid var(--lq-border);border-radius:12px;padding:16px}.lq-demo-flow b{display:grid;place-items:center;width:34px;height:34px;border-radius:999px;background:#fff1f5;color:var(--lq-pink);margin-bottom:10px}.lq-demo-flow strong{display:block;margin-bottom:6px}.lq-demo-flow span{font-size:13px;color:var(--lq-muted)}.lq-demo-links{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:22px}.lq-demo-link{display:block;text-decoration:none;color:var(--lq-text);background:#fff;border:1px solid var(--lq-border);border-radius:12px;padding:16px;box-shadow:var(--lq-shadow)}.lq-demo-link strong{display:block;margin-bottom:5px}.lq-demo-link span{font-size:13px;color:var(--lq-muted)}@media(max-width:1100px){.lq-demo-grid,.lq-demo-flow,.lq-demo-links{grid-template-columns:1fr 1fr}.lq-demo-orbit{opacity:.25}}@media(max-width:700px){.lq-demo-grid,.lq-demo-flow,.lq-demo-links{grid-template-columns:1fr}.lq-demo-hero{padding:28px}.lq-demo-hero h1{font-size:44px}}
</style>
</head>
<body class="lq-portal">
<div class="lq-shell">
<header class="lq-topbar"><div class="lq-brand"><span class="lq-logo">LQ</span><span>Local Quest</span></div><div class="lq-top-actions"><a class="lq-upgrade" href="start.php">Start Demo</a><a class="lq-upgrade" href="how-it-works.php">How it works</a><a class="lq-upgrade" href="api-examples.php">API Examples</a></div></header>
<aside class="lq-sidebar"><a class="lq-side-link active" href="demo.php"><span class="lq-side-icon">★</span><span class="lq-side-label">Demo overview</span></a><a class="lq-side-link" href="start.php"><span class="lq-side-icon">▶</span><span class="lq-side-label">Launcher</span></a><a class="lq-side-link" href="how-it-works.php"><span class="lq-side-icon">↔</span><span class="lq-side-label">How it works</span></a><a class="lq-side-link" href="deployment-checklist.php"><span class="lq-side-icon">☑</span><span class="lq-side-label">Checklist</span></a><a class="lq-side-link" href="api-examples.php"><span class="lq-side-icon">{}</span><span class="lq-side-label">API Examples</span></a><a class="lq-side-link" href="docs/local-quest-developer-handoff.md"><span class="lq-side-icon">DOC</span><span class="lq-side-label">Handoff doc</span></a></aside>
<main class="lq-main">
<section class="lq-demo-hero"><div class="lq-demo-orbit"></div><span class="lq-eyebrow">Microgifter example app</span><h1>Local Quest Rewards demo.</h1><p>A partner-facing starter app showing how an outside product can own the quest experience while Microgifter owns reward issuance, wallet claim reporting, signed webhooks, and audit-ready reward lifecycle data.</p><div class="lq-actions"><a class="lq-btn primary" href="start.php">Start Demo</a><a class="lq-btn soft" href="how-it-works.php">View lifecycle</a><a class="lq-btn soft" href="deployment-checklist.php">Deployment checklist</a></div></section>
<section class="lq-demo-grid"><article class="lq-demo-card"><h2>Third-party app UX</h2><p>Local Quest manages sign-in, QR/geolocation quest actions, participant progress, and the reward wallet interface.</p></article><article class="lq-demo-card"><h2>Microgifter API layer</h2><p>Microgifter handles linked accounts, Distribution Program permissions, reward issue, status, claim reports, and webhook events.</p></article><article class="lq-demo-card"><h2>Developer handoff ready</h2><p>The demo includes runtime diagnostics, API examples, webhook testing tools, seed data, and a launch checklist.</p></article></section>
<section class="lq-card" style="margin-top:22px"><div class="lq-card-head"><div><h2>API lifecycle at a glance</h2><p>The demo is built around a simple outside-app → Microgifter lifecycle.</p></div><span class="lq-pill green">Handoff flow</span></div><div class="lq-demo-flow"><article><b>1</b><strong>Link</strong><span>Participant links to Microgifter or uses a sandbox linked account.</span></article><article><b>2</b><strong>Quest</strong><span>Local Quest captures QR/geolocation task context.</span></article><article><b>3</b><strong>Issue</strong><span>The app issues a mapped Microgift through the Public Distribution API.</span></article><article><b>4</b><strong>Claim</strong><span>The app wallet reports claim evidence back to Microgifter.</span></article><article><b>5</b><strong>Webhook</strong><span>Signed lifecycle events reconcile app state and audit history.</span></article></div></section>
<section class="lq-demo-links"><a class="lq-demo-link" href="runtime-diagnostics.php"><strong>Runtime diagnostics</strong><span>Check SQL/API/webhook configuration.</span></a><a class="lq-demo-link" href="webhook-tools.php"><strong>Webhook tools</strong><span>Generate signed local payloads.</span></a><a class="lq-demo-link" href="admin-demo-tools.php"><strong>Demo seed tools</strong><span>Prepare a predictable partner demo.</span></a><a class="lq-demo-link" href="admin-developer-readiness.php"><strong>Admin readiness</strong><span>Review launch evidence.</span></a></section>
<?php if ($appUrl !== ''): ?><section class="lq-card" style="margin-top:22px"><h2>Configured app URL</h2><p><?= lqr_h($appUrl) ?></p></section><?php endif; ?>
</main>
</div>
</body>
</html>
