<?php
declare(strict_types=1);
require __DIR__ . '/app.php';
$steps = [
    ['Link', 'Participant links to Microgifter or uses a sandbox linked account.'],
    ['Quest', 'Local Quest captures QR/geolocation task context.'],
    ['Issue', 'The app issues a mapped Microgift reward after verified action.'],
    ['Claim', 'The app wallet reports claim evidence back to Microgifter.'],
    ['Webhook', 'Signed lifecycle events reconcile app state and audit history.'],
];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>How Local Quest Works</title><link rel="stylesheet" href="assets/portal.css"><style>.lq-how-hero{background:linear-gradient(135deg,#0f172a,#211816);color:#fff;border-radius:18px;padding:34px;margin-bottom:22px}.lq-how-hero h1{font-size:clamp(38px,6vw,74px);line-height:.9;letter-spacing:-.08em;margin:12px 0}.lq-how-hero p{color:#d9e2f2;max-width:880px}.lq-stage{display:grid;grid-template-columns:42px minmax(0,1fr);gap:14px;background:#fff;border:1px solid var(--lq-border);border-radius:12px;padding:15px;margin-bottom:12px;box-shadow:var(--lq-shadow)}.lq-stage b{display:grid;place-items:center;width:42px;height:42px;border-radius:999px;background:#fff1f5;color:var(--lq-pink)}.lq-stage p{margin:5px 0 0;color:var(--lq-muted)}</style></head><body class="lq-portal"><div class="lq-shell"><header class="lq-topbar"><div class="lq-brand"><span class="lq-logo">LQ</span><span>Local Quest</span></div><div class="lq-top-actions"><a class="lq-upgrade" href="demo.php">Demo overview</a><a class="lq-upgrade" href="start.php">Start Demo</a><a class="lq-upgrade" href="api-examples.php">API Examples</a></div></header><aside class="lq-sidebar"><a class="lq-side-link" href="demo.php"><span class="lq-side-icon">★</span><span class="lq-side-label">Demo overview</span></a><a class="lq-side-link active" href="how-it-works.php"><span class="lq-side-icon">↔</span><span class="lq-side-label">How it works</span></a><a class="lq-side-link" href="deployment-checklist.php"><span class="lq-side-icon">☑</span><span class="lq-side-label">Checklist</span></a><a class="lq-side-link" href="api-examples.php"><span class="lq-side-icon">{}</span><span class="lq-side-label">API Examples</span></a></aside><main class="lq-main"><section class="lq-how-hero"><span class="lq-eyebrow">API lifecycle</span><h1>How the outside app and Microgifter work together.</h1><p>Local Quest owns participant experience and action capture. Microgifter owns reward authority, claim reporting, signed events, and audit trail.</p><div class="lq-actions"><a class="lq-btn primary" href="start.php">Run the demo</a><a class="lq-btn soft" href="deployment-checklist.php">Deployment checklist</a></div></section><section class="lq-card"><div class="lq-card-head"><div><h2>Lifecycle stages</h2><p>Use this as the partner developer briefing. Exact request examples live in the API examples page.</p></div><a class="lq-btn soft" href="api-examples.php">Copy API examples</a></div><?php foreach ($steps as $i => $step): ?><article class="lq-stage"><b><?= $i + 1 ?></b><div><h3><?= lqr_h($step[0]) ?></h3><p><?= lqr_h($step[1]) ?></p></div></article><?php endforeach; ?></section></main></div></body></html>
