<?php
return [
    'downtown-coffee-checkin' => [
        'title' => 'Downtown Coffee Quest',
        'merchant' => 'Demo Coffee Merchant',
        'location' => 'Downtown district',
        'description' => 'Complete a simple coffee shop check-in and receive a small local reward.',
        'event_type' => 'quest.completed',
        'program_id' => null,
        'template_id' => null,
        'reward_label' => '$5 Coffee Microgift',
        'difficulty' => 'Easy',
        'permission' => [
            'requires_completion' => true,
            'requires_linked_account' => true,
            'max_rewards_per_user' => 1,
            'allowed_modes' => ['sandbox', 'live'],
            'consent_label' => 'Send one coffee reward for this completed quest.',
        ],
    ],
    'live-music-night' => [
        'title' => 'Live Music Night',
        'merchant' => 'Demo Venue Merchant',
        'location' => 'Local venue',
        'description' => 'Reward a fan after they complete a venue or show-night quest.',
        'event_type' => 'quest.completed',
        'program_id' => null,
        'template_id' => null,
        'reward_label' => 'Free Appetizer Microgift',
        'difficulty' => 'Medium',
        'permission' => [
            'requires_completion' => true,
            'requires_linked_account' => true,
            'max_rewards_per_user' => 1,
            'allowed_modes' => ['sandbox', 'live'],
            'consent_label' => 'Send one venue reward for this completed quest.',
        ],
    ],
    'food-crawl-three-stops' => [
        'title' => 'Food Crawl: Three Stops',
        'merchant' => 'Demo Food Crawl Sponsor',
        'location' => 'Participating restaurants',
        'description' => 'Complete a three-stop local food crawl milestone and unlock a dining reward.',
        'event_type' => 'quest.milestone',
        'program_id' => null,
        'template_id' => null,
        'reward_label' => '$10 Dining Microgift',
        'difficulty' => 'Challenge',
        'permission' => [
            'requires_completion' => true,
            'requires_linked_account' => true,
            'max_rewards_per_user' => 1,
            'allowed_modes' => ['sandbox', 'live'],
            'consent_label' => 'Send one dining reward for this completed milestone.',
        ],
    ],
];
