<?php
 declare(strict_types=1);
require __DIR__ . '/app.php';
require __DIR__ . '/training-storage.php';
$config=lqr_config();$state=lqr_load_state();$userId=lqr_current_user_id($config);$user=lqr_get_user($state,$config,$userId);
$slug=trim((string)($_GET['campaign']??'5-day-movement-challenge'));$campaign=tcl_storage_campaign_by_slug($slug);$message='';$error='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST' && ($_POST['tcl_action']??'')==='join'){try{tcl_join_campaign($slug,$user);$message='Campaign joined. You can start the sequence.';}catch(Throwable $e){$error=$e->getMessage();}}
$progress=$campaign?tcl_progress($slug,$user):['joined'=>false,'steps'=>[],'percent'=>0,'approved'=>0,'total'=>0];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Training Sequence</title><link rel="stylesheet" href="assets/training-lab.css"></head><body class="tcl-app"><div class="tcl-shell"><aside class="tcl-sidebar"><a class="tcl-brand" href="training-lab.php"><span class="tcl-logo">MG</span><span><strong>Microgifter</strong><span>Training Campaign Lab</span></span></a><nav class="tcl-nav"><a href="training-lab.php"><span class="tcl-nav-icon">⌂</span><span>Dashboard</span></a><a href="training-campaigns.php"><span class="tcl-nav-icon">◆</span><span>Campaigns</span></a><a class="active" href="training-sequence.php?campaign=<?=lqr_h(urlencode($slug))?>"><span class="tcl-nav-icon">▤</span><span>Sequence</span></a><a href="training-rewards.php?campaign=<?=lqr_h(urlencode($slug))?>"><span class="tcl-nav-icon">◉</span><span>Rewards</span></a><a href="index.php"><span class="tcl-nav-icon">LQ</span><span>Local Quest</span></a></nav><div class="tcl-sidebar-card"><strong>Phase 4</strong><p>Participant join and sequence view are now wired.</p></div></aside><main class="tcl-main"><header class="tcl-topbar"><button class="tcl-mobile-menu">☰</button><div class="tcl-search">⌕ <span>Sequence, tasks, proof status</span></div><div class="tcl-top-actions"><span class="tcl-user-chip"><span class="tcl-avatar"><?=lqr_h(strtoupper(substr((string)($user['display_name']??'T'),0,1)))?></span><span><?=lqr_h((string)($user['display_name']??'Training User'))?></span></span></div></header>
<?php if(!$campaign):?><section class="tcl-page-head"><div><span class="tcl-eyebrow">Not found</span><h1>Campaign unavailable</h1><p>Choose another campaign.</p></div><a class="tcl-btn primary" href="training-campaigns.php">Campaigns</a></section><?php else:?>
<section class="tcl-page-head"><div><span class="tcl-eyebrow"><?=lqr_h((string)$campaign['title'])?></span><h1><?=lqr_h((string)($campaign['sequence']['title']??'Sequence'))?></h1><p><?=lqr_h((string)($campaign['sequence']['description']??'Complete each required task and submit proof when ready.'))?></p></div><div class="tcl-actions"><a class="tcl-btn" href="training-campaign-detail.php?campaign=<?=urlencode($slug)?>">Campaign Detail</a><?php if(!$progress['joined']):?><form method="post"><input type="hidden" name="tcl_action" value="join"><button class="tcl-btn primary" type="submit">Join Campaign</button></form><?php else:?><a class="tcl-btn primary" href="#tasks">Continue</a><?php endif;?></div></section>
<?php if($message):?><div class="tcl-card" style="margin-bottom:16px"><span class="tcl-pill is-success"><?=lqr_h($message)?></span></div><?php endif;?><?php if($error):?><div class="tcl-card" style="margin-bottom:16px"><span class="tcl-pill is-danger"><?=lqr_h($error)?></span></div><?php endif;?>
<section class="tcl-grid cols-4"><div class="tcl-card tcl-kpi"><span>Progress</span><strong><?=number_format((int)$progress['percent'])?>%</strong><small><?=$progress['approved']?> of <?=$progress['total']?> approved</small></div><div class="tcl-card tcl-kpi"><span>Status</span><strong style="font-size:22px"><?= $progress['joined']?'Joined':'Not Joined'?></strong><small>Participant state</small></div><div class="tcl-card tcl-kpi"><span>Pending Review</span><strong><?=number_format((int)$progress['pending'])?></strong><small>Awaiting admin</small></div><div class="tcl-card tcl-kpi"><span>Needs Action</span><strong><?=number_format((int)$progress['needs_action'])?></strong><small>Rejected/resubmit</small></div></section>
<section id="tasks" style="margin-top:22px" class="tcl-card"><div class="tcl-card-head"><div><h2>Task sequence</h2><p>Open each task to upload proof. Pending proof does not count until approved.</p></div><span class="tcl-pill is-info">Phase 4/5</span></div><div class="tcl-step-list"><?php foreach((array)$progress['steps'] as $i=>$step):$status=(string)($step['status']??'locked');?><div class="tcl-step <?=lqr_h($status)"><span class="tcl-step-index"><?=$status==='approved'?'✓':($i+1)?></span><div><h4><?=lqr_h((string)$step['title'])?></h4><p><?=lqr_h((string)($step['instructions']??$step['description']??''))?></p><div class="tcl-tags"><span class="tcl-pill <?=tcl_status_class($status)?>"><?=lqr_h(tcl_status_label($status))?></span><span class="tcl-pill is-muted"><?=lqr_h((string)($step['proof']??'proof'))?></span><span class="tcl-pill is-purple"><?=number_format((int)($step['points']??0))?> pts</span></div><div style="margin-top:12px"><?php if($progress['joined'] && $status!=='approved' && $status!=='pending_review'):?><a class="tcl-btn primary" href="training-proof-upload.php?campaign=<?=urlencode($slug)?>&task=<?=urlencode((string)$step['slug'])?>">Upload Proof</a><?php elseif($status==='pending_review'):?><span class="tcl-pill is-warning">Waiting for review</span><?php elseif($status==='approved'):?><span class="tcl-pill is-success">Approved</span><?php else:?><span class="tcl-pill is-muted">Join to unlock</span><?php endif;?></div></div></div><?php endforeach;?></div></section>
<?php endif;?></main></div><nav class="tcl-bottom-nav"><a href="training-lab.php"><span>⌂</span>Overview</a><a href="training-campaigns.php"><span>◆</span>Campaigns</a><a class="active" href="training-sequence.php?campaign=<?=lqr_h(urlencode($slug))?>"><span>▤</span>Tasks</a><a href="training-rewards.php?campaign=<?=lqr_h(urlencode($slug))?>"><span>◉</span>Rewards</a><a href="wallet.php"><span>◎</span>Wallet</a></nav><script src="assets/training-lab.js"></script></body></html>
