<?php
 declare(strict_types=1);
require_once __DIR__.'/training-storage.php';
function tcl_create_receipts_for_submission(string $submissionId): array
{
    if(tcl_runtime_sql()){
        $pdo=tcl_storage_pdo();
        try{
            $s=$pdo->prepare('SELECT s.*,c.slug campaign_slug,q.slug sequence_slug,t.slug task_slug,t.points FROM training_task_submissions s JOIN training_campaigns c ON c.id=s.campaign_id JOIN training_sequences q ON q.id=s.sequence_id JOIN training_tasks t ON t.id=s.task_id WHERE s.public_id=:p AND s.status="approved" LIMIT 1');
            $s->execute(['p'=>$submissionId]);$sub=$s->fetch();if(!$sub)return [];$created=[];
            $exists=$pdo->prepare("SELECT id FROM training_action_receipts WHERE receipt_type='task_completion' AND submission_id=:sid LIMIT 1");$exists->execute(['sid'=>$sub['id']]);
            if(!$exists->fetchColumn()){$pub=tcl_public_id();$ins=$pdo->prepare("INSERT INTO training_action_receipts(public_id,receipt_type,campaign_id,participant_id,sequence_id,task_id,submission_id,points_awarded,status,receipt_payload_json) VALUES(:pub,'task_completion',:c,:p,:q,:t,:s,:pts,'verified',:m)");$ins->execute(['pub'=>$pub,'c'=>$sub['campaign_id'],'p'=>$sub['participant_id'],'q'=>$sub['sequence_id'],'t'=>$sub['task_id'],'s'=>$sub['id'],'pts'=>(int)$sub['points'],'m'=>json_encode(['submission_public_id'=>$submissionId])]);$created[]=['id'=>$pub,'receipt_type'=>'task_completion'];$tmp=[];tcl_event($tmp,'training.receipt.created','Task completion Action Receipt created.',['target_id'=>$pub]);}
            $needed=$pdo->prepare('SELECT COUNT(*) FROM training_tasks WHERE sequence_id=:q AND is_required=1');$needed->execute(['q'=>$sub['sequence_id']]);$need=(int)$needed->fetchColumn();
            $approved=$pdo->prepare('SELECT COUNT(DISTINCT task_id) FROM training_task_submissions WHERE participant_id=:p AND sequence_id=:q AND status="approved"');$approved->execute(['p'=>$sub['participant_id'],'q'=>$sub['sequence_id']]);$have=(int)$approved->fetchColumn();
            if($need>0&&$have>=$need){$ex=$pdo->prepare("SELECT id FROM training_action_receipts WHERE receipt_type='sequence_completion' AND participant_id=:p AND sequence_id=:q LIMIT 1");$ex->execute(['p'=>$sub['participant_id'],'q'=>$sub['sequence_id']]);if(!$ex->fetchColumn()){$pub=tcl_public_id();$points=$pdo->prepare('SELECT COALESCE(SUM(points),0) FROM training_tasks WHERE sequence_id=:q AND is_required=1');$points->execute(['q'=>$sub['sequence_id']]);$ins=$pdo->prepare("INSERT INTO training_action_receipts(public_id,receipt_type,campaign_id,participant_id,sequence_id,submission_id,points_awarded,status,receipt_payload_json) VALUES(:pub,'sequence_completion',:c,:p,:q,:s,:pts,'verified',:m)");$ins->execute(['pub'=>$pub,'c'=>$sub['campaign_id'],'p'=>$sub['participant_id'],'q'=>$sub['sequence_id'],'s'=>$sub['id'],'pts'=>(int)$points->fetchColumn(),'m'=>json_encode(['sequence_slug'=>$sub['sequence_slug']])]);$created[]=['id'=>$pub,'receipt_type'=>'sequence_completion'];$tmp=[];tcl_event($tmp,'training.sequence.verified_complete','Sequence completion Action Receipt created.',['target_id'=>$pub]);}}
            return $created;
        }catch(Throwable $e){return [];}
    }
    $state=tcl_state_load();$submission=$state['submissions'][$submissionId]??null;if(!is_array($submission)||($submission['status']??'')!=='approved')return [];$created=[];$participantId=(string)$submission['participant_id'];$campaignSlug=(string)$submission['campaign_slug'];$taskSlug=(string)$submission['task_slug'];$sequenceSlug=(string)$submission['sequence_slug'];$taskKey='task|'.$participantId.'|'.$campaignSlug.'|'.$taskSlug.'|'.$submissionId;if(empty($state['receipts'][$taskKey])){$state['receipts'][$taskKey]=['id'=>tcl_public_id(),'key'=>$taskKey,'receipt_type'=>'task_completion','participant_id'=>$participantId,'campaign_slug'=>$campaignSlug,'sequence_slug'=>$sequenceSlug,'task_slug'=>$taskSlug,'submission_id'=>$submissionId,'status'=>'verified','points_awarded'=>0,'created_at'=>tcl_now()];$created[]=$state['receipts'][$taskKey];tcl_event($state,'training.receipt.created','Task completion Action Receipt created.',['receipt_key'=>$taskKey]);}$campaign=tcl_storage_campaign_by_slug($campaignSlug);$steps=(array)($campaign['sequence']['steps']??[]);$complete=true;foreach($steps as $step){if(!($step['is_required']??true))continue;$latest=tcl_latest_submission_for_task($participantId,$campaignSlug,(string)$step['slug']);if(($latest['status']??'')!=='approved'){$complete=false;break;}}if($complete&&$steps){$sequenceKey='sequence|'.$participantId.'|'.$campaignSlug.'|'.$sequenceSlug;if(empty($state['receipts'][$sequenceKey])){$state['receipts'][$sequenceKey]=['id'=>tcl_public_id(),'key'=>$sequenceKey,'receipt_type'=>'sequence_completion','participant_id'=>$participantId,'campaign_slug'=>$campaignSlug,'sequence_slug'=>$sequenceSlug,'task_slug'=>'','submission_id'=>$submissionId,'status'=>'verified','points_awarded'=>array_sum(array_map(static fn($s):int=>(int)($s['points']??0),$steps)),'created_at'=>tcl_now()];$created[]=$state['receipts'][$sequenceKey];tcl_event($state,'training.sequence.verified_complete','Sequence completion Action Receipt created.',['receipt_key'=>$sequenceKey]);}}tcl_state_save($state);return $created;
}
