<?php
declare(strict_types=1);
require_once __DIR__ . '/_payments.php';
mg_require_method('POST');
$user=mg_require_permission('commerce.checkout.create');
$input=mg_input();mg_require_csrf_for_write($input);
$items=is_array($input['items']??null)?$input['items']:[];$idempotency=trim((string)($input['idempotency_key']??''));
if(!$items||count($items)>100||$idempotency===''||mb_strlen($idempotency)>190)mg_fail('Invalid checkout request.',422);
$pdo=mg_db();$resolved=[];$merchantId=null;$currency=null;
foreach($items as $row){$versionId=trim((string)($row['product_version_id']??''));$quantity=max(1,min(100,(int)($row['quantity']??1)));$stmt=$pdo->prepare("SELECT v.id version_db_id,v.public_id version_id,v.title,v.unit_value_cents,v.currency,p.id product_db_id,p.public_id product_id,p.merchant_user_id FROM catalog_product_versions v INNER JOIN catalog_products p ON p.id=v.product_id WHERE v.public_id=? AND v.version_status='published' AND p.status='published' LIMIT 1");$stmt->execute([$versionId]);$item=$stmt->fetch();if(!$item)mg_fail('A checkout item is unavailable.',409);if($merchantId!==null&&(int)$item['merchant_user_id']!==$merchantId)mg_fail('Checkout currently supports one merchant per order.',409);if($currency!==null&&$item['currency']!==$currency)mg_fail('Checkout items must use one currency.',409);$merchantId=(int)$item['merchant_user_id'];$currency=(string)$item['currency'];$item['quantity']=$quantity;$item['line_total_cents']=(int)$item['unit_value_cents']*$quantity;$resolved[]=$item;}
$totals=mg_payment_order_totals($resolved);$provider=mg_payment_provider_key();$pdo->beginTransaction();
try{$existing=$pdo->prepare('SELECT public_id FROM commerce_orders WHERE buyer_user_id=? AND idempotency_key=? LIMIT 1');$existing->execute([(int)$user['id'],$idempotency]);if($found=$existing->fetchColumn()){$pdo->commit();mg_ok(['order_id'=>$found,'reused'=>true],'Checkout already created.');}
$orderId=mg_public_uuid();$pdo->prepare("INSERT INTO commerce_orders (public_id,buyer_user_id,merchant_user_id,currency,subtotal_cents,discount_cents,tax_cents,platform_fee_cents,total_cents,payment_status,fulfillment_status,source_type,idempotency_key,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,'unpaid','pending','checkout',?,NOW(),NOW())")->execute([$orderId,(int)$user['id'],$merchantId,$currency,$totals['subtotal_cents'],$totals['discount_cents'],$totals['tax_cents'],$totals['platform_fee_cents'],$totals['total_cents'],$idempotency]);$orderDb=(int)$pdo->lastInsertId();$line=$pdo->prepare('INSERT INTO commerce_order_items (public_id,order_id,product_id,product_version_id,title_snapshot,quantity,unit_amount_cents,line_total_cents,currency,created_at) VALUES (?,?,?,?,?,?,?,?,?,NOW())');foreach($resolved as $item)$line->execute([mg_public_uuid(),$orderDb,(int)$item['product_db_id'],(int)$item['version_db_id'],$item['title'],$item['quantity'],(int)$item['unit_value_cents'],(int)$item['line_total_cents'],$currency]);
$intentId=mg_public_uuid();$pdo->prepare("INSERT INTO payment_intents (public_id,order_id,provider_key,amount_cents,currency,status,capture_method,idempotency_key,created_at,updated_at) VALUES (?,?,?,?,?,'created','automatic',?,NOW(),NOW())")->execute([$intentId,$orderDb,$provider,$totals['total_cents'],$currency,$idempotency.':intent']);$sessionId=mg_public_uuid();$expires=date('Y-m-d H:i:s',time()+1800);$pdo->prepare("INSERT INTO checkout_sessions (public_id,order_id,provider_key,status,success_url,cancel_url,expires_at,created_at,updated_at) VALUES (?,?,?,'open',?,?,?,NOW(),NOW())")->execute([$sessionId,$orderDb,$provider,$input['success_url']??'/checkout-success.php',$input['cancel_url']??'/cart.php',$expires]);$pdo->commit();mg_audit('commerce.checkout_created','commerce_order',['order_id'=>$orderId,'provider'=>$provider,'amount_cents'=>$totals['total_cents']],(int)$user['id']);mg_ok(['order_id'=>$orderId,'checkout_session_id'=>$sessionId,'payment_intent_id'=>$intentId,'provider'=>$provider,'mode'=>mg_payment_is_live()?'live':'test','checkout_url'=>'/checkout.php?session='.rawurlencode($sessionId),'expires_at'=>$expires],'Checkout session created.',201);
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();mg_security_log('error','commerce.checkout_failed','Checkout creation failed.',['exception_type'=>get_class($e)],(int)$user['id']);mg_fail('Unable to create checkout.',500);}
