<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/bootstrap.php';

final class MgOpsAlertException extends RuntimeException
{
    public function __construct(string $message, public readonly int $httpStatus=409){parent::__construct($message);}
}

function mg_ops_alert_install(PDO $pdo): void
{
    $pdo->exec("CREATE TABLE IF NOT EXISTS ops_alerts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(36) NOT NULL,alert_key VARCHAR(190) NOT NULL,fingerprint CHAR(64) NOT NULL,source_type VARCHAR(100) NOT NULL,source_id VARCHAR(190) NOT NULL,severity ENUM('info','warning','critical') NOT NULL DEFAULT 'warning',status ENUM('open','assigned','resolved') NOT NULL DEFAULT 'open',title VARCHAR(200) NOT NULL,body VARCHAR(1000) NOT NULL,assigned_to_user_id BIGINT UNSIGNED NULL,resolution_reason VARCHAR(500) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,resolved_at DATETIME NULL,PRIMARY KEY(id),UNIQUE KEY uq_ops_alert_public_id(public_id),UNIQUE KEY uq_ops_alert_key(alert_key),KEY idx_ops_alert_queue(status,severity,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $pdo->exec("CREATE TABLE IF NOT EXISTS ops_alert_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(36) NOT NULL,alert_id BIGINT UNSIGNED NOT NULL,event_key VARCHAR(190) NOT NULL,fingerprint CHAR(64) NOT NULL,actor_user_id BIGINT UNSIGNED NULL,event_type VARCHAR(80) NOT NULL,before_json JSON NULL,after_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_ops_alert_event_public_id(public_id),UNIQUE KEY uq_ops_alert_event_key(event_key),KEY idx_ops_alert_event_alert(alert_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $pdo->exec("INSERT INTO permissions (slug,name,description,created_at) VALUES ('ops.alerts.assign','Assign operations alerts','Assign operational alerts.',NOW()),('ops.alerts.resolve','Resolve operations alerts','Resolve operational alerts.',NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name)");
}
function mg_ops_alert_ensure(PDO $pdo): void{if(!$pdo->inTransaction())mg_ops_alert_install($pdo);}function mg_ops_json(array $v): string{return json_encode($v,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}function mg_ops_scalar(PDO $pdo,string $sql,array $p=[]): mixed{$s=$pdo->prepare($sql);$s->execute($p);return $s->fetchColumn();}
function mg_ops_has(PDO $pdo,int $userId,string $permission): bool{$sql="SELECT COUNT(*) FROM user_roles ur INNER JOIN roles r ON r.id=ur.role_id LEFT JOIN role_permissions rp ON rp.role_id=r.id LEFT JOIN permissions p ON p.id=rp.permission_id WHERE ur.user_id=? AND (r.slug='super_admin' OR p.slug=?)";return (int)mg_ops_scalar($pdo,$sql,[$userId,$permission])>0;}
function mg_ops_require(PDO $pdo,int $userId,string $permission): void{if(!mg_ops_has($pdo,$userId,$permission))throw new MgOpsAlertException('Ops action is not permitted.',403);}
function mg_ops_alert_fingerprint(array $input): string{return hash('sha256',mg_ops_json(['source_type'=>(string)($input['source_type']??''),'source_id'=>(string)($input['source_id']??''),'severity'=>(string)($input['severity']??''),'title'=>(string)($input['title']??''),'body'=>(string)($input['body']??'')]));}
function mg_ops_event_fingerprint(array $input): string{return hash('sha256',mg_ops_json(['event_type'=>(string)($input['event_type']??''),'actor'=>(int)($input['actor_user_id']??0),'alert'=>(string)($input['alert_public_id']??''),'assignee'=>(int)($input['assigned_to_user_id']??0),'reason'=>(string)($input['resolution_reason']??'')]));}
function mg_ops_event_key(array $input): string{$key=trim((string)($input['event_key']??''));if($key==='')throw new MgOpsAlertException('Missing request key.',422);if(mb_strlen($key)>190)throw new MgOpsAlertException('Request key is too long.',422);return $key;}
function mg_ops_alert_upsert(PDO $pdo,array $input): array{
    mg_ops_alert_ensure($pdo);$key=trim((string)($input['alert_key']??''));if($key==='')throw new MgOpsAlertException('Missing alert key.',422);$fp=mg_ops_alert_fingerprint($input);$owns=!$pdo->inTransaction();if($owns)$pdo->beginTransaction();
    try{$existing=$pdo->prepare('SELECT * FROM ops_alerts WHERE alert_key=? LIMIT 1 FOR UPDATE');$existing->execute([$key]);if($row=$existing->fetch(PDO::FETCH_ASSOC)){if(!hash_equals((string)$row['fingerprint'],$fp))throw new MgOpsAlertException('Ops alert conflicts with recorded alert.',409);if($owns)$pdo->commit();return ['alert_id'=>$row['public_id'],'duplicate'=>true,'status'=>$row['status']];}
        $public=mg_public_uuid();$pdo->prepare('INSERT INTO ops_alerts (public_id,alert_key,fingerprint,source_type,source_id,severity,status,title,body,created_at,updated_at) VALUES (?,?,?,?,?,?,\'open\',?,?,NOW(),NOW())')->execute([$public,$key,$fp,(string)$input['source_type'],(string)$input['source_id'],(string)$input['severity'],(string)$input['title'],(string)$input['body']]);if($owns)$pdo->commit();return ['alert_id'=>$public,'duplicate'=>false,'status'=>'open'];
    }catch(Throwable $e){if($owns&&$pdo->inTransaction())$pdo->rollBack();throw $e;}}
function mg_ops_load_alert(PDO $pdo,string $publicId): array{$s=$pdo->prepare('SELECT * FROM ops_alerts WHERE public_id=? LIMIT 1 FOR UPDATE');$s->execute([$publicId]);$row=$s->fetch(PDO::FETCH_ASSOC);if(!$row)throw new MgOpsAlertException('Ops alert not found.',404);return $row;}
function mg_ops_record_event(PDO $pdo,array $alert,array $input,array $before,array $after): array{$key=mg_ops_event_key($input);$fp=mg_ops_event_fingerprint($input);$s=$pdo->prepare('SELECT * FROM ops_alert_events WHERE event_key=? LIMIT 1 FOR UPDATE');$s->execute([$key]);if($row=$s->fetch(PDO::FETCH_ASSOC)){if(!hash_equals((string)$row['fingerprint'],$fp))throw new MgOpsAlertException('Ops alert event conflicts with recorded event.',409);return ['event_id'=>$row['public_id'],'duplicate'=>true];}$public=mg_public_uuid();$pdo->prepare('INSERT INTO ops_alert_events (public_id,alert_id,event_key,fingerprint,actor_user_id,event_type,before_json,after_json,created_at) VALUES (?,?,?,?,?,?,?,?,NOW())')->execute([$public,(int)$alert['id'],$key,$fp,$input['actor_user_id']??null,(string)$input['event_type'],mg_ops_json($before),mg_ops_json($after)]);return ['event_id'=>$public,'duplicate'=>false];}
function mg_ops_assign_alert(PDO $pdo,array $input,?callable $failureHook=null): array{
    mg_ops_alert_ensure($pdo);$actor=(int)($input['actor_user_id']??0);$assignee=(int)($input['assigned_to_user_id']??0);if($assignee<1)throw new MgOpsAlertException('Missing assignee.',422);mg_ops_require($pdo,$actor,'ops.alerts.assign');$owns=!$pdo->inTransaction();if($owns)$pdo->beginTransaction();
    try{$alert=mg_ops_load_alert($pdo,(string)$input['alert_public_id']);$before=['status'=>$alert['status'],'assigned_to_user_id'=>$alert['assigned_to_user_id']];$event=mg_ops_record_event($pdo,$alert,$input+['event_type'=>'assigned'], $before, ['status'=>'assigned','assigned_to_user_id'=>$assignee]);if(!$event['duplicate']){$pdo->prepare("UPDATE ops_alerts SET status='assigned',assigned_to_user_id=?,updated_at=NOW() WHERE id=?")->execute([$assignee,(int)$alert['id']]);mg_audit('ops.alert_assigned','ops_alert',['alert_id'=>$alert['public_id'],'event_id'=>$event['event_id'],'assigned_to_user_id'=>$assignee],$actor);if($failureHook)$failureHook('after_audit',['alert_id'=>$alert['public_id'],'event_id'=>$event['event_id']]);}if($owns)$pdo->commit();return $event+['status'=>'assigned'];
    }catch(Throwable $e){if($owns&&$pdo->inTransaction())$pdo->rollBack();throw $e;}}
function mg_ops_resolve_alert(PDO $pdo,array $input,?callable $failureHook=null): array{
    mg_ops_alert_ensure($pdo);$actor=(int)($input['actor_user_id']??0);$reason=trim((string)($input['resolution_reason']??''));if($reason==='')throw new MgOpsAlertException('Missing resolution reason.',422);mg_ops_require($pdo,$actor,'ops.alerts.resolve');$owns=!$pdo->inTransaction();if($owns)$pdo->beginTransaction();
    try{$alert=mg_ops_load_alert($pdo,(string)$input['alert_public_id']);$before=['status'=>$alert['status'],'resolution_reason'=>$alert['resolution_reason']];$event=mg_ops_record_event($pdo,$alert,$input+['event_type'=>'resolved'], $before, ['status'=>'resolved','resolution_reason'=>$reason]);if(!$event['duplicate']){$pdo->prepare("UPDATE ops_alerts SET status='resolved',resolution_reason=?,resolved_at=NOW(),updated_at=NOW() WHERE id=?")->execute([$reason,(int)$alert['id']]);mg_audit('ops.alert_resolved','ops_alert',['alert_id'=>$alert['public_id'],'event_id'=>$event['event_id'],'reason'=>$reason],$actor);if($failureHook)$failureHook('after_audit',['alert_id'=>$alert['public_id'],'event_id'=>$event['event_id']]);}if($owns)$pdo->commit();return $event+['status'=>'resolved'];
    }catch(Throwable $e){if($owns&&$pdo->inTransaction())$pdo->rollBack();throw $e;}}
